### ISSUE TITLE
Global Locks

### ISSUE THREAD

**Issue by georgyous** [lizardfs/lizardfs#171]
Hello,

First of all I am a moosefs user for some time and I like what you did with lizardfs. I am planning to migrate to it mainly for the quota support and performance improvements, but the IO limiter is also a nice feature.

Another feature that I am interested in is global locking. Any news on this feature?

Thank you

**Comment by psarna** [comment]
There are 2 open issues related to file locking, so I decided to close the older one.
Ref: https://github.com/lizardfs/lizardfs/issues/290

By the way, global locking support is a work-in-progress.
