### ISSUE TITLE
Allow users to find files with missing chunks

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#174]
Currently with MooseFS/LizardFS, finding files with missing chunks is a pain.

Are there any plans to make this a little less painful in LizardFS?

**Comment by gutleib** [comment]
Totally support!
A cli tool, like mfschunkinfo or whatever to make searches not by files, like "mfsfileinfo /some/file/", but in reverse, "mfschunkinfo --endangered /file/system/" which outputs list of files containing endangered (in this example) chunks and, optionally, their "last seen on" state.

**Comment by 4Dolio** [comment]
I have created a set of commands which accomplishes this. though it could be much better as an official tool.  Mine scans the logs for no valid chunk errors, dumps metadata to human format, then identifies the file given the chunk id and recurses for that files parents to provide the full path. Ill try to post my solution soon....

**Comment by psarna** [comment]
https://github.com/lizardfs/lizardfs/commit/8bdc025f1ed39dd8df15a11489a30ed33cdd93e3

**Comment by smurfix** [comment]
Yeah, now if this tool actually worked that'd be splendid, but unfortunately it does not.
```
pi-e4 ~# lizardfs fileinfo /mnt/d/backup/arm/tuxrail2/var/lib/dpkg/info/aptitude.list
/mnt/d/backup/arm/tuxrail2/var/lib/dpkg/info/aptitude.list:
	chunk 0: 000000000017500C_00000001 / (id:1527820 ver:1)
		no valid copies !!!
pi-e4 ~# lizardfs-admin list-defective-files 10.107.15.11 9421|grep aptitude
pi-e4 ~# 
```

**Comment by onlyjob** [comment]
https://github.com/lizardfs/lizardfs/issues/222#issuecomment-109157573

**Comment by smurfix** [comment]
Yeah, I wrote something like that yesterday; it's not rocket science. Took a few hours to whale through all my files.

Also that's probably going to be the last thing I do with lizardfs before I finally toss the thing.
