### ISSUE TITLE
What's the "shadow master" ?

### ISSUE THREAD

**Issue by liqiangvip** [lizardfs/lizardfs#179]
Lizardfs provides the High availbility: "the new ‘shadow master’ server which maintains a current copy of filesystem metadata and is prepared to immediately replace the master metadata server in case of a failure" "Shadow master obtains metadata updates from the master server using the old MooseFS/LizardFS metalogger protocol." -- from the Lizardfs website

However, I do not find the difference between "shadow master" in Lizardfs and "metalogger server" in Moosefs. In Moosefs, the meta data could be restored from metalogger server when the master sever stops working.

**Comment by jamesarems** [comment]
Hi Liqiangvip,

You are right we can promote shadow as master . But when we are implementing this into production system , if suddenly master server fails , How can we manually switch to this setting as soon as ? Or if we got 1 or 2 minute to setup this shadow to master then what will happen for that offline data that users trying to write on that time? Is there is any HA possibilities available?
