### ISSUE TITLE
How far to reach a windows client

### ISSUE THREAD

**Issue by liqiangvip** [lizardfs/lizardfs#183]
I noticed that " (polonaise) Add filesystem API for developers allowing to use the filesystem without FUSE (and thus working also on Windows)" in NEWS for Lizardfs (2.5.2) (2014-09-15).

So I guess it is possible to implement a windows client in future. I also found a video of Native Windows client for LizardFS on Youtube (http://youtu.be/YpfAc92ei90). 
I want to know if there is a plan to release the windows client. Thanks.

**Comment by ged-nn** [comment]
?

**Comment by onlyjob** [comment]
Windows client appears to be [available by request](https://lizardfs.com/download/) so I hope this bug can be closed.

Proprietary software is harmful, insecure and even unethical. Please don't waste your time on proprietary software...
