### ISSUE TITLE
mfsmount Segmentation fault

### ISSUE THREAD

**Issue by georgyous** [lizardfs/lizardfs#185]
Hello,

Can you please help we with a issue that seems to be a bug?
The problem manifests in Redhat 6.5
The rpm's compilation and other thing were made by me and worked on lizardfs 2.5.0, the problem seems to be in 2.5.2 only.

When I try to mount it gives me: Segmentation fault
GDB debug information:

GNU gdb (GDB) Red Hat Enterprise Linux (7.2-60.el6_4.1)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/mfsmount...(no debugging symbols found)...done.
[New Thread 9186]
Reading symbols from /lib64/libfuse.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libfuse.so.2
Reading symbols from /lib64/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /usr/lib64/libstdc++.so.6...done.
Loaded symbols for /usr/lib64/libstdc++.so.6
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Core was generated by `mfsmount -o mfsmaster=192.168.255.232,mfsdebug,mfsacl,mfssubfolder=/ /storage'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f749f67395a in __strchr_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install lizardfs-client-2.5.2-1rh.x86_64
(gdb) bt
#0  0x00007f749f67395a in __strchr_sse2 () from /lib64/libc.so.6
#1  0x00007f74a0777a3e in ?? () from /lib64/libfuse.so.2
#2  0x00007f74a0777ba3 in ?? () from /lib64/libfuse.so.2
#3  0x00007f74a0777d5a in ?? () from /lib64/libfuse.so.2
#4  0x00007f74a077811a in fuse_opt_parse () from /lib64/libfuse.so.2
#5  0x000000000041105f in main ()

There seems to be a problem with line 934 of /src/mount/fuse/main.cc.

Some more output with the debug headers enabled.

#0  0x00007ffff6ab895a in __strchr_sse2 () from /lib64/libc.so.6
#1  0x00007ffff7bbca3e in match_template (t=0x240166 <Address 0x240166 out of bounds>, arg=0x16e53b0 "mfsmaster=192.168.255.232", sepp=0x7fffffffe43c) at fuse_opt.c:171
#2  0x00007ffff7bbcba3 in find_opt (ctx=0x7fffffffe4c0, arg=0x16e53b0 "mfsmaster=192.168.255.232", iso=1) at fuse_opt.c:193
#3  process_gopt (ctx=0x7fffffffe4c0, arg=0x16e53b0 "mfsmaster=192.168.255.232", iso=1) at fuse_opt.c:274
#4  0x00007ffff7bbcd5a in process_real_option_group (ctx=0x7fffffffe4c0, opts=<value optimized out>) at fuse_opt.c:302
#5  process_option_group (ctx=0x7fffffffe4c0, opts=<value optimized out>) at fuse_opt.c:326
#6  0x00007ffff7bbd11a in process_one (args=0x7fffffffe560, data=<value optimized out>, opts=<value optimized out>, proc=<value optimized out>) at fuse_opt.c:342
#7  opt_parse (args=0x7fffffffe560, data=<value optimized out>, opts=<value optimized out>, proc=<value optimized out>) at fuse_opt.c:362
#8  fuse_opt_parse (args=0x7fffffffe560, data=<value optimized out>, opts=<value optimized out>, proc=<value optimized out>) at fuse_opt.c:397
#9  0x000000000045d223 in main (argc=4, argv=0x7fffffffe688) at /root/lizardfs-2.5.2/src/mount/fuse/main.cc:934

Thank you

**Comment by onlyjob** [comment]
I think it should be safe to close this old bug. With availability of v2.6.0 and v3.9.4 this problem in v2.5.4 is no longer relevant unless it can be reproduced in never version in which case it would be appropriate to open new bug report (or update/re-open this one). Please close.
