### ISSUE TITLE
mfstopology.cfg throws syntax errors

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#190]
Hey there,

When you try to start the LFS Master on Debian 7 it throws syntax errors like this when it attempts to load the included mfstopology.cfg file:

mfstopology: incomplete definition in line: 28
mfstopology: incomplete definition in line: 28

**Comment by onlyjob** [comment]
I'm unable to reproduce this problem on 2.6.0, let's close this issue please.

**Comment by psarna** [comment]
There you go.
