### ISSUE TITLE
documentation: please ship FAQ, quick start guide, operational guide etc.

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#205]
LizardFS is incomplete without its own documentation. Please create project Wiki (I shall be happy to contribute) and include documentation to tarball release. Thanks.

**Comment by pbeza** [comment]
[LizardFS wiki][1] was created as requested. Please reopen this issue if you think that it was prematurely closed.

[1]: https://github.com/lizardfs/lizardfs/wiki
