### ISSUE TITLE
Please consider implementing erasure-coded tier

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#207]
LizardFS is awesome but it will be a killer storage solution if/when an erasure-coded tier will be implemented. I see such feature as "cold" storage behind current replicated storage implementation which can act as cache for slower erasure-coded storage tier. As for particular choice of erasure algorithm it could be [Mojette Transform](https://en.wikipedia.org/wiki/Mojette_Transform) which is used in [RozoFS](https://github.com/rozofs/rozofs) or [Jerasure](http://web.eecs.utk.edu/~plank/plank/www/software.html) coding which is used by *Ceph* and *Openstack Swift*. Jerasure library is already [available in Debian](https://tracker.debian.org/pkg/jerasure). Thanks.

**Comment by Zorlin** [comment]
Merging my ticket: "Hi there,

I was wondering if LizardFS will eventually implement erasure coding - specifically Reed-Solomon. It would allow for higher fault tolerance than the regular "copies" system currently in use (in theoery) without sacrificing performance. Backblaze has implemented it to great success.

https://www.backblaze.com/blog/reed-solomon/

Would be very cool to see LizardFS doing this at some point."

**Comment by onlyjob** [comment]
_xorN+1_ implemented in v3.9.2 is awesome and it is indeed a step in the right direction (thanks!). However _xor_ modes have only one parity which makes 'em almost an equivalent of RAID-5. We still need _Jerasure_ coding to support 2 or more parity blocks.

**Comment by blink69** [comment]
I think this ticket should be closed :) Erasure code is implemented in 3.10.0

**Comment by onlyjob** [comment]
Agreed, I was going to close it myself even though Erasure is not implemented as tier. :)

**Comment by Asher256** [comment]
@blink69: what is the ETA of the erasure coding feature implemented on 3.10.0. Is it stable and safe enough to be used in prod?

What is the difference between the XOR feature and the new erasure coding feature? XOR is a simpler implementation?

Thank you.

Asher256
