### ISSUE TITLE
fallback to alternative hosts if chunk is targeted to overutilised volume

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#217]
On one chunkserver host I have two HDDs utilised by chunkserver over 99.3%. There is still little free space left but writing slowed down to ~2 MiB/s or less (probably due to fragmentation etc). No I've added two new HDDs to different chinkserver hosts. While data is slowly re-distributes I observe very slow write to LizardFS:

~~~~
Dec 12 14:17:56 deblab mfsmount[3140]: file: 2545101, index: 0, chunk: 2355979, version: 1 - writeworker: connection with (C0A800CC:9422) was timed out (unfinished writes: 3; try counter: 1)
Dec 12 14:17:57 deblab mfsmount[3140]: file: 2545102, index: 0, chunk: 2355980, version: 1 - writeworker: connection with (C0A800CC:9422) was timed out (unfinished writes: 2; try counter: 1)
Dec 12 14:17:58 deblab mfsmount[3140]: file: 2545101, index: 0, chunk: 2355979, version: 1 - writeworker: connection with (C0A800CC:9422) was timed out (unfinished writes: 3; try counter: 1)
Dec 12 14:17:59 deblab mfsmount[3140]: file: 2545102, index: 0, chunk: 2355980, version: 1 - writeworker: connection with (C0A80002:9422) was timed out (unfinished writes: 2; try counter: 1)
Dec 12 14:18:00 deblab mfsmount[3140]: file: 2545101, index: 0, chunk: 2355979, version: 1 - writeworker: connection with (C0A800CC:9422) was timed out (unfinished writes: 3; try counter: 1)
Dec 12 14:18:01 deblab mfsmount[3140]: file: 2545102, index: 0, chunk: 2355980, version: 1 - writeworker: connection with (C0A800CC:9422) was timed out (unfinished writes: 2; try counter: 1)
Dec 12 14:18:02 deblab mfsmount[3140]: file: 2545101, index: 0, chunk: 2355979, version: 1 - writeworker: connection with (C0A800CC:9422) was timed out (unfinished writes: 3; try counter: 1)
Dec 12 14:18:03 deblab mfsmount[3140]: file: 2545102, index: 0, chunk: 2355980, version: 1 - writeworker: connection with (C0A800CC:9422) was timed out (unfinished writes: 2; try counter: 1)
~~~~

It looks like `mfsmount` tries to squeeze some chunks to nearly full host while other hosts would me much more suitable. Probably client always expect cluster to be perfectly balanced? Maybe some logic to choose less allocated server(s) to send new data to would be desirable? IMHO when possible client should avoid writing to hosts where is less than 1% of free space left while hosts with 99% of free space are available.

**Comment by onlyjob** [comment]
@cloudweavers, please forgive my ignorance. Despite using Btrfs for years and having some near-full Btrfs partitions I just experienced free space problem on Btrfs for the first time, as you described.
2TB HDD formatted as Btrfs (no snapshots) started to manifest sporadic ENOSPC errors even though `df -h` reported over 400 GiB of free space (>25%).  I had to fiddle with `btrfs balance` to address the issue as described in Btrfs FAQ. Happened on Linux-3.16.7 on one of LizardFS volumes. Apparently this is either regression in kernel or something related to pattern of use (or both)...

**Comment by cloudweavers** [comment]
No need to apologize! We are just sharing our experiences, so no problem at all. I found several recent mentions of btrfs problems due to filled metadata space, and lots of rebalance problems so it may be a regression or a latent problem in the tree design of the filesystem. I believe that it still needs some maturation, despite the nice features.

**Comment by Zorlin** [comment]
@cloudweavers I will eat my hat if btrfs ever ends up better than ZFS.

**Comment by onlyjob** [comment]
With increase of `HDD_LEAVE_SPACE_DEFAULT` to 4GiB this issue is reduced to generic optimisation of distribution of data in cluster hence I'm closing this bug.
Related #280 "_uneven distribution of data between HDDs_" is still an issue that can cause performance degradation.
