### ISSUE TITLE
support: chunk NNN has only invalid copies (2) - please repair it manually

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#222]
I had a hard reset on server with master and chunkserver. Now after reboot 3 chunks "has only invalid copies (2) - please repair it manually".
How to repair? Please advise.

**Comment by 4Dolio** [comment]
Here is my hack to quickly identify the file which belongs to the invalid chunks:

When you get the dreaded:
mfsmaster[17085]: chunk 00000000237C7252 has only invalid copies (3) - please repair it manually
:And you think "I would LOVE to repair it, but mfsfilerepair <file> only works on files, not chunk IDs!!"...

First, dump the metadata to a more human parsable form:
root@meta_logger_server:~# cd ~/mfs/ ; mfsmetadump metadata_ml.mfs.back > metadata.dump

for MC in 237C7252 ;do  echo " MC=$MC";I=`grep $MC metadata.dump|cut -f2 -d\||grep "i: "|cut -b3-`;echo "  I=$I";   for i in $I;do N=`grep $i metadata.dump|grep "^E"|cut -f4- -d\:`;echo "   "N=\"$N\" \# $i; done;done
 MC=237C7252  
  I= 117897439
   7991599
   N="Some File out there that got broken.txt" # 117897439

@Lizard_Client:~$ locate "$N" # Now that we have the file name we can use locate, if we index our dataset with updatedb.
@Lizard_Client:~$ find /lizard/somewhere -name "$N" # Of use find to quickly locate the file.
/lizard/somewhere/that_folder/directory/Some File out there that got broken.txt

mfsfileinfo "/lizard/somewhere/that_folder/directory/Some File out there that got broken.txt" # Verify it has missing chunks
        chunk 24: 00000000237C7252_00000004 / (id:595358290 ver:4)
                no valid copies !!!

mfsfilerepair "/lizard/somewhere/that_folder/directory/Some File out there that got broken.txt" # Fix the file.
/lizard/somewhere/that_folder/directory/Some File out there that got broken.txt:
 chunks not changed:         24
 chunks erased:               1
 chunks repaired:             0

We have also used the find + mfsfileinfo scan of the entire dataset, but the above is much faster.
Ultimately I'm sure that a native utility could be added that does this much better than I do...

**Comment by ciroiriarte** [comment]
In that case, the tool actually recovers the data or it's just discarded?.

Atte
CI.-

**Comment by 4Dolio** [comment]
I do not believe that mfsfilerepair is not the point of this topic.. The point is that the log will complain about missing chunks by ID without identifying the filename.  And there is no tool to resolve a chunk ID into the filename which the chunk belongs to.. The process I described is just one way that you can solve that problem.  A native utility would be better, my script might be useful as a sort of pseudo-code for such a utility....
But yes, mfsfilerepair will either repair or erase the missing chunks, the result in either case is likely to be a corrupt file.  But with a missing chunk I believe that the client will become stuck in a hard I/O wait state and zombie...

**Comment by onlyjob** [comment]
Last time when I had to find corrupted files (after power failure) I used the following modified `find` command:

    find /mnt/r -xdev -type f -mtime 0 | while read F; do mfsfileinfo "$F" | grep -q "no valid copies" && echo "$F"; done

The trick is to check only files modified within last 24 hours (`-mtime 0`). Setting even shorter time limit will find corrupted files faster (otherwise list of corrupted files can be already found "Info" section under "Filesystem check info".

Running `mfsfileinfo` take the most time so I modified command to run 4 processes at a time:

    count=0; find /mnt/r -xdev -type f -mtime 0 | while read F; do ( mfsfileinfo "$F" | grep -q "no valid copies" && echo "$F" ) & [ $(((count+=1) % 4)) -eq 0 ] && wait ; done

There is no need to check snapshots. On our file system with over 20 million files the above command identified corrupted files in few minutes only.

**Comment by Zorlin** [comment]
Thanks for the script, Dmitry. Perhaps you could add it to the wiki?

**Comment by onlyjob** [comment]
@Zorlin, I'd love to and I'll probably do it eventually when time allows... At the moment there are too many things with higher priority in the queue... :(

**Comment by borkd** [comment]
Hi!
I have run into "chunk NNN has only invalid copies" issue recently on datasets with an explicit 3-way replication. LizardFS 2.5.4 was in use and problematic chunks were set to replicate with goal "all3: A B C", where A, B, and C are different failure domains. 

On the day of the incident one of the chunkservers with label "B" started flapping, and anticipating prolonged shutdown for service its storage was placed in the drain mode (* prefix in mfshdd.cfg) to avoid cross datacenter traffic. Millions of files with varying goals were being replicated, but when I saw the "chunk XXX has only invalid copies" syslog message for a file with all3 goal I was baffled. Indeed the VMs using two datasets with one missing chunk each were no longer responsive. While I'm very happy that the recovery steps mentioned above did work out in the end and there was no data loss I'm having some serious doubts about the under-goal file and chunk accounting that goes or doesn't go on.

Within two hours from "invalid copies" incident another chunkserver, this time with label "C", encountered a partial, non-instantaneous but catastrophic storage failure that necessitated a power cycle to bring remaining disks back online. 

Replication goals have been upped since the incident, and after a week of replication and rebalancing the chunks summary tab again shows all chunks as safe with nothing to replicate or remove but... "Filesystem check info" summary stubbornly shows 200k+ files and chunks as under-goal, no filenames ever listed below. I have updated the entire system to 2.6.0 but undergoal chunks and file count still shows up. Any suggestions?

**Comment by 4Dolio** [comment]
I would also be interested in how the ?check loop? Is triggered... I suspect perhaps a master transition may start one? it would be nice to be able to initiate a check on demand.

**Comment by borkd** [comment]
BTW, I did multiple tree walks with mfscheckfile and have not run into any any files reporting under-goal number of chunk copies. Dumping the metadata and looking for clues there may be next, unless developers or someone with more operations experience suggest another way of debugging this. 

![lizardfs undegoal or not - all space](https://cloud.githubusercontent.com/assets/12971584/8265882/f079f792-16db-11e5-8792-5e5f12dc4af3.png)

![lizardfs undergoal or not - regular space](https://cloud.githubusercontent.com/assets/12971584/8265883/f8497d3a-16db-11e5-90bd-dce317777ffd.png)

**Comment by 4Dolio** [comment]
that's odd. It appears to me that the 'filesystem check info' is inaccurate. Were there chunkservers offline during the associated check times? I presume not based on your original post. Can u transition to a shadow master or restart the master, maybe that would clear it up?

**Comment by borkd** [comment]
No chunkserver outages since the incident. Master was restarted since then when snapshot attempt crashed mfsmaster. No changes in filesystem check info area though.

**Comment by onlyjob** [comment]
Closing as there is nothing left to do here. Thanks.

**Comment by 4Dolio** [comment]
I thought I saw a more recent issue about this, but maybe it was #357 about damaged xor2 chunks.  Anyway, here is a set of functions and aliases to dump the metadata and then backtrack the file which belongs to a given chunk:
```
alias MissingChunks='m="has only invalid copies";l="/var/log/daemon.log";echo " MCS=\""$(grep "$m" $l|tail -n10|cut -f4- -d\:|sort -u|cut -f3 -d\ |sed s/^0*//g)"\" # Of `grep "$m" $l|cut -f4- -d\:|sort -u|grep -c ""` Missing Chunk IDs"'
function EstimateDumpSize { md=/var/lib/mfs/metadata.mfs;if [ -f $md.dump ] ; then MDS=`stat -c%s $md.dump` ; else MDS=$((`stat -c%s $md`*3/1000000*1000000)) ; fi ; export MDS ;}
# Note: The above *3 is using the metadata.mfs size * Three to over estimate the .dump size and /1000000*1000000 to remove precision from such an estimate
function EnoughFreeToDumpMSG { echo "May not have enough free space for dump. $FS less than $MDS. Press a key to continue anyway." ; read foo ;}
function EnoughFreeToDump { EstimateDumpSize ; FS=$((`df /var/lib/mfs/|tail -n1|awk '{print $4}'`*1000)) ; if [ $FS -lt $MDS ] ; then export FS; EnoughFreeToDumpMSG ; fi ;}
# Alias to dump metadata to human form as .dump file
alias MakeMetaDump='EnoughFreeToDump ; md=/var/lib/mfs/metadata.mfs;mfsmetadump $md | pv -tbrw60 -ps $MDS >| $md.dump' # Requires that pv be installed
alias IdentifyMissingChunkFiles='mdd=/var/lib/mfs/metadata.mfs.dump;for MC in $MCS ; do\
 echo -en " MC=$MC";I=$(echo $(grep $MC $mdd|cut -f2 -d\||grep "i: "|cut -b3-)) ;\
 echo -en "(I=$I)";for i in $I;do E=$(grep -e "|c: *$i|" $mdd);N=$(echo $E|cut -f4- -d\:) ;\
 echo -en "\n  N=$N";Pa=$(echo $E|cut -f2 -d\||cut -f2 -d\:); Path="/$N" ;\
 while [[ $Pa -ne 1 ]] ; do P=$(grep -m1 -e "|c: *$Pa|" $mdd);Pa=$(echo $P|cut -f2 -d\||cut -f2 -d\:);N=$(echo $P|cut -f4- -d\:);Path="/$N$Path";echo -en " ,$N";done ;\
 echo -en "\n   mfsfilerepair \"\$RootMount$Path\" # mfsfileinfo" ; done ; done ; echo -en "\n RootMount=$(mount|grep "mfs#"|head -n1|cut -f3 -d\ ) # Best Guess for your \$RootMount\n"'
 echo " Use: MissingChunks ; MakeMetaDump # Then IdentifyMissingChunkFiles # to identify and mfsfilerepair files with missing chunks."
```
Was fun to write this, hope it helps someone, looking forward to a native mfstool way of accomplishing this...

**Comment by kerneltravel** [comment]
> Thanks for quick replies guys. :)
> 
> I found the damaged file using
> 
> ```
> find /mnt/lizardfs/temp -type f -exec sh -c 'mfsfileinfo "{}" | grep -q "no valid copies" && echo "{}";' \;
> ```
example, to findout which file with lower valid chunks(assume the safy required chunks copies should be 3),then use this command to find out the "bad" files (chunks copies count less then 3)
find /mnt/lizardfs/temp -type f -exec sh -c 'mfsfileinfo "{}" | grep -q -c  "copy 3"  || echo "{}";' \;
