### ISSUE TITLE
Multimaster Sharding

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#224]
Let's pretend we have a folder structure as follows:

/
/Red
/Blue
/Green

We have three masters, distributed among three racks. The Red rack contains data from Group Red, the Blue and Green contain data from the Blue and Green groups respectively.

How do we provide adequate write speeds for each of them, assuming that 80% of a single metamaster is the most each group uses at peak loads?

I propose, similar to large databases, a sharding solution. We assign Red's master as the authoritative source for /Red, Blue's master as the authoritative source for /Blue and so on. As writes come in, (similar to #223) we redirect them to the appropriate server (alternatively, clients could be slightly more intelligent and automatically handle that). Lazy replication (synchronous where possible) would be used to then bring the whole cluster to parity.

In this way we could have horizontally scalable read workloads (see #223) and horizontally scalable write workloads to a limited but effective extent.

~ B

**Comment by 4Dolio** [comment]
So then segmenting ones dataset into multiple clusters is the only near term solution for things like distributing load among multiple cores? Has anyone attempted to execute such an environment? Any tips? Speculations? Thought experiments?

I'm considering running masters as Xen VM instances with multiple chunkservers at non-standard ports for each virtual metadata fragment. comments? I have already played around with some of this with some raspberry pi and external disks where each disk is it's own unique chunk service which could easily be attached to a different pi and includes a metalogger copy of the metadata so to be capable of acting independently if needed. But I digress.

**Comment by Zorlin** [comment]
Using Xen VMs might not be the most efficient method, but would probably
work. Maybe you could use Docker instances?
