### ISSUE TITLE
Chunk loss on unclean shutdown of master during changes

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#230]
Hey there,

Recently we had a master (and everything else) go down hard due to sudden power loss. Unfortunately our UPS had failed recently so we lost power immediately. Some users were in the middle of writes and they were obviously lost - that's perfectly reasonable. However, the files they were writing to were in some cases lost - a total of about 6 files. My coworker did some digging and believes he found the issue - the chunk revision was either too new  or too old (chunkserver wrote chunks, master wrote metadata, but did not yet flush it to disk) to be seen as valid.

So the question is - how do chunk revisions get used? Is it possible we could do something like "when a chunk's latest revision is not accessible or valid, try the revision one higher and then one lower if that fails" in order to avoid deleting files/chunks if they are being written to during power loss?

**Comment by onlyjob** [comment]
@Zorlin, you can be the first one to add details of your LizardFS cluster to wiki: https://github.com/lizardfs/lizardfs/wiki/Notable-users :)

**Comment by onlyjob** [comment]
I think this bug can be closed -- I could not find anything actionable by LizardFS developers in regards to power loss... I think maybe "continuous snapshotting" feature #281 can be the answer to preserving consistent state of file system for potential roll-back after power loss.

**Comment by Zorlin** [comment]
I would love to - it won't be a particularly big cluster, however. (Likely
below 1TB)

**Comment by onlyjob** [comment]
>  it won't be a particularly big cluster, however. (Likely below 1TB)

So [University](https://github.com/lizardfs/lizardfs/issues/230#issuecomment-68123510) still uses MooseFS?

**Comment by Zorlin** [comment]
I no longer work for them, as I moved to Australia. Hopefully they can
chime in, as they follow this list :)

**Comment by onlyjob** [comment]
> I moved to Australia

Awesome! :) We should meet some day if you are coming to Sydney. :)

**Comment by 4Dolio** [comment]
...Chiming in as I am still watching. Yes, the briliant Zorlin used to work with me at DigiPen. We have 2 active LizardFS 2.6.10 clusters and im hoping to migrate our main cluster from MooseFS 1.6? within a week or so.  Our masters are being upgraded from 128 to 256GB Ram.  At home i have a little raspberrypi, banannapi, odroid-xu4 cluster for fun.

I managed to get corosync on Debian7 working after lots of work to the crm script, ill find time to do a pull request soon.  Also recently found a half dozen bugs /quarkes /typos that were preventing me from compiling 2.6.10 on our FreeBSD 9.3 chunk servers.  I have yet to look at the master 3.x branch...

Perhaps someday ill also get around to adding ourselves to the users table. Happy holidays everyone.

**Comment by Zorlin** [comment]
@4Dolio Happy holidays to you too. I wish you a smooth upgrade :) Good luck!

**Comment by guestisp** [comment]
Is this still open ?

**Comment by psarna** [comment]
Well, yes, but it doesn't look like it should be anymore. I'm closing the issue, if anyone wants it reopened, just post something here.
