### ISSUE TITLE
Add an option to allow multiple copies on a single host to count towards goals

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#231]
Hi there,

I've run into some interesting use cases for people who need to store massive amounts of data but for whatever reason (can't afford to, don't want to, etc) want to store it on a single machine. It would be very cool if you could enable LizardFS to recognize each disk/brick/volume of data as separate and count them towards the goals.

Enabling single-system usage of LizardFS is a very strange use case, but it makes sense and as a bonus it may help ease people into the use of the system.

**Comment by 4Dolio** [comment]
As marcinsulikowski has already pointed out, configuring multiple chunkservers each with their own hdd.conf and unique port it is possible to do this already. As such I do not believe there is a need for any changes to support this request other than perhaps documenting that it is already possible.

**Comment by onlyjob** [comment]
> As such I do not believe there is a need for any changes to support this request other than perhaps documenting that it is already possible.

Agreed. It is easy to setup and operate more than one chunkserver per host.
I think we can close this bug.

**Comment by hradec** [comment]
You can setup multiple chunkservers on the same machine very easily with docker. 

```
docker run -d --restart always --net=host  -e MASTER_HOST=localhost \
     --name=chunk_HD01  \
     -e MFS_CSSERV_LISTEN_PORT=9460 \
     -e MFS_LABEL=HD01 \
     -v /mnt/HD01/:/mnt/HD01:rw \
     -e ACTION=chunk   hradec/docker_lizardfs_git 

docker run -d --restart always --net=host  -e MASTER_HOST=localhost \
     --name=chunk_HD02 \
     -e MFS_CSSERV_LISTEN_PORT=9461 \
     -e MFS_LABEL=HD02 \
     -v /mnt/HD02/:/mnt/HD02:rw \
     -e ACTION=chunk   hradec/docker_lizardfs_git 
```

where your first hard drive is mounted at /mnt/HD1, the second at /mnt/HD2, and son on... 

This docker image let you set ANY of the mfschunkserver.conf options by using `-e MFS_<option name>` in the command line.  (as for example, the chunkserver port number - ` -e MFS_CSSERV_LISTEN_PORT=9461 `)

The image can be used to start any of the servers, include metalogger, shadow, master and cgi. Just set the server in the `-e ACTION=<server name>`

running the image like this:
`docker run -ti --rm hradec/docker_lizardfs_git`

will display a quick help on how to use it! 

my 2 cents...
-H
