### ISSUE TITLE
Create "Gitter" chatroom

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#238]
Hi there,

I've noticed a ton of open source projects have started using "Gitter" for development and discussion. I think it would be awesome for this project - it uses your GitHub login so there's little friction for users, it's free for public rooms and it's a lot more suitable for asynchronous discussion than IRC is.

You can see a demo here: https://gitter.im/gogits/gogs

Anyways, just a thought. Let me know yours :)

~ b

**Comment by pbeza** [comment]
Ready: https://gitter.im/lizardfs/ :+1: :-)
