### ISSUE TITLE
cgi: automatic refresh feature

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#241]
I'm looking forward to see automatic refresh feature -- perhaps something like a drop-down list (next to tabs in the upper-right corner)  with options how often to refresh (30 sec, 1 min, 2 min, 3 min, 5 min, 10 min, 20 min, never).

**Comment by 4Dolio** [comment]
might as well... ;)

**Comment by psarna** [comment]
I'm just here to clean up old issues, but I actually have a comment here. I think it's better to use a browser plugin that provides auto refresh (and every decent browser has at least one such plugin).  Also, cgi interface needs to contact master/chunkservers to gather information every time it is refreshed, so auto-refreshing too often and on too many machines could affect performance (a little bit, but still).
