### ISSUE TITLE
cgi: please add time stamp

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#242]
In the CGI interface it will be useful to have date/time stamp to show when page was generated.

**Comment by 4Dolio** [comment]
This would be a nice enhancement.

**Comment by pbeza** [comment]
Will be [merged][1] soon. :-)

Besides adding timestamp I've also added Python version and improved CGI code quality with [`autopep8`][2].

This is how it looks like with new footer:
![Screenshot from 2019-06-07 12-25-46](https://user-images.githubusercontent.com/3036218/59098151-d8744200-891f-11e9-8056-e8bbc2a6e9b6.png)



[1]: http://cr.skytechnology.pl:8081/#/c/3351/
[2]: https://github.com/hhatto/autopep8
