### ISSUE TITLE
cgi: Shadow server not display on website "Metadata Backup Loggers"

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#243]
I compiled and installed version of the GIT and via the website do not see the "Metadata Backup Loggers" Shadow Server
From what I noticed this happens after installation lizardfs-master because as I will return to last year's version of the server shows up correctly now.

![lfs-master](https://cloud.githubusercontent.com/assets/7813646/5728067/cbb2f52a-9b67-11e4-9c92-81f326bfe655.jpg)

**Comment by marcinsulikowski** [comment]
Listing shadow masters in the "Metadata Backup Loggers" table has been intentionally removed in a87eba68b7cc59e110a2f7f18f736b534fecb8f7. These servers will be listed on the "Servers" tab in a new table, which will be introduced in the master branch within a week or two.

**Comment by marcinsulikowski** [comment]
If you installed code from git, you can use a command line tool to get a list of shadow master servers: `lizardfs-probe list-metadataservers <master ip> <master port>`. Similar information will be added to the "Servers" tab.

**Comment by andypl78** [comment]
Ok,
Information about changes in the mfs.cgi file would be useful because I modified the page, which now works with bootstrap.
This is an example of what it looks like :)

![lfs](https://cloud.githubusercontent.com/assets/7813646/5736769/1a3c58ae-9bda-11e4-9d39-f8c255f1c71c.png)


Sorry for my poor English I prefer Polish ;)

**Comment by telbizov** [comment]
The CGI page definitely need boostrap-ification. Thank you for doing this and good job. I hope those design changes make it to 2.5.5.

**Comment by andypl78** [comment]
Currently, it works with version 2.5.5 but I look forward to the changes described above.
After the release of 2.5.5 full version will give my work on github ;)

**Comment by Zorlin** [comment]
Drool.

I want that so badly.

**Comment by telbizov** [comment]
I asked this question over the mailing list but I guess no one really reads/cares about it. Do you guys know when the next release 2.5.5 is roughly scheduled to be released?

**Comment by Zorlin** [comment]
When it's done :)

**Comment by onlyjob** [comment]
LizardFS team and myself are working towards next release so please don't say "no one really cares". There were many changes made, lately.

**Comment by telbizov** [comment]
You misinterpreted my comment. It was referring to the fact that no one really responded to my email, not that no one works on the next release. I can clearly see the commits in the repo.

I simply think that this kind of discussion is better suited for the mailing list rather than github issues. But it seems like no one really cares about the mailing list since we have them over here and there's no traffic on the mailing list. That's all.

I appreciate yours and everyone else's contribution to LizardFS. I also try to contribute with bug reports and suggestions as you personally are well aware of.

**Comment by onlyjob** [comment]
@telbizov: No worries, mate. :) Actually I replied to you in the mail list on 2015-01-13 but strangely enough I do not see my response in the mail list archive... :(

**Comment by telbizov** [comment]
@onlyjob ha ... I never received it either. Neither have I received any other email from that list, but again I recently subscribed myself.

Lastly I would only suggest again that there's some sort of a reference for that mailing list address on the web page. Oh, ah make sure that the mailing list actually works ;)

**Comment by onlyjob** [comment]
It could be that my last email to mail list is stuck in the quarantine or moderation queue... I can see my previous posts in the archive... Mail list information was recently added to Wiki.

**Comment by marcinsulikowski** [comment]
@telbizov That's strange. I have seen someone replying this mail two days ago... But now I can see that there is no reply on the list.

**Comment by marcinsulikowski** [comment]
We think that at least a release candidate for the next stable release should be available in February. We need to finish Pacemaker integration and test it.

**Comment by andypl78** [comment]
Ok, so we are waiting for new version :)
