### ISSUE TITLE
Custom Goal Labels do not work properly, Over-Replicating.

### ISSUE THREAD

**Issue by 4Dolio** [lizardfs/lizardfs#245]
I hope i am not the only one who when trying to use the recent custom goal labels feature has encountered a situation where objects with such goal labels are replicated to all available chunk servers rather than obeying the goal definitions...  Odd thing is the goal health tab shows that such objects simultaneously need "X copies need added" and "X copied need deleted" when only one of those statements can possibly be true at any one point in time, never both. (Sorry the using the incorrect terms as I do not have access to my cluster at this moment with which to give more accurate examples and configuration examples...  Perhaps I am just doing something horribly wrong...

**Comment by marcinsulikowski** [comment]
Didn't you request creation of copies on chunkservers that don't exist at all? The system works in the way that if ANY requested copy is missing, it won't delete any other copy of such a chunk. For example if you have a goal:
```
11 custom: _ _ label1 label2
```
if there is no chunkserver labelled `label2`, even if chunk has 10 other copies, they won't be deleted until a copy on `label2` is created. In such a scenario CGI will report "1 copy to replicate" and "10 copies to delete".

**Comment by 4Dolio** [comment]
That is good to know, Does the same apply if a "11 custom: label1 label1 label2" but there is only 1*label1 chunkserver?

in my testing cluster I have: mfsgoals.cfg:
11  ALLcampus  : UShhd SGhdd EShdd
12  UScampus   : UShhd UShhd
13  SGcampus   : SGhdd UShhd
14  EScampus   : EShdd UShhd
* There are 2*UShdd and 1 each of EShdd and SGhdd chunkservers, There are also one of USssd and a USjobd1 chunkservers.
I recently attempted lowercasing all of these labels and removing any extra whitespace, no change.  There are only a few files, 4 to 7 each with goals 1 through 10 plus 2 each of these custom labels.  The standard goal labels of {1..10} work properly, but the custom labels do not.  The odd thing is that when a new file is created it initially has the proper chunks in the proper locations, but then it gets replicated up to the number of chunkservers.

Info Tab looks like:
0 	1 	2 	3 	4 	5 	6 	7 	8 	9 	10+ 	all
0 	- 	- 	- 	- 	- 	- 	- 	- 	- 	- 	- 	0
1 	- 	7 	- 	- 	- 	- 	- 	- 	- 	- 	- 	7
2 	- 	- 	4 	- 	- 	- 	6 	- 	- 	- 	- 	10
3 	- 	- 	- 	7 	- 	- 	2 	- 	- 	- 	- 	9
4 	- 	- 	- 	- 	4 	- 	- 	- 	- 	- 	- 	4
5 	- 	- 	- 	- 	- 	4 	- 	- 	- 	- 	- 	4
6 	- 	- 	- 	- 	- 	- 	4 	- 	- 	- 	- 	4
7 	- 	- 	- 	- 	- 	- 	4 	- 	- 	- 	- 	4
8 	- 	- 	- 	- 	- 	- 	4 	- 	- 	- 	- 	4
9 	- 	- 	- 	- 	- 	- 	4 	- 	- 	- 	- 	4
10+ 	- 	- 	- 	- 	- 	- 	4 	- 	- 	- 	- 	4
all 1+ 	0 	7 	4 	7 	4 	4 	28 	0 	0 	0 	0 	54

Chunks Tab looks like:
to replicate:...
1	7	-	-	-	-	-	-	-	-	-	-
2	4	-	-	-	-	-	-	-	-	-	-
3	7	-	-	-	-	-	-	-	-	-	-
4	4	-	-	-	-	-	-	-	-	-	-
5	4	-	-	-	-	-	-	-	-	-	-
6	4	-	-	-	-	-	-	-	-	-	-
7	-	4	-	-	-	-	-	-	-	-	-
8	-	-	4	-	-	-	-	-	-	-	-
9	-	-	-	4	-	-	-	-	-	-	-
10	-	-	-	-	4	-	-	-	-	-	-
allcampus	-	2	-	-	-	-	-	-	-	-	-
uscampus	-	-	2	-	-	-	-	-	-	-	-
sgcampus	-	2	-	-	-	-	-	-	-	-	-
escampus	-	2	-	-	-	-	-	-	-	-	-
all	30	10	6	4	4	-	-	-	-	-	-

to delete:...
1	7	-	-	-	-	-	-	-	-	-	-
2	4	-	-	-	-	-	-	-	-	-	-
3	7	-	-	-	-	-	-	-	-	-	-
4	4	-	-	-	-	-	-	-	-	-	-
5	4	-	-	-	-	-	-	-	-	-	-
6	4	-	-	-	-	-	-	-	-	-	-
7	4	-	-	-	-	-	-	-	-	-	-
8	4	-	-	-	-	-	-	-	-	-	-
9	4	-	-	-	-	-	-	-	-	-	-
10	4	-	-	-	-	-	-	-	-	-	-
allcampus	-	-	-	-	2	-	-	-	-	-	-
uscampus	-	-	-	-	-	-	2	-	-	-	-
sgcampus	-	-	-	-	-	2	-	-	-	-	-
escampus	-	-	-	-	-	2	-	-	-	-	-
all	46	-	-	-	2	4	2	-	-	-	-

**Comment by 4Dolio** [comment]
I'm still a little uneasy about this behavior of replicating everywhere well beyond the goal count...

Imagine a cluster of 5* "small" chunkservers and 1*"huge" chunkservers.
huge is so large it can store the entire dataset, but the combination of the 5*small results in >50% use of each small.  You might use the custom label to enforce the huge is guaranteed to get 1 copy of everything.  But it huge were to go offline, all 5 smalls would attempt to all keep 1 copy of everything, rather than the missing label "huge" simply being satisfied by one copy on _(any server)...

Wouldn't it be more appropriate to treat a missing chunkserver label as _(any) rather than *(everywhere)?

**Comment by 4Dolio** [comment]
It would be great if a labeled chunkserver defined in a custom goal is not online that it be presented in bold red on the cgi labels tab.

Some possible solutions. Add a new option to goal config lines. Add a new field following another : seperator. I'm listing a bunch of options, only _ and 0 and 1 are important, the rest are just other ideas.
* * (current broken behaviour, replicate everywhere if any target is missing, which I think is a bug)
* _ (treat all missing targets as if they were _)
* 0 (do not replicate for missing targets)
* 1 (treat all missing targets as if it were a single _, so replicate once to anywhere)
* 2+ (treat up to 2 missing targets as if they were _ _, so replicate twice to anywhere, continue for greater numbers...)
* TargetC (if A or B are missing then replicate only to C, if C is unavailable treat as if it were 0 and don't replicate)
* TargetC TargetD (similar to above... use C first, then use D, else use nothing.)

Examples:
9 GoalLabelNormal: TarbetA TargetB: _ # new default
10 GoalLabelA: targetA targetB: * # current default behaviour
11 GoalLabelB: targetA targetB: 0 # no replication if A or B are missing
12 GoalLabelC: targetC targetD: 1 # replicate anywhere once if C or D are missing
13 GoalLabelD: targetC targetD: 2 # replicate anywhere up to twice if C and D are missing
13 GoalLabelE: targetE targetF: targetA # replicate only to A if E or F are missing.

Anyother possible config format could be to follow each target with what to do if it is missing. Like:
9 GoalLabelA: targetA targetB(_) targetC(targetD targetE)
Here, if A is missing do nothing, if B is missing use _(any), if C is missing use D or E.

**Comment by marcinsulikowski** [comment]
> Wouldn't it be more appropriate to treat a missing chunkserver label as _(any) rather than *(everywhere)?

This is what we do. If you have a goal like this:
```
11 goal: main branchA
```
and all `branchA` servers disappear, LizardFS will replicate *one* copy of each missing chunk on a random server. It should not create more replicas than needed, but if such superfluous replicas exist for any reason, it won't remove them.
```
11 goal: label label label
```
means `3 copies on servers labelled 'label'`, but if there not enough `label` servers, some randomly chosen servers would be used instead to maintain at least 3 copies.

**Comment by marcinsulikowski** [comment]
> replicate everywhere if any target is missing, which I think is a bug

If this is true, you are right.

**Comment by 4Dolio** [comment]
Yes, it appears that every CHUNKS_LOOP_MIN_TIME it replicates to one additional chunkserver while attempting to handle the missing named chunkserver.

I'm curious if we could have a discussion regarding this behaviour.  I think there may be good reason to change the default behaviour or add an option such that a missing named chunkserver does not cause any replication.  If not then perhaps adding a new configuration option which does so.

Perhaps a new option similar to:
  *CHUNKS_REBALANCING_BETWEEN_LABELS*::
Call it CHUNKS_REBALANCING_MISSING_LABELS*::
* 0 = no rebalance when missing labels
* 1 = rebalance to _ in place of missing labels (current intended behaviour)

**Comment by marcinsulikowski** [comment]
When designing this mechanism we were thinking like this: if there are no servers to satisfy given constraints (e.g., someone requested creation of copies on servers labelled `xxx`, but there are no such servers), then something must be really wrong. If something is really wrong, there is no possibility to act correctly, so LizardFS should at least save data from being lost. Really, no servers is definitely not a normal situation :). In such case, LizardFS tries to make data safe by keeping number of replicas greater of equal to the desired number of replicas, even if it has to choose a server that user doesn't expect to be chosen. For example in case of a goal `some_goal: locationA locatioB` (a typo in the second label) keeping only a single replica in `locationA` is probably never a good idea -- any single failure might cause a loss of data. Moreover, in case of two typos `some_goal: locatioA locatioB`, creating chunks with no copies is probably even worse.

Indeed, creating a copy on all chunkservers make data safe, but is unacceptable for other reasons :). This is a bug and a bugfix is almost ready (http://cr.skytechnology.pl:8081/#/c/1446/) -- it needs a review, tests and will eventually be released. Thank you for reporting it.

**Comment by 4Dolio** [comment]
Thank you for the bug fix!

I hope you do not mind me starting a new feature request for CHUNKS_IGNORE_MISSING_LABELS option type options.
