### ISSUE TITLE
mfs.cgi - Server Charts change range not working.

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#247]
As the topic.

![lfs-cs-range](https://cloud.githubusercontent.com/assets/7813646/5886852/3d1fad72-a3b3-11e4-8418-e8f71850c610.jpg)

**Comment by marcinsulikowski** [comment]
Ranges don't work at all? I have no problems with these ranges...

**Comment by andypl78** [comment]
Tested FF35 / IE11 / Chrome 40.0.2214.91 64bit on any of these does not work.

**Comment by andypl78** [comment]
Can you send me your version mfs.cgi?

**Comment by marcinsulikowski** [comment]
Now we can see that this works only if you have more than one server, this is why I didn't have problems with these ranges. We will try to fix it also for a single server case.
