### ISSUE TITLE
preferring local chunkserver on read/write hurts performance

### ISSUE THREAD

**Issue by eigood** [lizardfs/lizardfs#250]
We have a moosefs installation(1.6.25).  We have been investigating lizardfs as an upgrade.  Yesterday, we finally figured out what had been hurting the cluster-wide performance degradation.

First, the environment.  6 disk-nodes, with 4 1TB drives in a raid-0.  2 extra cpu-only nodes.  All 8 machines run libvirt+kvm, managed by opennebula.  This means the disk-nodes also have mfsmount/client-access.

The issue we were having, was that performance across all machines was super slow.  Reads, writes, everything.  This turned out to be a very busy READ-centric mysql server, with a few WRITEs happening.  Moving the instance to a cpu-only machine fixed the problem.

I believe this issue is the fact that mfs-master does a chunkserver sort, and prefers a local chunkserver for data access.  However, when the heavy IO machine is hosted on a disk-node, then all these extra READ/WRITE requests get shoved into the local kernel, without any regard for any other requests coming from remote mfsmount operations.  We saw this through iotop; the jbd thread for the ext4 filesystem was getting lots of iotime, and lots of wait.

We think it would be better to have an option to turn off this prefer-local-chunkserver sort.  I have looked at moosefs/mfsmaster/chunks.c, and lizardfs/src/master/chunks.cc, and both have the distance=0 when chunkserver->ip==cuip scenario.

**Comment by eigood** [comment]
Another part of the infrastructure, is our disk network is isolated, on an infiniband substrate.  I can get 700MB/s using wget+apache.  The 4-disk raid0 gives 350MB/s(or so).  Loop-mounted virtual-machine image files on each host give 100MB/s; inside kvm we get about the same.

**Comment by eigood** [comment]
For reference, this was original described as a "feature" here: http://www.moosefs.org/news-reader/items/rack-awareness.html

**Comment by eigood** [comment]
Ok, I have a patch for this; I've tested it locally, and it seems to work.  I'll submit a merge request sometime during the next day.

**Comment by Zorlin** [comment]
@eigood Any updates?

**Comment by onlyjob** [comment]
I think in most cases it is correct behaviour to prefer local chunkserver(s). It would be nice to keep this behaviour by default but maybe it could be useful for some to have a client-side configuration option whether to prefer local chunkserver or randomise access among all chunkservers including local one. Interestingly GfarmFS have such option: `direct_local_access`.
Usually local HDDs have greater IO throughput than network but I imagine there might be cases when random IO is so intensive that it may be better to spread it among all chunkservers...

**Comment by eigood** [comment]
The issue we have seen in production use is that a client that is running locally on a chunkserver will have all it's read and write requests serviced by the local chunkserver.  If the client is very very very busy, then *all* requests go to the local node(for chunks that are stored locally). Reads and writes both.  If the goal is > 1, then a remote node might not be busy, so it would be better to possibly read from remote, instead of local.  Sometimes.

Which is why my patch removes this preference(it basically skips that first check), and gives random distribution over the remaining replicated chunks.  It defaults to the current mechanism, and only skips local when the option is set.

Without it, a local client can only get read speed to the max of a single chunkserver.  With the patch turned on, the read spead of the *entire* cluster becomes available, as a read could be local or remote.

Our network consists of 6 disks in a raid0, and then 10G infiniband.  The network is faster than the disk.

We have seen a single busy client having many reads, overload the local chunkserver, and then remote clients on other nodes can no longer be serviced, and the whole cluster starts to degrade.

As for update to my patch, I haven't been able to deploy it on anything in production yet, and I have no test case either.

I just made a pull request for this.

**Comment by ciroiriarte** [comment]
I think the optional change makes sense. Nutanix for example priorice
locality also, but provides "in host tiering" to solve this kind of i/o
hogging, moving the most accessed blocks to faster local disks.

Regards,
CI.-

**Comment by htbase** [comment]
Does Nutanix uses anything from Lizard?

**Comment by eigood** [comment]
Ok, this is a self-bump again.  We are finally working towards deployment of a new cluster.  I've got 3 nodes with 4 2G drives each, using ext4 with external journals on a 2-drive raid0 ssd.  Running lizardfs 2.6.0.

With goal 3(so a copy of each chunk is on each machine), I see an increase in performance when I stop  the local chunkserver.  This is showing that the prefer-local method still has merit.

I'm continuing to test

**Comment by eigood** [comment]
As an update, our storage network is infiniband, still, at 10G.  wget/apache gives 937MB/s over this fabric.

**Comment by onlyjob** [comment]
I find "prefer-local" to be very useful. It allows me to control location of the data using goals/labels and schedule I/O intensive jobs to machine/chunkserver with most of the data in order to reduce cluster-wide impact. Without "prefer-local" I/O is more distributed but also affect other workloads and cause (more) congestion on network.  @eigood, I understand that you are probably not concerned about network congestion but it is important for us on our 60 TiB cluster where all users have their `/home` folders on LizardFS hence everybody sensitive to latency and I/O time.
As discussed earlier, "prefer-local" should be configurable...

**Comment by htbase** [comment]
How do we get the "prefer-local" setup? I've looked at the topology file but its not every explanatory

We have 3 servers with 6 SSDs each (1TB each) and files distributed across the 3 servers. We want to try and get the prefer-local setup to see if we get performance improvement as of now, its going at half of what Gluster does

**Comment by eigood** [comment]
@htbase it's not in the standard software, but is a patch listed from here.

**Comment by htbase** [comment]
Thanks

Any guidelines or advices on performance tuning? We can't get our guest vms to go beyond 20K IOS while with GlusterFS we were getting around 40K

**Comment by Zorlin** [comment]
@eigood - Six disks in a RAID-0? That sounds like a great way to lose data :/

**Comment by schue** [comment]
If the cluster has 160 drives and each local machine has 4 then the local process can peg the local drives to the point that other remote network requests are serviced very poorly. It isn't so much about the local process getting poor performance. In fact, it gets pretty great performance. The problem is that the the rest of the cluster has trouble getting its requests serviced.

Does LizardFS notice if a particular chunkserver is saturated with IO and redirect requests to other units in the cluster? If it does not then that might be a better solution than disabling prefer local... depending on the workload.

**Comment by Blackpaw** [comment]
Where are we at with 3.11.3? is there a way to disable the "prefer local chunkserver" ?

**Comment by 4Dolio** [comment]
I concur, it would be nice to have an option to tune this hard coded preference...

**Comment by psarna** [comment]
Guys, this commit was merged a long while ago :)
https://github.com/lizardfs/lizardfs/commit/6f6cb80ed5d663999f09eb207bc146fbe2711d9c
