### ISSUE TITLE
After restart LFS 2.5.4 missing chunks

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#251]
Hi,
After shutdown clients/chunk/master-shadow and up master-shadow/chunk/clients a have a thousand missing files.
How to repair this ?

Need copies: 185473 Valid copies:0

Regards

**Comment by marcinsulikowski** [comment]
Are all the chunkservers connected? Do you see any strange things in "Info", "Disks" or "Servers" tab in the CGI interface?

**Comment by andypl78** [comment]
At the moment, I had to restore the data from backup and clear the Master and Chunks servers.
From what I remember it was evident Chunk servers.
The data is set Goal2 so if there were a second chunk should not show approx. 182,000 copies of files as Needed copies: 2, Valid Copies: 0

I tried to use it but the contents of a script file could not be read

#!/bin/bash
find /data/lfs/data -type f -exec sh -c 'mfsfileinfo "{}" | grep -q "no valid copies" && echo "{}" && mfsfilerepair "{}";' \;

**Comment by onlyjob** [comment]
Some repair instructions can be found in #222.
Related problem #342 was recently fixed in release 3.9.4 so I believe this bug can be closed.
