### ISSUE TITLE
replication sometimes needs all chunkservers

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#253]
Most of our LizardFS cluster lives on volatile machines (e.g. floor of workstations with chunkservers).
Naturally most of the time one or more chunkservers are down (suspended or off) and this is normal and expected mode of operation. It works very well with replication level 3 or above. We only had to increase `REPLICATIONS_DELAY_DISCONNECT` to delay migration of data from temporary offline chunkservers (e.g. workstation is switched off or suspended overnight). This has been proven to work well for several weeks on 2.5.4.2.

Lately we introduced custom goal "r6" to isolate single replica on dedicated server with RAID-6 backend. This data is mostly archival, rarely needed stuff that only few people occasionally need to access. When we mark some folders with `mfssetgoal -r r6` we observe how data flows from regular chunkservers to designated "r6" server.

The problem is that data migration to "r6" only works when all chunkservers are up and running -- no chunks replicate to "r6" if one regular (volatile) chunkserver is down.
It is probably a bug and we would very much like it fixed -- when goal is updated data should be replicating even in degraded mode when not all chunkservers are available.
Thanks.

**Comment by aniezurawski** [comment]
Hello onlyjob,
Thank you for your report. This problem actually exists and I think I found out the reason.
We will try to fix it soon.

**Comment by onlyjob** [comment]
Very good, thanks. Please let me know when you have something to test.

**Comment by kazik208** [comment]
[Here](http://cr.skytechnology.pl:8081/#/c/1522/) is a fix we are working on.

**Comment by onlyjob** [comment]
@kazik208, this fix works pretty well -- thank you very much. I stopped few chunkservers and changed goal on a folder: as expected data started to migrate onto designated labels. The only strange thing is that target goal was defined as 2 replicas and at first data was copied only to first server. After when "2 copies to replicate" counter run down to zero data started to flow to second chunkserver as per "1 copy to replicate". Somehow I thought that both replicas would be created simultaneously. This behaviour is _probably_ normal, I'm just not sure.
In any case fix improved situation a lot. Great work, guys. :)
