### ISSUE TITLE
tool to delete snapshots

### ISSUE THREAD

**Issue by jkiebzak** [lizardfs/lizardfs#254]
mfsmakesnapshot does a great job of creating snapshots. Can we have a mfsdelsnapshot ? Its painful when I create a snapshot of a folder with millions of files, and then have to use `find` or `rm` do delete the snapshot later.

**Comment by psarna** [comment]
What interface would you expect from mfsdelsnapshot?
Since mfsmakesnapshot works similarly to *cp -r*, deleting a snapshot with *rm -r* looks like a natural solution.

**Comment by jkiebzak** [comment]
Thanks for the reply.

When using mfsmakesnapshot on a directory structure with 10's or 100's of
millions of files, the operation only takes a few moments ( I don't have
the stats with me at this time). Then, when doing *rm -r* on this newly
created snapshot (with 10's or 100's of millions of files) the operation
take an order of magnitude longer.

I'm running some other stats on my lab equipment right now. If needed, I
can circle back to this and provide real numbers to show the *vast*
difference in time between creating a snapshot and then later trying to *rm
-r* it.

Thanks
Jason

**Comment by psarna** [comment]
Oh ok, I see your point now.

**Comment by 4Dolio** [comment]
humm.. ya.. a special mfsrm might be neat. not sure if it would need to be snapshot specific. My workaround is to have a special /mfsmountpoint/trash/trash folder.  I put things in trash that I can in all likelyhood toss out without any additional consideration.. things in trash/trash get their mfssettrashtime set to 120 seconds and then they are rm'ed by some cron task each evening...  I also purge some things from the mfsmeta/trash too but that's another story...

**Comment by onlyjob** [comment]
My problems with deleting snapshots is not the time of snapshot removal but the fact that removed snapshot ends up in the trash... For example at the moment I have ~10 TiB (~3_000_000 files) of removed snapshots in trash which makes trash practically unusable (because it is very hard and slow to work with directory with millions of files in it)... Yes, there is workaround to use `mfssettrashtime` to set small timeout on snapshot directories before their removal but indeed having an utility to take care of that would be nice.

For example Gfarm file system have all sort of utilities (e.g. `gfchgrp`, `gfchmod`, `gfchown`, `gfln`, `gfls`, `gfmkdir`, `gfmv`, `gfrm`, `gfrmdir`, `gfstat`, etc.) that work even without FUSE.

**Comment by 4Dolio** [comment]
Those Gfarm operations sound neat... I'm still looking firward to additional mfsfiletool? Functions for faster manipulation of bulky metastructures... like mfsdelsnapshot with a -t (no trash time) sort of option...

**Comment by 4Dolio** [comment]
Thought it would be nice to mention #281 continuous snapshotting, which seems related to this issue.  It occurred to me that perhaps another solution might be to add a new behaviour to the mfsmakesnapshot command.  Which currently has an `[-o] allow to overwrite existing objects`.  Which behaves similar to a cp command which is not aware of objects which no longer exist at the source. To contrast rsync can be leveraged to remove and optionally preserve objects which no longer exist in the source.

What if a new option were to be added which could be aware of such differences between the source and target?  Perhaps a new `[-s] allow to supplant or supersede and replace existing directory objects`.  This would allow for the re-use of an existing snapshot which would be far more exact a lazy copy than what -o currently does.  It would also allow for an empty source to supplant a much larger existing target and as such behave like a mfsremovesnapshot command might.

**Comment by TerraTech** [comment]
We are in the same boat, with LizardFS handling multiple large mail spools that have millions of files...  It would be nice if the snapshot removal worked like ZFS does (almost instant including space reclamation)...  The way it works now reminds me of how btrfs removes snapshots via btrfs-cleaner (kernel thread)...  Even though the snapshot removal will eventually run its course, deleting them ala 'rm -r' tacks on a lot of I/O overhead that could best be allocated to delivering client emails...

**Comment by blink69** [comment]
We are working on such a solution, please stand by :)

**Comment by krissfr** [comment]
Hi,
Can we have some informations about the solution where your working on ?

**Comment by psarna** [comment]
Sure. http://cr.skytechnology.pl:8081/#/c/2549/69

**Comment by krissfr** [comment]
Thank you @psarna 

This rremove option will be in the 3.10.5 or later ?

**Comment by psarna** [comment]
3.10.5 most likely.

**Comment by r5r3** [comment]
Such a tool would be highly appreciated! Will it be available in Version 3.10.7?

**Comment by psarna** [comment]
Unfortunately no, but that's just because 3.10.7 will not exist. Due to 
switching to semantic versioning system, the next version will be 3.11.0 
and it would most likely contain `lizardfs rremove`, a tool for 
recursive removal of directories, including snapshots.
