### ISSUE TITLE
increasing the rate of replication.

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#255]
Is it possible to increase the rate of replication? I currently have over 200 thousand files for replication and it takes quite a long time.

**Comment by psarna** [comment]
Have you tried manipulating those values in master config? (Reference: man mfsmaster.cfg)
CHUNKS_LOOP_MIN_TIME
CHUNKS_LOOP_MAX_CPS
CHUNKS_WRITE_REP_LIMIT
CHUNKS_READ_REP_LIMIT

**Comment by andypl78** [comment]
I'm using the default settings.
Changed now only

CHUNKS_WRITE_REP_LIMIT
CHUNKS_READ_REP_LIMIT

And as I see faster replication works.

Thx :)
