### ISSUE TITLE
hdd space bug.

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#256]
In the screenshot below you can see that are displayed incorrectly space used for the chunk servers.
Configuration is the same on both chunk servers.
How do I fix this?

![lfs](https://cloud.githubusercontent.com/assets/7813646/6603455/920a54ca-c822-11e4-8e58-f0861387ce26.jpg)

**Comment by kazik208** [comment]
Are you sure that the same chunks are on both chunkservers?
Some chunks are smaller than 64MB, and therefore the same number of chunks does not imply they will use the same space.
Maybe you have some files with goal 1?

The screenshot you have sent does not show too much information, maybe you could send one with sections=CS|CH|IN

**Comment by andypl78** [comment]
I am using the same version of LFS Chunk.
I made the following steps:
- one Chunk server has been disabled
- removed Chunk server on the Web page
- I removed all the files from the partition on Chunk Server
- run Chunk server
- launched the process of replication
![lfs-ch](https://cloud.githubusercontent.com/assets/7813646/6623143/6a4206ee-c8e1-11e4-9c11-08ef2e27ad9f.jpg)
![lfs-cs](https://cloud.githubusercontent.com/assets/7813646/6623144/6a4293c0-c8e1-11e4-90aa-aeed71d78f42.jpg)
![lfs-in](https://cloud.githubusercontent.com/assets/7813646/6623145/6a42babc-c8e1-11e4-95d5-6677e93ebf5c.jpg)
Now the difference is smaller but is still visible

**Comment by onlyjob** [comment]
I do not recognise a problem here... Free space is reported by underlying file system on chunkserver volume. `HDD_LEAVE_SPACE_DEFAULT` affects reported free space as the value of this variable is added to used space by the chunkserver. Closing as not-a-bug...
