### ISSUE TITLE
Is OSX still supported?

### ISSUE THREAD

**Issue by jedisct1** [lizardfs/lizardfs#259]
LizardFS 1.6.28 used to perfectly work on OSX.

But since version 2.5.0, LizardFS doesn't compile any more on OSX. Neither does version 2.5.4 or the current git code.

Will OSX be supported again or has support for it being abandoned?

**Comment by onlyjob** [comment]
You could at least include errors from build log, could you? From the 2.5.4 or _master_ branch please... Hopefully this is easy to fix.

**Comment by jedisct1** [comment]
PR #260
