### ISSUE TITLE
"master query: receive error" during snapshotting

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#267]
I'm getting `master query: receive error` when I snapshot some directories using `mfsmakesnapshot`. Directories are large and have around 750_000 files and over 66_000 directories. 

Resulting snapshot seems to be complete as number of files in the original and in the snapshot folders match. Snapshotting smaller folders exhibit no such problem.

**Comment by 4Dolio** [comment]
I have seen this also, my workaround was to segment the snapshot of large structures into multiple smaller snapshots.  A proper solution would be better..

**Comment by psarna** [comment]
Issues #267 and #283 regarding snapshots are recognised and will most likely be fixed soon. This one is just a timeout warning from mfsmakesnapshot tool, but it will disappear after the fix as well.
