### ISSUE TITLE
How to mount Trash Bin

### ISSUE THREAD

**Issue by devdesco-ceo** [lizardfs/lizardfs#275]
It may sound like a dumb question, bwt how to mount Trash Bin to manually delete trashed items?

**Comment by psarna** [comment]
Use mfsmount with `--meta` parameter. Ref: `man mfsmount`

**Comment by devdesco-ceo** [comment]
Thanks a lot. It is easie to do than I thought! So far I am so happy with the LizardFS after one month struggle and battle with freaking buggy GlusterFS!
