### ISSUE TITLE
client: `-o mfsmemlock` requirements?

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#285]
Client man page `mfsmount(1)` mention `-o mfsmemlock` option that "must be enabled at build time".
But how? Apparently it depends on `RLIMIT_MEMLOCK` definition but I'm not sure what provides it.
Please advise.

**Comment by psarna** [comment]
RLIMIT_MEMLOCK is provided by a kernel header <sys/resource.h>.
This check ensures, that RLIMIT_MEMLOCK is defined so setrlimit(RLIMIT_MEMLOCK,...) call will compile.

"must be **enabled** at build time" is misleading - cmake will check if mlockall function is available and if yes, enable memlock itself. The comment should actually be "must be **available** in operating system"

**Comment by onlyjob** [comment]
Thanks. I'm not sure if MEMLOCK detection is working as expected. I see that `RLIMIT_MEMLOCK` is defined in `asm-generic/resource.h` (linux-libc-dev) and in `bits/resource.h` (libc6-dev) but only `sys/resource.h` is included so perhaps that's why MEMLOCK never works for me...

**Comment by onlyjob** [comment]
Wait a sec, `<bits/resource.h>` is included from `sys/resource.h` so the problem must be somewhere else...

**Comment by psarna** [comment]
If you can see
~~~
-- Looking for mlockall
-- Looking for mlockall - found
~~~
while building and you have RLIMIT_MEMLOCK defined through `<sys/resource.h>` then memlock should work as expected.

**Comment by onlyjob** [comment]
Yes, `mlockall` reported as "found" in build log but feature do not work: when I run `mfsmount -o mfsmemlock` as root it fails with `fuse: unknown option 'mfsmemlock'`. Could it be because `MCL_CURRENT` and `MCL_FUTURE` not defined (see `src/mount/fuse/main.cc` line 53)?

**Comment by psarna** [comment]
Well, if your `sys/mman.h` does not define MCL_CURRENT or MCL_FUTURE, then memlock definitely wouldn't work.

**Comment by onlyjob** [comment]
So that's where MCL_* is defined... Grep shows MCL definitions. I have kernel headers installed yet I can not make MEMLOCK feature to work on Debian despite that `mlockall` is detected during build. I hope you have some ideas...

**Comment by psarna** [comment]
Well, I found the issue.

Here is what the code does now:
1. Checks if MCL_CURRENT and MCL_FUTURE are defined
2. If true, includes `<sys/mman.h>`, which contains definitions of MCL_CURRENT and MCL_FUTURE
~~~
#if defined(LIZARDFS_HAVE_MLOCKALL) && defined(RLIMIT_MEMLOCK) && defined(MCL_CURRENT) && defined(MCL_FUTURE)
#  define MFS_USE_MEMLOCK
#endif

#ifdef MFS_USE_MEMLOCK
#  include <sys/mman.h>
#endif
~~~

which is obviously doomed to fail.
A quick workaround is to replace
~~~
#if defined(LIZARDFS_HAVE_MLOCKALL) && defined(RLIMIT_MEMLOCK) && defined(MCL_CURRENT) && defined(MCL_FUTURE)
~~~
with
~~~
#if defined(LIZARDFS_HAVE_MLOCKALL) && defined(RLIMIT_MEMLOCK)
~~~

and I will prepare a patch with a solution for this today.

**Comment by psarna** [comment]
There you go: http://cr.skytechnology.pl:8081/#/c/1939/

**Comment by onlyjob** [comment]
Nicely done, Piotr. It works. Thank you very much.  :)

**Comment by onlyjob** [comment]
Piotr, could you please double-check that we don't have a similar problem in `main/main.cc` where `sys/mman.h` never gets included because `LIZARDFS_HAVE_SYS_MMAN_H` is not set...

**Comment by onlyjob** [comment]
@psarna, please check [main.cc](../blob/master/src/main/main.cc#L60) for correct inclusion of `sys/mman.h`. Thanks.

**Comment by psarna** [comment]
It's fine, `LIZARDFS_HAVE_SYS_MMAN_H` is set by cmake if `sys/mman.h` exists

**Comment by onlyjob** [comment]
No, @psarna, `LIZARDFS_HAVE_SYS_MMAN_H` is _never_ set by CMAKE as far as I can tell.
Not on 2.6.0 anyway. I'm checking `CMakeCache.txt` and `config.h` in build directory.
How on earth `LIZARDFS_HAVE_SYS_MMAN_H` would be set if it is not defined in `config.h.in`?
When I search for `LIZARDFS_HAVE_SYS_MMAN_H` in LizardFS sources it is found only once in the line 60 of `src/main/main.cc` file.

Would you like me to open a new bug?

**Comment by psarna** [comment]
My bad, it was indeed missing. I'll fix it today. Thanks
