### ISSUE TITLE
master: ENDANGERED_CHUNKS_PRIORITY with volumes marked for removal

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#287]
ENDANGERED_CHUNKS_PRIORITY is a very useful option but it does not work as expected with volume(s) marked for removal. When set to `1` ENDANGERED_CHUNKS_PRIORITY should rescue (i.e. replicate) endangered chunks first however it does so from "regular" view instead of "all" view and therefore prioritise replication of chunks from volumes marked for removal (which are not really endangered because volumes are not removed yet) and leaves really endangered chunks alone for a long time (or maybe even until all chunks from volumes marked for removals are replicated).

**Comment by onlyjob** [comment]
Also chunks with only one replica on the volume marked for removal (those chunks appear as "missing" in regular view) are not prioritised by the `ENDANGERED_CHUNKS_PRIORITY` and stay not replicated for hours while safer chunks are copied around...

**Comment by psarna** [comment]
Noted. We will try to resolve this issues soon.

**Comment by aniezurawski** [comment]
Fixed in 510142e8eb75cb96c4f67870343e639eb1fc7a9e
