### ISSUE TITLE
trash: files with lastmod date in the future are not removed from trash after `trashtime` period

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#288]
I've noticed that amount of files in LizardFS trash is growing. As it turned out files with last modification date in the future are not getting removed from trash. I have some files with last modification date set to year 2020. Every day a snapshot of directory with such file is taken and old snapshot is removed. However more and more files with lastmod date in the future are piling up in trash and not getting removed even after `trashtime` period.

**Comment by onlyjob** [comment]
Team, can we have some attention here please?

The problem is still there and getting worse over time. Once a snapshot is deleted, files with modify time in the future (e.g. 2020) just accumulate in trash and don't get removed.
My trash is growing with files deleted since last year and there are already 20_000+ unremovable files there... :(

**Comment by psarna** [comment]
One way to go is to update access time (or even modification time to avoid
problems with NO_ATIME=1 option) of files being removed and the other is to
treat files with trashtime=0 differently, i.e. remove them immediately
regardless of their access time. I think the first option makes more sense,
thoughts?

Also, I will look into the problem more closely in about 11 hours when my
office hours start, so do not expect immediate answers.

**Comment by onlyjob** [comment]
Thank you, thank you, @psarna. :)
