### ISSUE TITLE
catch-up with MooseFS features

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#292]
According to [announcement](http://www.moosefs.org/news-reader/items/moosefs-30-easter-edition.html) MooseFS introduced the following features:

  * Performance improvement for small file random I/O due to the new semantics for `close()` system call, which now by default has the same behaviour as on any local Linux/FreeBSD filesystem,
  * Support for global locks compatible with POSIX locks and `flock()` advisory lock mechanism when using fuse 2.9+.

I'm looking forward to read comments from LizardFS developers regarding the above features and their potential availability in LizardFS.
Thank you.

**Comment by xavierromero** [comment]
I've also read some new features in MooseFS 3 which I particullary like a lot about setting goals for create/keep/archive.
http://moosefs.com/Content/Downloads/moosefs-labels-manual.pdf

It would be nice a clear roadmap & changelop from lizardfs !

Best regards,
Xavier Romero

**Comment by FlorianHeigl** [comment]
It seems this is very very low priority.
I had tried as friendly as possible to ask for a roadmap... was closed.
https://github.com/lizardfs/lizardfs/issues/173

**Comment by onlyjob** [comment]
Locks are already implemented (but still buggy), see [release notes](https://github.com/lizardfs/lizardfs/releases). As for performance enhancements I'm not sure if they should be attributed to "new semantics for `close()` system call" or to something else. After some tuning 3.9.2 feels faster than 2.6.0 but there are still some problems (and regressions) in 3.9.2...

I agree that it would be nice to see list on features in development somewhere in wiki...

**Comment by onlyjob** [comment]
I suppose this was addressed by release of 3.9.4 so I'm closing this bug.

I'd like to remind developers that users would much appreciate public road map (i.e. list of current and planned development tasks) on wiki (e.g. "changes planned for upcoming release"). Alternatively bugs labelled as "TODO" or "task" can be used...
