### ISSUE TITLE
ignoregid does not seem to be working

### ISSUE THREAD

**Issue by alexcrow** [lizardfs/lizardfs#295]
Hi,

I've just realised that on my Lizardfs setup (for serving files via Samba) that I'd not set ignoregid in my mfsexports file.

I did so and restarted the master server and yet still I am unable to cd into a folder that has an RWX acl for a group that my user has as supplementary.

Is there anything else I need to do to get this to work?

```
> getfacl _test
# file: _test
# owner: root
# group: root
user::rwx
group::rwx
group:IFA_Infrastructure:rwx

---
...

> groups:

... IFA_Infrastructure ...

> cd _test
bash: cd: _test: Permission denied

/etc/mfs/mfsexports.cfg:

# Allow everything but "meta".
*                       /       rw,alldirs,maproot=0,ignoregid
...
```

Thanks,

Alex

**Comment by onlyjob** [comment]
Clients need to be re-{started|mounted} as well...

**Comment by alexcrow** [comment]
I did that too, and restarted all the chunkservers. Still no joy.

Thanks

Alex

**Comment by onlyjob** [comment]
Works for me:

~~~~
+--- a/src/data/mfsexports.cfg
++++ b/src/data/mfsexports.cfg
+@@ -1,6 +1,6 @@
+ # Allow everything but "meta".
+-*                       /       rw,alldirs,maproot=0
++*                       /       rw,alldirs,maproot=0,ignoregid
+ 
+ # Allow "meta".
+ *                       .       rw
+ 
~~~~

It might be worth checking if `mfsexports.cfg` is in correct location as per `EXPORTS_FILENAME`...

**Comment by alexcrow** [comment]
I uncommented the line in mfsmaster.cfg (already pointed to the correct location) and restarted all services, and remounted, but still no luck. I cannot cd into that directory while su'd to the user account that has the correct supplementary group.

Thanks.

**Comment by alexcrow** [comment]
Is the difference in your test that you have the normal permissions for your test directory allowed for the supplementary group, whereas in my case the normal permissions only allow root access, it's just the POSIX ACL entry on the directory that allow access?

**Comment by onlyjob** [comment]
Not sure what could be the problem but `ignoregid` was discussed in #265 and apparently works for everybody... 
One known issue is that re-login may be necessary to apply new group membership in which case utility [newgrp(1)](http://manpages.debian.org/cgi-bin/man.cgi?query=newgrp&apropos=0&sektion=0&manpath=Debian+8+jessie&format=html&locale=en) might be useful.

I suggest to close this bug and move discussion to #265.
