### ISSUE TITLE
Lizardfs Integrate  with  Xenserver6.2

### ISSUE THREAD

**Issue by syuanwei** [lizardfs/lizardfs#301]
Hi,Every:
            I  have successfully deployed lizardfs,and I't work good。Now I want use this file system  integrate  with Xenserver。I use the nfs or iscsi  for xenserver,but the Performance is very low。
who can provide a solution to solve that？？

**Comment by psarna** [comment]
Is nfs/iscsi the bottleneck for sure? If that's the case, you can wait until a native LizardFS driver for Xenserver comes up, but I can really predict how soon it will happen.
