### ISSUE TITLE
reserved directory files are not automatically deleted

### ISSUE THREAD

**Issue by daququ** [lizardfs/lizardfs#306]
lizardfs-mfs Installed already 15 days, but reserved the directory files are not deleted, I restart the cluster, any course can not be deleted, ask me where I can see the reserved file is opened by other processes

**Comment by psarna** [comment]
* A list of reserved files can be seen in meta mountpoint:
~~~
mfsmount --meta -H YOUR_HOST -P YOUR_PORT /tmp/lizardfs-meta
ls /tmp/lizardfs-meta/reserved
~~~
* After seeing what files are reserved, you can try to use lsof to see which process holds it
~~~
lsof | grep file_name
~~~
* Quick fix: Restarting mounts should probably fix your problem quickly

**Comment by onlyjob** [comment]
Could be related to #289...
