### ISSUE TITLE
introduce load as part of chunkserver selection

### ISSUE THREAD

**Issue by cloudweavers** [lizardfs/lizardfs#307]
We are working towards introducing a minimum of load awareness in chunkserver selection; in this sense we are looking at the simple (but effective) mechanism used by the latest MooseFS, where the chunkserver selection is mediated by a csdb_server_is_overloaded function that allows for skipping of servers that are experiencing a load too high (plus a timeoff to get the server time to recover from excessive IO). 
Is something similar planned already? Ideas on better way to do that?

**Comment by psarna** [comment]
Hi Carlo,
implementing load awareness of chunkservers is on our roadmap.
We are aware of MFS's simple solution and we have a bunch of ideas how to do it more precisely and effectively.
Right now we are busy preparing the next release, but once we are done, you can expect chunkserver load awareness to appear in LizardFS.

**Comment by cloudweavers** [comment]
Wonderful! Can I ask if there's a timeline for the next release?

**Comment by psarna** [comment]
Presumably 2/3 weeks.
