### ISSUE TITLE
Compiling mfs-client under CentOS 5

### ISSUE THREAD

**Issue by SyRenity** [lizardfs/lizardfs#311]
I have several legacy servers running on CentOS 5, which I need to connect to LizardFS.

What is the best way to compile the mfs-client (Fuse) for CentOS 5?

**Comment by psarna** [comment]
I assume that CentOS 5 has fuse and libfuse packages available.
I think the most reasonable way would be to download LizardFS sources,
checkout the needed version (e.g. v2.6.0), try and compile them,
see if there are any dependencies missing, add them, recompile and voilà.

**Comment by SyRenity** [comment]
@psarna Tried that with cmake 2.8 and gcc44/g++44, and keep getting following error:

[  6%] Building CXX object src/common/CMakeFiles/mfscommon.dir/setup.cc.o
/opt/lizardfs-2.6.0/src/common/setup.cc: In function ‘void prepareEnvironment()’:
/opt/lizardfs-2.6.0/src/common/setup.cc:34: error: expected initializer before ‘:’ token
/opt/lizardfs-2.6.0/src/common/setup.cc:37: error: expected primary-expression before ‘}’ token
/opt/lizardfs-2.6.0/src/common/setup.cc:37: error: expected ‘;’ before ‘}’ token
/opt/lizardfs-2.6.0/src/common/setup.cc:37: error: expected primary-expression before ‘}’ token
/opt/lizardfs-2.6.0/src/common/setup.cc:37: error: expected ‘)’ before ‘}’ token
/opt/lizardfs-2.6.0/src/common/setup.cc:37: error: expected primary-expression before ‘}’ token
/opt/lizardfs-2.6.0/src/common/setup.cc:37: error: expected ‘;’ before ‘}’ token
/opt/lizardfs-2.6.0/src/common/setup.cc:8: warning: unused variable ‘localeNames’
make[2]: *** [src/common/CMakeFiles/mfscommon.dir/setup.cc.o] Error 1
make[1]: *** [src/common/CMakeFiles/mfscommon.dir/all] Error 2
make: *** [all] Error 2

Any idea?

**Comment by psarna** [comment]
We usually use g++ >= 4.6 and it might be the reason why these errors
occure. Can you perhaps try updating gcc and g++ on your machines?

**Comment by SyRenity** [comment]
Installed 4.7.1 using Scientific Linux repo:
http://linux.web.cern.ch/linux/devtoolset/

Unfortunately the compilation still fails, now at this step:

```
In file included from /opt/lizardfs-2.6.0/src/common/acl_converter.h:4:0,
                 from /opt/lizardfs-2.6.0/src/common/acl_converter.cc:2:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h: In member function ‘size_t PosixAclXattrEntry::write(uint8_t*) const’:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:40:27: error: ‘htole16’ was not declared in this scope
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:42:25: error: ‘htole32’ was not declared in this scope
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h: In member function ‘size_t PosixAclXattrEntry::read(const uint8_t*)’:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:48:27: error: ‘le16toh’ was not declared in this scope
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:50:25: error: ‘le32toh’ was not declared in this scope
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h: In member function ‘size_t PosixAclXattr::write(uint8_t*) const’:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:71:39: error: ‘htole32’ was not declared in this scope
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h: In member function ‘void PosixAclXattr::read(const uint8_t*, uint32_t)’:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:86:30: error: ‘le32toh’ was not declared in this scope
make[2]: *** [src/common/CMakeFiles/mfscommon.dir/acl_converter.cc.o] Error 1
make[1]: *** [src/common/CMakeFiles/mfscommon.dir/all] Error 2
make: *** [all] Error 2
```

Ideas?

**Comment by SyRenity** [comment]
And this with gcc / g++ 4.8.2 from same repo, so it seems a missing system package?

```
In file included from /opt/lizardfs-2.6.0/src/common/acl_converter.h:4:0,
                 from /opt/lizardfs-2.6.0/src/common/acl_converter.cc:2:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h: In member function ‘size_t PosixAclXattrEntry::write(uint8_t*) const’:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:40:27: error: ‘htole16’ was not declared in this scope
   entry->tag = htole16(tag);
                           ^
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:42:25: error: ‘htole32’ was not declared in this scope
   entry->id = htole32(id);
                         ^
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h: In member function ‘size_t PosixAclXattrEntry::read(const uint8_t*)’:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:48:27: error: ‘le16toh’ was not declared in this scope
   tag = le16toh(entry->tag);
                           ^
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:50:25: error: ‘le32toh’ was not declared in this scope
   id = le32toh(entry->id);
                         ^
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h: In member function ‘size_t PosixAclXattr::write(uint8_t*) const’:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:71:39: error: ‘htole32’ was not declared in this scope
   uint32_t leVersion = htole32(version);
                                       ^
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h: In member function ‘void PosixAclXattr::read(const uint8_t*, uint32_t)’:
/opt/lizardfs-2.6.0/src/common/posix_acl_xattr.h:86:30: error: ‘le32toh’ was not declared in this scope
   version = le32toh(leVersion);
                              ^
make[2]: *** [src/common/CMakeFiles/mfscommon.dir/acl_converter.cc.o] Error 1
make[1]: *** [src/common/CMakeFiles/mfscommon.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by DarkHaze** [comment]
It looks like you aren't using the latest version from branch 2.6.0-wip. We have back ported some bug fixes to this branch. One of those patches deals with portable definition of hto* and *toh functions.
I think that looking at file src/common/portable_endian.h may help to explain it.

Otherwise it's possible that some includes are missing from portable_endian.h or you have really old kernel that doesn't define hto* and *toh functions. In that case you need to fix portable_endian.h to use functions available in your system.

**Comment by SyRenity** [comment]
@DarkHaze Managed to compile 2.6.0 for CentOS 5 using __bswap calls.

Thanks everyone for the help!

**Comment by SyRenity** [comment]
@DarkHaze Managed to build 2.6.0 on CentOS 5 / GCC 4,7 using __bswap_32 macros.

Unfortunately 3.9.2 still fails, even on GCC 4.8 with the following error:

```In file included from /opt/lizardfs-source/src/chunkserver/output_buffers.cc:30:0:
/opt/lizardfs-source/src/chunkserver/output_buffers.cc: In constructor ‘AvoidingCopyingOutputBuffer::AvoidingCopyingOutputBuffer(size_t)’:
/opt/lizardfs-source/src/chunkserver/output_buffers.cc:39:56: error: ‘pipe2’ was not declared in this scope
  eassert(pipe2(internalPipeFileDescriptors_, O_NONBLOCK) != -1);
                                                        ^
/opt/lizardfs-source/src/common/massert.h:58:31: note: in definition of macro ‘eassert’
 #define eassert(e) do { if (!(e)) { \
                               ^
make[2]: *** [src/chunkserver/CMakeFiles/chunkserver.dir/output_buffers.cc.o] Error 1```

Any ideas?

**Comment by SyRenity** [comment]
@DarkHaze Also seems I jumped too early, 2.6.0 client compilation fails on fuse, apparently missing some needed bits:

/tmp/lizardfs_rpm_working_directory/BUILD/lizardfs-2.6.0/src/mount/fuse/mfs_fuse.cc: In function ‘LizardClient::Context get_context(fuse_req*&)’:
/tmp/lizardfs_rpm_working_directory/BUILD/lizardfs-2.6.0/src/mount/fuse/mfs_fuse.cc:52:90: error: ‘const struct fuse_ctx’ has no member named ‘umask’
  auto ret = LizardClient::Context(fuse_ctx->uid, fuse_ctx->gid, fuse_ctx->pid, fuse_ctx->umask);
                                                                                          ^
/tmp/lizardfs_rpm_working_directory/BUILD/lizardfs-2.6.0/src/mount/fuse/mfs_fuse.cc:56:39: error: ‘const struct fuse_ctx’ has no member named ‘umask’
  checkTypesEqual(ret.umask, fuse_ctx->umask);
                                       ^
/tmp/lizardfs_rpm_working_directory/BUILD/lizardfs-2.6.0/src/mount/fuse/mfs_fuse.cc: In function ‘void mfs_setattr(fuse_req_t, fuse_ino_t, stat*, int, fuse_file_info*)’:
/tmp/lizardfs_rpm_working_directory/BUILD/lizardfs-2.6.0/src/mount/fuse/mfs_fuse.cc:181:48: error: ‘FUSE_SET_ATTR_ATIME_NOW’ was not declared in this scope
   static_assert(LIZARDFS_SET_ATTR_ATIME_NOW == FUSE_SET_ATTR_ATIME_NOW, "incompatible");
                                                ^
/tmp/lizardfs_rpm_working_directory/BUILD/lizardfs-2.6.0/src/mount/fuse/mfs_fuse.cc:182:48: error: ‘FUSE_SET_ATTR_MTIME_NOW’ was not declared in this scope
   static_assert(LIZARDFS_SET_ATTR_MTIME_NOW == FUSE_SET_ATTR_MTIME_NOW, "incompatible");
                                                ^
Any idea if the above needed or can be safely removed?

**Comment by SyRenity** [comment]
When building the RPM's, getting a2x errors:
a2x: failed: xsltproc  --stringparam callout.graphics 0         --stringparam navig.graphics 0         --stringparam admon.textlabel 1         --stringparam admon.graphics 0 --nonet         "/etc/asciidoc/docbook-xsl/manpage.xsl" "/tmp/lizardfs_rpm_working_directory/BUILD/lizardfs-2.6.0/build-pack/doc/lizardfs-admin.8.xml"

What is the way to disable the man building?

**Comment by SyRenity** [comment]
@DarkHaze Ok, I finally managed to finish the compilation of the RPM's by disabling the docs generation and successfully tested it :).

The only issue I see is the following logs appearing when on client connection to master:
[ OK ] Received IO limits configuration update from master
[WARN] master: tcp recv error: EINTR (Interrupted system call)
[WARN] master: register error (read header: EINTR (Interrupted system call))

They don't seem to influence the normal operations, any idea if I should be concerned about them?

Thanks again for all the help!

**Comment by onlyjob** [comment]
I think there is nothing here left for LizardFS team to do so I'm closing this bug...
