### ISSUE TITLE
Reed-solomon chunk storage

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#312]
Hi there,

I was wondering if LizardFS will eventually implement erasure coding - specifically Reed-Solomon. It would allow for higher fault tolerance than the regular "copies" system currently in use (in theoery) without sacrificing performance. Backblaze has implemented it to great success.

https://www.backblaze.com/blog/reed-solomon/

Would be very cool to see LizardFS doing this at some point.

**Comment by Zorlin** [comment]
Here's a basic port of Backblaze's Java library to C++:
https://github.com/DrPizza/reed-solomon

It's also available in Go:
https://github.com/klauspost/reedsolomon

**Comment by Zorlin** [comment]
Also, I understand that xor goals sort of fill this, but I'd like to be able to control both the number of pieces *and* the number of parity pieces.

**Comment by onlyjob** [comment]
We already have ticket for erasure coding #207...

**Comment by Zorlin** [comment]
Closing as duplicate of #207 - thanks @onlyjob
