### ISSUE TITLE
chunkserver communication timed out-on the node itself

### ISSUE THREAD

**Issue by cloudweavers** [lizardfs/lizardfs#318]
Dear friends, we are testing Lizardfs 3.9.2 using a simple configuration with mfsmaster and mfschunkserver on the same node; IP addresses are properly assigned, kernel is 3.18.17. 
Test is on an empty storage, performed on an SSD; before each test we empty both data and metadata directories, start with an empty metadata and perform a fio and iozone test. With 2.6.0 we find absolutely no problems, with quite stable and normal results.
With 3.9.2 we discover that after a few seconds (2-3 max) the master and the chunkserver lost connection, with no other apparent problems. No strange messages in logs, no errors on console or reported in any way. Just this:
Oct 29 19:17:39 localhost mfsmount[2835]: read file error, inode: 2, index: 0, chunk: 1, version: 1 - Chunkserver communication timed out: 192.168.128.199:9422 (try counter: 1)
Oct 29 19:17:41 localhost mfsmount[2835]: read file error, inode: 2, index: 0, chunk: 1, version: 1 - Chunkserver communication timed out: 192.168.128.199:9422 (try counter: 2)
Oct 29 19:17:43 localhost mfsmount[2835]: read file error, inode: 2, index: 0, chunk: 1, version: 1 - Chunkserver communication timed out: 192.168.128.199:9422 (try counter: 3)
Oct 29 19:17:45 localhost mfsmount[2835]: read file error, inode: 2, index: 0, chunk: 1, version: 1 - Chunkserver communication timed out: 192.168.128.199:9422 (try counter: 4)
Oct 29 19:17:47 localhost mfsmount[2835]: read file error, inode: 2, index: 0, chunk: 1, version: 1 - Chunkserver communication timed out: 192.168.128.199:9422 (try counter: 5)

As both processes are on the same node this (I suppose) means that the chunkserver stopped its communication.

Github is unable to attach binary files, but I made a small 7z with the metadata file and the rest. 
https://drive.google.com/file/d/0B9zGKi6imZ8mYzVlSXJVczd1cnM/view?usp=sharing
and this is the /etc/mfs directory:
https://drive.google.com/file/d/0B9zGKi6imZ8meDNaNXlfZHdhYU0/view?usp=sharing

Is there any parameter that would allow us to see why the chunkserver stopped responding? As I mentioned, 2.6.0 was flawless and worked under many (16) parallel fio processes without breaking a sweat.

**Comment by onlyjob** [comment]
I'm not too sure but I might have seen it too... Can you check if setting `NR_OF_NETWORK_WORKERS` >= 2 helps?

**Comment by cloudweavers** [comment]
Tried (2,3,4,10). It helps a little if there's no load, as soon as load is added it still locks up with the same message. Killing mfsmount and remounting works, but the files that were open are "dead" and trying to open them results in locking of the chunkserver again.

**Comment by psarna** [comment]
Hi Carlo,
can you verify the test with those config values in mfschunkserver.cfg?
~~~
NR_OF_NETWORK_WORKERS=1
NR_OF_HDD_WORKERS_PER_NETWORK_WORKER=10
~~~
These values were hard coded in 2.6.0 and maybe they were just enough not to overload your disk.
From what I can see, if I raise the *NR_OF_NETWORK_WORKERS* and *NR_OF_HDD_WORKERS_PER_NETWORK_WORKER* high enough, it gives me the same error you've got, which is caused by I/O overload.

**Comment by psarna** [comment]
It would be great if you also tried smaller values of *NR_OF_HDD_WORKERS_PER_NETWORK_WORKER*, like 4, 2, 1.

**Comment by cloudweavers** [comment]
Version 3.9.2 With NR_OF_NETWORK_WORKERS=1 and NR_OF_HDD_WORKERS_PER_NETWORK_WORKER=10 works without lockups. Performance is lower than 2.6.0 though; attached is a fast iozone test, where 2.6.0 gets 2x the performance of 3.9.2 (and, for comparison, of MooseFS 3.0)

![moosefs30](https://cloud.githubusercontent.com/assets/5920741/10852242/05f2a1de-7f30-11e5-903d-0158fccb17f0.png)
![lizardfs392](https://cloud.githubusercontent.com/assets/5920741/10852243/05f8f250-7f30-11e5-9998-b6d05f9b168d.png)
![lizardfs260](https://cloud.githubusercontent.com/assets/5920741/10852244/05fc03dc-7f30-11e5-8e00-ed6792c0ee98.png)

IO overload should however not lock up the chunkserver; maybe as a first step a logged message like "IO overload" would be a good first step

**Comment by blink69** [comment]
This perfomance drop is because MFS backward chunk compability, please use 
CREATE_NEW_CHUNKS_IN_MOOSEFS_FORMAT=0
in chunkserver cfg file, all new chunks will be created in new format.
We will set this variable as default in next releases.

**Comment by onlyjob** [comment]
Relevant commit: b3a894f0
My concern for using `CREATE_NEW_CHUNKS_IN_MOOSEFS_FORMAT=0` is #324.
