### ISSUE TITLE
`mfsmetarestore -a` is useless?

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#319]
After abnormal termination (when `.lock` file is left behind) Master fails to start with the following error:

```
stale lockfile exists, consider running `mfsmetarestore -a' to fix problems with your datadir.
```

However `mfsmetarestore -a` does not help: `[FAIL] can't find backed up metadata file` (why doesn't it say a file name that could not be found?).

Either Master suggests wrong command or `mfsmetarestore -a` is useless...

**Comment by Zorlin** [comment]
I feel like this latest release has lots of regressions. I'm curious as to
why.

**Comment by blink69** [comment]
When you use mfsmetarestore -a it should look into mfsmaster.cfg and take DATA_PATH as default. 

We will look on this, for now please use mfsmetarestore -a -d /path/to/metadata

**Comment by onlyjob** [comment]
No, this is not a regression. 2.6.0 behaves exactly like this, as well as 2.5.4.2 (as far as I remember). I had to report it long time ago -- it just came to my attention again...
Actually the only regression I've noticed on 3.9.2 is use of `libtcmalloc` by default (see #316). LizardFS 3.9.2 works quite all right when built without _libtcmalloc_...
At the moment it seems that most (if not all) of the slowness that I've experienced on 3.9.2 can be attributed to _libtcmalloc_...

**Comment by onlyjob** [comment]
Thanks, @blink69.

**Comment by psarna** [comment]
please reopen if it's still valid

**Comment by matthiaz** [comment]
it is still valid
mfsmetarestore -v
version: 3.12.0

**Comment by pbeza** [comment]
@matthiaz Do you know how can I reliably reproduce it?

**Comment by matthiaz** [comment]
Kill the lizardfs master
And then try to restart it.

It will say: run mfsmetarestore -a

If I remember correctly: if you run this on 3.13 and 3.12 no output will be given and nothing will be restored.
If you run this on 3.11 it will give output.

It's only when you manually supply mfsmetarestore -a -d /var/lib/mfsdata.. that it will do something

**Comment by pbeza** [comment]
I'm not able to reproduce it nether using `3.11` nor `3.13`. This is for `3.11`:

![Peek 2019-04-23 14-57](https://user-images.githubusercontent.com/3036218/56583100-13711f00-65d9-11e9-844f-62313e168feb.gif)
