### ISSUE TITLE
master: check loop should pause when chunkserver is joining

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#320]
I've noticed how _check loop_ complained about unavailable files during chunkserver start-up while the latter were still scanning its HDDs:

```
currently unavailable file NNNNNNNN: ...
```

Perhaps master should suspend _check loop_ until chunkservers complete initialisation?

**Comment by onlyjob** [comment]
Related to #347.

**Comment by onlyjob** [comment]
Hit this issue hard this morning on 3.10.0~rc. As soon as master is started, _check loop_ kicked in, even before all chunkservers had a chance to register!
Naturally many "unavailable" files were found (despite the fact that there were no unavailable files at all).
Timeouts and disconnections were observerd on clients and chunkservers when master counted 1_000_000 "unavailable" files. Master slowed down even more when counter reached 3_000_000.
During incident that lasted for over 20 minutes master used almost 100% of one CPU/core.

Solution to this problem is simple and straightforward:

 * Delay _check loop_ until master is fully initialised (i.e. processed all data from chunkservers).
 * Run check loop in low priority to avoid interference with master's functionality, ideally in its own thread to use multiple CPUs in order to minimise performance impact.
 * Suspend or restart _check loop_ if chunkserver joins during _check loop_.

**Comment by onlyjob** [comment]
Some days passed... Any progress delaying premature check loop? Once this problem fixed we should be able to continue working on #422...

**Comment by psarna** [comment]
Hi, I can see that delaying check loop was implemented from ancient 1.6.27 times, but limits are hardcoded - 10 minutes after chunkserver disconnects and 15 minutes after restart. Mentioned code lines are 231 and 243 @ filesystem.cc. Someone will refactor this code to be more sensible and dynamic soon.

**Comment by psarna** [comment]
I believe this patch solved the issue: https://github.com/lizardfs/lizardfs/commit/8d94dd50b57de89763666d8926a27732f375a52b
