### ISSUE TITLE
shadow metadata version ahead of master?

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#321]
On 3.9.2 I've noticed a weird thing in CGI/Servers: a shadow metadata version is slightly ahead of master:

~~~~
$ lizardfs-admin list-metadataservers mfsmaster 9421
Server 1:
	IP: 192.168.0.251
	Port: 9421
	Hostname: debstor
	Personality: master
	Status: running
	Metadata version: 3853037894
	Version: 3.9.2
Server 2:
	IP: 192.168.0.204
	Port: 9421
	Hostname: deblab
	Personality: shadow
	Status: connected
	Metadata version: 3853037896
	Version: 3.9.2
~~~~

In the above example the difference is very small but I've seen shadow metadata version about up to 1000 ahead of master... Is that normal? I've never observed such thing on 2.6.0... Looks like master is being asked for metadata version before shadow (hence the difference)... Please close this bug it this behaviour is expected.

**Comment by psarna** [comment]
It is expected and it is as you said - master is asked for its version before shadows. We could easily change the behaviour to assure that the most fresh version printed is the master's one, but we've got bigger issues to deal with right now;)

**Comment by onlyjob** [comment]
No worries, thanks for confirming. :) 
Good to see that you are active on bug tracker again, Piotr. :)
