### ISSUE TITLE
3.9.2: chromium profile corruption

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#322]
Since upgrade to 3.9.2 we observe corruption of chromium profiles (we have `/home` on LizardFS).

Second launch of `chromium` show dialog "_Your profile could not be opened correctly_" (on console it prints errors like "_History sqlite error 3850, errno 22: disk I/O error, sql: COMMIT_"). If profile `~/.config/chromium` is removed then first start of chromium is OK but second launch exhibit the same problem.
This problem is not reproducible if profile is moved to another file system.
Please advise.

**Comment by onlyjob** [comment]
Everything seems to be all right (problem is not reproducible) if LizardFS is mounted with `-o enablefilelocks=0` parameter.

**Comment by psarna** [comment]
Hi Dmitry...
normally I don't reply at weekends, but this bug is embarrassing enough.
Quick workaround: Please add `-o enablefilelocks=0` flag to mfsmount and the problem will be gone.
This is an issue with parsing complex flags passed to fcntl() call (which is done by chromium's sqlite3).
Once I'm in the office I will fix it and add a 'start chromium without issues' test to our suite, since it looks like a good idea.

**Comment by onlyjob** [comment]
Hi Piotr,

Thank you very much for quick reply and for your advise. I already found this workaround. I'm very glad that you will be working on the fix soon. Cheers!

**Comment by psarna** [comment]
Changed my mind, it's to annoying to leave it for Monday,
can you verify? http://cr.skytechnology.pl:8081/#/c/2231/

**Comment by onlyjob** [comment]
Thanks, Piotr. I tried your patch but unfortunately it did not fix the problem...

**Comment by psarna** [comment]
It was the single most annoying subtle bug in my whole career. Please verify that file locks work well with chromium now...
http://cr.skytechnology.pl:8081/#/c/2232/

**Comment by onlyjob** [comment]
I've reproduced the problem even with both patches applied on top of 3.9.2.

It is almost 3 am here in Sydney so I'll have some rest but will be ready to test more patches some hours later. :)

**Comment by psarna** [comment]
It might be related to the fact, that some leftover orphan locks remained in your installation.
You can get rid of them by calling
`lizardfs-admin manage-locks HOST PORT list posix`
and then
`lizardfs-admin manage-locks HOST PORT unlock posix --inode=X` for each inode X you wish to clear from locks.

Also, I've updated this: http://cr.skytechnology.pl:8081/#/c/2232/ ,
so make sure you use the latest version of this patch.
Good night then.

**Comment by onlyjob** [comment]
I tried again with updated 2232 but the effect is the same. I did not play with `lizardfs-admin manage-locks` yet but I'm making new chromium profile from scratch so old locks probably should not be a problem... Thanks.

**Comment by onlyjob** [comment]
Hold on, I just realised that c/2232 is for master which I need to re-deploy... So far I've been testing by upgrading only client... I'll check again ASAP...

**Comment by onlyjob** [comment]
All good, with re-deployed client and master (both patches applied to 3.9.2) chromium works properly. New profile worked right away but to fix old profile I had to manually unlock leftover locks using `lizardfs-admin manage-locks mfsmaster 9421 unlock posix --inode=XXXX`. I verified that there are no locks left behind after chromium termination. Well done, Piotr -- thank you very much.

**Comment by psarna** [comment]
At your service;]

**Comment by onlyjob** [comment]
Unfortunately this problem is not completely fixed. Today one machine started to exhibit this problem again (probably after unclean reboot). I dropped all locks with `lizardfs-admin manage-locks mfsmaster 9421 unlock posix --inode-K` but it did not help and every time I start chromium it complaints about broken profile. Re-mounting with `enablefilelocks=0` fixed the problem. I triple checked to avoid any doubts but problem still exist. :(
Also I applied recently committed 40514ec but it did not help. Please advise.

**Comment by psarna** [comment]
I didn't manage to reproduce the problem. Does the output of `lizardfs-admin manage-locks mfsmaster 9421 list all` show anything suspicious when starting chromium? What is chromium's console output on the error?

**Comment by onlyjob** [comment]
`manage-locks list all` show new locks when chromium is started. Locks disappear when chromium is closed. It is a very same/similar problem so console output is the same as in the first message.

**Comment by psarna** [comment]
Here's a literally-one-character-fix: http://cr.skytechnology.pl:8081/#/c/2242/
Remounting with new mount will suffice.
Chromium is actually a great testing device for file locks, it uses virtually every single functionality mentioned in the standard;)

**Comment by onlyjob** [comment]
Looks good, thank you. Or perhaps I should test longer. ;)
Chromium started without errors. FYI it was not just chromium -- user reported likely related sporadic errors opening documents in libreoffice...

**Comment by psarna** [comment]
It is in fact SQLite that helped in finding those bugs.

**Comment by Asher256** [comment]
I'm wondering if it is worth it to activate enablefilelocks=1?
I posted a question today about enablefilelocks: https://github.com/lizardfs/lizardfs/issues/522

Could enablefilelocks cause issues in an web application like Gitlab? For example 3 Gitlab app servers that will be load balanced (= multiple writes, sometimes to the same files from different servers, to a Git bare repository, docker registry, etc.).

**Comment by Zorlin** [comment]
@Asher256 In the case of GitLab, if I'm reading correctly you *must* enable file locks.

**Comment by psarna** [comment]
@Asher256 
Two things can happen:
1. Nobody touches the installation - locks are released as soon as broken user sessions expire. A session expires after SESSION_SUSTAIN_TIME seconds from `mfsmaster.cfg`.
2. Somebody launches `lizardfs-admin manage-locks` with appropriate parameters and releases dangling locks manually.

In any case, they will not remain locked for very long.

**Comment by Asher256** [comment]
@psarna so it should be all right then. Thanks for the fast answer Psarna! I'll close the ticket #522 .
