### ISSUE TITLE
3.9.2: locking feature break some applications

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#325]
Probably related to #322. Today user complained that searching emails in Icedove v38.0 (aka Thunderbird) suddenly stopped working (nothing found).
I reproduced the problem and managed to "fix" it by re-mounting lizardfs with `enablefilelocks=0`.
There were no particular errors logged but I have an easy way to test and reproduce the problem.
I'm pretty sure there are no stalled locks from previous sessions.
We are running LizardFS 3.9.2 + two patches from #322.

**Comment by psarna** [comment]
Can you share your easy way to test and reproduce the problem?

**Comment by onlyjob** [comment]
Basically just to open _Icedove_ and try to search for mail in the inbox.
Without locking search produces results; with locking search returns nothing...

**Comment by psarna** [comment]
Ok, thunderbird seems not to have this problem, I'll try Icedove v38.0.

**Comment by onlyjob** [comment]
Thanks.

**Comment by psarna** [comment]
Ok, now I'm replying from Icedove v38.0 after finding your mail twice 
(once from the Search box and once from Quick Filter), and it just 
works... Can you perhaps launch your mount in foreground debug mode 
(mfsmount -d *PATH*) and see if there is any particular pattern before 
Icedove's failure? I tried very hard to crash Icedove v38.0 on LizardFS 
and didn't succeed.

**Comment by psarna** [comment]
Also, LizardFS's file locks pass all tests provided in here for multiple processes and multiple mounts: https://github.com/linux-test-project/ltp/tree/master/testcases/network/nfsv4/locks

**Comment by onlyjob** [comment]
Thanks for trying. I'll see what I can get with foreground mode... Icedove do not crash or report any errors, it's just that its search do not work... This morning we had two users with this problem despite the weekend effort when patched LizardFS was re-deployed cluster-wide and all stalled locks was dropped....  `enablefilelocks=0` completely fixed the problem.
As for NFS test I wonder if Icedove works correctly on NFS4 -- I've seen a bug suggesting that it might not, see [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794742) and [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757199).

**Comment by onlyjob** [comment]
OK, we had this problem on two computers: on first one I can't reproduce the issue after reboot; on second one it was due to unrelated problem (deleting `global-messages-db.sqlite` from profile folder helped and according to user "it was not working for a while").
However on second computer when I enabled file locks again and started _chromium_ it complained about corrupted profile again so I removed active locks using `lizardfs-admin manage-locks mfsmaster 9421 unlock posix --inode=` and could not reproduce the problem ever since.
What's bothering me is one incident of spurious chromium profile corruption like if locks was not re-initialised and somehow inherited their values after being "unlocked" for a while...
Anyway I feel that I can't articulate what's wrong nor do I have a reproducible case.
Sorry for troubles and thanks for your time. Closing...

**Comment by onlyjob** [comment]
Unfortunately we are still experiencing problems with locks. For instance, _libreoffice_ fails to open some documents with the following error:

    The operation on {filename} was started with an invalid parameter.

We have all latest patches applied as per #322, including b312ab1 and `lizardfs-adm` show no active locks. We can open problematic files in `calligrasheets` but not in Libreoffice. 
Once again we had to fall back to mount with `enablefilelocks=0`.

Please advise.

**Comment by psarna** [comment]
I cannot reproduce this.
Is the error document-dependent or libreoffice-version-dependent?
If its only certain documents that cause trouble, do you have any that are not classified and can share their files?
Do the problematic documents have something in common, like format or specific operations performed on them?

Option 2:
Can you use some kind of verbose debug option for libreoffice in order to get detailed error description?

**Comment by onlyjob** [comment]
I think it may be related to unclean reboot. We use Libreoffice 5.0.1 from _jessie-backports_ so there are no other versions. I am pretty sure that content of documents is not important. I'm not sure if I can get permission to disclose those documents but I'll see if I can find out how to reproduce the problem. It seems that documents (.ods, .odt) were opened before suspend in the end of the day, then computer was accidentally rebooted in the following morning (it may be relevant).

I do not have experience troubleshooting LibreOffice. Moreover I need to disturb my users to remount their homes with locking in order to reproduce the issue and it is obviously a difficult thing to do due to timing but also because they've already suffered literally every time I tried to enable locking. ;)

**Comment by onlyjob** [comment]
I'm closing this issue since locks are no longer enabled by default. If there are any remaining problems with locks it would be better to open a new bug.

**Comment by psarna** [comment]
An update - commit https://github.com/lizardfs/lizardfs/commit/a6e192a9baf5e23ffb1a1f23e34ca7ec38288a39 resolves minor semantical issues with getlk/setlk, they just might help with this issue as well. A confirmation would be appreciated!
