### ISSUE TITLE
3.9.2: CGI: no chunk replications (empty chart)

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#327]
Ever since upgrade to 3.9.2 chart "number of chunk replications per minute" show no new replications whatsoever (only historical pre 3.9.2 data).

**Comment by blink69** [comment]
Confirm, on our instalations bug also exist.

**Comment by onlyjob** [comment]
Yours truly, reporting quality bugs (this is my 70th bug).  ;)

Thanks for confirming.
