### ISSUE TITLE
3.9.2: chunkserver "Did not manage to receive packet header"

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#336]
Every minute chunkservers v3.9.2 log `Did not manage to receive packet header` one or more times.  Is that normal?

**Comment by DarkHaze** [comment]
The only place that this can occur is in chunk replication. Chunk server is waiting for up to 1s for data from other chunk server. We are guessing that the other chunk server is too busy to send data fast enough.

**Comment by onlyjob** [comment]
I tried to test that theory by lowering master's `CHUNKS_READ_REP_LIMIT` but even a very low value `2` did not help to reduce amount of those messages. Only lowering `CHUNKS_WRITE_REP_LIMIT` seems to help.

How can I identify problematic chunkserver that can't send data fast enough?

Also I was not successful in attempt to throttle replication by setting `REPLICATION_BANDWIDTH_LIMIT_KBPS` on chunkservers but that could be if chunkservers do not update replication bandwidth on "reload". Do they?

**Comment by onlyjob** [comment]
After some more experimentation it becomes clear that manipulating values of `CHUNKS_READ_REP_LIMIT` and `CHUNKS_WRITE_REP_LIMIT` do not eliminate this warning. Warning still appears even when REP_LIMITs set to 2 and 2 accordingly...

**Comment by onlyjob** [comment]
In attempt to identify problematic chunkserver I've temporary raised `CHUNKS_WRITE_REP_LIMIT` to a high value (above 20) during replication and noticed which chunkserver started to timeout:

    replication error: Chunkserver communication timed out

On that (slow) chunkserver I've tried changing some parameters but in the end lowering `NR_OF_HDD_WORKERS_PER_NETWORK_WORKER` from _2_ to _1_ helped to eliminate `Did not manage to receive packet header` warnings.
(`NR_OF_NETWORK_WORKERS=1`).

To answer my own question, chunkservers do update `REPLICATION_BANDWIDTH_LIMIT_KBPS` on reload without restart.

**Comment by psarna** [comment]
Please reopen if it's still a problem.

**Comment by onlyjob** [comment]
Not a "problem" but those messages appear frequently in logs... Is there are any options that have direct effect on "Chunkserver communication timed out"? Where this timeout is set?

**Comment by psarna** [comment]
No great news here for now... it's configurable for mounts (`-o mfschunkservertotalreadto=MILLISECONDS`), yet hardcoded to 60 seconds for chunkserver replication.
