### ISSUE TITLE
3.9.4: chunkserver crash: "Too many open files"

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#343]
Branching off second issue from #330: Chunkserver abnormally terminates (crashes) when there are not enough available file descriptors (e.g. when value in `/etc/security/limits.d/10-lizardfs.conf` is too low):

```
mfschunkserver[19456]: failed assertion 'pipe2(internalPipeFileDescriptors_, O_NONBLOCK) != -1', error: EMFILE (Too many open files)
```

This is known to cause minor loss of data (missing chunks).

Abnormal termination should not be an option. Chunkserver is a mission-critical software that should not crash but instead perhaps refuse to do some operations, log errors and (in worst case) gracefully terminate without loss of data.

I recommend to add a test case specifically checking chunkserver behaviour to avoid crashing when open files limit is low.

**Comment by psarna** [comment]
Fixed in 3.10: https://github.com/lizardfs/lizardfs/commit/15bbe90e942ca5e62792fd18b454c4a718540a68
