### ISSUE TITLE
CGI: check loop to display unavailable trash files in separate row 

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#344]
Currently "Filesystem check info" show unavailable files in one row, no matter if they are regular files or trash files. It would be nice to display unavailable files in trash in separate row.

**Comment by matthiaz** [comment]
This has been solved because I am seeing this:
![lizard](https://user-images.githubusercontent.com/3532563/28314682-d17883ea-6bbb-11e7-991f-be0b01282526.png)

**Comment by psarna** [comment]
Well, you're right. It's not "separate row", but it's close enough.
