### ISSUE TITLE
3.9.2: chunkserver failed to join during check loop

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#347]
One chunkserver labelled _poolA_ hosts files with goal _std1_, pinned to the particular label.
(This is done quite deliberately since those files are unzipped sources).
During master's check loop I restarted chunkserver and master immediately started logging increasing number of "unavailable files" and "unavailable chunks". So perhaps the first (minor) problem is that check loop is not suspended while chunkservers are joining so check result might be inaccurate.
The second (serious) problem is that master choked on check loop and stopped processing joining chunkserver: as number of "unavailable chunks"  reached 105_000, chunkserver disconnected, CGI froze and while master was counting unavailable files (up to 1_200_000+ and above) chunkserver did not log a single message for over 20 minutes.
Since there is no interface to control check loop I could not prevent such pointless wrestle between check loop and joining chunkserver. The only thing I could do is to try restarting chunkserver -- from second try it managed to join but seemingly after completion of check loop as master stopped counting "unavailable files" before join was completed.
During this incident master used up to 30% of CPU.

**Comment by psarna** [comment]
It's been a while since buggy 3.9.2, please reopen in case it still happens.
