### ISSUE TITLE
Needless replication during chunkserver join

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#350]
Replication begins as soon as chunkserver register itself with master but replication should be delayed until all HDDs are fully scanned. Every restart of heavy chunkserver I see aggressive replication onto it before it have a chance to finish scaning all its HDDs. Certainly replication during scan is unnecessary not to mention that it slows down scanning and joining.

**Comment by psarna** [comment]
see reply for #349

**Comment by onlyjob** [comment]
Fixed by 069139a, thanks.
