### ISSUE TITLE
3.9.4: xor2 chunks placement and loss of data

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#356]
Reporting data loss in _xor2_ goal. :(
_xor2_ is placed on chunkservers labelled _poolA_, _poolB_ and _poolC_.
Due to electrical works we gracefully stopped all chunkservers in _poolB_ and all but one chunkserver in _poolC_.
After starting all _poolB_ chunkservers, CGI show ~280 missing chunks in _xor2_ goal -- this is unexpected and may indicate invalid placement of data.
After starting all _poolC_ chunkservers number of missing _xor2_ chunks reduced to 167 (there were no missing _xor2_ chunks prior to restart of chunkservers).

I confirmed that some _xor2_ files are not readable any more. _xor2_ files were not accessed during restart of chunkservers. Chunkservers were restarted when cluster was fully replicated.
Apparently merely restarting chunkservers is enough to lose _xor2_ chunks.

---

Issue is reproducible: I stopped 3 chunkservers in _poolC_ again; restarted one chunkserver in _poolB_; started chunkservers in _poolC_ and observed number of missing _xor2_ chunks increased to 171.

Please note that this problem may be related to #349 as some chunkservers exhibited errors as described in #349 during scaning.

**Comment by psarna** [comment]
Are the files recoverable by `mfsfilerepair`? It all looks like the issue with chunk versioning - maybe those files are OK, but, for some reason, when only 1 part from *poolA* was available, its version was somehow bumped (I will try to check if it is the issue and update my answer then), so even when *poolB* and *poolC* were started again, LizardFS reported that there are no valid copies for the most fresh version.
If `mfsfilerepair` is able to completely recover the files, then my reasoning is correct and we will try to amend master's behaviour.

**Comment by psarna** [comment]
update: Doesn't look like this is the case.
I'm afraid that it might be the aftermath of this whole bunch of 3.9.2 errors, which your installation suffered from in all previous issues...

**Comment by onlyjob** [comment]
> Are the files recoverable by `mfsfilerepair`?

Not recoverable of course due to missing chunks. For example, `mfsfileinfo` show the following information about one of such chunks:

~~~~
chunk 24: 0000000001A7EBA9_00000001 / (id:27782057 ver:1)
                copy 1: 192.168.0.250:9422:poolA part 1/2
~~~~

> It all looks like the issue with chunk versioning

It have nothing to do with versioning. All files converted to _xor2_ are archives that were never modified since creation and not expected to be modified.

> I'm afraid that it might be the aftermath of this whole bunch of 3.9.2 errors, which your installation suffered from in all previous issues...

Strongly disagree. Following 3.9.2 disaster I've eliminated all _xor2_ chunks before upgrading to 3.9.4. I've changed goal of some files to _xor2_ few days after upgrade to 3.9.4 when it became clear that other more important issues are fixed. All _xor2_ files/chunks were made by LizardFS v3.9.4. I don't see how it can be aftermath and it is then it must be a bug.

**Comment by onlyjob** [comment]
Just checked several damaged files and all their chunks (available and unavailable) are `ver:1`... This issue affects _xor2_ files/chunks only. As far as I can tell all replicated files are OK.

**Comment by psarna** [comment]
I forgot to post my results yesterday, so here there are:
I used a configuration like this
~~~
chunkserver1: poolA
chunkserver2: poolA
chunkserver3: poolB
chunkserver4: poolB
chunkserver5: poolC
chunkserver6: poolC

goal: $xor2{ poolA poolB poolC }
~~~

Tested files included both ones that previously had *std2* changed to *xor2* and ones that were created directly in *xor2*. By the way - what was your archives' previous goal? I assumed *std2*.

At first I tried to reproduce your case, which is turning off whole poolB and 1 server from poolC, then restarting poolB - nothing went missing. Did it several times.

Then I ran a script which randomly turns chunkservers on and off for hours and nothing went missing - as long as at least two pools were up, I was able to read all the files, just like in *xor2* definition.

I'm unable to reproduce this issue. I'm open to suggestions and details - how many files did you move to *xor2*? are there special in any way (big, small)? any suspicious syslogs? did *anything* wrong happen after turning off all poolB servers, or only after restarting all but one from poolC?
I'm out of ideas how to reproduce it.

**Comment by onlyjob** [comment]
Thanks for investigating, Piotr.

I have one chunkserver in PoolA, two in PoolB, and four in poolC.

Most files were 200MiB ... 8 GiB; previous goal _std2_.
I converted about 100 GiB of data in total (but I can't tell precisely as I already deleted most of the data due to corruption). As far as I can tell nothing went wrong (e.g. no file system errors or OS level syslog that would raise my attention).

Chunkservers do have suspicious logs like `Received invalid response for chunk get block`, `replication error: Status 'No such chunk' sent by chunkserver (server 192.168.0.250:9422)` (192.168.0.250 is poolA) and other errors as described in #349. Chunkservers are configured with `CREATE_NEW_CHUNKS_IN_MOOSEFS_FORMAT = 0` but have chunks in legacy formats.

**Comment by psarna** [comment]
From a very basic research it looks like `CREATE_NEW_CHUNKS_IN_MOOSEFS_FORMAT = 0` is shit. I suggest you switch to default and see if it gets better, while we try to see why it doesn't work well with xors, which seems to be the case.

**Comment by psarna** [comment]
update: Nope, `CREATE_NEW_CHUNKS_IN_MOOSEFS_FORMAT = 0` is not the culprit.

**Comment by psarna** [comment]
Patch will be here soon, it was a serious leftover error from couple of months ago and thank you **SO MUCH** for leading us to it. And a big sorry for the lost data.

**Comment by psarna** [comment]
b131de1caa5fe582c90009eeb1f92e40ec0c6bf0

**Comment by onlyjob** [comment]
Thanks, Piotr. I've applied b131de1 but restart of master produced ~2000 new missing chunks in goal _std2_... Maybe I've closed #342 prematurely...

**Comment by psarna** [comment]
Unfortunately restart didn't produce it, 3.9.2 did. It was just comfortably covered with a bug...

**Comment by onlyjob** [comment]
Did some testing -- all seems to be good, no new data loss since b131de1.
I believe this problem is fixed. Thanks.
