### ISSUE TITLE
fileinfo: difficult to identify damaged _xor2_ chunks

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#357]
`mfsfileinfo` utility show "no valid copies" message for unavailable replicated chunks. However it is difficult to find unreadable _xor2_ files because unavailable _xor2_ chunks are not clearly identified in the output of `mfsfileinfo`.

**Comment by blink69** [comment]
Fix in [http://cr.skytechnology.pl:8081/#/c/2328/](url)

**Comment by blink69** [comment]
also http://cr.skytechnology.pl:8081/#/c/2466/ will close this issue.
