### ISSUE TITLE
centos lizardfs-cgiserv and cgi rpm does not provide cfg file 

### ISSUE THREAD

**Issue by ruilinchu** [lizardfs/lizardfs#360]
I'm running on centos 7, rpm file compiled from source. 

# rpm -qlp /usr/local/src/lizardfs-cgiserv-v.3.9.4-0el7.x86_64.rpm 
/usr/lib/systemd/system/lizardfs-cgiserv.service
/usr/sbin/lizardfs-cgiserver
/usr/sbin/mfscgiserv
/usr/share/man/man8/lizardfs-cgiserver.8.gz
/usr/share/man/man8/mfscgiserv.8.gz

# rpm -qlp /usr/local/src/lizardfs-cgi-v.3.9.4-0el7.x86_64.rpm 
/usr/share/doc/lizardfs-cgi-v.3.9.4
/usr/share/doc/lizardfs-cgi-v.3.9.4/NEWS
/usr/share/doc/lizardfs-cgi-v.3.9.4/README
/usr/share/doc/lizardfs-cgi-v.3.9.4/UPGRADE
/usr/share/mfscgi
/usr/share/mfscgi/chart.cgi
/usr/share/mfscgi/err.gif
/usr/share/mfscgi/favicon.ico
/usr/share/mfscgi/index.html
/usr/share/mfscgi/logomini.png
/usr/share/mfscgi/mfs.cgi
/usr/share/mfscgi/mfs.css

after installation the cgi monitor does no work.

**Comment by psarna** [comment]
I've just built a package for CentOS 7 from source and cgi server works fine. What do you mean by `it does not work`? Any logs, statuses?

**Comment by ruilinchu** [comment]
sorry I was trying to use the previous configuration files, I did a fresh configure and everything works.
