### ISSUE TITLE
3.9.4: CHUNKS_READ_REP_LIMIT do not work?

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#367]
Some files with goal 1 are located on a particular chunkserver -- I've changed their goal to 2 and set value of `CHUNKS_WRITE_REP_LIMIT` to be 5 times of `CHUNKS_READ_REP_LIMIT` to check if the latter have any effect.
However it seems that even if set to very low value `CHUNKS_READ_REP_LIMIT` do not limit replication rate from one chunkserver which I expected because man page describes the latter as "Maximum number of chunks to replicate from one chunkserver".

**Comment by DarkHaze** [comment]
At the moment this value is only checked during chunk rebalancing. Not sure why is it this way (bug or some design decision), but most probably we will fix it soon.
