### ISSUE TITLE
Deserialization error received on mfsmaster version 2.6.0

### ISSUE THREAD

**Issue by workst** [lizardfs/lizardfs#368]
The following can be seen in the syslog on the master server running under (RH EL 7.1):
 
Jan 07 11:57:39 <____> mfsmaster[3732]: chunkserver register begin (packet version: 5) - ip: <____>, port: 9422
master <-> chunkservers module: got inconsistent message (type:1101, length:13008), Deserialization error: expected packet version 1, got 0

lizardfs version 2.6.0;

the message is caused by a newer version (3.9.4) chunkserver connects to the old version (2.6.0)

Solved by: making the environment consistent by downgrading the chunkserver to 2.6.0 

Recommendation: it may be a good idea to keep this here for reference or add a record in the documentation

**Comment by psarna** [comment]
We have that information in UPGRADE notes found in the root directory of source code:
~~~
- Upgrade shadow master servers before the master server; shadow master will always
  refuse to connect to the master server in any newer version.
     (...)
- Upgrade the master/shadow servers before any chunkserver or client.
~~~
We will include information about the UPGRADE notes location when releasing a new version to avoid confusion - thanks for pointing it out.
