### ISSUE TITLE
Cannot contact LizardFS team by phone

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#373]
Hey there,

On LizardFS.com this text can be seen:
Contact us now: (+1) 646 655 0 693
(+48) 22 100 32 48

I have tried calling both numbers numerous times at different times of day, as my employer wants to get quotes for commercial support for a small installation. No-one ever picks up. I've also sent emails to info@lizardfs.com as well as submitted things through the Contact Us form and got no replies.

Maybe the phones aren't working? I've tried from both Google Voice and Skype, neither worked.

Thanks,
~ Benjamin

**Comment by blink69** [comment]
Hi Zorlin,

phones are working ok, maybe you call when the office was closed ? Support phone is always 24/7 but this is diffrent number that you see on website.
Also I double checked info@lizardfs.com and didnt found any email from you (unfortunately lizardfs.com is on gmail so we dont have any logs), maybe you can email me directly to my email adam.ochmanski@skytechnology.pl.

Thanks.

**Comment by Zorlin** [comment]
Hi, thanks for the quick reply! I really appreciate it.

What are the office hours? I think I called at like 3pm Poland time at one
point.

The email title was "Commercial support/consulting enquiry", from my
company email (not this one).

Thanks again.
- Benjamin

**Comment by blink69** [comment]
Ok, we will continue on email. About this call, probably when you call us we got in Poland holiday and office was closed...
