### ISSUE TITLE
dns not working for lizardfs.com

### ISSUE THREAD

**Issue by richard-scott** [lizardfs/lizardfs#375]
From the UK the DNS for lizardfs.com is not working.
The parent zone servers for the domain are not working either.
It looks like these servers are offline:

```
$ whois lizardfs.com | grep -i "^name server"
Name Server: NS1.SKYTECHNOLOGY.PL
Name Server: NS2.SKYNODE.EU
```

**Comment by Zorlin** [comment]
Confirmed down from Northbridge/Perth, Western Australia, Australia via Telstra Mobile 3G.

**Comment by Zorlin** [comment]
It would be worth considering a switch to CloudFlare's free plan instead of hosting DNS servers directly.

**Comment by onlyjob** [comment]
From Sydney I can open lizardfs.com but IntoDNS report reveals some problems: http://www.intodns.com/lizardfs.com

**Comment by richard-scott** [comment]
Closing this now as things look to be back online.
