### ISSUE TITLE
Debian 8 packages seem to lack systemd support.

### ISSUE THREAD

**Issue by richard-scott** [lizardfs/lizardfs#376]
I've just done a fresh install of all LizardFS packages on a new Debian 8 (Jessie) box and the installation doesn't provide the required Systemd service files.

The CentOS packages support systemd nicely... so how can I get full systemd support in Debian for LizardFS?

**Comment by onlyjob** [comment]
On Debian one should be very careful installing vendor packages. Ideally vendor packages should not be installed at all when official Debian packages are available. Official Debian packages from native Debian repositories do not have this problem. LizardFS vendor packaging is mediocre (if maintained) and far behind official Debian packages.

**Comment by richard-scott** [comment]
ah yes. found them now. much better.
it confused me by packages.lizardfs.com having deb files on there.
I'll ignore that site for now and install from 'sid' instead.

**Comment by onlyjob** [comment]
> it confused me by packages.lizardfs.com having deb files on there.

It confuses everyone... I'm not sure why LizardFS team still produce their own Debian packages. Certainly they are not packaging experts and it is much more difficult for them to meet Debian quality standards hence IMHO it is preferable to install superiour packages from Debian repositories.

On _Jessie_ please consider installing from [jessie-backports](http://backports.debian.org/Instructions/).
Alternatively you can install from "_testing_" suite. _sid_ may be too unstable so it is safer to install from "testing" once package migrates there from _sid_ (aka _unstable_).

**Comment by richard-scott** [comment]
I tried jessie-backports, but only found v2.6.0... is that correct?

```
# apt-cache -t jessie-backports showpkg lizardfs-adm
Package: lizardfs-adm
Versions:
2.6.0+dfsg-1~bpo8+1 (/var/lib/apt/lists/httpredir.debian.org_debian_dists_jessie-backports_main_binary-amd64_Packages)
 Description Language:
                 File: /var/lib/apt/lists/httpredir.debian.org_debian_dists_jessie-backports_main_binary-amd64_Packages
                  MD5: 0cd3337c74bd44959f040867b9357c94
 Description Language: en
                 File: /var/lib/apt/lists/httpredir.debian.org_debian_dists_jessie-backports_main_i18n_Translation-en
                  MD5: 0cd3337c74bd44959f040867b9357c94


Reverse Depends:
Dependencies:
2.6.0+dfsg-1~bpo8+1 - libc6 (2 2.14) libgcc1 (2 1:4.1.1) libstdc++6 (2 4.9)
Provides:
2.6.0+dfsg-1~bpo8+1 -
```

**Comment by onlyjob** [comment]
That's right, 3.9.4 only recently stabilised in "testing" so I did not upload it to backports yet.
I'll put it on my TODO list...

https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=sourcenames&keywords=lizardfs
