### ISSUE TITLE
master-chunkserver unknown message 1100

### ISSUE THREAD

**Issue by cloudweavers** [lizardfs/lizardfs#383]
Dear friends, we are getting a curious issue in some clusters where a previous 2.5.4 master is seemingly unable to get a 2.6.0 chunkserver connecting properly. The logs of the master report 
mfsmaster[4921]: master <-> chunkservers module: got unknown message (type:1100)
Is it possible to get a list of messages and their meaning? I suppose it's some feature that is present in 2.6 and not in 2.5.4, but it should not prevent joining a running cluster.

**Comment by psarna** [comment]
All message types can be browsed in our source code: https://github.com/lizardfs/lizardfs/blob/master/src/protocol/MFSCommunication.h. Message 1100 is a registration message
sent from 2.6.0 chunkserver to master, so it requires master in version >= 2.6.0 to understand
this message. Upgrade notes also mention that master should be upgraded before any
chunkservers or clients:
~~~
* Upgrading to LizardFS 2.6.0:

    Direct upgrade is possible from:
    - MooseFS  1.6.27 -- 1.6.27-5
    - LizardFS 1.6.28 -- 2.5.4.3

    When upgrading from LizardFS 2.5.4 or 2.5.4.*
    - Upgrade shadow master servers before the master server; shadow master will always
      refuse to connect to the master server in any newer version.
    - Upgrade the master server before any chunkserver or client.
~~~
