### ISSUE TITLE
Poll: Regular statistics

### ISSUE THREAD

**Issue by DarkHaze** [lizardfs/lizardfs#385]
We are thinking about removing regular statistics (Statistics that don't include chunkservers/disks marked for removal). It would slightly reduce memory usage in master and number of computations required for chunk registrations (chunkservers connecting to master).

The question is if somebody thinks that they are important enough to keep them.

**Comment by Zorlin** [comment]
I like seeing lots of aspects of my cluster, good and bad. Especially
access times, read and write latency etc. Whatever you do, please keep it
easy to tune and test for better performance.

**Comment by DarkHaze** [comment]
We don't want to remove all statistics (with operations times, etc). We just want to remove following items (for regular state):
numbers of chunks in state, number of missing parts, number of redundant parts,number of full copies.
To access those information in web interface (cgi) you must select Chunk tab and then click 'switch to regular'.

**Comment by 4Dolio** [comment]
The info tab already provides a view of that information, correct. The only thing lost is the more specific information regarding which specific goal/labels are under/over. I rarely use the chunks tab so I would be fine with losing it.
