### ISSUE TITLE
Global Deployment

### ISSUE THREAD

**Issue by faddat** [lizardfs/lizardfs#386]
I'm about to attempt a global (worldwide) deployment of lizardfs.  Has this been done before?  Were any latency issues hit?  if so, how were they addressed?  

Thanks!

-Jake

**Comment by 4Dolio** [comment]
I have deployed a global LizardFS cluster (only used for testing) which spans three continents via high latency VPN links.  IMHO LizardFS is not really intended to be used in this manor.  While it should function in this configuration it is likely to behave as one might expect any other filesystem to act when used over high latency network links.  The features like chunkserver labels, custom goals, topology, and snapshots might be leveraged to make the high latency aspect relatively transparent to users but I have not quite nailed down any acceptable methods for accomplishing this.

With my test cluster I was only attempting to accomplish slow overnight replication from any given sites writable branch to any other sites read-only replica of the that data.  I can not currently conceive of any method for achieving high performance writes to a common set of data from all sites in real time.  It does function with goals at remote chunkserver targets but with the performance one might expect when clients are forced to push data through slow links.

Some thoughts on that use case:
It would be handy in this sort of geo-distributed situation to be able to instruct via topology configurations or other new features for lizardfs clients to avoid read/write from/to particular chunkservers so to fall back on the lazy replication mechanic to accomplish the slow push between distant racks while still allowing for expensive/slow read/writes to distant nodes should no local copies be available.  I'm confident that such a feature could be added to LizardFS to make this unique behaviour a reality.

I believe the only way to accomplish something like this currently would be to actively block communications between clients and chunkservers which do not reside at the same site, forcing chunkservers between sites to fall back on replication to push data between sites in the background.  Unfortunately in my experience this results in poor client performance as the client will continue to attempt to communicate with chunkservers which they are unable to contact.  I have not looked further into eliminating this behaviour so to accomplish this hack of a solution.  I'm also unsure of any adverse data integrity impacts which this might result in.

Another thing to keep in mind is that a single active master service must reside in only one location.  While loggers or shadows may exist at remote sites, they can not all be leveraged in parallel.  Read-Only Shadows or Write-Forwarding Shadows might help further improve such a clusters performance but those features are not yet available, nor am I aware if they are on the roadmap.

Would be thrilled to hear others thoughts on this topic.

**Comment by faddat** [comment]
Well maybe we can start with a question: other than lizardFS, are you aware
of any way of accomplishing this? After reading thoroughly the
documentation on both glusterFS and on ceph and then doing a couple of
tests appointments, I came to the conclusion that it wasn't really going to
work with either of those tools. There's weed FS but it is not a POSIX file
system as you probably know.

Basically I'm doing the whole start by making a list of possible solutions
and then narrow it from there. May I ask, how high was your latency? It's
our hope to be able to put Storage just about anywhere  when we're done
with this.  And we are fully aware that it's going to take several years
but this is the path we have chosen to take so that's what we're doing.
Anyway, I'd love to hear about your project and chat sometime if you want
to get ahold of me I'm pretty much always on Google Hangouts my email is
faddat@gmail.com.

**Comment by Zorlin** [comment]
Ceph would be my suggestion, but it's not ready yet.

**Comment by onlyjob** [comment]
_Ceph_ is such a hopeless rubbish (I mean it) that I strongly advise to stay away from it (unless you value integrity of your data).
[Gfarm](https://sourceforge.net/p/gfarm/wiki/Home/) is a better option for geo-replication.

**Comment by Burning-Daylight** [comment]
I was also investigating the possibility to establish geo distributed filesystem and the only open solution I have found available at the moment is gfarm, even though it still has some implementation features which could be undesirable. Lizardfs seems to be very close to the state when it could be used for geographically distributed setups, but in my view lacks two critical features: chunk server selection strategy configuration and `acknowledgment_goal` configuration.

**Comment by onlyjob** [comment]
> I have found available at the moment is gfarm, even though it still has some implementation features which could be undesirable

@Burning-Daylight, Could you elaborate please? I'm not aware of such features and I'm curious...
Gfarm is pretty good - in my testing it won over all other distributed parallel storage systems except LizardFS.

> \[LizardFS\] ... in my view lacks two critical features: chunk server selection strategy configuration and acknowledgment_goal configuration.

So true. But we have opened bugs for that so hopefully this functionality will be implemented eventually...

**Comment by faddat** [comment]
To be honest, I think the system that achieves this is going to be written
in Go or rust.  Seems every time I poke my head up, I see something that
was previously thought to be impossible being done in one of those two
languages.  I'll go into more depth tomorrow when I don't have a
self-imposed deadline hanging over my head :).

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by onlyjob** [comment]
Except that Golang threw out the window ~20 years of best practice in software engineering... :(  I'm sceptical...

**Comment by Burning-Daylight** [comment]
@onlyjob the replication unit in Gfarm is the file. If there are two distant data centres NY and Paris, there is a file which does not have a replica in Paris, but only in NY, and a client in Paris tries to access this file - it must either be fully replicated in Paris and then the client can use it, or it can be accessed directly over the low-latency network without replication. Ideally replication in such a case should happen in background simultaneously to file-access. When the client requests the file, he should receive the data directly and the FS should also use transferred data to create a replica in background. The writes should then happen locally and replicate lazily. LizardFS could achieve these goals as its replication unit is a chunk.

**Comment by onlyjob** [comment]
Thanks, @Burning-Daylight. As for Panzura - who cares about proprietary rubbish? ;-)

I think Hadoop might be the only option then. It looks like some (e.g. MapR) are already building proprietary solutions on top of Hadoop...

**Comment by onlyjob** [comment]
Just found another interesting system - [iRODS](http://irods.org). Here is their GitHub repo: https://github.com/irods/irods
