### ISSUE TITLE
Ubuntu 16.04 packages

### ISSUE THREAD

**Issue by faddat** [lizardfs/lizardfs#387]
I see the script in the repo, but wanted to inquire if I should expect anything unusual because I'm on Ubuntu 16.04.  

Thanks!

**Comment by blink69** [comment]
As I see on packages.ubuntu.com, there are avaiable latest stable packages of lizardfs 3.9.4. 

http://packages.ubuntu.com/search?keywords=lizardfs&searchon=names&suite=xenial&section=all

**Comment by faddat** [comment]
You're right-- I was doing something bizarre and missed them the first time around.  Thanks!

**Comment by onlyjob** [comment]
[Debian packages](https://packages.debian.org/search?keywords=lizardfs) already pulled by Ubuntu...
