### ISSUE TITLE
The Lizard and the Moose had a baby!?

### ISSUE THREAD

**Issue by faddat** [lizardfs/lizardfs#388]
Actually, just curious to know if you are syncing with MooseFS 3.0  at all, or if your paths have diverged, never to meet again?

**Comment by psarna** [comment]
No, LizardFS is not compatible with Moose 3.0 and this situation is not likely to change.
If you were very desperate and found a C/C++ programmer with a lot of free time and patience, it's probably still doable, though.

**Comment by faddat** [comment]
No need for this, only curiosity.  Still curious about where the two
codebases diverge.  If you're worried don't be:  I have heard better things
about the lizard than I have about the moose ;).

**Comment by onlyjob** [comment]
> I have heard better things about the lizard than I have about the moose

I hope you can be more specific about that...
