### ISSUE TITLE
Concerns for removal of client CRC checking

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#390]
According to comments of recent commit c812169a4, client-side CRC checking is apparently removed (I did not verified the code).

I believe it is a mistake to do such thing. CRC checks should be done on chinkservers and clients.
That was one of the very useful features that motivated our choice of LizardFS.

It is very important to validate transferred data on client. What were you thinking, @psarna?
Please ensure/restore CRC checking on client.

**Comment by psarna** [comment]
Every single piece of data read from a chunkserver is then checked by chunkserver itself,
and then sent to client.
Checking CRC in client would only detect a corruption that happened during transmission.
Is 32-bit checksum provided by Ethernet + 16-bit checksum provided by TCP not enough to believe that data is consistent?
We've made a decision that yet another (at least _fourth_) check is redundant and it wastes CPU time.

However, if the community doesn't trust their network cards enough,
we can restore the additional client-side check.

**Comment by onlyjob** [comment]
> Is 32-bit checksum provided by Ethernet + 16-bit checksum provided by TCP not enough to believe that data is consistent?

No, not enough. There are buggy firmware and drivers as well as malfunctioning NICs with endless combination of offload checks let alone other (hardware and software) components that can cause corruption. 

Data integrity is one of the biggest strengths of LizardFS. How can you make such decisions so lightly? It is not a redundant check -- well it may be redundant but nevertheless useful.

I feel so bad about removing that feature, so frustrated like I've never felt ever since I left Ceph behind... :(

**Comment by cloudweavers** [comment]
As an example, it prevented problems with the recent VETH bug: https://tech.vijayp.ca/linux-kernel-bug-delivers-corrupt-tcp-ip-data-to-mesos-kubernetes-docker-containers-4986f88f7a19 
we actually encountered it (we use OpenVSwitch in our infrastructure) and the CRC properly identified a corruption that was not reported by the kernel CRC check.

**Comment by onlyjob** [comment]
Another reason for client integrity checks is to double check that chunkserver is not sending rubbish which can happen due to bad hardware, malice, bug, version mismatch or other unforeseen factors. In some environments data corruption can not be tolerated. Integrity features of LizardFS is your competitive advantage over most other storage systems.

Please restore client CRC checks.

**Comment by onlyjob** [comment]
Excellent example, @cloudweavers. Thank you.

**Comment by psarna** [comment]
Fair enough, client-side checks help prevent bugs in kernel and/or native code, which couldn't hurt. Well, that's the advantage of having an open-source system, bugs are tracked and hunted as soon as they are published ;)

**Comment by onlyjob** [comment]
Yes, peer review is a very powerful thing. :)
Yet I'm so worried about such poor decisions that I'm beginning to fear what might be coming next... You've really scared me, Piotr as I rely on functionality you've removed...

**Comment by Zorlin** [comment]
Thanks for listening to your users. :)

**Comment by onlyjob** [comment]
Also I think it is more than "prevent bugs in kernel and/or native code". It is protecting data from damage, avoid interruption of services and ensure reliability. It is a matter of trust and confidence in technology.

**Comment by psarna** [comment]
@cloudweavers Yeah, but it could as well be that incorrect data was sent by a chunkserver, which _did not_ perform CRC checks, so TCP/Ethernet checks would naturally accept data as consistent.

**Comment by onlyjob** [comment]
Thanks for restoring client-side CRC checks, Piotr. :)

**Comment by onlyjob** [comment]
In this context it is very interesting to mention recent "SPLICE" incident #378 when chunkservers were sending incorrect data _rejected by clients due to CRC checks_.

Without CRC checking on clients we would have massive data corruption and if that had happened most certainly I wouldn't be using LizardFS by now...

I still find it difficult to comprehend how the very same person (@psarna) who found the root cause of #378 decided to remove CRC checks from client just some hours later...

**Comment by cloudweavers** [comment]
I am first of all grateful of the work of @psarna and all the friends here. I believe it was not a sensible decision, and in this case I am happy that the community helped in finding reasons for reverting it, and for the Lizardians to accept it. That's it- we are all a happy family :-) No need to insist anymore, IMHO...

**Comment by onlyjob** [comment]
Same here, @cloudweavers. I'm grateful for all the work LizardFS team does and for fantastic technology we're all enjoy. Mistakes are naturally made when the work is done. That's understandable. Though learning lessons from mistakes is important that's why I've added more information.
