### ISSUE TITLE
iscsi

### ISSUE THREAD

**Issue by htbase** [lizardfs/lizardfs#391]
Hi folks,

We can't find any documentation or way to present LizardFS volume as iscsi.

We wanted to use HyperV and it does not support NFS

Thanks

**Comment by Zorlin** [comment]
AFAIK there's no (simple) way to mount it via iSCSI. You would likely need
a host/adapter machine that mounts LizardFS and then re-exports it as iSCSI
target.

**Comment by Zorlin** [comment]
For an example (albeit one that uses Ceph's RBD) check this out:
https://www.susecon.com/doc/2015/sessions/TUT16512.pdf

**Comment by blink69** [comment]
Agree with @Zorlin, you need to use third party software in eg. LIO with FILEIO and as a backend for this use LizardFS.

**Comment by 4Dolio** [comment]
Just leaving a note that I have successfully used EIT and LIO to deliver iSCSI backed by LizardFS to XenServer initiators.  Started playing with it about 6 months ago and still have not completely abandoned more traditional ways of delivering storage for out Xen.

**Comment by guestisp** [comment]
> Just leaving a note that I have successfully used EIT and LIO to deliver iSCSI backed by LizardFS to XenServer initiators. Started playing with it about 6 months ago and still have not completely abandoned more traditional ways of delivering storage for out Xen.

Could you please describe ? I'm planning to bring up an iSCSI SAN backed by Lizard, the ability to use disk-less hypervisors with direct boot from iSCSI is great

**Comment by guestisp** [comment]
> the ability to use disk-less hypervisors with direct boot from iSCSI is great

to be honest, the same could be done with NFS by using a simple tftp server and bootp

**Comment by 4Dolio** [comment]
I will try to share my process soon,  and yes you could likely use nfs, I find iSCSI slightly more stable-ish? But i sometimes miss the file level access when using nfs for virtual disks. Shrugs, more to come.

**Comment by guestisp** [comment]
Maybe more stable, but also it has a huge overhead compared to NFS and is much harder to configure.

**Comment by 4Dolio** [comment]
I will grant you the hard to configure, but IDK about the overhead claim.  When you see my script that I use to setup the iSCSI you may become ill, fair warning...

PS, I have not executed multipath due the similarly complex client config needed, but in theory any shadow can be a target, in parallel, i believe.  Each shadow would stull use the single master, but if each has local chunks, they would prefer those for all reads.
