### ISSUE TITLE
OS X (Apple) client binaries in repo

### ISSUE THREAD

**Issue by gutleib** [lizardfs/lizardfs#393]
This product seems to be one of a few, which work similarly in OS X and linux, thanks to FUSE.

It would be great if there would be an apple binary package for lizardfs, in separate .pkg or in macports repo.
Also documentation on it's usage would be helpful.

**Comment by blink69** [comment]
As a osx user I will handle this myself :)

**Comment by krissfr** [comment]
Hi Blink69,

is there an url to download a precompiled version (.pkg) for OSX ?

maybe on http://packages.lizardfs.com ?

thanks

**Comment by 4Dolio** [comment]
>As a osx user I will handle this myself :)

@blink69 sounds like you might have built on OSX? Could you share some build cookbook commands?

**Comment by krissfr** [comment]
@4Dolio check the last commit :)
https://github.com/lizardfs/lizardfs/blob/master/create-osx-package.sh

**Comment by blink69** [comment]
@krissfr we will add to our website after weekend :)

**Comment by krissfr** [comment]
@blink69 Thank you ! :)

**Comment by Zorlin** [comment]
@blink69 Thank you! I can use this to show off LizardFS at talks! :)

**Comment by gutleib** [comment]
Um, hai.

Could you point me to where can I find those packages?

**Comment by krissfr** [comment]
@blink69 i don't find OSX package on the website, can you please tell me where to find it ?

thanks

**Comment by FlorianHeigl** [comment]
I think there's still nothing on the website. A build script as mentioned above exists, but you need to use master to get the last bugfix.
