### ISSUE TITLE
ACLs not working with "mfsmount -o mfsacl /mnt/lizardfs"

### ISSUE THREAD

**Issue by tyler274** [lizardfs/lizardfs#394]
mounted system with "mfsmount -o mfsacl /mnt/lizardfs"

If I make a directory as root /mnt/lizardfs/testdir and use "setfacl -Rm u:tyler274:rwx /mnt/lizardfs/testdir" I am still unable to touch a file to the directory.

**Comment by richard-scott** [comment]
I had to do this to get non-root users to be able to write to my mount point:

```
echo "* / rw,maproot=0:0" >/etc/mfs/mfsexports.cfg
```

See if that helps?

**Comment by tyler274** [comment]
@richard-scott Didn't seem to change anything. all users can write to /mnt/lizardfs but if for example, root creates a folder named "testacl" at "/mnt/lizardfs/testdir" and I run "setfacl -Rm u:tyler274:rwx /mnt/lizardfs/testdir" I am still unable to touch a file to testdir due to permissions denied.

**Comment by richard-scott** [comment]
Did you mount the volume with the "mfsacl" flag?

**Comment by tyler274** [comment]
@richard-scott the specific command used was "mfsmount -o mfsacl /mnt/lizardfs"

**Comment by richard-scott** [comment]
lol, my bad. I missed that one ;-)
BTW do you have SELinux enabled?

**Comment by tyler274** [comment]
@richard-scott Don't believe I do, running latest Arch and haven't gone through any steps to enable it.

**Comment by 4Dolio** [comment]
Cant find it atm, but there is an export option to ignoregid i think. Look for and try that...

**Comment by tyler274** [comment]
@4Dolio issues #265 and #295 

just adding the ignoregid value such that my mfsexports.cfg file is 

`# mfsexports.cfg(5)
# Allow everything but "meta".
127.0.0.1                       /       rw,alldirs,maproot=0,ignoregid

# Allow "meta".
127.0.0.1                       .       rw`

I unmounted the cluster with `umount /mnt/lizardfs` 
Restarted the master server with `systemctl restart lizardfs-master`
remounted with `mfsmount -o mfsacl,mfsdebug /mnt/lizardfs`

checked that the acls are there with `getfacl /mnt/lizardfs/testacl/`
which returns 
`user::rwx
user:tyler274:rwx
group::r-x
mask::rwx
other::r-x`

attempting to touch a file to that directory from my user shows

`getattr (1)
lookup (1,test)
getattr (15484)
lookup (15484,eee)
status: ENOENT (No such file or directory)
lookup (15484,eee)
status: ENOENT (No such file or directory)`

**Comment by 4Dolio** [comment]
Yes per issue #265 what you have done should be working.  The only difference i see is that my mfsexports.cfg has `rw,alldirs,ignoregid,maproot=0` so my ignoregid and maproot are inverted compared to yours, but I can't imagine that should matter.

Some tests with my 2.6.0 seem to work fine:
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ sudo mkdir acl_test_dir`
`normaluser@lfs-us-courses7:/lfs-us-courses/shares/courses/ACL_Tests$ ls -la .`
`drwxr-xr-x  2 root root     0 Mar  7 18:55 acl_test_dir`
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ touch acl_test_dir/basic_acl`
`touch: cannot touch acl_test_dir/basic_acl: Permission denied`
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ setfacl -Rm u:normaluser:rwx acl_test_dir/`
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ touch acl_test_dir/add_owner_acl`
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ setfacl -b acl_test_dir/`
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ touch acl_test_dir/add_group_acl`
`touch: cannot touch acl_test_dir/add_group_acl: Permission denied`
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ sudo setfacl -Rm g:1182:rwx acl_test_dir/` normaluser is member of 1182
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ touch acl_test_dir/add_group_acl`
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ rm acl_test_dir/add_group_acl`
`normaluser@lfs-debian-client:/LizardFS/ACL_Tests$ setfacl -b acl_test_dir/`

**Comment by richard-scott** [comment]
What Linux Distro are you using?
How did you install the Lizard Packages?

**Comment by tyler274** [comment]
@richard-scott 
Arch Linux
via modified https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lizardfs

**Comment by richard-scott** [comment]
ah, Arch Linux, don't know what distro yet ;-(
I looked at it once, but Debian installed easier and it was more stable for my needs.
I thought you may have installed packages for Debian from [here](http://packages.lizardfs.com/), and that is not the best source for the .debs.

**Comment by pbeza** [comment]
Note that `-o mfsacl` [is][1] now deprecated. ACL support is enabled by default. If you still have any problem with this issue, please reopen it.

[1]:https://github.com/lizardfs/lizardfs/blob/master/src/mount/fuse/mount_config.cc#L157

**Comment by baby-gnu** [comment]
Hello.

I'm testing on Ubuntu with lizardfs 3.12.0+dfsg-1 and I still have ACL issue.

I'm testing with the command `sudo -u foo ls /mnt/test-lizard`:

* Doing `setfacl -m user:foo:rx /mnt/test-lizard` fail
* Doing `chown foo /mnt/test-lizard` works

This should be reopened.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by pbeza** [comment]
@baby-gnu ACLs were fixed in #816 _after_ releasing `3.12`. It will be released in `3.13`.

**Comment by baby-gnu** [comment]
@pbeza thanks, I'm doing a rough backport to 3.12 to test on my test machine.

**Comment by pbeza** [comment]
AFAIR I had really hard time trying to solve this problem for FUSE `2.9`. AFAIK supporting ACL in FUSE < 3 is/was supported by applying [this][1] and [this][2] patch to Linux kernel (it was written by our ex-developer @lalek 6 years old ago)...

Maybe it's worth trying to [backport][3]/install [`fuse3`][4]?

[1]: https://github.com/lizardfs/lizardfs/blob/master/utils/libfuse_acl.patch
[2]: https://github.com/lizardfs/lizardfs/blob/master/utils/linux_fuse_acl.patch
[3]: https://backports.debian.org/Instructions/
[4]: https://packages.debian.org/bullseye/fuse3

**Comment by baby-gnu** [comment]
@pbeza thanks for all the informations.

It was an experiment to fix Samba `SYSVOL` replication.

I think we will wait for fuse3 to arrive in the next Ubuntu (since our work is based on that) but I note that buster [can use it](https://packages.debian.org/source/stable/fuse3) ;-)

Regards.
