### ISSUE TITLE
FTBFS: expected template-name before '<' token

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#403]
The following FTBFS in Debian _sid_ was reported: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822505

> [ 24%] Building CXX object src/common/CMakeFiles/mfscommon_tests.dir/small_vector_unittest.cc.o
> cd /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/build/src/common && /usr/bin/c++   -DENABLE_CRC -DLIZARDFS_HAVE_CONFIG_H -DTHROW_INSTEAD_OF_ABORT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/<<BUILDDIR>>/lizardfs-3.9.4+dfsg/build -I/<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src -I/<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common -I/usr/include/crcutil  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -pipe -std=c++0x -pthread -Wall -Wextra -fwrapv -pedantic  -O3 -DNDEBUG -O3 -DNDEBUG -g   -o CMakeFiles/mfscommon_tests.dir/small_vector_unittest.cc.o -c /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc
> In file included from /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:20:0:
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector.h:145:40: error: expected template-name before '<' token
>  class small_vector : public std::vector<T, detail::static_preallocator<T, N>> {
>                                         ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector.h:145:40: error: expected '{' before '<' token
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector.h:145:40: error: expected unqualified-id before '<' token
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector.h:285:2: warning: extra ';' [-Wpedantic]
>  };
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc: In member function 'virtual void SmallVectorTest_GeneralBehaviour_Test::TestBody()':
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:36:23: error: aggregate 'small_vector<int, 5ul> vec1_A' has incomplete type and cannot be defined
>   small_vector<int, 5> vec1_A;
>                        ^
> In file included from /usr/include/gtest/gtest.h:1929:0,
>                  from /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:23:
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:38:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec1_A, vec1_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:40:32: error: variable 'small_vector<double, 3ul> vec2_A' has initializer but incomplete type
>   small_vector<double, 3> vec2_A(5, 1.0);
>                                 ^
> In file included from /usr/include/gtest/gtest.h:1929:0,
>                  from /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:23:
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:42:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec2_A, vec2_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:44:39: error: variable 'small_vector<double, 3ul> vec3_A' has initializer but incomplete type
>   small_vector<double, 3> vec3_A(vec2_A);
>                                        ^
> In file included from /usr/include/gtest/gtest.h:1929:0,
>                  from /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:23:
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:46:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec2_A, vec3_A);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:47:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec3_A, vec3_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:52:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec3_A, vec3_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc: In member function 'virtual void SmallVectorTest_InsertTest_Test::TestBody()':
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:58:2: error: 'iota' is not a member of 'std'
>   std::iota(range.begin(), range.end(), 1);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:60:23: error: aggregate 'small_vector<int, 3ul> vec_A' has incomplete type and cannot be defined
>   small_vector<int, 3> vec_A;
>                        ^
> In file included from /usr/include/gtest/gtest.h:1929:0,
>                  from /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:23:
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:69:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec_A, vec_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:74:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec_A, vec_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc: In member function 'virtual void SmallVectorTest_EraseTest_Test::TestBody()':
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:80:2: error: 'iota' is not a member of 'std'
>   std::iota(range.begin(), range.end(), 1);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:82:27: error: aggregate 'small_vector<short int, 7ul> vec_A' has incomplete type and cannot be defined
>   small_vector<int16_t, 7> vec_A;
>                            ^
> In file included from /usr/include/gtest/gtest.h:1929:0,
>                  from /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:23:
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:91:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec_A, vec_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:96:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec_A, vec_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:101:2: error: template argument 1 is invalid
>   EXPECT_EQ(vec_A, vec_B);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc: In member function 'virtual void SmallVectorTest_IteratorTest_Test::TestBody()':
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:105:27: error: variable 'small_vector<int, 33ul> vec' has initializer but incomplete type
>   small_vector<int, 33> vec(200);
>                            ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:107:2: error: 'iota' is not a member of 'std'
>   std::iota(vec.begin(), vec.end(), 0);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:109:2: error: incomplete type 'small_vector<int, 33ul>' used in nested name specifier
>   small_vector<int, 33>::iterator it;
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:110:2: error: incomplete type 'small_vector<int, 33ul>' used in nested name specifier
>   small_vector<int, 33>::const_iterator cit;
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:113:2: error: 'it' was not declared in this scope
>   it = vec.begin();
>   ^
> In file included from /usr/include/gtest/gtest.h:1929:0,
>                  from /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:23:
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:116:3: error: template argument 1 is invalid
>    EXPECT_EQ(*it, vec[i]);
>    ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:121:2: error: template argument 1 is invalid
>   EXPECT_EQ(it, vec.end());
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:126:3: error: template argument 1 is invalid
>    EXPECT_EQ(*it, vec[i]);
>    ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:131:2: error: 'cit' was not declared in this scope
>   cit = it;
>   ^
> In file included from /usr/include/gtest/gtest.h:1929:0,
>                  from /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:23:
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:133:2: error: template argument 1 is invalid
>   EXPECT_EQ(it, cit);
>   ^
> /<<BUILDDIR>>/lizardfs-3.9.4+dfsg/src/common/small_vector_unittest.cc:134:2: error: template argument 1 is invalid
>   EXPECT_EQ(*it, *cit);
>   ^
> src/common/CMakeFiles/mfscommon_tests.dir/build.make:185: recipe for target 'src/common/CMakeFiles/mfscommon_tests.dir/small_vector_unittest.cc.o' failed
> make[3]: *** [src/common/CMakeFiles/mfscommon_tests.dir/small_vector_unittest.cc.o] Error 1

Please advise.

**Comment by Fretek** [comment]
Is commit def4183 applied?

**Comment by onlyjob** [comment]
def4183 fixes the problem.  Thank you, @Fretek. :)
