### ISSUE TITLE
Allow for mfsfilerepair to perform only chunk version update and not zeroing 

### ISSUE THREAD

**Issue by cloudweavers** [lizardfs/lizardfs#404]
Dear friends, in our platform sometimes after one (or many) unclean shutdowns there may be a few missing chunks due to incorrect version, and a good mfsfilerepair is able to properly restore everything. We want to distinguish between this situation and one where a chunk is truly missing, without having to explicitly do a mfsfilerepair and erasing chunks that are caused by other issues. Would it be possible to add to mfstools/mfsfilerepair something like a "only correct version" flag? At the moment we have to crudely change the part in chunks.cc in the master source (the "didn't find sensible chunk - so erase it" part)- this means that we have to boot with a modified master, perform the filerepair if necessary, shutdown and then start the official mfsmaster. 
A flag for tuning the degree of changes to apply would be IMHO useful for others as well.

**Comment by Zorlin** [comment]
+1, this would be useful and any sane improvement in reliability is worth it

**Comment by psarna** [comment]
It is, of course, possible, unfortunately it is also a little bit more complicated than just adding another flag to mfsfilerepair (assuring changelog compatibility etc). I'll put it in our backlog and someone will take care of it.
