### ISSUE TITLE
mfsmount point permission

### ISSUE THREAD

**Issue by jamesarems** [lizardfs/lizardfs#405]
Hi , 

I have created Lizardfs for getting OpenNebula HA server. Every thing went right , but when mounting filesystem using mfsmount its mounting with root:root permission .
I changed export settings with oneadmin permission . But no hope. 
Inside mount point i can able to change permission .
Do i need to provide any extra configuration?

mkdir /var/lib/one
chown oneadmin:oneadmin /var/lib/one
mfsmount /var/lib/one
chown -R oneadmin:oneadmin /var/lib/one   is giving "You have no permission to change privillages"

ls -l /var/lib/one    is giving  root:root  permission result .

How can i change this? or is it a bug ?

**Comment by psarna** [comment]
Hi James,

once you mount fresh LizardFS installation at /var/lib/one, root directory is indeed owned by root:root, but it is LizardFS's root user. All you have to do is change it once.

Mount LizardFS at /var/lib/one and use superuser privileges to set appropriate permissions to /var/lib/one. Doing it once will permanently change ownership of LizardFS root directory to whatever you need and every subsequent mfsmount call will create a mountpoint with appropriate permissions.
~~~
mfsmount /var/lib/one
sudo chown -R oneadmin. /var/lib/one
# From now on, root directory of your LizardFS installation is owned by oneadmin:oneadmin.
~~~

**Comment by jamesarems** [comment]
Hi psarna , 

Thanks for you reply .
I tried another method and this times it works perfectly .

Mounted /var/lib/one using lizardfs before OpenNebula installation. After installation , permission's are set to  oneadmin:oneadmin .

Thanks mate...:)
