### ISSUE TITLE
Chunks stuck in pending deletion state

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#408]
Hi there,

I have been running benchmarks and experiments on our LizardFS cluster (latest version of the official Debian packages, not the vendor packages) on Debian 8 (Jessie). It mostly handles everything just fine.

However, I have 678 chunks with 1 copy and 218 chunks with 2 copies - both in pending deletion state. Nothing I change seems to get rid of those last pending deletion chunks. I'm a little picky and really want to see 0 pending deletion under normal use.

Is there a way to figure out how to remove those?

Thanks,
~ B

**Comment by psarna** [comment]
Have you played with CHUNKS_SOFT_DEL_LIMIT and CHUNKS_HARD_DEL_LIMIT values from mfsmaster.cfg to speed these up?

Also, master is very cautious when it comes to chunk deletions, which is obviously a good thing.
It may have decided that it is not safe to remove some of these chunks just yet. It may be wrong, but it's better to be wrong this way than the other and remove something that should stay ;)

You can try to browse mfsfileinfo of your files and find which ones are overreplicated. Maybe this additional info will help in recognizing the case.

**Comment by Zorlin** [comment]
Hi @psarna - yes, I have played with both values. It sped up deletion of chunks significantly (I had 100,000 chunks to delete!) but left these last chunks in a pending deletion state. I gave it about an hour and it didn't budge...

Agreed re: right way to do things. I'd definitely rather it be done the safe way.

I'm not sure mfsfileinfo will help - no files are showing as over-goal, and all of these chunks should be belonging to deleted files...

**Comment by psarna** [comment]
Maybe it's related to reserved files, then.

**Comment by Zorlin** [comment]
I thought so too, but the CGI shows 0 reserved files :(

**Comment by onlyjob** [comment]
I'm experiencing this issue as well. At the moment I have 625308 "pending deletion" chunks.
Number is growing around 10_000...20_000 chunks per day and I do not have nearly enough reserved files to account for that many chunks to be deleted.
Setting CHUNKS_(SOFT|HARD)_DEL_LIMIT to 20x times of their default values does not help...
Any ideas?

**Comment by blink69** [comment]
And how master charts "chunk deletions (per minute):" looks like ?

**Comment by onlyjob** [comment]
Looks good. :) Number of "pending deletion" chunks eventually went down to 361 over few last weeks but maybe it is due to upgrade to HEAD of "master". Originally problem manifested on 3.9.4.
Or it could be that master needed more time to work with greater values of *_DEL_LIMIT variables.
Now everything is good, thank you.

**Comment by onlyjob** [comment]
@Zorlin, I'm not the original reporter of this bug but it looks like my reply lead to its close. Are you still experiencing this problem?

**Comment by Zorlin** [comment]
@onlyjob no, the issue eventually resolved itself :) Thanks for checking.
