### ISSUE TITLE
Replication over dedicated network?

### ISSUE THREAD

**Issue by creolis** [lizardfs/lizardfs#410]
Hej Guys,

we recently switched to lizardFS and for now we're pretty impressed.
Coming from CEPH, we're "used" to have our chunk replication handled by a
dedicated NIC / Switch / L2 network - but we're not sure how to realize this
with lizardFS and we did not find any information about this mentioned in the
docs.

Is it possible to handle client traffic with one NIC and have chunk replication
configured to use another network?

An example why this would be great: Out frontend network is configured to
an MTU of 1500, while the chunk replication could in our opinion take advantage
of jumbo frames.

Did we miss this feature, is it on some sort of roadmap or are there any compelling
reasons?

all the best, and keep up the great work,

Daniel

**Comment by 4Dolio** [comment]
I dont think that is possible. The chunk servers register to the master at an IP, which the master will convey to clients to use to contact the chunk servers also.  You could run the lizard cluster members all on the storage network and from there do something like have the chunkservers run nfs and export to clients via the other NIC via your client network.  Or run some dedicated clients with a leg in both networks to re-nfs export, iSCSI export, cifs export, etc to the client network. All my clients have legs in both our storage and client networks.

**Comment by MPaszkiewicz** [comment]
Hi @creolis
Replication over dedicated network is currently not possible and we have no plans for adding it in the nearest future. However, if you consider this feature being essential and would like it to be implemented, please contact support@lizardfs.com
