### ISSUE TITLE
libisal portability

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#413]
3.10.0-rc uses _libisal_ which is [not very portable](https://buildd.debian.org/status/package.php?p=libisal) (to say the least).

LizardFS currently [builds on 20 architectures](https://buildd.debian.org/status/package.php?p=lizardfs&suite=sid) so portability of _libisal_ is a concern.

Is there a fallback or alternative library that could be used?
Maybe [Jerasure library](http://web.eecs.utk.edu/~plank/plank/www/software.html)?

**Comment by cloudweavers** [comment]
Unfortunately Jerasure is no longer maintained, after a spat with a commercial vendor:
"GF-Complete and Jerasure versions 2.0 and later are no longer supported...GF-Complete and Jerasure version 2.0 have been removed from web sites at the University of Tennessee and bitbucket.org. The source code of both projects have been archived for non-commercial use" and they explicitly mention possible patent coverage: "StreamScale, Inc. asserts that the use of GF-Complete (particularly as part of Jerasure 2.0 or later) or any similar software, method or code for erasure coding infringes StreamScale's issued United States Patent No. 8,683,296."
While this does not means that other libraries are non-infringing, the fact that it's no longer maintained IMHO means that we should look elsewhere.

**Comment by Zorlin** [comment]
Ouch, could this affect LizardFS on Raspberry Pi and similar ARM boards?

I know few clusters are built on ARM, but they're a great way to experiment
with LizardFS.

**Comment by psarna** [comment]
A substitute for ISA-L is implemented (see https://github.com/lizardfs/lizardfs/blob/master/src/common/galois_field_encode.cc for instance) and should build fine. Architectures with ISA-L support should benefit from it, but, nonetheless, a fallback implementation is already prepared.

**Comment by Zorlin** [comment]
@psarna Excellent, thanks for your input. 👍

**Comment by onlyjob** [comment]
Sad news about Jerasure... I wonder if there are any free alternatives?
It would be nice to see a successor of the Jerasure project...

I'm closing this bug since fallback is already implemented hence there is nothing left to do here.

Once 3.10 is released I'll update official Debian packaging to build LizardFS with _libisal_ on x86_64 (a.k.a. _amd64_) only...
