### ISSUE TITLE
How does Lizard balance storage and handle full volumes?

### ISSUE THREAD

**Issue by syadnom** [lizardfs/lizardfs#417]
I've read all the docs I can find and they don't seem to specifically state how LizardFS will handle full disks.  I'm going to setup a test cluster designed with a meta and shadow and then a number of storage servers with just 1-2 large disks per storage node.

I would be running up to 80-90% capacity on disks before adding to the cluster so I can leverage decreasing storage costs (instead of building a very large cluster up front).  Basically, what if I get a rather large commit to the storage cluster that fulls a disk to 100%?

Thanks.

**Comment by borkd** [comment]
Lizardfs tends to be graceful in typical abuse scenarios, but it won't do miracles. So yes, you _could_ set it up like that if it fits your needs and you are OK with consequences. If you care about your data and/or system performance you should also consider the arguments why _this may not be the best idea_.

Most underlying filesystems will not perform optimally when at 80%+ full. Lizardfs performance will thus suffer as a consequence. Your ability to absorb failures will be unpredictable at best, recovery times and chances for unmet replication goals will increase unless you are planning to have **lots** of such chunkservers (and thus significantly reduce the odds of saturating all of them at the same time).

**Comment by cloudweavers** [comment]
There are two separate aspects: LizardFS handling of disk (nearly) full and the underlying filesystem handling of the same condition.
As for LizardFS, there is no specific limit that we found related to individual disk occupation. We pushed chunkservers to disk full condition in our testing, and we found no problems at all. 
Much different is the underlying situation, that is how filesystems handle a disk that is nearly full. The answer: badly. From somehow badly (XFS, EXT4) to unbelievably badly (BTRFS), to anything inbetween (ZFS).
XFS for example slows down a bit, trying to find space; BTRFS hangs there, and recovery is painful and difficult. ZFS works, but slows down a lot (up to 4 times slower) as soon as you reach 85%-90% of disk occupation (more or less the same applies to other CoW filesystems like NetApp)
So: LizardFS works equally well even with full occupation, but the underlying filesystems do not.

**Comment by syadnom** [comment]
maybe I need to clarify a bit.  Lets say a single disk is essentially full, but other disks on other nodes have plenty of space.  Will lizard be able to avoid writing to the full device, knowing that there is free space on another node?

**Comment by cloudweavers** [comment]
Let's say you have two disks on the same chunkserver. Then, Lizard will spread the chunk creation on the disks, to preserve approximately the same occupation percentage on both disks. This means that occupation is evenly spread to within a few percent (changeable using the ACCEPTABLE_DIFFERENCE parameter in mfsmaster.cfg)§.

**Comment by syadnom** [comment]
ok, so if I have 2 chunk servers, one with 2TB and one with 4TB, Then lizard is basically going to 'waste' 1/2 of the larger disk?

If I have 10 chunk servers with all various sized disks,how can lizard not be bound by the smallest disk?

**Comment by Zorlin** [comment]
It measures usage based on percentage, not actual size. So each disk would
go to ~95% usage as they filled, wasting little space.

**Comment by psarna** [comment]
And in order to address potential problems with full filesystems mentioned by @cloudweavers, chunkservers have HDD_LEAVE_SPACE_DEFAULT parameter in their configuration files. It defaults to 4GiB and prevents filesystems from being filled to 100% of their capacity.

**Comment by syadnom** [comment]
ok, that works.  I'm not necessarily planning to fill the disks up typically, but more thinking that I would add drives and chunk nodes as needed and there would be mis-matched sizes.

What I'm taking away from this is that as long as there is free space available on some chunk node that the data will find a home.

As far as native filesystem issues with full disks, I would very likely be using ext4 or XFS.  I wouldn't be doing any raid or raidlike(zfs,btrfs) stuff under lizard, rather rely on lizard having multiple copies.

**Comment by Zorlin** [comment]
That sounds like a solid plan. I've dabbled with stuff like RAID and ZFS
(zRAID) bricks, but simply using the disks directly has consistently worked
best.

**Comment by syadnom** [comment]
well, thanks for the words guys.  I'm going to close this 'issue' out.

**Comment by onlyjob** [comment]
We are using Btrfs volumes on some chunkservers in order to take advantage of data compression while we wait for #366 to be implemented. Btrfs needs periodic maintenance to avoid problems with (lack of) free space. The following nightly (or weekly) script helps to prevent problems:

~~~~
for M in $(grep btrfs /proc/mounts | awk '{print $2}'); do
    btrfs balance start -v -dusage=65 "$M"
done
~~~~
