### ISSUE TITLE
How I can take csv text data for charts, which displays after select field changing?

### ISSUE THREAD

**Issue by butteff** [lizardfs/lizardfs#418]
Hello!
I am creating new charts design for lizard and I have got problem, can you help me with it?

The problem is here:
For some charts we have got url to charts.cgi, where I can see timestamp and data in text csv format.
So I can use it for js charts generation, instead of your images and it is ok for me, I've already did few charts with this data and them looks perfect.

But I can't take text data of charts form select field, for example, for this "Traffic from clients and other chunkservers (bits/s)" it gives to us image only without any urls to text timestamp.

I've tried to use image data for charts.cgi (like id from image url), similar with another charts, where I can take text data, but it gives image as result anyway.
I've tried to edit code and leave only displaying of timestamp, without any img, but still I have image as result in this case.
I've tried to search any csv files on the server, but can't find nothing.

Can you help me with it? 

thank you.

**Comment by psarna** [comment]
Browsing the cgi code is not exactly my hobby, but fortunately this case looks simple. I can see that when image's URL (let's take your **Traffic from clients and other chunkservers (bits/s)** as an example) is of the form
~~~
http://localhost:9425/chart.cgi?host=192.168.88.202&port=10022&id=1020
~~~
then its corresponding csv is available at **id + 90000**, i.e. 
~~~
http://localhost:9425/chart.cgi?host=192.168.88.202&port=10022&id=91020
~~~

**Comment by butteff** [comment]
Thank you so much!
