### ISSUE TITLE
can't write from OS X client

### ISSUE THREAD

**Issue by krissfr** [lizardfs/lizardfs#425]
Hello,

i have compiled and installed an OS X client, i can read file without problem but i can't write.
In attachment you will find the output in with the debug parameter of mfsmount.
[lizardfs_debug_output.docx](https://github.com/lizardfs/lizardfs/files/348084/lizardfs_debug_output.docx)

Do you have any advices to write successfully with an OS X client ?

**Comment by Fretek** [comment]
What version of client, chunkserver do you have?

Probably you are using newer version of client then chunkservers. 
In that case write didn't work. 
This issue was fixed in commit d4b67d2036443a1b63d67ed305c147eb06674da5.

**Comment by krissfr** [comment]
Thank you @Fretek !
you're right my chunck server are 3.9.4 and to build my OSX client i use the 3.10.0 branche.

i will rebuild the OSX Client from the master branche.

thank you again :)
