### ISSUE TITLE
TapeServer code missing

### ISSUE THREAD

**Issue by proceau** [lizardfs/lizardfs#428]
Hi,

on TU and other matots and other part of code mention of tapeserver, but code missing, where can find, or i'm need to rewrite ?

https://github.com/lizardfs/lizardfs/blob/f7c7f9f3275a3ec6a4b8ea56e330e955b40710df/tests/test_suites/TapeserverTests/test_tapeserver_goal.sh

**Comment by blink69** [comment]
This part of LizardFS is not on GPL licence, if you are intrested supporting LTO library, please contact sales@lizardfs.com
