### ISSUE TITLE
3.10.1 release plan

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#431]
As far as I'm concerned 3.10.0 (or 3.10.1) is ready to be released.
Let's track remaining issues here.

-  [ ] Tag new release
-  [ ] Mention _REPLICATIONS_ to _OPERATIONS_ conf options rename in NEWS: 8d94dd5

**Comment by onlyjob** [comment]
How's plans for release? What's the time frame?

**Comment by psarna** [comment]
3.10.0 is virtually ready, it should be officially announced very soon. 3.10.1 is unstable and 3.10.2 is almost ready, but there are some patches waiting to be merged (and then it will be tested for some time).

**Comment by blink69** [comment]
3.10.0 released.

https://github.com/lizardfs/lizardfs/releases/tag/v.3.10.0

**Comment by onlyjob** [comment]
It happens that 3.10.0 does not include fix for #412 and #402 which makes me worry if all three fixes for #422 are included... Please handle releases more carefully.
