### ISSUE TITLE
Trash file bug

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#434]
Debian Jessie, LFS 3.10.1

I have a strange problem with a trash and I can not remove certain files
example:

>  ls: cannot access 0007CC55|data|owc|cloud|web.tgz: No such file or directory
>  
>  find /data/lfs-kosz -type f -exec sh -c 'mfsfileinfo "{}" | grep -q "no valid copies" && echo "{}" && mfsfilerepair "{}";' \;
>  find: `/data/lfs-kosz/trash/0007CC55|data|owc|cloud|web.tgz': No such file or directory
> ls *web.tgz
> ls: cannot access 0007CC55|data|owc|cloud|web.tgz: No such file or directory

**Comment by blink69** [comment]
Hmm, this looks like a pipe escape problem :)

**Comment by onlyjob** [comment]
I don't see how is that related to LizardFS... 
@andypl78, please give us straightforward reproducer (and we shall be happy to re-open this bug).
Alternatively you can give us a sequence of commands (and their output) that clearly demonstrates the problem.
We can't troubleshoot your scripts...
