### ISSUE TITLE
lizardfs-uraft missing from ubuntu repo

### ISSUE THREAD

**Issue by nadiasvertex** [lizardfs/lizardfs#436]
According to the install instructions there should be a package named lizardfs-uraft that can be used in an HA setting. However, I do not see any such package:

```
$ apt-cache search "lizardfs*"
lizardfs-chunkserver - LizardFS data server
lizardfs-common - LizardFS common files
lizardfs-cgi - LizardFS CGI Monitor
lizardfs-cgiserv - Simple CGI-capable HTTP server to run LizardFS CGI Monitor
lizardfs-adm - LizardFS administration tools
lizardfs-master - LizardFS master server
```

**Comment by richard-scott** [comment]
Either that is part of the commercial paid-for support or it doesn't exist... not sure exactly, but I've never seen it.

**Comment by blink69** [comment]
Right now its a part of our commercial support, we don't have plan to release this on gpl licence.

**Comment by nadiasvertex** [comment]
It would be nice to identify that in the setup instructions so people don't
spend alot of time trying to find the package.

**Comment by blink69** [comment]
Ok, we will fix that.
