### ISSUE TITLE
Downgrade a LizardFS Master to Shadow?

### ISSUE THREAD

**Issue by Asher256** [lizardfs/lizardfs#439]
Hi,

Question: **Can I change the Masters' PERSONALITY from MASTER to SHADOW safely?**

I did it, but I've noticed this in the logs:
```
"trying to preform forbidden personality change from Master to Shadow"
```

Let me explain how I got the error/warning message below:

**I've 2 servers, configured for HA:** 
- Server A: _LizardFS Master_ (with the **mfsmaster** virtual IP 10.100.0.120)
- Server B: _LizardFS Shadow_ 

If the Server A (LizardFS Master) fails, my failover script will: 
- Upgrade the Shadow (Server B) to Master
- Move the virtual IP  10.100.0.120 from Server A (old master) to Server B (the new master)

After that, my failover script will do this in Server A (the previous master):
- put PERSONALITY=shadow on  /etc/lizardfs/mfsmaster.cfg (the personality was 'MASTER' before)
- mfsmaster restart

It worked successfully, but I've noticed this in the logs:
```
"trying to perform forbidden personality change from Master to Shadow"
```

Does it mean I lose some data because I've changed from Master to Shadow?

What is the alternative solution, if the one below is forbidden?
(do I need, for example, to wipe out the LizardFS data on the old master "server A" + start a clean shadow that is going to synchronize with the new master?)

Thank you!

Asher256

**Comment by psarna** [comment]
Hi,

"forbidden" personality change occurs if you try to downgrade master online
(i.e. change configuration from PERSONALITY=master to PERSONALITY=shadow
and reload via `mfsmaster reload`). Master server restart is the right way
to perform downgrade, so your script is correct and there is no way data
loss can occur. Perhaps you reloaded master after changing its
configuration and it just refused to become a shadow. There is absolutely
no need of wiping out any data and it is not recommended as well - it is a
valid copy of your metadata, so it's valuable stuff;)

**Comment by Asher256** [comment]
Thank you Psarna for the fast answer!

Have a nice day.

Asher256

**Comment by 4Dolio** [comment]
There is also an mfsmaster command that can communicate with the master service when running in PERSONALITY=ha-cluster-managed which https://github.com/4Dolio/lizardfs/commits/4Dolio-corosync-ocf-metadataserver-patch-1 and I think the native uraft failover solution also leverages.  It can change personalities on the fly without modifying the config file among other things.

**Comment by Asher256** [comment]
+1
