### ISSUE TITLE
How do I safely move hdd paths in mfshdd.cfg?

### ISSUE THREAD

**Issue by biocyberman** [lizardfs/lizardfs#446]
I first assigned `/mnt/mydrive/data/lizardchunks` in `mfshdd.cfg`. Now I want to keep the chunks that have been placed there, but change path in mfshdd to something else, like: `/mnt/hdd1/lizardchunks`. 

How do I do that safely?

**Comment by 4Dolio** [comment]
If you have a goal greater than 1 then you just what you proposed. If you only have a goal of 1 then those files will be offline for a few moments as you make that change. Stop chunkservice. Reconfig. Remount. Start CS.

**Comment by biocyberman** [comment]
So chunks have unique IDs, and do not depend on where they are saved. That's smart.

**Comment by Asher256** [comment]
I agree, that's smart ;-) . I like the idea.

**Comment by 4Dolio** [comment]
yup.. You can move/copy disks and/or chunk folders/files around the cluster without any problem, though they may go stale and old during the time you are moving them around.
