### ISSUE TITLE
Question: how to set a XOR goal?

### ISSUE THREAD

**Issue by Asher256** [lizardfs/lizardfs#450]
Hi,

How to set a xor goal to a directory?

I tried the command mfssetgoal with xor3 in the goal but it didn't work. Do I need to set it in a configuration file before?

**Comment by MPaszkiewicz** [comment]
Hi,
In order to use a specific goal, you should first define it inside mfssetgoals.cfg file and reload the master. You can find the example configurations of goals in mfssetgoals.cfg.dist file.
To use xor3, you could add something like this:
6 xor3 : $xor3

**Comment by Asher256** [comment]
Thank you MPaszkiewicz. I will try the setting "6 xor3 : $xor3" you suggested.
