### ISSUE TITLE
Chunk name format?

### ISSUE THREAD

**Issue by biocyberman** [lizardfs/lizardfs#454]
I am learning to understand LizardFS working to better manage manage my data.

This should be straight forward: what is the format of file name for a chunk?

True or False: Chunk names are generated by a centralized process in mfsmaster to avoid duplication or race?

For example, what does this name tell us:

```
./chunks00/chunk_0000000000001BB3_00000001.mfs
# break into 6 portions for readability
1:./chunks 2:00 / 3:chunk_0000000000 2:00  4:1BB3 _  5:00000001 . 6:mfs
```

My guess:
1. **chunks**: indicate a chunk folder.
2. **00**: unique chunk folder id in a disk, can have duplicates across disks or chunkservers. 
IDs ranges from "00" to "FF" in Hex number. So there are max 256 chunks folders in a disk.
3. **chunk_0000000000**: prefix? placeholder? I don't know.
4. **1BB3**: Hex unique ID across chunk folders with the same ID (`00` in this case). 
This ranges from `0000` to `FFFF`, so there are max 65535 chunks in across chunks with the same ID.
This is true in the whole cluster.
5. **00000001**: Chunk replicate ID?
6. **mfs**: File extension, of course.

All of this make sure that diskX/chunks??/*.mfs and /diskY/chunks??/*.mfs will never duplicate filenames. Is this true?

**Comment by 4Dolio** [comment]
Is that a real example? Or just made up? I use:
* /MountPoint00 (one of many disks)
 * /ClustersNameDir (forces error if ^mount fails, and allows for multiple cluster using same disk)
  * /chunk00 (was once just "00", first native organizational shard folder)
   * chunk_(prefix)000BIG0HEX0Sequential(chunkid(last 2 match parent folder?))_(seperator)00001(chunk revision value).mfs(extension)
.oO( without looking at any actual chunk files in the wild )

**Comment by biocyberman** [comment]
@4Dolio I fetched the name from one of my real chunks.

**Comment by psarna** [comment]
If you speak C++, these can help you:
https://github.com/lizardfs/lizardfs/blob/master/src/chunkserver/chunk_filename_parser.h
https://github.com/lizardfs/lizardfs/blob/master/src/chunkserver/chunk_filename_parser.cc

In short, things encrypted in each chunk filename are **chunk id**, **chunk version** and **chunk format**.

**Comment by biocyberman** [comment]
@psarna I can mumble C++. So it's possible to figure out the format rules from there. I was just trying to make it in non-programming language.
