### ISSUE TITLE
Ubuntu install instructions in PDF depend on non-existent lsb_release

### ISSUE THREAD

**Issue by drauschenbach** [lizardfs/lizardfs#455]
The `lsb_release` Debian package is not available to modern Ubuntu distros, and getting it installed is not straightforward. So the Ubuntu install instructions should not depend on it.

**Comment by biocyberman** [comment]
@drauschenbach  I don't know which PDF document you are talking about. I used instructions in this wiki page and it does not mention anything about lsb_release. https://github.com/lizardfs/lizardfs/wiki/Quick-Start-Guide-(Debian-Ubuntu-repository)

**Comment by drauschenbach** [comment]
1. Start at http://lizard.org (--> redirects to lizard.com)
2. Click Documentation (--> loads https://lizardfs.com/documentation/)
3. Click "Technical Documentation describes all functionality available in LizardFS - pdf" (--> loads https://lizardfs.com/wp-content/uploads/2016/02/LizardFS-technicaldocumentation_16072016.pdf)
4. Page 11 contains the section "How to install LizardFS from precompiled packages on Debian / Ubuntu", which instructs Ubuntu users to use the non-existent lsb_release command.

**Comment by pbeza** [comment]
[`lsb_release`](https://linux.die.net/man/1/lsb_release) command is provided by [`lsb-release`](https://packages.ubuntu.com/search?keywords=lsb-release) package which is present in all Ubuntu [releases](https://wiki.ubuntu.com/Releases) (from [Ubuntu Trusty 14.04](https://wiki.ubuntu.com/TrustyTahr) to [Ubuntu Disco](https://wiki.ubuntu.com/DiscoDingo)), so it shouldn't be a problem.

Referred instructions are no longer in [PDF file](https://lizardfs.com/wp-content/uploads/2016/02/LizardFS-technicaldocumentation_16072016.pdf). Instructions that you've mentioned are still present [here](https://docs.lizardfs.com/adminguide/installation.html?highlight=lsb_release).

This issue should be closed.
