### ISSUE TITLE
Using LizardFS on a slow and unreliable network

### ISSUE THREAD

**Issue by annymous** [lizardfs/lizardfs#457]
I have a test cluster with seven VPS: master, four chunkservers, metalogger/cgiserv, and client. The network is slow and unreliable: latency 500-1500 ms, bandwidth 500-1500 kbps, and 0%-10% packet loss. The amazing thing is that "mfsmount /mnt/lizardfs" completes in the client, and files can sometimes be written and read. But often, even small reads hang and fail with I/O errors, and nothing will work until I restart LizardFS services on all nodes.

Is it possible to tweak configuration options for such a slow and unreliable network? Looking at the manual, perhaps these values would be appropriate:

```
CHUNKS_LOOP_MAX_CPS = 1000
CHUNKS_LOOP_PERIOD = 10000
GLOBALIOLIMITS_RENEGOTIATION_PERIOD_SECONDS = 2
```

Thanks.

**Comment by psarna** [comment]
You can also amend some mount settings (since it's probably the connection between mount and chunkserver that fails in your case). Some examples from `man mfsmount`
~~~
       -o mfschunkserverreadto=MSEC
           set timeout for whole communication with a chunkserver during read operation in milliseconds (default: 2000)

       -o mfschunkserverwriteto=MSEC
           set chunkserver response timeout during write operation in milliseconds (default: 5000)

       -o mfschunkserverrtt=MSEC
           set timeout after which SYN packet is considered lost during the first retry of connecting a chunkserver (default: 200)

       -o mfschunkserverconnectreadto=MSEC
           set timeout for connecting with chunkservers during read operation in milliseconds (default: 2000)

       -o mfschunkserverwavereadto=MSEC
           set timeout for executing each wave of a read operation in milliseconds (default: 500)

       -o mfschunkservertotalreadto=MSEC
           set timeout for the whole communication with chunkservers during a read operation in milliseconds (default: 2000)

~~~

Chunkservers have some configurable timeouts in their mfschunkserver.cfg files as well, e.g.
~~~
       CSSERV_TIMEOUT
           timeout (in seconds) for client (mount) connections (default is 5)
~~~
