### ISSUE TITLE
xor3: failed (Invalid argument)

### ISSUE THREAD

**Issue by Asher256** [lizardfs/lizardfs#459]
I added two goals in mfsgoals.cfg and reloaded mfsmaster successfully:
```
13 xor3 : $xor3
12 xor2 : $xor2
```

But when I tried to set the goal, I had an error:
```
$ mfssetgoal -r 13 xor3
xor3: failed (Invalid argument)
```

Is there something wrong with my mfsgoals.cfg?

Thanks.

**Comment by psarna** [comment]
mfssetgoal works on goal names, not numbers. With your config, appropriate
command is 'mfssetgoal -r xor3 DIRECTORY_NAME'

On Wednesday, August 31, 2016, Asher256 <notifications@github.com> wrote:
> I added two goals in mfsgoals.cfg and reloaded mfsmaster successfully:
>
> 13 xor3 : $xor3
> 12 xor2 : $xor2
>
> But when I tried to set the goal, I had an error:
>
> $ mfssetgoal -r 13 xor3
> xor3: failed (Invalid argument)
>
> Is there something wrong with my mfsgoals.cfg?
>
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/zUgUh8c9Ct85eXAwmkUY6FVN7acXD_NgYOJ1ute_5IvPviUQVzAm0XkJFtt9UtOQ4QHWg65G6SkMZEiXbNCljTYDX4Yx0euJY5Vvte2j5O_MYjGeDy7Q2l4fvcqG9qgGlpHXgqt7_h8R90e9FcfGVDWZc4vWiw=s0-d-e1-ft#https://github.com/notifications/beacon/AJ8yFwR7ie54_K74TfJ02bAsQM4FnjD9ks5qlcHYgaJpZM4Jx5Oq.gif>

**Comment by Asher256** [comment]
Thank you!
