### ISSUE TITLE
Print reason for chunkserver failure after installation

### ISSUE THREAD

**Issue by pjanicki** [lizardfs/lizardfs#46]
Chunkserver normally does not start after installation,  because it is disabled.
Enabling and starting causes failure as folows

--
root@debian:~# /usr/local/etc/init.d/lizardfs-chunkserver start
Starting LizardFS chunkserver daemon:
cannot load config file: /usr/local/etc/mfs/mfschunkserver.cfg
can't load config file: /usr/local/etc/mfs/mfschunkserver.cfg - using defaults
working directory: /usr/local/var/lib/mfs
lockfile created and locked
initializing mfschunkserver modules ...
init: hdd space manager failed !!!
error occured during initialization - exiting
[FAIL] Starting lizardfs-chunkserver... ... failed!

--

The cause of this error is missing configuration file mfs/mfshdd.cfg. This should be stated explicitly.

**Comment by psarna** [comment]
It works now.
