### ISSUE TITLE
errors writing to chunkservers

### ISSUE THREAD

**Issue by liahsire** [lizardfs/lizardfs#461]
I'm experimenting with a LizardFS cluster on Digital Ocean droplets. In a client, writing to /mnt/lfs yields, in debug mode:
    ...
    X bytes have been written to inode Y
    flush (Y)
    [WARN] write file error, inode: Y, index: 0 - Read from chunkserver: connection closed by peer (server w.x.y.z:9422) (try counter: 1)
    ...
    [WARN] error writing file number Y: EIO (Input/output error)
    release (Y)
I thought that perhaps LizardFS won't accept filesystem directories as HDD mount points, so I instead mounted file-back virtual disks. That doesn't work either. But perhaps I've made some other mistake.
Should I expect chunkservers to work with storage in /dev/loop0 mounted at /mnt/lfs?

**Comment by psarna** [comment]
LizardFS works perfectly fine with filesystem directories as HDD mount points. Try using `lizardfs-admin list-chunkservers YOUR_MASTER_IP 9421` and `lizardfs-admin list-disks YOUR_MASTER_IP 9421` and see if there are some anomalies there. If, for example, chunkservers seem to have available space of 0 bytes, maybe it is the issue with permissions. Your data directories specified in mfshdd.cfg should have proper rights for `mfs` user. If that's the case, `chown -R mfs. /mnt/your_data_directory` will help you.

**Comment by richard-scott** [comment]
Do you have SELinux or AppArmor enabled? Maybe that is restricting where your processes can write to?

**Comment by liahsire** [comment]
Thank you. About filesystem directories as HDD mount points, perhaps my question was ambiguous. Is it OK to simply use a filesystem directory as chunkserver storage, without actually having a disk mounted there?
Anyway, my chunkservers are currently using file-backed virtual disks mounted in /mnt/lfs/. The lizardfs-admin commands succeed for all nine chunkservers:

    # lizardfs-admin list-chunkservers a.b.c.d 9421
      Server w.x.y.z:9422:
              version: 3.10.0
              label: _
              chunks: 0
              used space: 2.0GiB / 14GiB
              chunks marked for removal: 0
              used space marked for removal: 0B / 0B
              errors: 0

    # lizardfs-admin list-disks a.b.c.d 9421
      w.x.y.z:9422:/mnt/lfs/
              to delete: no
              damaged: no
              scanning: no
              last error: no errors
              total space: 14GiB
              used space: 2.0GiB
              chunks: 0

And on each chunkserver, I see:

    # ls -lah /mnt
      total 20K
      drwxr-xr-x   3 root root 4.0K Sep  5 03:59 .
      drwxr-xr-x  22 root root 4.0K Aug 31 06:17 ..
      drwxr-xr-x 259 mfs  mfs   12K Sep  5 04:04 lfs
    
    # ls -lah /mnt/lfs
      total 1.1M                                                                                     
      drwxr-xr-x 259 mfs  mfs   12K Sep  5 04:04 .                                                   
      drwxr-xr-x   3 root root 4.0K Sep  5 03:59 ..                                                  
      drwxr-x---   2 mfs  mfs  4.0K Sep  7 01:03 chunks00                                            
      ...
      drwxr-x---   2 mfs  mfs  4.0K Sep  5 04:04 chunksFF
      -rw-r-----   1 mfs  mfs     0 Sep  5 04:04 .lock
      drwx------   2 root root  16K Sep  5 03:58 lost+found

I neglected to mention that client, master, metalogger and chunkservers are connected via OnionCat with ip4ip6 tunnels, and that rtt among them is 200-1000 ms. I have adjusted some parameters to tolerate high latency. In the master ...

    # nano /etc/mfs/mfsmaster.cfg
      ...
      CHUNKS_LOOP_MAX_CPS = 1000
      CHUNKS_LOOP_PERIOD = 10000
      GLOBALIOLIMITS_RENEGOTIATION_PERIOD_SECONDS = 2

... and in the client ...

    # nano /etc/mfs/mfsmount.cfg
      ...
      mfsdebug
      mfscachemode=NO
      mfschunkserverreadto=20000
      mfschunkserverwriteto=50000
      mfschunkserverrtt=2000
      mfschunkserverconnectreadto=20000
      mfschunkserverwavereadto=5000
      mfschunkservertotalreadto=20000

Those settings worked in a smaller test cluster, also connected via OnionCat. In that cluster, I used VirtualBox VMs, and added a second VDI to each chunkserver for storage.

Are there other parameters that I ought to tweak for high latency?

**Comment by liahsire** [comment]
@richard-scott

I'm using stock Digital Ocean droplets (via bithost.io) running Debian 8.5 x64. I've never used SELinux or AppArmor, so honestly I can't say whether or not they're configured. Thanks. I'll check.

**Comment by liahsire** [comment]
@richard-scott

Yes, it does appear that AppArmor is enabled. At least, in /etc/apparmor.d/local/ I see the file "system_tor", created when I installed tor, and in /etc/apparmor.d/abstractions/ I see the file "tor".

So I'm guessing that I need to configure AppArmor to allow lizardfs-chunkserver to write to /mnt/lfs/. I'll look, but a pointer would be helpful.

**Comment by liahsire** [comment]
@richard-scott

No, I was wrong. AppArmor isn't installed. Tor must have added those files.

**Comment by liahsire** [comment]
@psarna

LizardFS does indeed work perfectly with plain filesystem directories posing as HDD mount points. In my first cluster, I changed chunkserver storage from mounted VirtualBox VDIs to plain filesystem directories. And it still works.

But the Digital Ocean cluster still doesn't work. So I need to review and compare all of the configurations. But I do know that the client can write to at least one of the chunkservers. After mounting /mnt/lfs/ in chunkserver lfs02 via sshfs on /mnt/lfs02 in the client, I could read and write to, for example, /mnt/lfs/chunks00/.

Also, in the course of testing that, I realized that LizardFS is in fact creating .mfs files in /mnt/lfs/chunksNN/. For example, I see in /mnt/lfs02/chunks00/:

    total 48K
    drwxr-x--- 1 110 116 4.0K Sep  8 10:57 .
    drwxr-xr-x 1 110 116  12K Sep  8 06:09 ..
    -rw-r----- 1 110 116 5.0K Sep  8 00:52 chunk_000000000000000A_00000001.mfs
    -rw-r----- 1 110 116 5.0K Sep  8 04:13 chunk_0000000000000010_00000001.mfs
    -rw-r----- 1 110 116 5.0K Sep  8 09:30 chunk_0000000000000012_00000001.mfs
    -rw-r----- 1 110 116 5.0K Sep  8 10:07 chunk_0000000000000013_00000001.mfs

However, those .mfs contain only "LIZC 1.1^@^@^@...^@^@^@".

**Comment by liahsire** [comment]
OK, I think that I understand what's going on. But not exactly why.

My first test cluster comprised seven VirtualBox VMs:

    192.168.100.100   master
    192.168.100.101   meta logger
    192.168.100.102   chunkserver 1
    192.168.100.103   chunkserver 2
    192.168.100.104   chunkserver 3
    192.168.100.105   chunkserver 4
    192.168.100.111   client

Although those are local IPv4 addresses, I configured iptables to isolate them, and to allow connections among them only via ip4ip6 tunnels through OnionCat links.

My second test cluster comprised twelve Digital Ocean droplets:

    a.b.c.d   master lfs00
    e.f.g.h   meta logger lfs01
    i.j.k.l   chunkserver lfs02
    ...
    s.t.u.v   chunkserver lfs10
    w.x.y.z   client lfs11

I configured connections among them via ip4ip6 tunnels through OnionCat links, just as for the VirtualBox cluster. I configured iptables to block all new incoming connections, and to allow outgoing connections only for the tor daemon. Each of the droplets could ping all of the others. And yet writes to chunkservers failed.

So far I've managed to get DO chunkserver lfs02 working with the VirtualBox cluster. Basically, I just needed to add an IPv4 address in 192.168.100.0/24.

    # ip addr add 192.168.100.106/24 dev eth0
    # ip -6 tunnel add ip6tnl1 mode ip4ip6 remote [VBox master OnionCat IPv6] local [DO cserver OnionCat IPv6]
    # ip -6 tunnel add ip6tnl2 mode ip4ip6 remote [VBox mlogger OnionCat IPv6] local [DO cserver OnionCat IPv6]
    # ip -6 tunnel add ip6tnl3 mode ip4ip6 remote [VBox client OnionCat IPv6] local [DO cserver OnionCat IPv6]
    # ip link set dev ip6tnl1 up
    # ip link set dev ip6tnl2 up
    # ip link set dev ip6tnl3 up
    # ip route add to 192.168.100.100/32 dev ip6tnl1 metric 1
    # ip route add to 192.168.100.101/32 dev ip6tnl2 metric 1
    # ip route add to 192.168.100.111/32 dev ip6tnl3 metric 1
    # ip route show
      default via i.j.k.l dev eth0
      ...
      i.j.k.l/20 dev eth0  proto kernel  scope link  src i.j.k.l
      192.168.100.0/24 dev eth0  proto kernel  scope link  src 192.168.100.106
      192.168.100.100 dev ip6tnl1  scope link  metric 1 
      192.168.100.101 dev ip6tnl2  scope link  metric 1 
      192.168.100.111 dev ip6tnl3  scope link  metric 1 
    # nano /etc/hosts
      127.0.1.1        lfs02 lfs02
      127.0.0.1        localhost
      192.168.100.106  lfs02
      192.168.100.100  mfsmaster
    # nano /etc/mfs/mfschunkserver.cfg
      ...
      BIND_HOST = 192.168.100.106
      MASTER_HOST = 192.168.100.100
      ...
      HDD_LEAVE_SPACE_DEFAULT = 2GiB
      ...

Perhaps I could have just accomplished that using BIND_HOST and MASTER_HOST. But in any case, I would not want to share public IP addresses of chunkservers with clients, and so would have followed the same path.

I am very impressed with how well LizardFS performs on such slow and unreliable connections.

**Comment by psarna** [comment]
We have some fancy pictures of how LizardFS clients, chunkservers and metadataservers connect to each other during reads/writes, if you're curious. All communication is done through tcp/ip. This is roughly how reading and writing to regular goals (not xor/ec) works:

![lizardfs_read](https://cloud.githubusercontent.com/assets/10433047/18480166/f4491816-79d7-11e6-81dc-d4c00cf98082.png)
![lizardfs_write](https://cloud.githubusercontent.com/assets/10433047/18480167/f44af640-79d7-11e6-9bcd-7941df59ab28.png)

**Comment by liahsire** [comment]
Thanks. Cool pictures.

So, would putting "BIND_HOST = i.j.k.l" and "MASTER_HOST = a.b.c.d" in /etc/mfs/mfschunkserver.cfg have likely resolved my issue with failed chunkserver writes?

Having "i.j.k.l  lfs02" and "a.b.c.d  mfsmaster" in /etc/hosts was clearly not enough. But then, those are unrelated public IPv4 addresses from different DCs.

Or is it necessary for master and chunkservers to have IPv4 addresses in the same subnet?

Also, can IPv6 addresses be used with LizardFS?

**Comment by psarna** [comment]
IPv6 is, unfortunately, not supported **yet**.

As for reads and writes. When a chunkserver connects to master, it does so with certain IP address, let's say _192.168.100.106_. This address can indeed be specified with BIND_HOST configuration entry. When a client wants to perform a read operation, it asks master server where the data is and receives IP addresses of chunkservers. In this case, it gets _192.168.100.106_. If _192.168.100.106_ is accessible from the client,  everything works fine.

On the other hand, if communication between master and chunkserver is in some local network, here is what happens: chunkserver connects to master with some local address, let's say _10.0.0.1_. Then, a client asks master server via some globally accessible IP where the data is and receives _10.0.0.1_, a local, totally unreachable address. That's when reads/writes wouldn't work. There are various ways of making it work, of course, depending on how the installation/network/hardware/etc looks like. If anyone is interested in more detailed and tailored solution, I guess support@lizardfs.com is the way to go.

**Comment by liahsire** [comment]
Thanks. IPv6 support would be very cool for OnionCat, because it basically maps .onion hostnames to IPv6 addresses in fd87:d87e:eb43::/48, and so there would be no need for ip4ip6 tunnels and point-to-point routing, etc. That's the challenge now, in that cluster nodes can only reach each other via ad hoc point-to-point connections. Anyway, I will eventually write this up, and will post a link here.
