### ISSUE TITLE
please consider semantic versioning

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#462]
Please consider semantic versioning.

Specifically it would be great to reserve minor versions for "point releases" (i.e. bugfixes).

Even though so far there were no point releases (please do them!) normally minor (or patch) version change (like from 3.10.0 to 3.10.2) should not include new features or backwards incompatible changes. That's what major releases are for.

Read more:
- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning
- [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

**Comment by Zorlin** [comment]
+1. Semantic versioning leads to a predictable experience when upgrading between versions.

**Comment by psarna** [comment]
ok
