### ISSUE TITLE
3.10.4: FTBFS on [armel]: invalid use of incomplete type 

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#464]
~~~~
/«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache_unittest.cc:181:6: error: invalid use of incomplete type 'class std::future<void>'
     }));
      ^
In file included from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache_unittest.cc:22:0:
/usr/include/c++/6/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
In file included from /usr/include/c++/6/vector:64:0,
                 from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/debug_log.h:27,
                 from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/massert.h:27,
                 from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache.h:33,
                 from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache_unittest.cc:20:
/usr/include/c++/6/bits/stl_vector.h: In instantiation of 'std::_Vector_base<_Tp, _Alloc>::~_Vector_base() [with _Tp = std::future<void>; _Alloc = std::allocator<std::future<void> >]':
/usr/include/c++/6/bits/stl_vector.h:259:15:   required from 'std::vector<_Tp, _Alloc>::vector() [with _Tp = std::future<void>; _Alloc = std::allocator<std::future<void> >]'
/«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache_unittest.cc:172:33:   required from here
/usr/include/c++/6/bits/stl_vector.h:161:9: error: invalid use of incomplete type 'class std::future<void>'
       { _M_deallocate(this->_M_impl._M_start, this->_M_impl._M_end_of_storage
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         - this->_M_impl._M_start); }
         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache_unittest.cc:22:0:
/usr/include/c++/6/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
In file included from /usr/include/c++/6/memory:64:0,
                 from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/debug_log.h:25,
                 from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/massert.h:27,
                 from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache.h:33,
                 from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache_unittest.cc:20:
/usr/include/c++/6/bits/stl_construct.h: In instantiation of 'void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::future<void>*]':
/usr/include/c++/6/bits/stl_construct.h:151:15:   required from 'void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_T2>&) [with _ForwardIterator = std::future<void>*; _Tp = std::future<void>]'
/usr/include/c++/6/bits/stl_vector.h:426:22:   required from 'std::vector<_Tp, _Alloc>::~vector() [with _Tp = std::future<void>; _Alloc = std::allocator<std::future<void> >]'
/«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache_unittest.cc:172:33:   required from here
/usr/include/c++/6/bits/stl_construct.h:127:11: error: invalid use of incomplete type 'std::iterator_traits<std::future<void>*>::value_type {aka class std::future<void>}'
       std::_Destroy_aux<__has_trivial_destructor(_Value_type)>::
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  __destroy(__first, __last);
  ~~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /«BUILDDIR»/lizardfs-3.10.2+dfsg/src/common/lru_cache_unittest.cc:22:0:
/usr/include/c++/6/future:115:11: note: declaration of 'std::iterator_traits<std::future<void>*>::value_type {aka class std::future<void>}'
     class future;
           ^~~~~~
/usr/include/c++/6/future: At global scope:
/usr/include/c++/6/future:179:5: error: 'std::future<typename std::result_of<typename std::decay<_Tp>::type(typename std::decay<_BoundArgs>::type ...)>::type> std::async(std::launch, _Fn&&, _Args&& ...) [with _Fn = LruCacheTests_TestMultiThreadedCache_Test::TestBody()::<lambda()>; _Args = {}; typename std::result_of<typename std::decay<_Tp>::type(typename std::decay<_BoundArgs>::type ...)>::type = void]', declared using local type 'LruCacheTests_TestMultiThreadedCache_Test::TestBody()::<lambda()>', is used but never defined [-fpermissive]
     async(launch __policy, _Fn&& __fn, _Args&&... __args);
     ^~~~~
src/common/CMakeFiles/mfscommon_tests.dir/build.make:689: recipe for target 'src/common/CMakeFiles/mfscommon_tests.dir/lru_cache_unittest.cc.o' failed
make[3]: *** [src/common/CMakeFiles/mfscommon_tests.dir/lru_cache_unittest.cc.o] Error 1
make[3]: Leaving directory '/«BUILDDIR»/lizardfs-3.10.2+dfsg/build'
CMakeFiles/Makefile2:413: recipe for target 'src/common/CMakeFiles/mfscommon_tests.dir/all' failed
make[2]: *** [src/common/CMakeFiles/mfscommon_tests.dir/all] Error 2
~~~~

See full build log here: https://buildd.debian.org/status/fetch.php?pkg=lizardfs&arch=armel&ver=3.10.2%2Bdfsg-1&stamp=1473877555

**Comment by onlyjob** [comment]
Bugs like this may appear to be relatively unimportant but they have implications for Debian where migration to "testing" is blocked until package builds on all hardware architectures where it was successfully built previously. In turn, policy prohibits uploads of packages to backports until they reach "testing" suite...

**Comment by DarkHaze** [comment]
The reason is that future is broken on armel platform (
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64735). We'll create some
workaround for it.

**Comment by onlyjob** [comment]
3.10.4 still FTBFS or _armel_: https://buildd.debian.org/status/fetch.php?pkg=lizardfs&arch=armel&ver=3.10.4%2Bdfsg-1&stamp=1476940644

**Comment by DarkHaze** [comment]
The bug occurs during compilation of unit tests. Removing -DENABLE_TESTS=ON
from build scripts would resolve the problem.
This option shouldn't be enabled anyway, because it's only useful for
developers.

**Comment by DarkHaze** [comment]
Should be resolved by patch http://cr.skytechnology.pl:8081/#/c/2749/

**Comment by onlyjob** [comment]
Thanks, @DarkHaze, c2749 fixed the problem. Please feel free to close this bug once c2749 is merged.

I want to keep `-DENABLE_TESTS=ON` so developer(s) on _armel_ (or any other architecture) could build and test. Besides eventually it would be nice to build _lizardfs-tests_ package and use it for continuous integration testing. I could drop `-DENABLE_TESTS=ON` on _armel_ but that would increase complexity of packaging...
