### ISSUE TITLE
How do I completely reset a cluster?

### ISSUE THREAD

**Issue by liahsire** [lizardfs/lizardfs#465]
I have a master, metadata logger, chunkservers and a client. I have tested them in separate clusters. And now I want to use them together in a new cluster. They are connected and configured. But there is chaos. So in order to start fresh, I want to lose all data and metadata, and retain only configurations.

What is the best way to accomplish that?

I could purge and reinstall packages, but that seems extreme.

**Comment by Zorlin** [comment]
Start the master with a blank metadata file, then restart all other
servers. You may want to empty the mounts on your chunkservers, but if you
don't LizardFS will eventually garbage collect them.

That should be all there is to it...

**Comment by blink69** [comment]
True, the simplest way is creating new metadata file.
Go to your metadata directory on your current master server (look at the DATA_PATH in mfsmaster.cfg file), then stop master and create new empty metadata file by executing 
echo -n "MFSM NEW" > metadata.mfs
start master and your cluster will be clear, all remaining chunks will be deleted.

**Comment by liahsire** [comment]
Thank you both. So simple!
