### ISSUE TITLE
3.10.2: "settrashtime -r" fails on large directories

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#478]
`lizardfs settrashtime -r` fails on large directories with

    master query: receive error

**Comment by DarkHaze** [comment]
This should be fixed by commit 2713.

**Comment by onlyjob** [comment]
With 2713I tried _settrashtime -r_ on large directory and got 100% CPU use in master for 4+ hours... Restarting master did not give any relief and it just returned to normal performance some hours later so it is still a regression... (related to #475)...
