### ISSUE TITLE
Bug: LizardFS CGI error because /usr/bin/python is Python 3

### ISSUE THREAD

**Issue by Asher256** [lizardfs/lizardfs#479]
The CGI Server error:
```
-- Logs begin at Fri 2016-01-01 00:46:37 EST, end at Sat 2016-09-17 20:32:59 EDT. --
Sep 17 20:32:55 desktop systemd[1]: Started LizardFS CGI server daemon.
Sep 17 20:32:55 desktop lizardfs-cgiserver[15436]:   File "/usr/sbin/lizardfs-cgiserver", line 247
Sep 17 20:32:55 desktop lizardfs-cgiserver[15436]:     if (fstatdata.st_mode & 0170000) == 0040000:    # directory
Sep 17 20:32:55 desktop lizardfs-cgiserver[15436]:                                   ^
Sep 17 20:32:55 desktop lizardfs-cgiserver[15436]: SyntaxError: invalid token
```
LizardFS CGI crashed because the default version of Python in Arch Linux is Python 3.

Solution: since the lizardfs-cgiserver is a Python 2 script, I recommend you to force Python 2 with this shebang:
```
#!/usr/bin/env python2
```

**Comment by onlyjob** [comment]
Actually correct shebang would be `#!/usr/bin/python2` but the preferred solution is to update for compatibility with Python3 (or even migrate to python3 entirely).

**Comment by Asher256** [comment]
This shebang is more portable:
```
#!/usr/bin/env python2
```
 
Instead of trying to guess the path of the Python interpreter (a hardcoded /usr/bin/python2 for example) env will use $PATH to find python2.
