### ISSUE TITLE
How to migrate from MooseFS to LizardFS safely?

### ISSUE THREAD

**Issue by Asher256** [lizardfs/lizardfs#483]
We have 1 Petabytes of data managed by MooseFS 1.6.20 and we want to upgrade safely to the last version of LizardFS. 

What is the best way to upgrade safely, without any loss of data ?

**Comment by Zorlin** [comment]
First off, please always make backups. No matter how safe you think an
upgrade process is, and how safe it is in reality, you need to think about
the impact of losing that data. I hate to nag, but I imagine a data loss
scenario would hurt.

That aside, the UPGRADE file in LizardFS' repos will be of great help to
you. It details exactly what you need to do to migrate from old versions to
new versions, including from MooseFS 1.6.27.

https://github.com/lizardfs/lizardfs/blob/master/UPGRADE

You will need to upgrade to MooseFS 1.6.27 (but ideally 1.6.27-5) before
you proceed.

Once you have done that, upgrade to LizardFS 2.6.0, following exactly the
instructions in that document (upgrade master, upgrade chunkservers, then
upgrade clients).

Then upgrade to LizardFS 3.10.0, again following the instructions.

Finally, upgrade to 3.10.2 - you may be able to skip 3.10.0 and go straight
to 3.10.2 but don't quote me on that.

- Benjamin

**Comment by Asher256** [comment]
Thank you Benjamin! I'll follow your advice during the upgrade from MooseFS to LizardFS.

**Comment by Zorlin** [comment]
@Asher256 note that you need to check the instructions at every step of the upgrade, as it's not always the same instructions for each upgrade. Good luck and you're welcome :)

**Comment by Zorlin** [comment]
Hi @Asher256,

How did it go? Can this issue be closed now?

**Comment by Asher256** [comment]
Yes the upgrade worked very well. I'll close the issue. Thanks.
