### ISSUE TITLE
LizardFS master 3.10.2 crash

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#487]
[4581135.415771] mfsmaster[13210]: segfault at 0 ip 00000000004fa3b7 sp 00007ffc9fb8f1f0 error 4 in mfsmaster[400000+15d000]

Setup: 
- Debian Wheezy;
- lizardfs-master 3.10.2 from repo deb http://packages.lizardfs.com/debian/wheezy wheezy main

**Comment by blink69** [comment]
Please send us more details regarding that, 
- numbers of files,
- numbers of chunks,
- numbers of connected chunkservers, clients
also syslog from before this crash dump will also help.

**Comment by blink69** [comment]
patch for that is in our CR http://cr.skytechnology.pl:8081/#/c/2720/

**Comment by andypl78** [comment]
When can we expect a new version in the repo?

**Comment by blink69** [comment]
In next few days we will publish 3.10.4 with all fixes.

**Comment by devdesco-ceo** [comment]
Same thing here. 
lizardfs-master crashes one a day on average load.

**Comment by devdesco-ceo** [comment]
Same thing here. 
lizardfs-master crashes one a day on average load.

**Comment by DrProfi** [comment]
Confirm problem with 3.10.4

```
[3780056.793786] mfsmaster[19333]: segfault at 7fffc4c68ff8 ip 00000000004db2b5 sp 00007fffc4c69000 error 6 in mfsmaster[400000+13a000]

[3789174.107720] mfsmaster[7194]: segfault at 7ffe06e40ff8 ip 00000000004db2b2 sp 00007ffe06e41000 error 6 in mfsmaster[400000+13a000]

```

**Comment by blink69** [comment]
This issue is related to bug in libjudy, see issue #496

**Comment by psarna** [comment]
#496 is already closed with https://github.com/lizardfs/lizardfs/commit/e77895af3be6d09f4fb115147b06417dcc1f0f3d
