### ISSUE TITLE
Metadata.mfs.tmp on shutdown/shadow/mfsmetarestore

### ISSUE THREAD

**Issue by teddymoo** [lizardfs/lizardfs#496]
Metadata files metafada.mfs consumes about 3 Gb of disk space, but when I try to run shadow master it starts dumping new metadata file metadata.mfs.tmp which is getting bigger and bigger untill disk space is over (more than Tb). The same thing with restoring metadata with mfsmetarestore. Also, in case of stopping active master it starts dumping this enormous metadata.mfs.tmp.
As the result, I can nor restore my metadata from metalogger, neither keep shadow master running.

Is it possible to turn off or fix such a behavior?

**Comment by psarna** [comment]
Which version of LizardFS are you using?

**Comment by teddymoo** [comment]
3.10.10

**Comment by psarna** [comment]
Alright, first of all I would suggest updating to the newest release (3.10.4). A lot of small fixes were applied since 3.10.0 and one of them might just fix your issue. If the problem persists on 3.10.4, we can resume the investigation.

Our upgrade procedures (https://github.com/lizardfs/lizardfs/blob/master/UPGRADE) advise to upgrade shadow masters first anyway, so please try a 3.10.4 shadow and see if it works properly.

**Comment by psarna** [comment]
Also, which operating system are you on? If it's CentOS/RedHat then 3.10.4 should most likely fix your issues (we indeed had some issues with these OS's and metadata dumps on 3.10.0).

**Comment by teddymoo** [comment]
Thanks for your advice, I have just done it, but it was not helpful. 
With 3.10.4:

```
-rw-r-----  1 mfs  mfs   3466004611 Nov  3 13:10 metadata.mfs
-rw-r-----  1 mfs  mfs            8 Nov  3 13:03 metadata.mfs.1
-rw-r--r--  1 mfs  mfs            8 Oct 18 10:33 metadata.mfs.empty
-rw-r-----  1 mfs  mfs            0 Nov  3 13:12 metadata.mfs.lock
-rw-r-----  1 mfs  mfs  64437964503 Nov  3 13:18 metadata.mfs.tmp

```

I am on ubuntu 14.04.

**Comment by psarna** [comment]
We are not able to reproduce your issue, all our shadows are fully operational. 

Is it possible for you to give us the problematic metadata file (privately, of course)? That way we could both help you solve your issue and fix a bug that is most likely somewhere in there. If it's alright, just send somehow-uploaded metadata to support@lizardfs.com with a reference to this issue (#496).

**Comment by teddymoo** [comment]
Thanks for your fast replies!
The other way to reproduce it - try to restore metadata from metalogger. In my case, it creates normal metadata.mfs and then starts to write that metadata.mfs.tmp.
Ok, I will send you some fragment of metadata.mfs.tmp - it seems like there are mostly zero values, cause it grows very fast.  metadata.mfs itself seems to be ok - I can run standalone master above it. Also my cluster is pretty big - 3 Pb, used about 1,5 Pb.

**Comment by psarna** [comment]
The sample you provided is unfortunatelly too small. What could really help is the original metadata.mfs file or big enough part of metadata.mfs.tmp to include the trailing zeroes.

Alternatively (and this is a much faster solution), can you provide the outcome of this command on your metadata.mfs.tmp file?
~~~
mfsmetadump metadata.mfs.tmp |& grep -C3 header
~~~
It will at least lead us to which part of metadata (nodes, chunks, locks, etc.) is problematic.

**Comment by teddymoo** [comment]
Sorry, metadata.tmp is more than 100Gb, I was not sure how much is going to be enough.
"header: is common word in filenames, it seems like you are looking for something more specific . Could you please narrow down search expression? Maybe "section header" or "header:" is ok?
Also, I will send you original metadata file metadata.mfs.

**Comment by psarna** [comment]
~~~
mfsmetadump metadata.mfs.tmp |& grep -C3 'section header'
~~~
is fine.

**Comment by teddymoo** [comment]
Hello again, I sent full metadata file and grep result over more than 100Gb metadata dump file, do you have something about it? Thank you!

**Comment by MPaszkiewicz** [comment]
Hi,
We are still investigating the case, although we think that it might be a problem with Judy on Ubuntu 14.04

**Comment by teddymoo** [comment]
I checked out how it does on 12.04 and... It runs perfectly on 12.04 with libjudydebian1=1.0.5-1, but fails with trusty and libjudydebian1=1.0.5-1ubuntu1.

**Comment by DarkHaze** [comment]
I can confirm that the problem is caused by a bug in Judy library on Ubuntu 14.04. We are in a process of creating workaround. It should be available soon.

**Comment by DrProfi** [comment]
I confirm the problem with 3.10.4 and ubuntu 14.04
During save of metadata (on 3.9.4 it's ca.5.8GB) on 100GB disk, disk will be full, the master writes metadata endless.
Downgrade to 3.9.4 helps.
