### ISSUE TITLE
HDD_PUNCH_HOLES doesn't work on CentOS/RHEL 7

### ISSUE THREAD

**Issue by jdieter** [lizardfs/lizardfs#497]
I have six chunkservers, grouped into three groups of two, and I just recently reconfigured the goals so there's one copy of each chunk in each group.  I have HDD_PUNCH_HOLES=1 set in mfschunkserver.cfg for each chunkserver, but when I reset the goals and the chunks started migrating around, I noticed my free space was being dramatically reduced.

I ran `find ./ -iname "*.liz" -exec fallocate -v --dig-holes '{}' ';'` on one group and ended up freeing 4TB (out of 79TB).  This seems to indicate that the chunkserver is not actually creating the file as a sparse file.

FWIW, my filesystems are all XFS

**Comment by jdieter** [comment]
Sorry, forgot to say, we're running 3.10.4 on all our servers.

**Comment by jdieter** [comment]
I've just finished digging holes in all our chunkservers, and managed to free up a total of 9TB out of 79TB.

**Comment by psarna** [comment]
Holes in chunks are punched on every disk write performed by a chunkserver, so it is weird indeed...
What operating system are you on? Also, do you experience lack of hole punching only during migration/replication, or on writes as well?

Also, a trivial question, but I need to ask it anyway - did you restart chunkservers after changing HDD_PUNCH_HOLES to 1?

**Comment by jdieter** [comment]
Ok, I've done some more digging and figured out what the problem is.  I ran a test and it turns out that this is happening on writes as well as replication.

So I recompiled the code and found that `FALLOC_FL_PUNCH_HOLE` is missing from `fcntl.h`.  On my Fedora 24 desktop (glibc-2.23.1), it's there (well, technically in `/usr/include/bits/fcntl-linux.h` that gets included into `fcntl.h`), but on CentOS 7 (glibc-2.17), it's missing.

`FALLOC_FL_PUNCH_HOLE` _is_ available in `/usr/include/linux/falloc.h`, provided by the kernel-headers package.  My cmake foo isn't that great, but how hard would it be to use that alternate location if `fcntl.h` doesn't have `FALLOC_FL_PUNCH_HOLE`?

**Comment by psarna** [comment]
Are you sure this `FALLOC_FL_PUNCH_HOLE` definition isn't available in some userspace header? It's generally not a good idea to use kernel headers in userspace programs. CMake changes would look like that: http://cr.skytechnology.pl:8081/#/c/2783/1 , but I made this commit mostly for presentation purposes, as I would rather see some userspace header in there.

**Comment by jdieter** [comment]
I've done grep across /usr/include on a couple of CentOS systems I have, and it's only in the kernel headers.

FWIW, rocksdb fixed this using the kernel headers (See https://github.com/facebook/rocksdb/pull/584/commits/e8808b91285d92f3a34765aebe49832e8ead11cf), while sheepdog fixed this by just defining the constants (See https://github.com/sheepdog/sheepdog/commit/a62977592992d10cfd5a2a6fd6355fa8d8c32d87).

**Comment by psarna** [comment]
Well, out of these two poor choices, I prefer including a kernel header to defining magic constants on your own. Can you verify if http://cr.skytechnology.pl:8081/#/c/2783/1 works? I am a little to busy to launch a test right now. Anyway, this commit will be under review, and, if it works, it may get merged and fix your issue.

**Comment by jdieter** [comment]
Yeah, I'm with you on kernel headers vs magic constants.  I've tested the patch at the link and it fixes the problem.  Thanks so much!
