### ISSUE TITLE
Wishlist 5.x - Integrate SMART data monitoring

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#500]
It would be awesome if LizardFS could do SMART monitoring and inform you in the CGI when a brick is stored on a failing HDD/SSD. This could sometimes predict failures and help you avoid data loss before it happens.

**Comment by onlyjob** [comment]
To me one of the advantages of LizardFS is that I can safely ignore unreliable SMART data from HDDs.
If safety of data depends on SMART monitoring it means that there is insufficient redundancy (i.e. not enough replicas). What I love about LizardFS is that I can use backend HDDs far beyond their warranty period and take full advantage of HDDs with SMART errors and even some unreadable blocks as LizardFS compensates for minor errors. in my cluster I have some old HDDs that produce some noise to independent SMART monitoring yet continue to work -- normally I would not trust/use those HDDs but LizardFS allows me to use even unreliable HDDs<sup>1</sup> to the full extent of their usability. This is very cost effective.

My opinion is that SMART monitoring as a low level hardware feature do not belong to high level software defined storage. IMHO SMART monitoring is not very useful in such context.

<sup>1</sup>: I believe all HDDs are unreliable. ;)

**Comment by 4Dolio** [comment]
I agree to not consider smart in lizard operations.  Yet... i watch my disks smart results, if i expect one to fail i have a hot copy of it to a spare disk so i can update (rsync) the spare quickly and swap it into service. Used this method for 2 disks so far and yet those smart failed disks may still be of use within a less critical Lizard cluster? Or not.  I am holding on to them to use them to devise better automated smart notifications and automation outside of lizards direct control.

**Comment by cloudweavers** [comment]
I would also advise against using SMART. We have done hundreds of tests with lots of different disks, and found out that most of the results reported by SMART are unreliable at most. Hard errors (read or write I/O) are actionable and useful, SMART certainly not.

**Comment by Zorlin** [comment]
Thanks @cloudweavers, @4Dolio, @onlyjob - very interesting discussions. I'm formally withdrawing this suggestion as I agree with all of you that it would do more harm than good. Thanks for turning me around on it :)
