### ISSUE TITLE
No upgrade instructions for 3.10.4

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#501]
Hi there,

I have a LizardFS 3.9.4 cluster I want to upgrade all the way to 3.10.4 but the instructions in UPGRADE do not go past 3.10.0-rc. This is a showstopper and means we can't upgrade until it's fixed.

Please add instructions for the latest releases.

**Comment by psarna** [comment]
Oh, the "fix" is very straightforward - UPGRADE instructions for 3.10.4 are identical to 3.10.0. UPGRADE notes will be updated, thanks for noticing.

**Comment by Zorlin** [comment]
@psarna Thanks for your quick response! 👍
