### ISSUE TITLE
3.10.x package for ubuntu 16

### ISSUE THREAD

**Issue by htbase** [lizardfs/lizardfs#507]
Hi there

Do we already have the 3.10.x package for Ubuntu 16? I tried installing it but only one I see is 3.9

Thanks

**Comment by blink69** [comment]
In Xenial official repo from packages.ubuntu.com there is 3.9.4 but in our repo you will find 3.10.4
http://packages.lizardfs.com/ubuntu/xenial/pool/main/l/lizardfs/
