### ISSUE TITLE
debian - which packaging to use?

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#511]
I always tend use packages direct from the vendor/developer if available, assuming they are the most up-to-date. However I saw a few discussions recommending the debian backports packages, actively maintained by onlyjob and better integrated with debian? Is there an offical position on this?

If that is the case, I gather they use a different prefix - "/etc/lizardfs", "/var/lib/lizardfs" instead of /etc/mfs. Can I just:
* shut down lizard
* purge the lizardfs.com packages
* install the debian backports packages
* move all the config files & meta files to the enw lizardfs locations
* start everything backup?

Also - how much do the debian packages lag official releases? given onlyjob is mildly active here :) I presume he's on it fairly quickly (thanks mate! appreciated)

**Comment by Zorlin** [comment]
(Note, I am not affiliated with LFS)

The Debian packages are updated very quickly after each stable release.
These can however be delayed by FTBFS (failed-to-build-from-source) errors,
as Debian packages must be able to build and run on ARM and sometimes that
gets broken.

Basically the Debian packages are the way to go - the delays are for good
reason, and onlyjob includes (well-tested) patches and hotfixes that are
not necessarily in the plain vendor packages.

**Comment by Blackpaw** [comment]
Thanks Zorlin. I ended up moving to the debian packages, tedious but done. Process was much as detailed above, except the default user changed from mfs to lizardfs.

I have a Ubuntu 14.04.1 server, no ppa for it as far as I know. Probably best to stick to the lizardfs.com packages for Ubuntu?

**Comment by Zorlin** [comment]
For Ubuntu 14.04, yes you will have to use vendor packages. As I understand
it Ubuntu 16.04 and later pull from Debian and thus the packages that
@onlyjob build end up in their repos after a short delay.

**Comment by Blackpaw** [comment]
I just checked 16.04 - still only at 3.9.4

**Comment by Zorlin** [comment]
@blackpaw Yep, they're a little slow sometimes :(
