### ISSUE TITLE
Compilation error version 3.9.4

### ISSUE THREAD

**Issue by marcin-github** [lizardfs/lizardfs#518]
Hi!
I'm getting cmake configure error on Gentoo:

> -- Could NOT find system libcrcutil (but it's not required)
-- Using bundled crcutil-1.0
-- JUDY_LIBRARY: JUDY_LIBRARY-NOTFOUND
-- Found PAM: /usr/lib64/libpam.so  
CMake Error at CheckIncludes.cmake:4 (check_include_files):
  Unknown CMake command "check_include_files".
Call Stack (most recent call first):
  CMakeLists.txt:113 (check_includes)

>-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeOutput.log".
See also "/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeError.log".

\# cat /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeError.log
Performing C SOURCE FILE Test LIZARDFS_HAVE_STRUCT_STAT_ST_BIRTHTIME failed with the following output:
Change Dir: /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_33490/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_33490.dir/build.make CMakeFiles/cmTC_33490.dir/build
gmake[1]: Entering directory '/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_33490.dir/src.c.o
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc     -DNDEBUG -O2 -march=native -pipe -fpeel-loops              -fuse-linker-plugin -fuse-ld=bfd -fvar-tracking-assignments -g -gdwarf-4 -DLIZARDFS_HAVE_STRUCT_STAT_ST_BIRTHTIME   -o CMakeFiles/cmTC_33490.dir/src.c.o -c /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/src.c
/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/src.c: In function ‘main’:
/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/src.c:6:35: error: ‘struct stat’ has no member named ‘st_birthtime’
    (void)sizeof(((struct stat *)0)->st_birthtime);
                                   ^
gmake[1]: *** [CMakeFiles/cmTC_33490.dir/build.make:66: CMakeFiles/cmTC_33490.dir/src.c.o] Error 1
gmake[1]: Leaving directory '/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:126: cmTC_33490/fast] Error 2

Source file was:

#include <sys/stat.h>

int main()
{
   (void)sizeof(((struct stat *)0)->st_birthtime);
   return 0;
}

Performing C SOURCE FILE Test LIZARDFS_HAVE_STRUCT_STAT_ST_FLAGS failed with the following output:
Change Dir: /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_ff127/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_ff127.dir/build.make CMakeFiles/cmTC_ff127.dir/build
gmake[1]: Entering directory '/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ff127.dir/src.c.o
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc     -DNDEBUG -O2 -march=native -pipe -fpeel-loops              -fuse-linker-plugin -fuse-ld=bfd -fvar-tracking-assignments -g -gdwarf-4 -DLIZARDFS_HAVE_STRUCT_STAT_ST_FLAGS   -o CMakeFiles/cmTC_ff127.dir/src.c.o -c /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/src.c
/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/src.c: In function ‘main’:
/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/src.c:6:35: error: ‘struct stat’ has no member named ‘st_flags’
    (void)sizeof(((struct stat *)0)->st_flags);
                                   ^
gmake[1]: *** [CMakeFiles/cmTC_ff127.dir/build.make:66: CMakeFiles/cmTC_ff127.dir/src.c.o] Error 1
gmake[1]: Leaving directory '/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:126: cmTC_ff127/fast] Error 2

Source file was:

#include <sys/stat.h>

int main()
{
   (void)sizeof(((struct stat *)0)->st_flags);
   return 0;
}

Determining if the pthread_create exist failed with the following output:
Change Dir: /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_9ee75/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_9ee75.dir/build.make CMakeFiles/cmTC_9ee75.dir/build
gmake[1]: Entering directory '/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9ee75.dir/CheckSymbolExists.c.o
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc   -I/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/sys/mman.h   -DNDEBUG -O2 -march=native -pipe -fpeel-loops              -fuse-linker-plugin -fuse-ld=bfd -fvar-tracking-assignments -g -gdwarf-4    -o CMakeFiles/cmTC_9ee75.dir/CheckSymbolExists.c.o -c /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_9ee75
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9ee75.dir/link.txt --verbose=1
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc  -O2 -march=native -pipe -fpeel-loops              -fuse-linker-plugin -fuse-ld=bfd -fvar-tracking-assignments -g -gdwarf-4   -Wl,-O1 -Wl,--as-needed -z relro -Wl,--sort-common -O2 -march=native -pipe -fpeel-loops              -fuse-linker-plugin -fuse-ld=bfd -fvar-tracking-assignments -g -gdwarf-4  CMakeFiles/cmTC_9ee75.dir/CheckSymbolExists.c.o  -o cmTC_9ee75 -rdynamic 
CMakeFiles/cmTC_9ee75.dir/CheckSymbolExists.c.o: In function `main':
/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_9ee75.dir/build.make:98: cmTC_9ee75] Error 1
gmake[1]: Leaving directory '/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:126: cmTC_9ee75/fast] Error 2

File /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_8758d/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_8758d.dir/build.make CMakeFiles/cmTC_8758d.dir/build
gmake[1]: Entering directory '/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8758d.dir/CheckFunctionExists.c.o
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc     -DNDEBUG -O2 -march=native -pipe -fpeel-loops              -fuse-linker-plugin -fuse-ld=bfd -fvar-tracking-assignments -g -gdwarf-4 -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_8758d.dir/CheckFunctionExists.c.o -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_8758d
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8758d.dir/link.txt --verbose=1
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc  -O2 -march=native -pipe -fpeel-loops              -fuse-linker-plugin -fuse-ld=bfd -fvar-tracking-assignments -g -gdwarf-4 -DCHECK_FUNCTION_EXISTS=pthread_create  -Wl,-O1 -Wl,--as-needed -z relro -Wl,--sort-common -O2 -march=native -pipe -fpeel-loops              -fuse-linker-plugin -fuse-ld=bfd -fvar-tracking-assignments -g -gdwarf-4  CMakeFiles/cmTC_8758d.dir/CheckFunctionExists.c.o  -o cmTC_8758d -rdynamic -lpthreads 
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_8758d.dir/build.make:98: cmTC_8758d] Error 1
gmake[1]: Leaving directory '/var/tmp/portage/sys-cluster/lizardfs-3.9.4/work/lizardfs-3.9.4_build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:126: cmTC_8758d/fast] Error 2

3.10.6 compiles fine on the same host.

**Comment by psarna** [comment]
This issue was reported here https://github.com/lizardfs/lizardfs/issues/363 and fixed here https://github.com/lizardfs/lizardfs/commit/60f64d7077ebd2b29b18faa3b25ee593e126e347 . The patch wasn't backported because 3.10.X is recommended anyway. It is a one-liner, so you can apply it manually without problems if needed.

**Comment by marcin-github** [comment]
Thank you Piotr, I didn't found #363. At this moment I'm going to use 3.9.4 because Ubuntu uses this version of lizardfs. If lizard will be working without problem for m then I'll try to install newer version of packages.

**Comment by psarna** [comment]
Debian uses 3.10.X though, maybe you will consider that a 
counter-argument ;) If you browse NEWS sections of releases after 3.9.4, 
they contain a lot of fixes, so it is _really_ advised to switch to 3.10.X.

On 01/25/2017 10:05 AM, Marcin wrote:
>
> Thank you Piotr, I didn't found #363 
> <https://github.com/lizardfs/lizardfs/issues/363>. At this moment I'm 
> going to use 3.9.4 because Ubuntu uses this version of lizardfs. If 
> lizard will be working without problem for m then I'll try to install 
> newer version of packages.
>
Lizard would probably work fine, but there actually _were_ problems 
discovered in 3.9.4 and they were fixed in 3.10.X :)

**Comment by marcin-github** [comment]
Ech:)
I didn't hit any "various fixes and community requests" nor "Many fixes" mentioned in NEWS but I've upgraded Lizardfs to 3.10.6. Still works;)
