### ISSUE TITLE
mfsmetarestore in the failover script?

### ISSUE THREAD

**Issue by Asher256** [lizardfs/lizardfs#520]
Hi,

Is it safe to execute this command automatically by a script:
```
mfsmetarestore -a -d /opt/data/lizardfs-master/
```

Before each "systemctl start lizardfs-master" (for masters and shadows).

--
Asher256

PS: I put mfsmetarestore is a keepalived failover script FYI, because it was looping from the server1 to server2 (and vice versa). Both of them (master + shadow) weren't able to start because I had to execute mfsmetarestore manually.

**Comment by Blackpaw** [comment]
I have:
`## When this option is set (equals 1) master will try to recover metadata`
`## from changelog when it is being started after a crash; otherwise it will`
`## refuse to start and 'mfsmetarestore' should be used to recover the metadata.`
`## (Default: 0)`
`AUTO_RECOVERY = 1`

set in mfsmaster.cfg, does the same thing and seems more reliable. I haven't had any issues with it on normal restarts.

**Comment by Asher256** [comment]
Excellent suggestion. Thank you Blackpaw!

**Comment by Blackpaw** [comment]
Cheers, interested to see your results, scripts and environment. I've been testing keepalived/lizardfs in a proxmox cluster and got it down to a reliable failover, handled power outages and rolling reboots quite well. Did'nt look into handling mfsmaster crashes though.

But I noticed some network quirks - occasional connectivity dropouts on the master node, they seemed to go away if I disabled keepalived (vs 1.2.13-1). I had the floating IP sitting on a linux bond (balance-alb).

ucarp can be used as an alternative but I found keepalived much easier to manage and less obtrusive, plus I needed two floating ip's (public & private).

**Comment by Asher256** [comment]
I'm also interested to know more about your reliable keepalived config ;) . Can you share it with us?

This my keepalived configuration: https://github.com/Asher256/puppet-lizardfs/blob/master/templates/etc/keepalived/keepalived.conf.erb (it is the template of the puppet module).

A final result would look like this:
```
##############################################################################
# MANAGED BY PUPPET
# Author: Asher256 <asher256@gmail.com>
# 
# This file is part of the module puppet-lizardfs
# https://github.com/Asher256/puppet-lizardfs
##############################################################################

global_defs {
	# Each keepalived should have a different ID because this will be used 
	# in SMTP alerts
	lvs_id MFS_inf-p-vcg001

		# notification
		notification_email_from email@domain.com
		notification_email {
			email@domain.com
		}

		smtp_server relay.domain.com
		smtp_connect_timeout 30
	}

vrrp_script chk_mfsmaster {
	script "mfsmaster isalive"
	interval 10   # x seconds
	fall 5           # require x failures for KO
	raise 2         # require x success for OK
}

vrrp_instance VI_1 {
	interface  eth0
	nopreempt
	priority 100
	virtual_router_id 246

	authentication {
		auth_type PASS
		auth_pass ThisIsThePassword
	}
	
	track_script {
		chk_mfsmaster
	}
	
	virtual_ipaddress {
		10.137.5.90/21 dev eth0 label eth0:mfsmaster
		
	}

	# Switch to MASTER
	notify_master "/etc/lizardfs/lfs_failover.sh to_master"
	
	# Switch to SHADOW
	notify_backup "/etc/lizardfs/lfs_failover.sh to_shadow"
	notify_fault  "/etc/lizardfs/lfs_failover.sh to_shadow"
}
```

The failover script: https://github.com/Asher256/puppet-lizardfs/blob/master/templates/etc/lizardfs/lfs_failover.sh

Feel free to send me your pull requests Blackpaw, if you have ideas to improve the configuration above.

--
Asher256
