### ISSUE TITLE
Is file locking + no_root_squash supported?

### ISSUE THREAD

**Issue by Asher256** [lizardfs/lizardfs#522]
We want to use LizardFS as the DFS of a highly-available Gitlab installation.

The Gitlab requirements are:
```
1. File locking: GitLab requires advisory file locking, which is only supported natively in NFS version 4. NFSv3 also supports locking as long as Linux Kernel 2.6.5+ is used. We recommend using version 4 and do not specifically test NFSv3.

2. no_root_squash: NFS normally changes the root user to nobody. This is a good security measure when NFS shares will be accessed by many different users. However, in this case only GitLab will use the NFS share so it is safe. GitLab requires the no_root_squash setting because we need to manage file permissions automatically. Without the setting you will receive errors when the Omnibus package tries to alter permissions. Note that GitLab and other bundled components do not run as root but as non-privileged users. The requirement for no_root_squash is to allow the Omnibus package to set ownership and permissions on files, as needed.
```

The the NFS mount options required:
```
lookupcache=positive	Tells the NFS client to honor positive cache results but invalidates any negative cache results. Negative cache results cause problems with Git. Specifically, a git push can fail to register uniformly across all NFS clients. The negative cache causes the clients to 'remember' that the files did not exist previously.
```

Questions:
1. Is enablefilelocks enough to activate file locking in LizardFS? Is it as as reliable as NFS 4 file locking? 

2. What is the equivalent to no_root_squash in LizardFS?

3. What is the equivalent of lookupcache=positive in LizardFS? Is mfscachemode=AUTO the same? Should I disable mfscachemode to be safe (I'm going to store Git repositories + Docker registries)?

Thank you!

Asher256

**Comment by psarna** [comment]
1. Yes, enablefilelocks on mount side is enough. There were indeed problems with file locks reported in #322, but they were fixed and no more issues with file locks appeared to this day. They definitely pass samba's ping pong test (which is not very complicated, though) and several tests of ours. The best thing to do is test them yourself and present results - we will be very grateful for both positive and negative feedbacks :) There's also a `lizardfs-admin manage-locks` command with some examples in this commit message: https://github.com/lizardfs/lizardfs/commit/86e0d16d22cf174364cf0559786cc9f164326f10

2. The closest functionality is maproot in `mfsexports.cfg`. maproot=0 will do the job.

3. Always use default mfscachemode value (i.e. don't set it up at all), it won't affect any git repositories etc.

**Comment by Asher256** [comment]
Thanks. I'll test it and send you my feedbacks (positive or negative ;-) ).

**Comment by Zorlin** [comment]
@Asher256 How'd it go?
