### ISSUE TITLE
new, clean install - disk space is 100% used?

### ISSUE THREAD

**Issue by bofhdk** [lizardfs/lizardfs#528]
I'm in the process of giving lizardfs a spin and am rather stumped.

This is a clean install on VMware VMs with ubuntu 16.04 and lizardfs 3.10.6.
1 master, 1 metalogger and 4 chunkservers. The chunkservers each have 2 2GB disks attached that were completely un-used (mkfs.ext4) before starting mfschunkserver.

Yet lizardfs seems to think that all space is used?

All 4 chunkservers report:
root@lzchunk01:~# df -h /var/lfs/*
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1       2.0G  4.1M  2.0G   1% /var/lfs/disk1
/dev/sdc1       2.0G  4.1M  2.0G   1% /var/lfs/disk2

fs i mounted on the master server:
root@lzmaster01:~# mount|grep mfs
mfs#mfsmaster:9421 on /data1/lfs type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
mfsmeta#mfsmaster:9421 on /data1/lfsmeta type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)

root@lzmaster01:~# mfsdirinfo /data1/lfs
/data1/lfs:
 inodes:                          3
  directories:                    2
  files:                          1
 chunks:                          0
 length:                          0
 size:                            0
 realsize:                        0

root@lzmaster01:~# cp /etc/hosts /data1/lfs/testfile
cp: failed to close '/data1/lfs/testfile': No space left on device
root@lzmaster01:~# ls -l /etc/hosts
-rw-r--r-- 1 root root 217 Mar  3 12:38 /etc/hosts
root@lzmaster01:~# tail -2 /var/log/syslog
Mar  3 13:29:41 lzmaster01 mfsmount[1072]: write file error, inode: 5, index: 0 - error sent by master server (No space left) (try counter: 1)
Mar  3 13:29:41 lzmaster01 mfsmount[1072]: error writing file number 5: ENOSPC (No space left on device)

mfs.cgi reports:

Disks
#	info	I/O stats last min (switch to hour,day)	space
transfer	max time (switch to avg)	# of ops
name path (switch to IP)	chunks	last error	status	read	write	read	write	fsync	read	write	fsync	used	total	used (%)
1	(unresolved):9422:/var/lfs/disk1/mfs/	0	no errors	ok	-	-	-	-	-	-	-	-	1.9 GiB	1.9 GiB	
100.00
2	(unresolved):9422:/var/lfs/disk1/mfs/	0	no errors	ok	-	-	-	-	-	-	-	-	1.9 GiB	1.9 GiB	
100.00
3	(unresolved):9422:/var/lfs/disk1/mfs/	0	no errors	ok	-	-	-	-	-	-	-	-	1.9 GiB	1.9 GiB	
100.00
4	(unresolved):9422:/var/lfs/disk1/mfs/	0	no errors	ok	-	-	-	-	-	-	-	-	1.9 GiB	1.9 GiB	
100.00
5	(unresolved):9422:/var/lfs/disk2/mfs/	0	no errors	ok	-	-	-	-	-	-	-	-	1.9 GiB	1.9 GiB	
100.00
6	(unresolved):9422:/var/lfs/disk2/mfs/	0	no errors	ok	-	-	-	-	-	-	-	-	1.9 GiB	1.9 GiB	
100.00
7	(unresolved):9422:/var/lfs/disk2/mfs/	0	no errors	ok	-	-	-	-	-	-	-	-	1.9 GiB	1.9 GiB	
100.00
8	(unresolved):9422:/var/lfs/disk2/mfs/	0	no errors	ok	-	-	-	-	-	-	-	-	1.9 GiB	1.9 GiB	
100.00

I'm completely stumped - any ideas?

**Comment by psarna** [comment]
from mfschunkserver.cfg config file:
~~~
HDD_LEAVE_SPACE_DEFAULT
free space threshold to set volume as 100% utilized when there is less than given amount
of free space left (default is "4GiB"). This number is always added to the used disk space
reported by chunkserver.
~~~

**Comment by Zorlin** [comment]
*HDD_LEAVE_SPACE_DEFAULT*::
free space threshold to set volume as 100% utilized when there is less than
given amount of free
space left (default is "4GiB"). This number is always added to the used
disk space reported by
chunkserver.


This is a safety feature to help reduce issues of running out of disk
space. Set this to something like 100MB in mfschunkserver.cfg

That should solve your issue

- Benjamin

**Comment by bofhdk** [comment]
Argh! I'm sure my facepalm has registered on seismographs worldwide.

I never thought to check that as it's commented out (and set to 256MiB) in the file.

Sure enough - removing the # in front and restarting the chunkservers fixed this :)

Thanks a lot - impressive response  time too! :)
