### ISSUE TITLE
Check if master is alive

### ISSUE THREAD

**Issue by guestisp** [lizardfs/lizardfs#537]
In a clustered environment, could be useful to check if master is working properly

Looking for it's PID is not a reliable check, master could be running but totally blocked and in this case it's PID is still available

Any solution to make some "ping/pong" to master or any dummy command to run through the master port?

**Comment by psarna** [comment]
`lizardfs-admin metadataserver-status HOST PORT`

**Comment by guestisp** [comment]
Great. The output is as follow:
```
$ lizardfs-admin metadataserver-status localhost 9421
     personality: master
   server status: running
metadata version: 63
```

using this when checking for master liveness is much more reliable than looking at process PID or pinging the server.
