### ISSUE TITLE
Endangered Chunks not being replicated

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#544]
I have a test 3 node cluster
- Replica 3 hosting 8 VM Images (358 GB). 
- 12735 Chunks
- LizardFS 3.10.6
- lizardfs.com debian repo
- ENDANGERED_CHUNKS_PRIORITY = 0.5

I tested doing a rolling server reboot (typical for kernel upgrades). Deliberately rebooted before heals were fully complete. Ended up with 87 chunks endangered, they healed fairly rapidly until the last 3 or so. Now I'm down to *1* endangered chunk, no others need replication and its just sitting there with no change for two hours now.

Have seen this happen many times - a small number of endangered chunks that take hours to get replicated.

**Comment by Blackpaw** [comment]
Seeing lots of this in the syslog of the master server

```
May  3 20:36:06 pvetest mfsmaster[2583]: (10.10.10.240:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error
May  3 20:41:10 pvetest mfsmaster[2583]: (10.10.10.241:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error
May  3 20:46:14 pvetest mfsmaster[2583]: (10.10.10.241:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error
May  3 20:51:18 pvetest mfsmaster[2583]: (10.10.10.241:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error
May  3 20:51:39 pvetest systemd-timesyncd[1912]: interval/delta/delay/jitter/drift 2048s/+0.001s/0.186s/0.037s/-4ppm
May  3 20:53:36 pvetest mfsmaster[2583]: DEL_LIMIT temporary increased to: 15 per server
May  3 20:56:22 pvetest mfsmaster[2583]: (10.10.10.240:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error
May  3 21:01:27 pvetest mfsmaster[2583]: (10.10.10.240:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error
May  3 21:06:33 pvetest mfsmaster[2583]: (10.10.10.240:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error
May  3 21:11:37 pvetest mfsmaster[2583]: (10.10.10.240:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error
May  3 21:16:43 pvetest mfsmaster[2583]: (10.10.10.241:9422) chunk: 000000000000FDE8 replication status: Unknown LizardFS error

```

**Comment by Blackpaw** [comment]
Looks like the last chunk finally replicated 3 hours later

**Comment by psarna** [comment]
You can also use the following master config options to speed up/slow down the main chunk loop execution (during which chunks are checked if they need replication/deletion/rebalance/etc):

~~~
       CHUNKS_LOOP_PERIOD
           Time in milliseconds between chunks loop execution (default is 1000).

       CHUNKS_LOOP_MAX_CPU
           Hard limit on CPU usage by chunks loop (percentage value, default is 60).
~~~

**Comment by Blackpaw** [comment]
Thanks Piotr, but would that explain why the remaining one chunk stayed endangered for three hours? the system was not under load.
