### ISSUE TITLE
Client O_SYNC/O_DIRECT & mfswritecachesize/PERFORM_FSYNC Behaviour

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#545]
I was wondering what is the behaviour of files opened on the fuse mount with O_SYNC or O_DIRECT, or flushed with fsync(fd)?

**Scenario 1 : mfswritecachesize**
* Mounted with mfswritecachesize=2048
* Open file, write a few K to it
* Call fysnc() on the file descriptor

Is the data flushed from the local write cache and sent to all relevant chunk servers immediately? or does it sit in the cache until a timeout period?

**Scenario 2 : Chunkserver PERFORM_FSYNC = 0**
* Open file, write a few K to it
* Call fysnc() on the file descriptor

I imagine the data is sent to the chunkserver immediately, but does the chunkserver then call fsync() on the chunk after writing the data? or is it just written and left unflushed?

Thanks.

**Comment by psarna** [comment]
1. Calling `fsync` on the file descriptor will go through FUSE which will run our `fsync` callback implementation, which sends blocks to all relevant chunk servers immediately.

2. If `PERFORM_FSYNC=1` is present in chunkserver's config, the chunkserver will call fsync after each write operation (which might be a single 64KiB block).
If `PERFORM_FSYNC=0`, the chunkserver will let kernel decide when to perform writebacks.

**Comment by Blackpaw** [comment]
Thanks Piotr, 1) is good to know as bumping the writeback cache to 1G or 2G makes impressive gains for write and IOPS performance.

Overall that makes sense - fsync flushs client writes to the underlying store,  PERFORM_FSYNC is chunkserver only.


Trying to assess how unsafe having PERFORM_FSYNC=0 is. If a chunkserver loses power while it has writes unflushed to disk will it know that? or would it be not discovered till it gets a checksum failure?

**Comment by psarna** [comment]
It will be the same case as disk failure, it will be discovered during periodic chunk scrubbing or on first access (checksum mismatch).

**Comment by psarna** [comment]
It will be the same case as disk failure, it will be discovered during periodic chunk scrubbing or on first access (checksum mismatch).

**Comment by Blackpaw** [comment]
Thanks for the clarifications Piotr.
