### ISSUE TITLE
High CPU usage lizardfs-master 3.11.0

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#547]
System: Debian Wheezy, Debian Jessie
Version 3.11.0 from LizardFS Repo

> deb http://packages.lizardfs.com/debian/wheezy wheezy main

Constant use of 100% CPU

Tested after upgrade to version 3.11.0 as well as pure installation with default configuration without data

![lfs-master](https://cloud.githubusercontent.com/assets/7813646/25923966/88fa3098-35e0-11e7-8500-83e0ef316fbc.jpg)

![lfs-master-cgi](https://cloud.githubusercontent.com/assets/7813646/25923981/a8763dae-35e0-11e7-9067-1cb9089d22fb.jpg)

**Comment by Zorlin** [comment]
Try the official Debian LizardFS packages instead, they have newer fixes.

**Comment by Blackpaw** [comment]
Debian backports are still only at 3.10.4

**Comment by Blackpaw** [comment]
Is this still a problem for you Andy? I reviewed my logs and saw 100% CPU usage after my upgrade but it appeared to be related to chunk replication - it only lasted about half an hour and reduced to near nil once all chunks were healed.

**Comment by andypl78** [comment]
I do not use Debian backports for LizardFS only official Repo

> deb http://packages.lizardfs.com/debian/wheezy wheezy main

So the problem with using 100% CPU is all the time for several hours

![lfs-master-cgi2](https://cloud.githubusercontent.com/assets/7813646/25937289/671ee356-362b-11e7-95c2-44c4d246c80c.jpg)

100% CPU is even like I would do a clean installation on a clean Debian Jessie without meta data.

**Comment by andypl78** [comment]
I do not want to do downgrade now from 3.11.0 to 3.10.6 because I can lose the data and I do not know what changes were made in the new version

**Comment by andypl78** [comment]
After the upgrade I see that the new version sends and receives more packages
Well, you can see the charts after 22 o'clock

![lfs-master-cgi3](https://cloud.githubusercontent.com/assets/7813646/25937733/17910966-362d-11e7-8fb8-b65fdb8d4912.jpg)

![lfs-master-cgi4](https://cloud.githubusercontent.com/assets/7813646/25937742/1c0c6c24-362d-11e7-9c53-ea0bcdb4c71d.jpg)

**Comment by psarna** [comment]
OK, I found it. Your `OPERATIONS_DELAY_INIT` setting in master config is rather high, right? Due to the redesign of file test loop and a slight mistake in one of the conditions, master will have increased CPU usage for the whole `OPERATIONS_DELAY_INIT` period. Good news 1: the fix will be here in minutes; Good news 2: it is not affecting master's responsiveness (actually it temporarily boosts it at the cost of higher CPU usage).

**Comment by andypl78** [comment]
1) 
> OPERATIONS_DELAY_INIT = 300
So as I can see I have default settings
2) "temporarily boosts" It is still a few hours. Is it still time to use such a large CPU?

**Comment by Blackpaw** [comment]
Yes, my OPERATIONS_DELAY_INIT is 30 but the CPU is 100% and has been for nearly an hour. 

It started when I restarted a chunkserver causing 18 chunks to be under goal. It has taken them nearly an hour to reach goal (replica 3), which seems very slow.

The CPU is still 100% even after all has reached goals. I basically only have 8 large files on the system (VM Images)

**Comment by psarna** [comment]
Well yes, correct, it affects both OPERATIONS_DELAY_INIT and OPERATIONS_DELAY_DISCONNECT, they use exactly the same mechanism. This patch, when merged, will help: http://cr.skytechnology.pl:8081/#/c/2927/

**Comment by andypl78** [comment]
Is it possible to add this patch to the official lizardfs-master package in your repo because now anyone who downloads from you will have the same problem?

**Comment by Blackpaw** [comment]
> it affects both OPERATIONS_DELAY_INIT and OPERATIONS_DELAY_DISCONNECT

Ah, and OPERATIONS_DELAY_DISCONNECT defaults to an hour.

Thanks Piotr.

**Comment by psarna** [comment]
Well, it will go through release procedure again, but it will soon be added in our repo as 3.11.1.

**Comment by andypl78** [comment]
Ok, waiting... ;)

**Comment by Blackpaw** [comment]
Rebuilt 3.11 with the patch, can confirm it seems to have solved the problem. After restart a couple of chunkservers resulting in 35 chunks under goal cpu stayed at around 2-5%

**Comment by gutleib** [comment]
Seriously, why is it closed? It's not like one would'n bump into it if using your manual.
And how soon can we have a 3.11.1?
