### ISSUE TITLE
3.10.4: master segfaults on disconnect of nameless chunkserver

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#548]
Master crashes (segfault) when nameless chunkserver is stopped. To reproduce one needs to make sure that chunkserver have unresolvable name (no DNS entry)...

**Comment by psarna** [comment]
We didn't manage to reproduce it. Any more installation details? Starting/stopping chunkservers on 3.10.4 with DNS disabled worked fine.

**Comment by onlyjob** [comment]
Sorry, no more details, that's all I have... We had several crashes that were easily tracked to restart of nameless chunkserver... Incidents occurred on packages from Debian Stretch. Introducing DNS entry resolved the problem.

**Comment by onlyjob** [comment]
May be root cause _is_ different... We had several(!) more segfault incidents on 3.11.0 apparently triggered by reloading of "Info" page in browser...

**Comment by DarkHaze** [comment]
Could you check if commit 2943 <http://cr.skytechnology.pl:8081/#/c/2943/>
fixes the problem ?

**Comment by onlyjob** [comment]
Applied this patch on 3.11.0 and first attempt to reproduce the crash was unsuccessful -- well done. :)
Thanks.
