### ISSUE TITLE
mfsmount segfault bug

### ISSUE THREAD

**Issue by andypl78** [lizardfs/lizardfs#551]
System Debian Jessie 8
lizardfs-client 3.11.0

/etc/fstab

> mfsmount                                        /var/vmail              fuse            mfsmaster=XX.XX.XX.XX,mfssubfolder=/data/mail-farm01,_netdev,big_writes        0       0

dmesg

> [308724.044799] mfsmount[568]: segfault at 10 ip 000000000045f7c4 sp 00007fe369727c10 error 4 in mfsmount[400000+ca000]

**Comment by onlyjob** [comment]
What `big_writes` is for? It is neither in _fuse(8)_ man page nor in _mfsmount(1)_ man page...
Probably a legacy parameter for 2.6 era kernels that is not used any more?

**Comment by cypromis** [comment]
big_writes: this option prevents fuse from splitting write buffers into 4K chunks, enabling big write buffers to be transferred from the application in a single step (up to some system limit, generally 128K bytes).
As far as my experience goes it still is a performance improver for fuse based filesystems even on cutting edge kernels.

**Comment by onlyjob** [comment]
Thanks, @cypromis.
