### ISSUE TITLE
Different users on chunkservers 

### ISSUE THREAD

**Issue by htbase** [lizardfs/lizardfs#554]
Hi there

We are running a test where we have two chunkservers where each chunkserver has its own user 

We changed the chunkserver configuration file to run the process with each specific user

The master is configured to run with the same user as chunkserver 1 (they are on the same machine)

The problem happens when the application writes in the lizardfs folder, it all shows fine on the master/chunkserver1 but on chunkserver2, it shows as permission denied when we try accessing the files, since users are different 

What is the workaround for this?

**Comment by psarna** [comment]
I need some clarification here. Does the *application* return permission denied error? Or is it in *chunkserver* logs when it tries to write to its internal chunk files?

If it's the application, then just adjust file permissions with some chmod/chown operations on a mountpoint. File permissions do not depend on which chunkservers the chunks are stored.

If it's the chunkserver, then just adjust permissions to the catalogues listed in mfshdd.cfg, so the user that owns the chunkserver process is able to write to it.

**Comment by htbase** [comment]
It's the application in this case

How do we set that permisssiom on mfshdd.cfg?

**Comment by psarna** [comment]
If it's the application, then set these permission on your files and directories inside your LizardFS mount point, just like you would do on any other file system. File permissions are part of the metadata, so you cannot set them in chunkserver configuration file.

**Comment by htbase** [comment]
Sorry, meant is the chunkserver, not application 

Which setting should we include in the mfshdd.cfg?

**Comment by richard-scott** [comment]
Don't you need both users to be in the same "group" and then have that "group" be the owner for the folder listed in mfshdd.cfg?

**Comment by Blackpaw** [comment]
The directory structure that the chunkserver writes to (as set in mfshdd.cfg) needs to be owned by the same user which the chunkserver is running as.

**Comment by htbase** [comment]
Problem is the the chunkserver process is been run by 2 different users, one for each server

**Comment by Blackpaw** [comment]
I'm not understanding the problem here - maybe your could detail your setup a lot more?
- Number of servers
- Processes running on each server
- chunk storage directories
- users they are running as.

Why do you need chunkservers running as different users?

**Comment by psarna** [comment]
The directory structure that the chunkserver writes to does not need to be **owned** by the same user which the chunkserver is running as, the user just needs to have **rights to write and read** to this directory structures. Just add appropriate permissions (with regular chmod) to the directories listed in mfshdd.cfg and to the paths where chunkservers store their configs, locks and other needed things (/var/lib/mfs & /etc/mfs most likely).

**Comment by psarna** [comment]
I assume this is resolved, if not, please reopen.
