### ISSUE TITLE
High CPU load for mfsmaster in version 3.11.0

### ISSUE THREAD

**Issue by r5r3** [lizardfs/lizardfs#555]
The mfsmaster process runs on Centos 7.3. The process has a constant CPU-Load of 100%. This behavior is independent of the actual workload caused by clients and is even the same without any clients connected.

The perf command shows the following:

    $ perf top -p $(pgrep mfsmaster)
    Overhead  Shared Object        Symbol
     70.21%  libJudy.so.1.0.3     [.] JudyLNext
     17.14%  mfsmaster            [.] fs_process_file_test
      2.14%  mfsmaster            [.] JudyLNext@plt
 
Judy is installed in version 1.0.5.

The `mfsmaster.cfg` file contains the following settings:

    PERSONALITY = master
    NO_ATIME = 1
    ADMIN_PASSWORD = my-admin-password
    WORKING_USER = mfs
    WORKING_GROUP = mfs
    DATA_PATH = /path/to/meta/data
    LOCK_MEMORY = 1
    MASTER_HOST = hostname-of-master
    TOPOLOGY_FILENAME = /etc/mfs/mfstopology.cfg

I also have a test-setup with version 3.10.6 running on Centos 7.3. There, the CPU load of the mfsmaster process is always very low.

**Comment by psarna** [comment]
Triplicate of https://github.com/lizardfs/lizardfs/issues/547, https://github.com/lizardfs/lizardfs/issues/552

**Comment by psarna** [comment]
*thanks for the perf output though, I wish more people did that!

**Comment by r5r3** [comment]
Sorry for the duplicate, I only searched for open issues....

**Comment by r5r3** [comment]
I downloaded the latest source code from the master branch, which includes the bugfix. But the problem is unfortunately not solved. I still get the very same behavior, the master server runs at 100% CPU load, the output of perf still looks the same. 

Here is some information about the setup:
```
$ lizardfs-admin info
LizardFS v3.12.0
Memory usage:	623MiB
Total space:	42TiB
Available space:	34TiB
Trash space:	108KiB
Trash files:	34
Reserved space:	0B
Reserved files:	0
FS objects:	1349525
Directories:	55562
Files:	1290917
Chunks:	1407171
Chunk copies:	1407171
Regular copies (deprecated):	1407171
```

```
$ lizardfs-admin chunks-health 
Chunks availability state:
	Goal	Safe	Unsafe	Lost
	default	0	1407171	-

Chunks replication state:
	Goal	0	1	2	3	4	5	6	7	8	9	10+
	default	1407171	-	-	-	-	-	-	-	-	-	-

Chunks deletion state:
	Goal	0	1	2	3	4	5	6	7	8	9	10+
	default	1407171	0	-	-	-	-	-	-	-	-	-
```

By the way, the state `unsafe` is a bit misleading. All files have the default goal 1 with one copy somewhere, which means their availability is exactly as defined.

**Comment by Blackpaw** [comment]
Not an expert but this looks very weird:
```
Goal	0	1	2	3	4	5	6	7	8	9	10+
	default	1407171	-	
```

I didn't even know you could have a goal Zero (copies). Why isn't everything Goal One?

**Comment by Blackpaw** [comment]
I just tried, I was able to set "0 0 : _" in mfsgoals.cfg but got an invalid argument for "lizardfs setgoal"

Could you post your mfsgoals.cfg?

**Comment by Blackpaw** [comment]
Gah, complete brain fart on my part, ignore my last two posts ... :(

**Comment by DarkHaze** [comment]
Try to set FILE_TEST_LOOP_MIN_TIME in config file to some high value (like 3000 or more). This tells master server how fast it must process files in test loop.

**Comment by r5r3** [comment]
Thanks for the suggestion. I just included this option in my `mfsmaster.cfg`. After restarting the master server, the CPU load for the process remains low for a couple of minutes, then it goes up to 100% again.

However, there is something else strange and is it possibly related. The master thinks that all my files are "defective": 
```
$ lizardfs-admin list-defective-files hostname-of-master 9421
/filename1 - undergoal
/filename2 - undergoal
/filename3 - undergoal
....
```
This command lists all my files, all of them marked as `undergoal`. But this is just wrong. The files have the goal 1 and they have 1 chunk. This is the output of `perf`: 
```
  73.81%  libJudy.so.1.0.3     [.] JudyLNext
  22.52%  mfsmaster            [.] fs_process_file_test
   2.37%  mfsmaster            [.] JudyLNext@plt
   0.09%  mfsmaster            [.] chunk_handle_disconnected_copies
   0.06%  mfsmaster            [.] compact_vector<ChunkPart, void, std::allocator<ChunkPart> >::end
   0.05%  mfsmaster            [.] ChunkWorker::mainLoop
   0.04%  mfsmaster            [.] eventloop_run
   0.02%  mfsmaster            [.] std::_Hashtable<std::reference_wrapper<ChunkGoalCounters const>, std::pair<std::reference_wrapper<ChunkGoalCounters co
   0.02%  libJudy.so.1.0.3     [.] JudyLGet
   0.02%  mfsmaster            [.] std::_Destroy<detail::Slice*, detail::static_preallocator<detail::Slice, 3ul> >
```

**Comment by r5r3** [comment]
I just tried to downgrade to version 3.10.6, but that seems to be impossible:
```
mfsmaster[30028]: loading extra attributes (xattr) from the metadata file
mfsmaster[30028]: error: unknown section found (leng:8,name:ACLS 1.1)
mfsmaster[30024]: [....] loading extra attributes (xattr) from the metadata file
mfsmaster[30024]: [FAIL] error: unknown section found (leng:8,name:ACLS 1.1)
mfsmaster[30024]: [FAIL] error reading metadata (structure)
mfsmaster[30028]: error reading metadata (structure)
```

**Comment by psarna** [comment]
We set up an installation to reproduce your issues and this patch was confirmed to help: https://github.com/lizardfs/lizardfs/commit/1dc583b0e8058fb2a964db7becd77db6868636b3

It will be included in 3.11.1 as well and you can expect an official release really soon.

Downgrading is (almost) never guaranteed to succeed, because metadata structure on disk may potentially change, just like in your case. It is still possible with some manual metadata editing, but it involves very internal knowledge of metadata format and is definitely not recommended. Downgrades are also not recommended because they contain other fixes that showed up in previous versions.

**Comment by r5r3** [comment]
Thank you very much! The commit 1dc583b fixed the 100% cpu usage issue. 

`lizardfs-admin list-defective-files` reports no under-goal files anymore. In the web-gui in the "Filesystem check info" section, the reported duration of the check loop is one hour. In the "Statistics of chunks" all chunks are still listed as "endangered". While this was also the case for version 3.10.6, it still sounds a bit odd.

**Comment by psarna** [comment]
Well, it kind of makes sense. Files with goal 1 and 1 copy are not `undergoal`, but they are `endangered` - losing 1 copy out of 1 is going to lead to data loss. It's consistent with our definition of `endangered`.

**Comment by psarna** [comment]
3.11.1 is out.
