### ISSUE TITLE
Is there a way to avoid trash completely?

### ISSUE THREAD

**Issue by reschandreas** [lizardfs/lizardfs#563]
I don't need the trash, what I delete should be permanently deleted.
Setting the trashtime to zero for each file and directory doesn't work for me, because the file-system is used by several people and those little extra tasks destroy the workflow.

**Comment by Zorlin** [comment]
In theory trashtime is inherited from the parent object... you could set it
on the root of the filesystem and all new files and folders created after
that point should have a trashtime of zero.

**Comment by reschandreas** [comment]
That could work, I still need to `lizardfs settrashtime 0 lizardfs` tough.
The best way to handle this for me would be if I could specify the trashtime in a configuration file of some sort, so that no client has to care about it

**Comment by Zorlin** [comment]
If you set it on one node, it should automatically be set everywhere else as it's part of the filesystem's metadata.

**Comment by reschandreas** [comment]
Ok then I'll handle it that way, thank you. Sorry for my lack of knowledge, I just discovered LizardFS yesterday.

**Comment by Zorlin** [comment]
No problem, everyone starts somewhere! Have a play with it and you'll quickly become comfortable :)
