### ISSUE TITLE
How to force replication of chunks?

### ISSUE THREAD

**Issue by reschandreas** [lizardfs/lizardfs#564]
I'm testing lizardfs right now and I noticed that it takes a while until the master replicates chunks that are undergoal. In the picture you can see that there are 1000 newly added files that are under goal and as I'm writing this these files are at least ten minutes old and the master has not even started replicating them. How can I configure the master to force to be stricter and faster with the goals? 
![lizardfs](https://user-images.githubusercontent.com/16179620/26923732-54b3b59c-4c43-11e7-9f22-87332fac1b29.png)

**Comment by psarna** [comment]
mfsmaster.cfg:
~~~
       OPERATIONS_DELAY_INIT
           initial delay in seconds before starting chunk operations (default is 300)

       OPERATIONS_DELAY_DISCONNECT
           chunk operations delay in seconds after chunkserver disconnection (default is 3600)

       CHUNKS_LOOP_PERIOD
           Time in milliseconds between chunks loop execution (default is 1000).

       CHUNKS_LOOP_MAX_CPU
           Hard limit on CPU usage by chunks loop (percentage value, default is 60).

       CHUNKS_SOFT_DEL_LIMIT
           Soft maximum number of chunks to delete on one chunkserver (default is 10)

       CHUNKS_HARD_DEL_LIMIT
           Hard maximum number of chunks to delete on one chunkserver (default is 25)

       CHUNKS_WRITE_REP_LIMIT
           Maximum number of chunks to replicate to one chunkserver (default is 2)

       CHUNKS_READ_REP_LIMIT
           Maximum number of chunks to replicate from one chunkserver (default is 10)

~~~

**Comment by reschandreas** [comment]
I configured it like this
```
OPERATIONS_DELAY_INIT = 300

OPERATIONS_DELAY_DISCONNECT = 3600

CHUNKS_LOOP_PERIOD = 10

CHUNKS_LOOP_MAX_CPU = 100

CHUNKS_SOFT_DEL_LIMIT = 10

CHUNKS_HARD_DEL_LIMIT = 25

CHUNKS_WRITE_REP_LIMIT = 100

CHUNKS_READ_REP_LIMIT = 20
```

But it won't replicate instantly.

**Comment by pkali** [comment]
Hi!
What is the situation now?
BTW - 
OPERATIONS_DELAY_INIT = 300
means 5 mins delay, so no instant replications here.
Also
CHUNKS_WRITE_REP_LIMIT = 100
CHUNKS_READ_REP_LIMIT = 20
might delay the replications.

Please also update LizardFS to the current version (3.11.2) - it fixes some issues with processor power consumption.

**Comment by reschandreas** [comment]
Hi! @pkali 
Well, turns out I had a rule that needed 4 copies of anything, but since I was new to LizardFS (and due to my stupidity) I didn't know that it needed 4 chunkservers to have 4 copies. As soon as I added a forth chunkserver it worked.

I also did update to 3.11.2
