### ISSUE TITLE
Timeout for cgiserv in Info view in 3.11.2

### ISSUE THREAD

**Issue by r5r3** [lizardfs/lizardfs#565]
After a restart of the master server, the cgiserv becomes unresponsive when the default info view is opened. After some time, the info page is displayed, but the "Filesystem check info" box contains the following traceback:
```
Traceback (most recent call last):
  File "/usr/share/mfscgi/mfs.cgi", line 929, in 
    data = myrecv(s,length)
  File "/usr/share/mfscgi/mfs.cgi", line 285, in myrecv
    raise RuntimeError, "socket connection broken"
RuntimeError: socket connection broken
```
Before opening the web page, the master server process has only a CPU utilization of a few percent. After opening the web page, the CPU utilization goes up to 100% until the timeout of the web page occurs. The output of perf of the mfsmaster is then the following:
```
  91.98%  libJudy.so.1.0.3     [.] JudyLNext
   3.76%  mfsmaster            [.] FSNodeDirectory::getChildName
   1.76%  mfsmaster            [.] JudyLNext@plt
   0.16%  mfsmaster            [.] fsnodes_escape_name
   0.13%  mfsmaster            [.] chunk_find
   0.13%  libJudy.so.1.0.3     [.] JudyLGet
   0.11%  libc-2.17.so         [.] _int_free
   0.11%  mfsmaster            [.] fs_test_getdata
   0.11%  mfsmaster            [.] chunk_handle_disconnected_copies
   0.10%  mfsmaster            [.] fsnodes_getpath_data
```
This behavior was first observed after the update to version 3.11.2. The problem goes away after the master runs for some time (don't know exactly how long, but hours). Unfortunately, the master becomes completely unresponsive when the web page is opened and until the timeout occurs. That means, client are not served during this time.

**Comment by psarna** [comment]
Did you update cgi to 3.11.2 as well?

**Comment by r5r3** [comment]
Yes, all lizardsfs-packages are installed in version 3.11.2

**Comment by DarkHaze** [comment]
It's possible that your machine running cgi doesn't have network access to
chunkservers. This would give the behaviour you are observing.

10.06.2017 14:09 "Robert Redl" <notifications@github.com> napisał(a):

**Comment by r5r3** [comment]
All chunkservers are located in the same vlan with no firewall in between the machines, ping works in both directions... The "Servers"-view of the webpage shows all chunkservers as connected.
The cgi runs on the same machine as the master.

**Comment by DarkHaze** [comment]
Could you post information about your system version ?
