### ISSUE TITLE
176 Chunks to replicate unchanged for 12 hours

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#570]
This is a test cluster, so not important, and I did some strange things to it which may have started the problem, but I'm curious as to how to resolve it.

Situation:
* Debian 8 (jessie)
* Lizardfs 3.11.2
* 3 chunkservers
* 1 Master server

I wanted to test a thought regarding the difference between the chained writes for replica goals and simultaneous writes for ec goals. So I created a ec(3,0) goal - which I did not expect to work :)

Starting from a empty state I copied a 28GB VM file (913 chunks) to the volume with my ec(3,0) goal. That actually looked like it worked - ran, interesting performance figures until I realised the webui status was "10+ copies to replicate=913"

* Made a snapshot of it
* Set the snapshot to Goal 3
* Did some more testing
* Deleted the Goal ec(3,0) file
* deleted the ec(3,0) goal and reloaded the master server
* cleared the trash
* let the system finish its rebalancing
* changed the Goal 3 file to e(2,1)
* The system started rebalancing but stopped at "1 copy to replicate=199"
* Restarted the masterserver
* restarted the chunkservers
* Got some "endangered chunks"
* The system started rebalancing, healed the endangared chunks but stopped at "1 copy to replicate=176"
* has been like that for approx 12 hours now

I presume the db has got into some weird state - is this fixable from a user perspective?

**Comment by Blackpaw** [comment]
```
lizardfs-admin chunks-health mfsmaster 9421
Chunks availability state:
        Goal    Safe    Unsafe  Lost
        EC21    913     -       -

Chunks replication state:
        Goal    0       1       2       3       4       5       6       7       8       9       10+
        EC21    737     176     -       -       -       -       -       -       -       -       -

Chunks deletion state:
        Goal    0       1       2       3       4       5       6       7       8       9       10+
        EC21    737     -       -       176     -       -       -       -       -       -       -

```

**Comment by psarna** [comment]
ec(3,0) is not a valid goal definition! If it parsed correctly then it's a bug in our goal config parser.
Your ec(3, 0) config most likely resulted in something like ec(2, 31). We'll create a patch that checks whether ec(M, N) is correct taking into account that N must be >= 1.

**Comment by Blackpaw** [comment]
> ec(3,0) is not a valid goal definition! If it parsed correctly then it's a bug in our goal config parser.

Never underestimate the ability of a user to do weird shit you never thought anyone would possibly try :)

**Comment by cypromis** [comment]
Well said
