### ISSUE TITLE
LizardFS mailing list?

### ISSUE THREAD

**Issue by lonnieOST** [lizardfs/lizardfs#573]
Greetings All,

I am trying to locate a LizardFS mailing list or Slack so that I can ask how to set up 3 node LizardFS with docker containers?

Sorry, but I did not know where else to post this question.
Thanks,
Lonnie

**Comment by Blackpaw** [comment]
https://sourceforge.net/projects/lizardfs/lists/lizardfs-users

**Comment by pkali** [comment]
@lonnieOST - I am happy you have joined the mailing list and received guidance! Please do not hesitate to ask us (Skytechnologies) or the community when a doubt arises.

**Comment by cypromis** [comment]
you can also use the forum https://lizardfs.org/forum. I guess its time to update the readme file :)
