### ISSUE TITLE
Ubuntu packages

### ISSUE THREAD

**Issue by guestisp** [lizardfs/lizardfs#574]
Is possible to have updated packages for ubuntu ?

Latest version is 3.10.4, that is buggy and not working properly due to Judy library bug fixed in 3.10.6

**Comment by psarna** [comment]
It is, but we're not official Ubuntu repository maintainers! Ask the packages.ubuntu.com guys. Our packages.lizardfs.org Ubuntu repo always has the latest releases.

**Comment by guestisp** [comment]
Last time i've checked your official ubuntu repos, configuration was very different than any standard Debian/Ubuntu system.

If your official packages was similiar in structure to Debian/Ubuntu packages, I have no regrets to use your official packages.
