### ISSUE TITLE
ChunkServer limiting harddrive usage

### ISSUE THREAD

**Issue by matthiaz** [lizardfs/lizardfs#575]
Description:    Ubuntu 16.04.2 LTS
lizardfs-chunkserver
Architecture: amd64
Source: lizardfs
Version: 3.11.2

According to the documentation found here: 
https://docs.lizardfs.com/adminguide/basic_configuration.html#configuring-your-chunkservers

You you should be able to define which harddrives get mounted in /etc/mfs/mfshdd.cfg and you should be able to define limits on them.

The first two examples work. 
```
# use directory '/mnt/hd1' with default options:
/mnt/hd1

# use directory '/mnt/hd2', but replicate all data from it:
*/mnt/hd2

```
But the last two don't
```
# use directory '/mnt/hd3', but try to leave 5GiB on it:
/mnt/hd3 -5GiB

# use directory '/mnt/hd4', but use only 1.5TiB on it:
/mnt/hd4 1.5TiB
```
I adapted the config for my needs as such:
`/mnt/hd3temp/lizardfs_vol/      10GiB`

But as you can see in this screenshot, the 10GiB does not get interpreted as expected... 
![mfs error](https://user-images.githubusercontent.com/3532563/27828942-275f2bf4-60bf-11e7-84ed-9805fa1e6c2e.png)

Is the documentation wrong? Or am I missing something?

**Comment by psarna** [comment]
The documentation is not up to date, this commit was merged a while ago: https://github.com/lizardfs/lizardfs/commit/d259551be932d9acf81b6c07e189d8c9f81fd388

**Comment by matthiaz** [comment]
If I understand the code correctly, it means this feature was removed, right?

it now uses **gLeaveFree** for all harddrives, correct?
What setting is gLeaveFree?

**Comment by psarna** [comment]
Yes, it was removed as legacy code, it also created unnecessary performance impact.
gLeaveFree is related to a configuration entry in mfschunkserver.cfg:
~~~
HDD_LEAVE_SPACE_DEFAULT
    free space threshold to set volume as 100% utilized when there is less than given amount of free space left (default is "4GiB"). This number is always added to the used disk space reported by
    chunkserver.

~~~

**Comment by matthiaz** [comment]
Great thanks!
