### ISSUE TITLE
40 days of metadata lost on master restart

### ISSUE THREAD

**Issue by creolis** [lizardfs/lizardfs#577]
Hey guys,

we ran into a problem we can not fix on our own and since restore
procedures are afaik not covered in any documentation of lizardFS, 
I'm seeking advice here.

A few days ago, I had to restart the master. When it came back I noticed
that it was missing large quantities of chunks while stating others as over- and undergoal,
in short: something was *wrong*. First I thought the master lost contact to some chunk
servers and restarted them - they all reconnected successfully but the situation stayed
the same.

Then I noticed that all files I stored within the last 40 days were missing,
while others that were deleted reappeared - but were inaccessible since there
were no chunks available for them.

I realized, that the metadata base obviously was not updated on disk during the
last 40 days - but lizardfs seemed to work properly while the metadata was still
available in memory.

We are running a couple of backup metaloggers - but in /var/lib/... there were
no changelog files since end of may (thus, the 40 days gap I refer to) - the changelog
files ended in may and started again at the day I restarted the master.

I guess there's no way to restore the changes that happened during the fault period,
it's a weird feeling to know that the chunks are still there but I can't do anything with them).

In my opinion, LizardFS should not acknowledge syncs when metadata is not written to a physical disk or should switch to read-only mode if metadata can not be written .. it should clearly not "continue to do it's job" in a way that makes a fatal condition like this imperceptible for the user.

(Note: Disks on Master are fine and not out of space)

**Comment by psarna** [comment]
1. What's your LizardFS release and operating system?
2. Do you have any high-availability solution? Automatic failover? How many shadows/metaloggers are there in your installation? How do you manage them?
3. Full metadata dumps are made every hour and changelogs are created continuously. Even if full metadata dump fails, which is very unlikely, master will try dumping the metadata in emergency locations (see code snippet below). Your description implies that there were no changelogs in metaloggers as well (do you actually think metaloggers here as in mfsmetalogger, or shadow masters? The names are sometimes confused).

Do you have any logs (/var/log/syslog or /var/log/messages ones) that indicate something is wrong? When master is unable to create changelogs (or send them to metaloggers) it would definitely be logged. And when it's not possible to create an hourly metadata dump it's considered a very serious issue and syslog would be loaded with warnings and errors, as well as information that metadata was stored in a first place available (see below).
Also, do you have any screenshots from CGI interface that could help? Anything with more context...

~~~
int fs_emergency_saves() {
#if defined(LIZARDFS_HAVE_PWD_H) && defined(LIZARDFS_HAVE_GETPWUID)
	struct passwd *p;
#endif
	if (fs_emergency_storeall(kMetadataEmergencyFilename) == 0) {
		return 0;
	}
#if defined(LIZARDFS_HAVE_PWD_H) && defined(LIZARDFS_HAVE_GETPWUID)
	p = getpwuid(getuid());
	if (p) {
		std::string fname = p->pw_dir;
		fname.append("/").append(kMetadataEmergencyFilename);
		if (fs_emergency_storeall(fname) == 0) {
			return 0;
		}
	}
#endif
	std::string metadata_emergency_filename = kMetadataEmergencyFilename;
	if (fs_emergency_storeall("/" + metadata_emergency_filename) == 0) {
		return 0;
	}
	if (fs_emergency_storeall("/tmp/" + metadata_emergency_filename) == 0) {
		return 0;
	}
	if (fs_emergency_storeall("/var/" + metadata_emergency_filename) == 0) {
		return 0;
	}
	if (fs_emergency_storeall("/usr/" + metadata_emergency_filename) == 0) {
		return 0;
	}
	if (fs_emergency_storeall("/usr/share/" + metadata_emergency_filename) == 0) {
		return 0;
	}
	if (fs_emergency_storeall("/usr/local/" + metadata_emergency_filename) == 0) {
		return 0;
	}
	if (fs_emergency_storeall("/usr/local/var/" + metadata_emergency_filename) == 0) {
		return 0;
	}
	if (fs_emergency_storeall("/usr/local/share/" + metadata_emergency_filename) == 0) {
		return 0;
	}
	return -1;
}
~~~

**Comment by rubensutter** [comment]
Did you setup LizardFS using the available OS Packages and then compile the new updated version of LizardFS from source?

**Comment by creolis** [comment]
Hey guys,

I'm afraid I kind of "found" the reason.
First of all sorry for the bad style (dropping an issue without version information and logs is bad and I really should know better. I blame it on the pressing matter ;-)

The version we're using right now is 3.11.2, running on Ubuntu Server using
the lizardfs package repo (http://packages.lizardfs.com/ubuntu/xenial).

Since @psarna hinted me at syslog I went through the logs - logrotate almost munched
all the information away that would tell me what exactly happened to the system, but
I found the following entries that pretty much seems to sum it up:

`
Jul 10 06:25:02 master mfsmaster[29645]: lost metadata change 152107038: 1499660702|ACCESS(31)

Jul 10 06:25:02 master mfsmaster[29645]: lost metadata change 152107039: 1499660702|ACCESS(32)

Jul 10 06:25:02 master mfsmaster[29645]: lost metadata change 152107040: 1499660702|ACCESS(46)

Jul 10 06:25:02 master mfsmaster[29645]: lost metadata change 152107041: 1499660702|ACCESS(47)
Jul 10 06:25:02 master mfsmaster[29645]: lost metadata change 152107042: 1499660702|ACCESS(48)
Jul 10 06:25:02 master mfsmaster[29645]: lost metadata change 152107043: 1499660702|CHECKSUM(3.10.6):18272065527203145895
`

**Comment by creolis** [comment]
Hey guys,

I'm afraid I kind of "found" the reason.
First of all sorry for the bad style (dropping an issue without version information and logs is bad and I really should know better. I blame it on the pressing matter ;-)

The version we're using right now is 3.11.2, running on Ubuntu Server using
the lizardfs package repo (http://packages.lizardfs.com/ubuntu/xenial).

Since @psarna hinted me at syslog I went through the logs - logrotate almost munched
all the information away that would tell me what exactly happened to the system, but
I found the following entries that pretty much seems to sum it up:

> master mfsmaster[29645]: lost metadata change 152107038:1499660702|ACCESS(31)
> master mfsmaster[29645]: lost metadata change 152107039: 1499660702|ACCESS(32)
> master mfsmaster[29645]: lost metadata change 152107040: 1499660702|ACCESS(46)
> master mfsmaster[29645]: lost metadata change 152107041: 1499660702|ACCESS(47)
> master mfsmaster[29645]: lost metadata change 152107042: 1499660702|ACCESS(48)
> master mfsmaster[29645]: lost metadata change 152107043: 1499660702|CHECKSUM(3.10.6):18272065527203145895
> master mfsmaster[29645]: lost metadata change 152108609: 1499661639|WRITE(350527,0,0,2371099136):2928404

this goes on like forever, day after day, thousands of error messages we did not notice.

Then I stumbled upon these lines:

> master mfsmaster[29645]: can't store sessions, open error: EACCES (Permission denied)
> master mfsmaster[29645]: error creating charts data file: EACCES (Permission denied)
> master mfsmaster[29645]: rename backup file changelog.mfs.49 to changelog.mfs.50 failed (Permission denied)
> master mfsmaster[29645]: rename backup file changelog.mfs.48 to changelog.mfs.49 failed (Permission denied)
> [...]
> master mfsmaster[29645]: rename backup file changelog.mfs.1 to changelog.mfs.2 failed (Permission denied)
> master mfsmaster[29645]: rename backup file changelog.mfs to changelog.mfs.1 failed (Permission denied)
> master mfsmaster[19392]: can't open metadata file
> master mfsmaster[19392]: metadata were stored to emergency file: /tmp/metadata.mfs.emergency - please copy this file to your default location
as 'metadata.mfs'
> master mfsmaster[29645]: the dumping process finished without producing output

I **think** I know what might has happened here:
First, I thought the filesystem where the metadata resides had an error and the kernel chose to remount it read-only to prevent it from corruption. LizardFS could not write its data any more - so it chose to write a metadata emergency file to /tmp/ - but the system was restarted eventually, so all content in /tmp was lost.

But there are no syslog entries that support the that the filesystem mounted to /var/lib/lizardfs had such an error. Then I realized that suddenly, the data is fetched from /var/lib/mfs - but /var/lib/mfs does not have the same access permissions. I assume that's  were the journey begins 

@rubensutter - We started on compiled versions and then at some point switched over to source - I assume that's were the confusion with configuration paths (/var/lib/mfs vs. /var/lib/lizardfs) started?
I vaguely remember that we were puzzled about the fact that lizard still uses mfs-* style commands and paths. 

/var/lib/lizardfs/metadata.mfs is dated back to march, that's probably when we switched to the repository version.

**Comment by creolis** [comment]
PS:
> Your description implies that there were no changelogs in metaloggers as well (do you actually
> think metaloggers here as in mfsmetalogger, or shadow masters? The names are sometimes
> confused).

metaloggers as in mfsmetalogger. We did not run a shadow master since we felt a shadowmaster is just a mfsmetalogger that can be used as master if the master dies and that mfsmetaloggers provide the same level of data security (with additional work to be done on restore)

**Comment by rubensutter** [comment]
I guess the EACCES (Permission denied) are caused by the wrong permissions on the /var/lib/mfs which should be set to mfs for the mfsmaster process or a still existing lock file on the master server. 

e.g. of a Shadow Server (this Shadow Server was shutdown as expected on June 25th) shows 
ls -l /var/lib/mfs  
-rw-r----- 1 mfs mfs ****** Jun 25 10:05 metadata.mfs

and a lock file

ls -la /var/lib/mfs
-rw-r-----  1 mfs  mfs       0 Mai 16 13:28 .mfsmaster.lock

To get an additional metadata backup from the active LizardFS Master Server I use a cronjob that runs the [mfsmetadump](https://docs.lizardfs.com/man/mfsmetadump.8.html?highlight=mfsmetadump) command which dumps the metadata into a specified file and generate encrypted backups on a different storage location.

**Comment by creolis** [comment]
> To get an additional metadata backup from the active LizardFS Master Server I use a cronjob that
> runs the mfsmetadump command which dumps the metadata into a specified file and generate
> encrypted backups on a different storage location.

Vielen Dank :)  - that's is a great way of dealing with this kind of data .. if I only knew beforehand ;-)

**Comment by creolis** [comment]
Okay, so basically I am back on track again - some data is lost but nothing I can't cope with.

To have a better level of security for the (very vital) metadata - I have something that might be worth a feature request - but I think I just post it here to see if you guys agree with me:

I would love to have something like mfsmetadump - BUT it should ask the mfsmaster process to dump its memory content to a specified file. See, I had a problem with the metadata file not being written to the desired location due to a permission problem. If I back up the metadata file regularly but the mfsmaster process could not write memory content to the file, this won't result in a backup but just copying away the same (not updated) file over and over again.

But if I could run a cronjob like e.g. "mfsmemorydump <path-to-dumptarget>" I could directly take all metadata from the server and throw it at a backup storage whatsoever.

Is this an idea worth considering or do I miss a point?

**Comment by jkiebzak** [comment]
I think a simpler approach would be to have a cron job "touch" a file in
the desired location, and send an email on failure. Run the job as the
`mfs`user. Same job could use used to copy off the metadata to your backup
location.

On Thu, Jul 27, 2017 at 11:26 AM, Daniel Haslinger <notifications@github.com

**Comment by creolis** [comment]
@jkiebzak right ... that's a possible way to get notified if anything prevents us from writing to the disk, I just thought it would be nice to have a tool that lets mfsmaster dump its memory directly on request, but I will probably go with your hint :)

@all - thanks for your input and time, I consider this to be closed and now know that I need to pay attention to certain aspects of the master in order to run lizardFS safely and in production :)

**Comment by 4Dolio** [comment]
btw. There is a way to ask the master to do a metadata dump on demand with the lizardfs-admin tool, i believe... in fact, i have resorted to disabling the default hourly dumps which can only happen at the top of the hour.  I then use cron tasks at staggered times to schedule my metadumps so they don't all happen at the same time on all masters.

**Comment by creolis** [comment]
This sounds good, I'm going to have a look at that :) Thanks!

**Comment by psarna** [comment]
`lizardfs-admin save-metadata`
