### ISSUE TITLE
SELinux relabeling support

### ISSUE THREAD

**Issue by TerraTech** [lizardfs/lizardfs#581]
In furthering the work started in:  https://github.com/lizardfs/lizardfs/issues/486
now that the controller attach/detach issue has been fixed in Kubernetes 1.7.x.

I am trying to mount lizardfs via Kubernetes FlexVolume driver, however I seem to have run into a brick wall.  FlexVolume is defined to always try to relabel [Chcon()] a volume mount due to it being hardcoded with no way to override the 'default'.
https://github.com/kubernetes/kubernetes/blob/v1.7.1/pkg/volume/flexvolume/mounter-defaults.go#L50
```
10s        10h         131       bb-lzfs   Pod       spec.containers{bb-lzfs}   Warning   Failed       kubelet, m06   Error: failed to start container "bb-lzfs": Error response from daemon: {"message":"SELinux relabeling of /var/lib/kubelet/pods/3d1c7109-77ce-11e7-8d21-0018f3531b4f/volumes/fq~lizardfs/lzfs-test is not
allowed: \"operation not supported\""} 
```
Technically, it is Docker (opencontainers/runc) that is generating the error via selinux.Chcon(), but it is being told how to mount the volume by Kubernetes.

```sh
# cd /var/lib/kubelet/pods/3d1c7109-77ce-11e7-8d21-0018f3531b4f/volumes/fq~lizardfs
# ls -ldZ lzfs-test
drwxr-xr-x. 2 root root system_u:object_r:fusefs_t:s0 0 Aug  3 02:45 lzfs-test
```

/ping @lowet84 @M0nsieurChat @chakri-nelluri @verult

Before I turn my attention to (CoreOS) Kubernetes + FlexVolume, can anyone confirm if lizardfs supports context relabeling or not.  It seems that GlusterFS has (or had) the same problem, until Fuse was updated to be more SELinux friendly.
https://github.com/gluster/glusterfs/issues/55

As it stands now, I would have to run a custom patched kubelet to forcibly override the default.

TIA!

**Comment by psarna** [comment]
From what I read, it's basically Linux kernel that tells you that SELinux is not supported for fuse (because some fuse versions and/or fuse-based file systems do not support xattrs correctly). LizardFS is perfectly capable of handling setxattr/getxattr used by SELinux. Once some kernel patches for fuse enable SELinux support inside it, it will just work out of the box. Right now it just won't.

Ref:
*https://sourceforge.net/p/fuse/mailman/fuse-devel/thread/1385389343-55663-1-git-send-email-bfoster%40redhat.com/#msg31678712*
*http://engardelinux.net/modules/index/list_archives.cgi?list=selinux&page=0183.html&month=2012-08*

**Comment by TerraTech** [comment]
I had seen both of those list messages and had hoped that since 2012/2013, this had been addressed within the kernel.  The first message was the most promising, but I guess those patches never made it into the kernel.

At this point, I was trying to ascertain if:
1. This was a SELinux policy that was blocking the relabel
1. It is a kernel limitation
1. It is a fuse/libfuse limitation
1. It is a lizardfs limitation

So if it is truly <span>#</span>2 above, then that leads me to patching the kubelet to work around this problem.

**Comment by TerraTech** [comment]
This has been resolved via: https://github.com/kubernetes/kubernetes/pull/50843

I have also added a note regarding the updated lizardfs-flexvolume driver to:  https://github.com/lizardfs/lizardfs/issues/486#issuecomment-324890197

**Comment by psarna** [comment]
Cool, thanks
