### ISSUE TITLE
3.11.3: master segfault in check loop

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#582]
We had a blackout due to strong wind in Sydney and most of our chunkservers were stopped. Only few still had enough charge in UPS batteries by the time when power was restored. We've lost shadow master due to power loss and primary master due to segfault: in the absence of all  but two chunkservers most files (estimated over 50 millions) became unavailable and master crashed during check loop after logging thousands of `Chunks unavailable in file ` messages...

This problem added to troubles as master segfaulted again shortly after I restarted it because not all chunkservers were available at a time...

**Comment by Blackpaw** [comment]
Wow, and shit, my sympathies, sounds *very* stressful. Hope it resolves itself as more chunkservers come online.

Hope you don't mind me asking, but what sort of data are you storing and how many users to require (to me) such vast numbers of files?

**Comment by psarna** [comment]
Do you have the log line from syslog that reported the segfault (the one looking like `segfault at 0 ip 000000000043dacf sp 00007fff43dbddc0 ...`)? This along with operating system version + lizardfs release will allow us to pinpoint the line of code that triggered the error.

**Comment by psarna** [comment]
It's most likely fixed by https://github.com/lizardfs/lizardfs/commit/0ff659db5d0847db2aa0d59be4955c16012d6fc2 in 3.11.3 though.

**Comment by onlyjob** [comment]
> what sort of data are you storing and how many users to require (to me) such vast numbers of files?

About 10 users only but IMHO number of files is not that great as we have large _Maildir_ folders, hundreds of _git_ repositories and pretty much everything that you can find in `/home`. Multiplied by number of snapshots if is not hard to get that many files...

Log line from syslog that reported the segfault on Debian 9 "Stretch" (official Debian packages):

    segfault at 7f00b8dbdf40 ip 0000561cc7ca4ae2 sp 00007ffdb8dbded0 error 6 in mfsmaster[561cc7c65000+1a1000]

> It's most likely fixed by 0ff659d in 3.11.3 though.

Thank you, I'll prioritise upgrade right away. :)

**Comment by onlyjob** [comment]
Master 3.11.3 also segfaults if enough chunkservers are stopped to produce massive amount of unavailable files. :(

**Comment by psarna** [comment]
Sorry, I just noticed that you reopened this one. Do you have a line from syslog, like last time? It would help pinpoint the issue a lot (since we didn't manage to reproduce it on our test clusters).

**Comment by onlyjob** [comment]
It happened again - I had a very very bad day because master crashed...
This time crash was caused by upgrade of network switch. Connectivity between master and some chunkservers was disrupted long enough for master to _segfault_ during check loop after logging 100_000+ `Chunks unavailable in file NNNN`.

    kernel: [567767.128773] mfsmaster[42283]: segfault at 7ffe7c000000 ip 00007faae663f514 sp 00007ffe7e376688 error 4 in libc-2.24.so[7faae65c4000+195000]

Reproducer is straightforward, you just need millions of unavailable files and few disconnected chunkservers...

**Comment by onlyjob** [comment]
Probably fixed in 3.12.0; 3.13.0~rc1 is not affected...
