### ISSUE TITLE
Backward/forward compatibility

### ISSUE THREAD

**Issue by six86** [lizardfs/lizardfs#588]
I'm playing around with a lizardfs setup. 
Master is at Ubuntu 16.04 LTS and uses version 3.9.4 (mfsmount --version). With a client that is also on Ubuntu 16.04 LTS everything is working fine so far, but with a Ubuntu 17.04 client (mfsmount 3.10.4)I cannot write files to the storage:

~~~
Received malformed WRITE_INIT message (length: 22)
~~~

Is this expected behaviour? Are minor updates not guaranteed to not break the existing functions?

If this is the case, I either have to install lizardfs on all clients manually in an older version or I cannot run LTS versions on the server anymore.

**Comment by psarna** [comment]
Upgrade procedures are listed here: https://github.com/lizardfs/lizardfs/blob/master/UPGRADE

Basically, master+shadows must be upgraded first in order for everything to work fine. Newer clients are not guaranteed to work with older master.

**Comment by Zorlin** [comment]
You can still run an LTS version by using the vendor-provided packages instead of the ones packaged with Ubuntu.
