### ISSUE TITLE
default goal

### ISSUE THREAD

**Issue by guestisp** [lizardfs/lizardfs#593]
How can I set default goal as "3" ?
Should i use `lizardfs setgoal 3` to the mountpoint root ?

**Comment by 4Dolio** [comment]
setgoal -r 3 /mountroot if there is already data there..  and yes, new object inherit their goals from parent dirs.

**Comment by guestisp** [comment]
Is this mandatory?
Shouldn't lizard automatically set a default goal on new install? If yes, how can I set the default goal?

Anyway, I'm getting constantly about 100mbps writing with goal 3 on a single gigabit link. Is this normal? It sounds too good too be true, almost zero overhead. How can I ensure that lizard is acknowledging after all 3 chunkserver has properly written data? (In other words, no forced writeback)

**Comment by 4Dolio** [comment]
The default label is _ so you probably want to change it to a more appropriate word.. you can use the same for equivalent CS or a unique one for each CS. Im still waiting on ability to give more than one label to each CS..

With goal 3 writes are only finished after all 3 cs have written. Unless only 2 are available, then after 2 have written.  Writes never use lazy replication, unless you have some serious problems (accidental or intentional) with clients ability to write...

**Comment by guestisp** [comment]
Can you give me a simple mfsgoal config file to set 3 as default?

How can I remove what I've manually set with `lizardfs setgoal` ?

So, are you saying that except some manual configuration, writes are always atomic, when a write is returned, all affected chunkserver have properly wrote to disk?
In my case , all 3 chunkserver have write properly to disk. Right ?

**Comment by 4Dolio** [comment]
I generally leave goals.conf as is for goals 1 through x ( maybe through goal 9 ).  So setgoal 1..9 just do default style goals.  Then goal 10+ i replace with my custom goals.  that way setgoal x<10 just yo x copies, and goal 10 might be ssd+ssd and 11 ssd+hdd+hdd, etc...

If you customized goal 3 then it no longer means _ _ _ and could be tricky change stuff.  So leave say 1..5 or whatever as stock goals.

Yes, I believe writes to all goal targets are atomic.. i could be mistaken, maybe there are additional features that augment that default behaviour..

**Comment by 4Dolio** [comment]
You have 40 goal definitions, so plenty off space to start from the end and work backwards.. i try to also not overlap goals between different clusters.  So all clusters share a common goals layout.. even if some are invalid in some clusters...
