### ISSUE TITLE
Ubuntu Xenial Packages have an invalid signature

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#596]
> Reading package lists... Done
> W: GPG error: http://packages.lizardfs.com/ubuntu/xenial xenial InRelease: The following signatures were invalid: 4E545F8BD6FDC4BDE65F7E723EE4D2780BF8466D
> W: The repository 'http://packages.lizardfs.com/ubuntu/xenial xenial InRelease' is not signed.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> 

I have installed the key are per the docs:

>wget -O - http://packages.lizardfs.com/lizardfs.key | apt-key add -

This is on Zenial (17.04), but that shouldn't make a difference for the signature.

**Comment by epol** [comment]
There is the same problem on Debian Stretch with jessie sources:

> deb http://packages.lizardfs.com/debian/jessie jessie main

**Comment by jkiebzak** [comment]
any updates on this?

**Comment by blink69** [comment]
fixed, resigned xenial and jessie repo.

**Comment by Blackpaw** [comment]
Thanks, updates with no warnings now.

**Comment by epol** [comment]
Same on debian stretch with jessie repos. Thank you.
