### ISSUE TITLE
filerepair - chunks erased vs chunks repaired

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#597]
When I do the following:

```
lizardfs checkfile 109/*
109/vm-109-disk-1.qcow2:
 chunks with 0 copies:            6
 chunks with 1 copy:              1
 chunks with 2 copies:            5
 chunks with 3 copies:          219

lizardfs filerepair 109/vm-109-disk-1.qcow2
109/vm-109-disk-1.qcow2:
 chunks not changed:        507
 chunks erased:               0
 chunks repaired:             6

```

What does it mean? has the file been repaired with no data loss? is so, how?

thanks

**Comment by psarna** [comment]
Something bad happened in your installation (a master failover, chunkserver failure, etc.) during a write operation, which resulted in master having different information on chunk version than chunkservers. After you run `lizardfs filerepair`, master browsed through previous versions of this chunk available on any of the chunkservers and updated its version information. Basically master restored your chunks to newest version possible at the moment, so there's a very good chance there's no data loss whatsoever.

The point is that you shouldn't run `lizardfs filerepair` if you know that some chunkservers are down and they might have the correct version of given chunk, because in that case you might lose the newest version in favour of some older one.

**Comment by Blackpaw** [comment]
Thanks Piotr, was testing power outages by kills all servers via `echo b > /proc/sysrq-trigger`

metafiles were being written to ext4 which I'm pretty sure had journaling turned off, so could have had data lost. Chunkservers are on zfs with sync=standard.

>  Basically master restored your chunks to newest version possible at the moment, so there's a very good chance there's no data loss whatsoever.

I'd say thats what happened. VM Were fine after being repaired.

I'm guessing it would be essential to stop all writes to the damaged file before repairing it, or do writes to damaged files get blocked anyway?

**Comment by Blackpaw** [comment]
On 30/09/2017 11:22 PM, Piotr Sarna wrote:
> The point is that you shouldn't run |lizardfs filerepair| if you know 
> that some chunkservers are down and they might have the correct 
> version of given chunk, because in that case you might lose the newest 
> version in favour of some older one.

Ah, good to know thanks. Did do that anyway.


I have a feeling the following triggers the issue as well:


> Sep 30 23:17:10 vnb mfsmaster: about 20 seconds passed and the lock 
> /var/lib/mfs/.mfsmaster.lock still exists...
> Sep 30 23:17:10 vnb pvestatd[4433]: mount error: Mount failed. Please 
> check the log file for more details.
> Sep 30 23:17:10 vnb pvestatd[4433]: status update time (16.158 seconds)


Downgrading a master to a shadow requires it to be restarted of course 
and I've noticed it sometimes takes it over 50 seconds. If the 
keepalived trys to swicth back while that is going on it will call a 
reload on the service, or a start if that fails.


Not sure what the effect of that would be.


Edit: Actually I think know what happened - switched it back to master 
before it had a chance to sync the metadata from the previous master. 
Hence the lost chunks that were repairable.

I'm going to have to think on this as I have a flapping problem when 
servers come up.

-- 
Lindsay Mathieson

**Comment by guestisp** [comment]
Why a possible data loss?
If chunks was wrote properly on disk and master was outdated, only metadata (stored on master) could be lost, but real data stored on each chunk should be still available

Am I miss something?

**Comment by Blackpaw** [comment]
Well I guess there is the possibility that the chunk data could have been lost to - if you were runnign with PERFORM_FSYNC off or the server filesystem wasn't flushing properly.

I suspect chunks created that were lost from the meta data would be an issue to.

**Comment by guestisp** [comment]
But with `PERFORM_FSYNC` se to on (default), no data loss should happen in this cases.

Anyway, probably having a detailed example of what master is storing and in which format, could explain many things.

Maybe a simple metadata dump in plain text to see what master is storing.

**Comment by 4Dolio** [comment]
In the case of a power loss. You should carefully check the metedata version of each master/shadow after doing metadata restore.

I have an alias to quickly evaluate the metadata file version and recent changelog files last complete line versions to do that more quickly.

Starting up a power lost cluster takes a little more effort than a cleanly stopped cluster. And my corosync HA locks out shadows with older than HEAD metadata from seeding the cluster backwards in time.

**Comment by 4Dolio** [comment]
Ill try to share more aliases/functions.
To list available metadatas you can use:
Use metadata restore to just print revisions.
Use tail -n2 to see revisions in changelog files.

The corosync i use is shared from some other posts already.  It does a few odd things like:
* artificially rotates a stopped shadow metadata file so a shadow can never bootstrap without intervention.
* any uncleanly stopped metadata file, or quick stopped master, lfs already will refuse to use without metadatarestore to clean it.
* dont ever automatically use metadatarestore.
* so, only a cleanly stopped solo master can seed without intervention. All others require a human.
