### ISSUE TITLE
HDD marked for removal progress

### ISSUE THREAD

**Issue by guestisp** [lizardfs/lizardfs#602]
Is possible to know, when a disk marked for removal, can be safely removed ?

A sort of progress update for the evacuation process

I've tried to mark a disk for removal, then waited about 30-40 minutes and then phisycally removed.
Process was still unfinished and now I have tons of missing chunks

**Comment by psarna** [comment]
Such disk can be removed once all chunks are migrated from it. You can check it in CGI or just by listing your chunk files locally via something like `find YOUR_PATH -type f`

**Comment by guestisp** [comment]
hdd removal will delete file locally ?
I've seen an issue opened where file removal can't be done on a read-only filesystem (maybe due to some write error, that would explain why a disk is marked for removal), thus relying on listing local files is not good, because file would be still there even if disk is unused anymore by lizard.

The same would apply for CGI interface, I think. Is "chunks" column in "Disks" tab the number of chunks available on hdd or the chunks that master is using ?
It's different, because if master is not using that disk anymore, "chunks" could be 0 even if chunks are still available on disk.

**Comment by 4Dolio** [comment]
You can not lose any files if you have minimum safe goal values.  The mark for removal simply treats such a disk as a read only store for chunk files.. It does not aggressively 'evacuate' such a disk. If you want to quickly recover such a disk you remove it completely and let replication recover.  Replication will 'quickly' recover based on your other tunings like max read/write rep settings.

Marked for removal just prevents new writes, giving you time to take the appropriate actions. 
 Those actions may well be outside of LFS native mechanics, such as copying chunks files by hand to a new disk.

**Comment by 4Dolio** [comment]
It might be good to add a new hdd.cfg disk status.  Such as --/path with could 'mark for evacuation' and rapidly move those chunks to new disks and quickly from the disks chunk count to 0.

As it is, you can ensure no additional use of a disk marked for removal while you address saving those chunks if you need to.. otherwise just pull the disk and let replication kick in.

**Comment by guestisp** [comment]
Good idea the --/path one
