### ISSUE TITLE
metadata server protocol (Sorry for the heated debate)

### ISSUE THREAD

**Issue by 4Dolio** [lizardfs/lizardfs#629]
Re: https://github.com/lizardfs/lizardfs/issues/621
... I think perhaps @guestisp has "block or report user"-ed me? bummer. Can no longer interact with issues that he has create? perhaps? Can no longer reply anyway?  Not sure how that whole moderation system works.  Anyway, Up front, sorry for letting the discussion become so heated.  

> Really, please stop

I promise, I will.

> Stop asking WHY I have to do so, this issue is for HOW to communicate with master.

Even @psarna has stated multiple times in your issues, lizardfs-admin is the tool to "communicate with master"

> I'm not interested in using lizardfs-admin and I don't have to justify this to you so STOP.

That makes no sense at all, but fine.

> Are you able to provide useful responses? Then reply with something useful. In other case, please stop to hijack every issue that I open.

My useful information is that the lizardfs-admin tool is the human, scriptable, programmable interface to communicate with the master. It works perfectly. There is nothing wrong with it. That IS my answer to you.

> Your behavior is very similar to a troll

I am not a troll and I am slightly offended by being called that.  I am honestly trying to help you arrive at a solution.  I have been trying to convey that in numerous ways.  I am sorry that you feel I was trolling you.  I actually got some new valuable insights into some things I would like to give more attention to in my own HA implementations.  So I appreciate differences in perspectives and the exchange of ideas.  I am most sorry that we could not come to some understanding of each others perspectives.  I am still honestly curious as to why you do not want to use the lizardfs-admin tool.  It baffles me and I do not like unresolved mysteries.

I am done now.. Cheers.

**Comment by pkali** [comment]
I can understand the rationale behind the need to control LizardFS from within own software without invoking external binary. This is perfectly possible, one just need to re-implement communication with Master server as described in these source files - https://github.com/lizardfs/lizardfs/tree/master/src/admin.
There is no better communication protocol description than these sources - these are very well readable even if one's no expert in C++ and must be treated as the reference implementation.

Best regards,
Pawel Kalinowski
