### ISSUE TITLE
mfsmount disable-multi-threaded option

### ISSUE THREAD

**Issue by cratoo** [lizardfs/lizardfs#638]
Hi there, currently I experience some issue, that a LFS mount ha a terrible performance on a machine that's generally under high load.
The same mount on a machine without any significant load performs fine.

This leads me to the conclusion that the master server and the chunks are fine (this correlates with their stats in regards to cpu/mem/io), but the mfsmount seems to have an issue.

I also found the option "-s" which is used in my case, and I'm asking myself if there is any reason to use it and if so, why?

LizardFS version 3.10.4 for master/chunks/mount.

**Comment by Blackpaw** [comment]
>generally under high load.

* CPU or IO load?

>I also found the option "-s" which is used in my case, and I'm asking myself if there is any reason to use it and if so, why?

I can't imagine why. Have you tried without it?

**Comment by psarna** [comment]
`-s` is a FUSE-specific option. And if you don't know why it's there, just don't use it at all - most FUSE-based applications benefit from multi-threading.

**Comment by Programie** [comment]
The `-s` option is specified if using autofs to mount LizardFS storages (it is hardcoded in autofs, enabled at build time).

In case of NFS, the `-s` option does a "sloopy" mount, but in case of LizardFS (or any other fuse mount?) it disables multi-threading which IMHO is a bad thing on high load machines.

**Comment by cratoo** [comment]
As our issue was "solved". I'm closing it.
