### ISSUE TITLE
debian 9 (stretch) packages

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#639]
Is there any chance of stretch packages for 3.x? my cluster environment (proxmox) has upgraded to stretch. Its been around for a while now.

Or can the jessie packages be used on stretch? I can test that if no one knows for sure :)

**Comment by Zorlin** [comment]
Jessie packages *should* work on Stretch but I would test them extensively
before using them in production.

**Comment by Blackpaw** [comment]
Would dependency problems be the only possible issues or would you be worried about operational bugs - data corruption, crashes etc?

**Comment by Zorlin** [comment]
Primarily dependencies, but when running anything in an "unsupported" configuration you should be careful.

**Comment by Blackpaw** [comment]
Fair enough, thanks. Something to do over the Christmas break :)

**Comment by onlyjob** [comment]
3.11.3 has been accepted to _stretch-backports_ some hours ago: https://packages.debian.org/source/stretch-backports/lizardfs

**Comment by psarna** [comment]
Thanks!
