### ISSUE TITLE
Wrong YUM repo metadata

### ISSUE THREAD

**Issue by kubikrobert** [lizardfs/lizardfs#640]
Hello,
can you please update the YUM repo metadata to include new 3.12 version?

I see, that 3.12 packages are here, but yum update won't update those packages:

`Pakiet lizardfs-master-3.11.3-0el7.x86_64 jest już zainstalowany w najnowszej wersji`

Thanks in advance!
Regards

**Comment by blink69** [comment]
Thanks for report, fixed.
