### ISSUE TITLE
Connection failed, error: No route to host

### ISSUE THREAD

**Issue by tcjdesign** [lizardfs/lizardfs#642]
I'm setting up a simple 3 node cluster, and everything is fine and dandy with the master and the chunkserver on the same box. But the other two chunkservers always get `Connection failed, error: No route to host`.

My `/etc/hosts` file has an entry for mfsmaster. I can ping mfsmaster no problem. Looking at nethogs it appears like it's sending traffic to the correct machine (192.168.1.201 in this case). But despite that I keep getting this error.

Am I forgetting something? Do I need to change a config on my master to allow connections from X IP addresses? Or is something wonky going on?

**Comment by ehsan310** [comment]
@tcjdesign did you checked your Selinux and your firewall status ?

is your master started and listening successfully on your mentioned IP ? 

It might be good if you send your mfschunkserver log.

**Comment by tcjdesign** [comment]
I'm a dummy. I totally forgot to put a hole in the firewall for it. We're all good now.

Thanks @ehsan310!
