### ISSUE TITLE
Link Error for NFS-Ganesha with RHEL7 Packages

### ISSUE THREAD

**Issue by r5r3** [lizardfs/lizardfs#646]
Dear LizardFS-Team, 

I followed the instructions in your documentation (https://docs.lizardfs.com/adminguide/gateways.html) to setup NFS-Ganesha. 

The following packages are installed:

    libntirpc.x86_64                                                 1.3.1-1.el7   
    lizardfs-lib-client.x86_64                                       3.12.0-0el7 
    lizardfs-nfs-ganesha.x86_64                                      3.12.0-0el7
    nfs-ganesha.x86_64                                               2.3.2-1.el7

When I now try to start the nfs-ganesha service, then everything seems to be fine. I can mount the nfs4-Share, but unfortunately it is completely empty. A lock at the ganesha log file revealed the problem:

    ganesha.nfsd-18272[main] load_fsal :NFS STARTUP :CRIT :Could not dlopen module:/usr/lib64/ganesha/libfsallizardfs.so Error:/usr/lib64/ganesha/libfsallizardfs.so: undefined symbol: log_attrlist
    ganesha.nfsd-18272[main] load_fsal :NFS STARTUP :MAJ :Failed to load module (/usr/lib64/ganesha/libfsallizardfs.so) because: Can not access a needed shared library

Their are no obvious link errors for libfsallizardfs.so:

    $ ldd /usr/lib64/ganesha/libfsallizardfs.so
	linux-vdso.so.1 =>  (0x00007fffa79aa000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fd9bc02b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fd9bbe23000)
	libJudy.so.1 => /lib64/libJudy.so.1 (0x00007fd9bbbd2000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd9bb9ce000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd9bb6c6000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd9bb3c3000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd9bb1ad000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd9baf91000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd9babcd000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a0cc2e7000)

But the symbol is indeed undefined:

    $ nm -D /usr/lib64/ganesha/libfsallizardfs.so
    ....
    00000000000346f0 T liz_write
                     U load_config_from_node
                     U load_config_from_parse
                     U localeconv
                     U localtime_r
                     U log_attrlist
                     U LogMallocFailure
    0000000000032d60 T lzfs_fsal_alloc_state
    000000000002fcd0 T lzfs_fsal_create_context
    000000000002ff30 T lzfs_fsal_delete_handle
    00000000000325e0 T lzfs_fsal_ds_handle_ops_init
    ....

The missing symbol `log_attrlist` seems to belong to the FSAL-API: https://github.com/nfs-ganesha/nfs-ganesha/blob/b2b3fb402a23d8d038b9c42c01ef338874711333/src/include/fsal.h

Was this library possibly linked against an old version of Ganesha?

**Comment by cypromis** [comment]
It is the other way around. The library is linked against 2.5.2. If you check out the documentation here: https://docs.lizardfs.com/adminguide/gateways.html, you will see where you can find all elements that are being used by us.

**Comment by r5r3** [comment]
As mentioned above, I followed already your documentation at https://docs.lizardfs.com/adminguide/gateways.html

In your documentation you write, that the EPEL-Repository should be used. This repository contains NFS-Ganesha in version 2.3.2: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/n/

Did you install ganesha from a different repository not mentioned in your documentation?

**Comment by r5r3** [comment]
Thank you very much for the clarification. I have to admit that I missed it!

However, I think that `/etc/yun.conf.d/lizardfs-deps.repo` should be `/etc/yum.repos.d/lizardfs-deps.repo`.

**Comment by cypromis** [comment]
Fixed the path, thanks for the info.
