### ISSUE TITLE
Silent write errors after update of master to version 3.12.0

### ISSUE THREAD

**Issue by r5r3** [lizardfs/lizardfs#648]
Dear LizardFS Team,

recently we updates our master-server to version 3.12.0, but not all clients are updated yet. Some of the clients still run the version 3.11.3. One of our users made me now aware of a very strange behavior:

When you compile libcurl (https://curl.haxx.se/download/curl-7.57.0.tar.gz) on a machine with 3.11.3-Client (on Ubuntu 16.04), then the configure script will fail. The configure script is writing several small files, one of these files for the test of the openssl/rsa.h header. The problem is now, that this file (`confdefs.h`) is created by writing multiple lines into it depending on deferment conditions (I guess you now how configure works). When the configure script is executed on a client with 3.12.0-Client, then (among other) the following line is writting:

    #define HAVE_OPENSSL_X509_H 1

If you run the configure script on a client with 3.11.3-Client, then this line is corrupted to:

    509_H 1

Running the script on the same client, but on a different filesystem works fine, which means that it really is LizardFS-related. 

I'm now really concerned that lots of comparable errors happen that have not yet been spotted. Is the 3.12.0 master not compatible anymore with the 3.11.3 client?

**Comment by r5r3** [comment]
Additional comment: the problem can be circumvented by adding a sleep-statement to the configure script. That suggests that LizardFS has here a problem with fast consecutive append operations on one file.

**Comment by psarna** [comment]
3.12.0 master works fine with 3.11.3 client, because that's the correct upgrade order.
The reason here is trivial - you're just experiencing a bug that was there in 3.11.3, but is already fixed in 3.12.0.

I suppose that this particular one was fixed by this commit, though I'm not entirely sure: https://github.com/lizardfs/lizardfs/commit/b350a3b1318b723a7cb19916dff1ede57cfb7802 , 3.12.0 included a lot of little fixes. So, the simplest way to deal with this is to finish your upgrade procedure :)

**Comment by r5r3** [comment]
Thank you for the information!

**Comment by 4Dolio** [comment]
This makes me nervous.  That moving forward partially may cause backward compatibility problems. Are there any safe ways to verify some stable backward compatibility? Especially for clients specifically?

**Comment by Zorlin** [comment]
My interpretation is that this bug still occurs with a 3.11.3 master *and*
3.11.3 client, and is not specific to the master upgrade.

**Comment by psarna** [comment]
If we ever break any backward compatibility, it would be clearly stated in commit messages and release notes. Otherwise, the upgrade order works. It wasn't an issue with partial upgrade, it was an issue with 3.11.3. Fixed already.
