### ISSUE TITLE
Compile LizardFS on macOS

### ISSUE THREAD

**Issue by mxworm** [lizardfs/lizardfs#650]
Hi,

I tried to compile lizards on macOS 10.13.2 and osxfuse 3.7.1  with the create-osx-package.sh script. But linking of the libs is not working. Any suggestion?

Thanks Mattias 

[ 97%] Built target lizardfs
[ 99%] Built target mount_fuse
[100%] Linking CXX executable mfsmount
Undefined symbols for architecture x86_64:
  "RichACL::Ace::kWriteData", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kAppendData", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kWriteOwner", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kDeleteChild", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kSynchronize", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kReadAttributes", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kReadNamedAttrs", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kWriteRetention", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kWriteAttributes", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kWriteNamedAttrs", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kWriteRetentionHold", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kDelete", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kAddFile", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kExecute", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kReadAcl", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kReadData", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
  "RichACL::Ace::kWriteAcl", referenced from:
      __GLOBAL__sub_I_osx_acl_converter.cc in libmount.a(osx_acl_converter.cc.o)
ld: symbol(s) not found for architecture x86_64

**Comment by MShah890** [comment]
Hi I have the following error when trying to make which are similar to yours. How did you fix them ?

`[ 99%] Building CXX object src/uraft/CMakeFiles/lizardfs-uraft.dir/__/common/time_utils.cc.o
[100%] Linking CXX executable lizardfs-uraft
Undefined symbols for architecture x86_64:
  "boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) in main.cc.o
  "boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) in main.cc.o
  "boost::program_options::basic_parsed_options<char> boost::program_options::parse_config_file<char>(std::basic_istream<char, std::char_traits<char> >&, boost::program_options::options_description const&, bool)", referenced from:
      parseOptions(int, char**, uRaftController::Options&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in main.cc.o
  "boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)", referenced from:
      parseOptions(int, char**, uRaftController::Options&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in main.cc.o
  "boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int) in main.cc.o
      void boost::program_options::validate<int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long) in main.cc.o
  "boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) in main.cc.o
  "boost::program_options::arg[abi:cxx11]", referenced from:
      boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char>::name[abi:cxx11]() const in main.cc.o
      boost::program_options::typed_value<int, char>::name[abi:cxx11]() const in main.cc.o
      boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name[abi:cxx11]() const in main.cc.o
  "boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*) in main.cc.o
  "boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)", referenced from:
      boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const in main.cc.o
      void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int) in main.cc.o
  "boost::program_options::operator<<(std::basic_ostream<char, std::char_traits<char> >&, boost::program_options::options_description const&)", referenced from:
      parseOptions(int, char**, uRaftController::Options&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in main.cc.o
  "boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      boost::program_options::variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const in main.cc.o
  "boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      vtable for boost::program_options::invalid_option_value in main.cc.o
      vtable for boost::program_options::validation_error in main.cc.o
      vtable for boost::wrapexcept<boost::program_options::validation_error> in main.cc.o
      construction vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >-in-boost::wrapexcept<boost::program_options::validation_error> in main.cc.o
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> > in main.cc.o
      vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error> in main.cc.o
      vtable for boost::wrapexcept<boost::program_options::invalid_option_value> in main.cc.o
      ...
  "boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const", referenced from:
      vtable for boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char> in main.cc.o
      vtable for boost::program_options::typed_value<int, char> in main.cc.o
      vtable for boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char> in main.cc.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/uraft/lizardfs-uraft] Error 1
make[1]: *** [src/uraft/CMakeFiles/lizardfs-uraft.dir/all] Error 2
make: *** [all] Error 2`

**Comment by pbeza** [comment]
Did you manage to solve your problem?
