### ISSUE TITLE
is REPLICATION_BANDWIDTH_LIMIT_KBPS stable?

### ISSUE THREAD

**Issue by mwaeckerlin** [lizardfs/lizardfs#658]
According to the comments in #474, `REPLICATION_BANDWIDTH_LIMIT_KBPS` is defect. There is a post from @psarna, stating that there is «a bug in bandwidth limiting», which «will be fixed right away».

I am now using LizardFS 3.12.0.

Question: Is this bug fixed, yes or no? Is it safe to enable `REPLICATION_BANDWIDTH_LIMIT_KBPS`?

**Comment by psarna** [comment]
It's stable, fixed in https://github.com/lizardfs/lizardfs/commit/745c2e88afd823644f69e28b37b064c94b7e2a03

**Comment by mwaeckerlin** [comment]
It seems to work, it is now running for two hours with `REPLICATION_BANDWIDTH_LIMIT_KBPS=1000`, and I don't see any (new) problem, but response time is much better now.

**Comment by guestisp** [comment]
Are you able to check if used bandwidth is really about 1000kbps ?

**Comment by mwaeckerlin** [comment]
@guestisp:
> Are you able to check if used bandwidth is really about 1000kbps ?

How can I check this?

**Comment by guestisp** [comment]
Install `bwm-ng` or similiar and look at used bandwidth during a replication

**Comment by mwaeckerlin** [comment]
Seems to work (of course the system is running more than only replication, i.e. data read/write):
```
marc@universum:~$ bwm-ng -t 1000 -o plain -I eno1 -T avg
bwm-ng v0.6 (delay 1.000s); press 'ctrl-c' to end this
 /proc/net/dev
 -         iface                    Rx                   Tx               Total
 ==============================================================================
            eno1:        1442.25 KB/s         1442.25 KB/s         1442.25 KB/s
 ------------------------------------------------------------------------------
           total:        1442.25 KB/s         1442.25 KB/s         1442.25 KB/s
```

**Comment by mwaeckerlin** [comment]
After increasing the value to `4000`, it gous up and down, but it's mostly between 3000 and 4000:
```
 bwm-ng v0.6 (delay 1.000s); press 'ctrl-c' to end this
 /proc/net/dev
 \         iface                    Rx                   Tx               Total
 ==============================================================================
            eno1:        3677.06 KB/s         3677.06 KB/s         3677.06 KB/s
 ------------------------------------------------------------------------------
           total:        3677.06 KB/s         3677.06 KB/s         3677.06 KB/s
```

**Comment by mwaeckerlin** [comment]
And back to `1000`, bandwith goesdown to about 1000, so yes, it seems to have an influence.
