### ISSUE TITLE
dd failed to write file althoug enough space should be available

### ISSUE THREAD

**Issue by greensquirrel** [lizardfs/lizardfs#661]
Dear developers!

LizardFS is under evaluation on my machine.  I have setup some VirtualBox VMs with the same settings:
 - RAM: 1024 MiB
 - SATA hard drive for OS: 8 GiB
 - SATA hard drive for distributed file system: 8 GiB
 - OS: CentOS 7 
 - LizardFS version 3.12

Three chunkserver VMs are running. Each one has one dedicated 8 GiB hard drive
for storing chunk data.  Master runs in its separate VM.  When this setup is started,  LizardFS reports free available storage space of 12 GiB.  I don't know why 12 GiB  but  OK.

Then the following script `dd_benchmark.sh` is run from a client VM (in total 5 VMs are running):
```
#!/bin/sh

die()
{
    exit 1
}

for i in `seq 1 5`;
do
    echo "Run #$i"
    dd if=/dev/zero of=a.blob bs=1M count=3072 || die
    rm a.blob || die
done
```
The first three iterations work but the fourth iteration fails by `dd` complaing `Invalid argument`.
According to `df -h`,  only 225 MiB are free available und 2.5 GiB were in used.

What does LizardFS do in the background?  I assumed that creating a file and, thereafter,  deleting the file,  frees the occupied diskspace but this is not the case,  unfortunately.  Can someone explan?

Thank you in advance!

**Comment by DarkHaze** [comment]
Removing the file moves it to trash (where it is stored for specified
time). You can set trash time for file/directory by using command
lizardfs settrashtime.

usage:
 lizardfs settrashtime [-nhHrl] SECONDS[-|+] name [name ...]
 -n - show numbers in plain format
 -h - "human-readable" numbers using base 2 prefixes (IEC 60027)
 -H - "human-readable" numbers using base 10 prefixes (SI)
 -r - do it recursively
 -l - wait until settrashtime will finish (otherwise there is 30s timeout)
 SECONDS+ - increase trashtime to given value
 SECONDS- - decrease trashtime to given value
 SECONDS - just set trashtime to given value

**Comment by greensquirrel** [comment]
I have experienced that the default trash time is 24 hours.
How to configure LizardFS to disable the trash, i.e. setting trash time to 0 by default?

My attempt to set `mintrashtime=0`  and `maxtrashtime=0` in mfsexports.cfg for `/` in order to disable the trash only affects `lizardfs settrashtime`.  When a new file is created (e.g. via `touch`),  its trashtime is still 24 hours.  Is this a bug or a feature?

**Comment by psarna** [comment]
Trash time is a file attribute, not a mount configuration thing. Just set
it to 0 for your lizardfs root directory (and all existing directories) and
all new files created in it will inherit the value.

**Comment by greensquirrel** [comment]
Just to summarize the steps to disable the trash feature:
 
1. Set mount option `mintrashtime=0` and `maxtrashtime=0` in `mfsexports.cfg` for `/`.
2. Invoke `cd /path/to/lizardfs_mount/ && lizardfs settrashtime 0 .`

Right?

**Comment by psarna** [comment]
Yes, and step 1. is entirely optional. Use it only if you want to prevent clients from changing trash time to anything else than 0.

**Comment by greensquirrel** [comment]
Issue is solved.
