### ISSUE TITLE
Please port CGI app(s) to use Python 3

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#665]
CGI still uses Python 2.x which is due for deprecation and will not be maintained past 2020.

Please port CGI app(s) to use Python 3.

**Comment by cypromis** [comment]
Looking at the current queue I doubt that this will be happening any time soon. Someone here interested in helping with this ?

**Comment by 4Dolio** [comment]
Will get to it in about 1.8 years..  ;)  jk..
I do patch my cgi, to include a drop down navigation between different clusters, would be neat to support such tweaks via an easier simple file inclusion(s)..

**Comment by onlyjob** [comment]
Because of this issue LizardFS was already removed from Debian "testing" which means that unless this issue is fixed, LizardFS will not be included into next release of Debian "stable" because Python2 will not be available.

**Comment by Peperzastey** [comment]
I ported the CGI to Python3. Commit 10b4ab6
So I'm closing this issue.

**Comment by Peperzastey** [comment]
Thanks for letting us know about this issue with Debian repository.
I ported the CGI to Python3. Commit 10b4ab6
I'm closing this issue.

**Comment by onlyjob** [comment]
Thanks.
