### ISSUE TITLE
Package lizardfs-nfs-ganesha empty in debian stretch

### ISSUE THREAD

**Issue by epol** [lizardfs/lizardfs#678]
Hi,

I'm trying to configure ganesha NFS to use lizardfs as a FSAL, but the nfs daemon doesn't start because it can't find the file `/usr/lib/x86_64-linux-gnu/ganesha/libfsallizardfs.so`. I'm using debian 9.4 stretch with the lizardfs repos (`http://packages.lizardfs.com/debian/stretch`).

I checked the content of the package `lizardfs-nfs-ganesha` and I don't see that library:
```
# dpkg-query -L lizardfs-nfs-ganesha 
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/lizardfs-nfs-ganesha
/usr/share/doc/lizardfs-nfs-ganesha/changelog.gz
/usr/share/doc/lizardfs-nfs-ganesha/copyright
```

i don't find that file also in the package `lizardfs-lib-client` (that's the only dependence of `liblizardfs-nfs-ganesha`:
```
# dpkg-query -L lizardfs-lib-client 
/.
/usr
/usr/include
/usr/include/lizardfs
/usr/include/lizardfs/lizardfs_c_api.h
/usr/include/lizardfs/lizardfs_error_codes.h
/usr/lib
/usr/lib/liblizardfs-client-cpp.a
/usr/lib/liblizardfs-client-cpp_pic.a
/usr/lib/liblizardfs-client.a
/usr/lib/liblizardfs-client.so
/usr/lib/liblizardfs-client_pic.a
/usr/lib/liblizardfsmount_shared.so
/usr/share
/usr/share/doc
/usr/share/doc/lizardfs-lib-client
/usr/share/doc/lizardfs-lib-client/changelog.gz
/usr/share/doc/lizardfs-lib-client/copyright
```

Where do I find the nfs ganesha libraries for lizardfs?

Thank you,
Enrico

**Comment by albertdb** [comment]
Same in Ubuntu Xenial.

**Comment by foxpdll** [comment]
Аналогично!

**Comment by paladox** [comment]
Same for me.

**Comment by eleaner** [comment]
Is it still not fixed since March?
any workarounds?
