### ISSUE TITLE
Can't read data from socket: connection reset by peer

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [lizardfs/lizardfs#681]
my problem:
 ./lizardfs-admin chunks-health master_ip master_port
Error: Can't read data from socket: connection reset by peer

**Comment by 4Dolio** [comment]
Do you have a password defined in the master config?

**Comment by grosbedos** [comment]
Hi,

I have set a password yes, and i have this issue, how can i pass password argument to this command ?

Best regard

**Comment by grosbedos** [comment]
I have tried without admin password, but same error occured, any idea ?

Thanks

**Comment by 4Dolio** [comment]
I think you can pass the password through a pipe.

echo the-pass-word | lizardfs-admin dothing

**Comment by grosbedos** [comment]
Hi,

thanks for your answer, but i have remove the admin password, and i have the same error,

Any idea ?

**Comment by grosbedos** [comment]
Oh, it's not the port 9419, but 9421 ;)
It's working now !

Best regard

**Comment by grosbedos** [comment]
A last question please ;)
When i execute "lizardfs-admin list-tasks 10.5.1.15 9421", it always respond :
`No tasks are being executed`

But for example, lizardfs is changing goals, it is not a task ? What task are listed ?
When lizardfs is rebalancing, no tasks too.

Is this normal ?

Where can i see what lizardfs is doing ? In /var/log/messages, i have no entry that said lizardfs is reblancing, or changing goals..

Best regards
