### ISSUE TITLE
temporary metadata file exists

### ISSUE THREAD

**Issue by mwaeckerlin** [lizardfs/lizardfs#700]
After a crash of master, restarting the master failed with `stale lockfile exists, consider running mfsmetarestore -a to fix problems with your datadir.` After `sudo mfsmetarestore -a` restarting complains: `temporary metadata file exists, metadata directory is in dirty state`.

What now?

There are two metadata loggers up and running.

**Comment by mwaeckerlin** [comment]
Found in `/var/log/syslog`:
```
May 17 18:48:59 universum systemd[1]: Starting LizardFS master server daemon...
May 17 18:48:59 universum mfsmaster: set gid to 120
May 17 18:48:59 universum mfsmaster: set uid to 114
May 17 18:48:59 universum mfsmaster: changed working directory to: /var/lib/mfs
May 17 18:48:59 universum mfsmaster: lockfile /var/lib/lizardfs/.mfsmaster.lock created and locked
May 17 18:48:59 universum mfsmaster: sessions have been loaded
May 17 18:48:59 universum mfsmaster: initialized sessions from file /var/lib/lizardfs/sessions.mfs
May 17 18:48:59 universum mfsmaster: initialized exports from file /etc/mfs/mfsexports.cfg
May 17 18:48:59 universum mfsmaster: initialized topology from file /etc/mfs/mfstopology.cfg
May 17 18:48:59 universum mfsmaster: initialized goal definitions from file /etc/mfs/mfsgoals.cfg
May 17 18:48:59 universum systemd[1]: lizardfs-master.service: Control process exited, code=exited status=2
May 17 18:48:59 universum mfsmaster: stale lockfile exists, consider running `mfsmetarestore -a' to fix problems with your datadir.
May 17 18:48:59 universum systemd[1]: Failed to start LizardFS master server daemon.
May 17 18:48:59 universum systemd[1]: lizardfs-master.service: Unit entered failed state.
May 17 18:48:59 universum systemd[1]: lizardfs-master.service: Failed with result 'exit-code'.
```

Run:
```
sudo rm /var/lib/lizardfs/.mfsmaster.lock
```

Still get:
```
May 17 18:51:08 universum systemd[1]: Starting LizardFS master server daemon...
May 17 18:51:08 universum mfsmaster: set gid to 120
May 17 18:51:08 universum mfsmaster: set uid to 114
May 17 18:51:08 universum mfsmaster: changed working directory to: /var/lib/mfs
May 17 18:51:08 universum mfsmaster: lockfile /var/lib/lizardfs/.mfsmaster.lock created and locked
May 17 18:51:08 universum mfsmaster: sessions have been loaded
May 17 18:51:08 universum mfsmaster: initialized sessions from file /var/lib/lizardfs/sessions.mfs
May 17 18:51:08 universum mfsmaster: initialized exports from file /etc/mfs/mfsexports.cfg
May 17 18:51:08 universum mfsmaster: initialized topology from file /etc/mfs/mfstopology.cfg
May 17 18:51:08 universum mfsmaster: initialized goal definitions from file /etc/mfs/mfsgoals.cfg
May 17 18:51:08 universum mfsmaster: stale lockfile exists, consider running `mfsmetarestore -a' to fix problems with your datadir.
May 17 18:51:08 universum systemd[1]: lizardfs-master.service: Control process exited, code=exited status=2
May 17 18:51:08 universum systemd[1]: Failed to start LizardFS master server daemon.
May 17 18:51:08 universum systemd[1]: lizardfs-master.service: Unit entered failed state.
May 17 18:51:08 universum systemd[1]: lizardfs-master.service: Failed with result 'exit-code'.
```

Running again:
```
sudo mfsmetarestore -a
```

Again:
```
May 17 18:57:17 universum systemd[1]: Starting LizardFS master server daemon...
May 17 18:57:17 universum mfsmaster: set gid to 120
May 17 18:57:17 universum mfsmaster: set uid to 114
May 17 18:57:17 universum mfsmaster: changed working directory to: /var/lib/mfs
May 17 18:57:17 universum mfsmaster: lockfile /var/lib/lizardfs/.mfsmaster.lock created and locked
May 17 18:57:17 universum mfsmaster: sessions have been loaded
May 17 18:57:17 universum mfsmaster: initialized sessions from file /var/lib/lizardfs/sessions.mfs
May 17 18:57:17 universum mfsmaster: initialized exports from file /etc/mfs/mfsexports.cfg
May 17 18:57:17 universum mfsmaster: initialized topology from file /etc/mfs/mfstopology.cfg
May 17 18:57:17 universum mfsmaster: initialized goal definitions from file /etc/mfs/mfsgoals.cfg
May 17 18:57:17 universum mfsmaster: temporary metadata file exists, metadata directory is in dirty state
May 17 18:57:17 universum systemd[1]: lizardfs-master.service: Control process exited, code=exited status=2
May 17 18:57:17 universum systemd[1]: Failed to start LizardFS master server daemon.
May 17 18:57:17 universum systemd[1]: lizardfs-master.service: Unit entered failed state.
May 17 18:57:17 universum systemd[1]: lizardfs-master.service: Failed with result 'exit-code'.
```

…?

Need help!

**Comment by guestisp** [comment]
Ensure that master process isn't restarted automatically by systemd before deleting the lockfile
Stop it and keep it stopped, then clear the lockfile, , run mfsmetarestore and start master again

**Comment by guestisp** [comment]
Don't you have any shadow running? Because if you are restoring from dump files, any changes done after dump are lost

**Comment by mwaeckerlin** [comment]
@guestisp
> Ensure that master process isn't restarted automatically by systemd before deleting the lockfile
Stop it and keep it stopped, then clear the lockfile, , run mfsmetarestore and start master again

 That's exactly, what I did several times, see above. With no success.

> Don't you have any shadow running?

Two Metalogger, no Shadow.

**Comment by mwaeckerlin** [comment]
How can I fix this:
```
mfsmaster: temporary metadata file exists, metadata directory is in dirty state
```

Nees Help!?!?!?

**Comment by mwaeckerlin** [comment]
Can start restoration using the metaloggers?

**Comment by mwaeckerlin** [comment]
The messages toggle somehow between:
```
temporary metadata file exists, metadata directory is in dirty state
```
and
```
stale lockfile exists, consider running `mfsmetarestore -a' to fix problems with your datadir.
```

…?

**Comment by guestisp** [comment]
> Two Metalogger, no Shadow.
A recipe for a disaster and data-loss. Metalogger are not synced in realtime. Is something like a scheduled "mysqldump" for MySQL. Everything that is changed between the last dump and the crash, is lost.

> mfsmaster: temporary metadata file exists, metadata directory is in dirty state

this is triggered by the existance of `metadata.mfs.tmp`. Did you remove it ?

**Comment by mwaeckerlin** [comment]
```
$ lizardfs-admin info universum 9421
LizardFS v3.12.0
Memory usage:   15GiB
Total space:    89TiB
Available space:        27TiB
Trash space:    219TiB
Trash files:    16333386
Reserved space: 0B
Reserved files: 0
FS objects:     50022424
Directories:    1700476
Files:  47088074
Chunks: 8319024
Chunk copies:   16637889
Regular copies (deprecated):    16637889
```

**Comment by mwaeckerlin** [comment]
BTW, @guestip, why is `Trash space` so exorbitant high? What does it mean and how do I clean-up?

BTW: Mounting metadata shows empty trash…

**Comment by mwaeckerlin** [comment]
It seems, that there are only undergoal files, but no defective:
```
$ lizardfs-admin list-defective-files universum 9421 | wc -l
1001
$ lizardfs-admin list-defective-files universum 9421 | grep -v undergoal | wc -l
0
```

What other tests should I run?

**Comment by mwaeckerlin** [comment]
```
$ lizardfs-admin chunks-health universum 9421 
Chunks availability state:
        Goal    Safe    Unsafe  Lost
        workers 8318938 -       76

Chunks replication state:
        Goal    0       1       2       3       4       5       6       7   89       10+
        workers 8318938 -       76      -       -       -       -       -   --       -

Chunks deletion state:
        Goal    0       1       2       3       4       5       6       7   89       10+
        workers 8319011 3       -       -       -       -       -       -   --       -
```

**Comment by 4Dolio** [comment]
Metaloggers so sync in real time. The record changelog files between each full sync. Should not lose anything.

**Comment by mwaeckerlin** [comment]
@4Dolio, do I need to do something to restore from metaloggers or does lizardfs automatically detect it state and start the necessary steps?

So it is enough to have two metaloggers, or to I need a shadow master?

**Comment by guestisp** [comment]
> So it is enough to have two metaloggers, or to I need a shadow master?

With a shadow, you don't have to restore anything, just reload the shadow process after changing the personality in config file and everything would be up and running in almost zero time.

With metaloggers you have to restore from disk, on huge cluster, this could take hours.

**Comment by mwaeckerlin** [comment]
Since my server is up again, I can now close this ticket. Please feel free to add more information regarding mettalogger, restoring and suggested setups.

Thank you, @guestisp for saving my ass and @4Dolio for your clarification.

**Comment by guestisp** [comment]
@mwaeckerlin I strongly suggest you to add at least one shadow server.

**Comment by mwaeckerlin** [comment]
@guestisp, I have only servers with much less memory and cpu ressources.

I suppose, a shadow master consumes  much less memory and cpu ressources compared to the active master, right?

**Comment by mwaeckerlin** [comment]
BTW: Perhaps the root cause of the problem is, that my trash is not cleaned up correctly? → #702

**Comment by guestisp** [comment]
I think you should read official docs at least one time.
Yes, shadow is an exact copy and as so, it keep everything in RAM, ready to be promoted to master.
Without keeping everything in ram, there wuould be no differences between shadows and metalogger.

**Comment by 4Dolio** [comment]
The metadatarestore command considers the newest bin metadata and the two most recent changelogs when you use the -a (automatic) option.  It revalidates the bin and the replays the older changelog(already in the bin) then it replays the newest changelog to catch up after the bin.  You get a new clean metadata bin with zero lost revisions.

**Comment by 4Dolio** [comment]
Shadows are most useful when using the personality ha-managed. In that mode a shadow can be sent a command to promote itself, instantly becoming a master.  But shadows need equal Ram, and you need to move the masters floating IP address. And you should quick stop the old master first, quick stop skips the netadata bin write to disk when it exits, so the shadow does not need to wait for the master to write metadata to disk before the rest of the promotion process can proceed.  I am not sure if you can do a running promotion without the ha-managed personality.
