### ISSUE TITLE
Include FUSE3 as apt packages

### ISSUE THREAD

**Issue by paladox** [lizardfs/lizardfs#718]
Hi, is it possible to upload the deb for libfuse3 please?

**Comment by paladox** [comment]
Hmm, i meant as a apt repo to apt install

**Comment by Blackpaw** [comment]
They are .deb packages and can be installed with "dpkg -i"

**Comment by pbeza** [comment]
`libfuse3` is present both in [Ubuntu Disco (19.04)](https://packages.ubuntu.com/search?keywords=libfuse3&searchon=names&suite=all&section=all) and in [Debian Sid](https://packages.debian.org/sid/libfuse3-3).

**Comment by jkiebzak** [comment]
and Debian Buster (testing): https://packages.debian.org/buster/libfuse3-3

>
