### ISSUE TITLE
Puppet module for lizardfs

### ISSUE THREAD

**Issue by lamvak** [lizardfs/lizardfs#72]
Related link: https://github.com/KrisBuytaert/vagrant-moosefs

**Comment by Asher256** [comment]
+1

**Comment by blink69** [comment]
:) I started to do that a long time ago, I will try to push what I have. Maybe someone will finish that for me :)

**Comment by Asher256** [comment]
Share it with us blink ;-) . I'm sure a lot of people would be interested to contribute and improve it!

**Comment by Asher256** [comment]
I developed a new Puppet module to install and configure LizardFS (Master, Client, Chunkserver and Metalogger).

The Github repository of puppet-lizardfs: https://github.com/Asher256/puppet-lizardfs

I encourage you guys to contribute!
Asher256

**Comment by pkali** [comment]
Thanks a bunch! Link to the module is in our docs now https://github.com/lizardfs/documentation/blob/master/source/ressources.rst so closing.
