### ISSUE TITLE
"lizardfs getgoal -r" results incorrect - serialization bug

### ISSUE THREAD

**Issue by mrh42** [lizardfs/lizardfs#723]
The files/directories numbers reported "getgoal -r" by are swapped.  For example:
 files with goal        x :          2
 directories with goal  x :       1226

I believe bug is due matocl.h defining directories,files where as matoclserv.cc sends files,directories.

matocl.h:
LIZARDFS_DEFINE_SERIALIZABLE_CLASS(FuseGetGoalStats,
	        std::string, goalName,
                uint32_t, directories,
		uint32_t, files);

matoclserv.cc:
                        serializeMooseFsPacket(reply, MATOCL_FUSE_GETGOAL,
                                        msgid,
                                        uint8_t(mooseFsReplyFiles.size()),
                                        uint8_t(mooseFsReplyDirectories.size()),
                                        mooseFsReplyFiles,
                                        mooseFsReplyDirectories);

**Comment by pbeza** [comment]
I can confirm the problem. [Bugfix][1] will be probably merged very soon.

[1]: http://cr.skytechnology.pl:8081/#/c/3340/

**Comment by szycha76** [comment]
Can we cherry-pick 1218dfc into 3.12 branch and release it as 3.12.1, before we are ready with 3.13.0? #723 is a most notorious bug in (otherwise nearly perfect :-) ) 3.12.0 IMHO.
