### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [lizardfs/lizardfs#726]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [stats_get_subnode](https://github.com/lizardfs/lizardfs/blob/c181a0194047df92d690f2681d71bcccd04ba694/src/mount/stats.cc#L53)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [fs_newfileinfo](https://github.com/lizardfs/lizardfs/blob/a00615107d88795c6cf03aac2b6ef2727cdf25e0/src/mount/lizard_client.cc#L1635)

**Comment by pbeza** [comment]
Thanks for report. [Fix](http://cr.skytechnology.pl:8081/#/c/3339/) will be merged soon.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by pbeza** [comment]
Thanks for suggestions. We will try to improve static and dynamic code analysis but for now fixing bugs is more important. See also [this post][1].

[1]: https://github.com/lizardfs/lizardfs/commit/59988c67755dd03488c89be70fdf5c086e8cb2f2#commitcomment-33703300

**Comment by elfring** [comment]
I am trying to increase the software development attention also for the error category of incomplete exception handling (for years).
How many bugs are still waiting for a corresponding fix here?

**Comment by pbeza** [comment]
Probably a lot. :-P Sorry, I don't have statistics because not all bugs have been labelled as `Bug` (I set this label only after I verify it). Currently one of the bugs I try to fix is [ACL being not honored][1] (#816). Next bugs on the TODO list are #748 and #784.

[1]: https://github.com/lizardfs/lizardfs/issues/816
