### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [lizardfs/lizardfs#727]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “WriteCacheBlock”](https://github.com/lizardfs/lizardfs/blob/7110f5cb2a98b763e72e70148eace993cbd8af4f/src/mount/write_cache_block.cc#L60 "Update candidate: Destructor for WriteCacheBlock").

**Comment by pbeza** [comment]
Thanks for your report. [Fix][1] will be merged soon.

[1]: http://cr.skytechnology.pl:8081/#/c/3342/

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/lizardfs/lizardfs/commit/f7a831c4ff3e31232867d549e332768e59216dea#diff-e721d1b77cbe377b340baf38985eea59L60 "Removed redundant check.").
