### ISSUE TITLE
Purge missing chunks?

### ISSUE THREAD

**Issue by dragon2611** [lizardfs/lizardfs#729]
Was messing around with LizardFS on a test cluster, I have 32 chunks which are missing and will never be coming back because I deliberately destroyed them on the chunkservers. ( rm -rf /mfs-chunk/* ) - It was a test file (1GB of junk data) 

What I can't seem to find in the documentation is anyway to tell the master these chunks are gone for good and not to worry about them.

I presume there is some way to do this for cases where there is only one copy of the chunks and the chunkserver it's on goes away?

**Comment by njhurst** [comment]
You could delete the files associated with them I think?  They are usually listed in the info tab in the web interface.

**Comment by dragon2611** [comment]
They were already deleted (showing as in the trash)

**Comment by njhurst** [comment]
They still exist in the trash until the garbage truck comes (i think 24 hours?).  You can mount the metadata and explicitly garbage collect them yourself if it matters.

**Comment by dragon2611** [comment]
Thanks, I suspect I'll just end up deleting the entire test cluster as given it was built on very low end VM's I can't really think of much of a use for it.

It was mostly to have a quick play with lizardfs, they were in 2 different DC's (fairly close) and linked via zerotier.

**Comment by onlyjob** [comment]
Since there is no actionable task here for maintainers to address, I'm closing this bug.  
Please let us know if it should be re-opened.
