### ISSUE TITLE
726dc9 appears to break autofs mounts

### ISSUE THREAD

**Issue by eriklindahl** [lizardfs/lizardfs#731]
The redesigned initialization functions change seems to have done something bad with autofs mounts.

Autofs entries like the following worked before this change:

/mnt/lizardfs -fstype=fuse,mfsmaster=xxx.yyy.zzz.www :mfsmount

... but after 726dc9a, it just hangs. Normal mounts still work fine on the command line.

**Comment by eriklindahl** [comment]
This appears to have been due to moving the duplication of the file descriptors; with change in the referenced pull request it works with either mfsmount or mfsmount3 in autofs.

**Comment by onlyjob** [comment]
3.13.0~rc1 definitely introduced a regression: even without _autofs_, _mfsmount_ fails or hangs so I can only mount after several tries... #732 fixes the problem.
