### ISSUE TITLE
Setting trash time to 0 is still having trash added

### ISSUE THREAD

**Issue by paladox** [lizardfs/lizardfs#736]
Hi, when i set the trash time to 0, it's still adding the trash. How can i disable this please? As i doin't really want to clean this up all the time to save space.

**Comment by mrh42** [comment]
Interesting, this works for me.  I set the trashtime to 0 on the top-level directory (so all files inherit this setting) and nothing has ever been saved in the trash.  Are you doing something different?

**Comment by paladox** [comment]
when you say top-level directory what do you mean? I created this /mnt/mediawiki-static and then mounted using mfsmount. I then ran the lizardfs command to set trash to 0 on there, but am still seeing trash fill up.

**Comment by mrh42** [comment]
If you have existing files, they still may be set to trashtime > 0.  Each file can have its own trash policy.  If you want trashtime to be 0 for everything, use "lizardfs settrashtime -r 0"

**Comment by paladox** [comment]
Oh thanks, didn't realise there was -r option.
