### ISSUE TITLE
2 missing chunks after restarting chunkserver and master server

### ISSUE THREAD

**Issue by Pneumaticat** [lizardfs/lizardfs#740]
Hi,

Currently trying out LizardFS with an `ec(2,1)` goal in the middle of rebalancing. I have a 9.7 TB array with ~3 TB used.

After stopping file transfer and unmounting, I stopped a chunkserver and then lizardfs-master. But after bringing them back up, I found I had 2 missing chunks:

```
Chunks availability state:
        Goal    Safe    Unsafe  Lost
        ec_2_1  198315  206129  2

Chunks replication state:
        Goal    0       1       2       3       4       5       6       7       8       9       10+                                                        
        ec_2_1  175299  176838  25875   26434   -       -       -       -       -       -       -                                                          

Chunks deletion state:
        Goal    0       1       2       3       4       5       6       7       8       9       10+                                                        
        ec_2_1  329089  75321   36      -       -       -       -       -       -       -       -
```

Is this typical? Will it go away? I've only had the cluster back up for a few (10s) of minutes now. Nothing has showed up on the filesystem check info box on the CGI server yet.

**Comment by Pneumaticat** [comment]
Ah, the check info found it:

```
currently unavailable chunk 146715 (inode: 155412 ; index: 0)
* currently unavailable file 155412: Kevin/Computing/Android/maguro/postmarketOS/uboot-tuna/board/spc1920/hpi.h
currently unavailable chunk 195856 (inode: 210477 ; index: 0)
* currently unavailable file 210477: Kevin/Computing/Games/Steam Library/steamapps/shadercache/252950/mesa/08/fd39d6b4eea6656b624c5dcfa42fb9f23fafe6
unavailable chunks: 2
unavailable files: 2
```

I can probably just delete those; they aren't very important to me.

Is this normal just due to having unsafe-replicated ec2,1 chunks? If I got to full replication, would this still happen?

**Comment by njhurst** [comment]
How many chunkservers do you have?

**Comment by Pneumaticat** [comment]
4 chunkservers—3 are on one PC, though, each hosting one disk.

**Comment by Pneumaticat** [comment]
Also using LizardFS 3.11.3, not latest 3.12—perhaps I should try an upgrade.

**Comment by njhurst** [comment]
That should be enough.  I have also lost chunks when regoaling then disconnecting some years back, perhaps there is a safety gap in the regoaling algorithm.

**Comment by Pneumaticat** [comment]
I see. I guess 2 chunks isn't so bad, and hopefully once it's regoaled, it'll be stable.

I'll also try upgrading to 3.12 (after regoaling) and see if the issue ever comes up again.

**Comment by Pneumaticat** [comment]
Yes, I was going from {1, 0} (one copy only) to {2, 1} (error correcting, 2 data, 1 parity).

It's definitely not ideal; if a developer or other user has a potential explanation, that would be great.

**Comment by njhurst** [comment]
In that case I think we just chalk it up to bad luck :(

If you are at {1,0} you pretty much can be certain of losing some data on any file system - a single bit flip in ram is all it takes, at which point the checksum fails and the chunk/file is lost (if you go looking at old files, say jpegs, stored without FEC, you'll find random corruptions soon enough).  That's why forward error correction is awesome.  I guess we can close this?

**Comment by Pneumaticat** [comment]
I guess so. It hasn't happened again yet on a few more master restarts on 3.12, either.
