### ISSUE TITLE
Can't add LizardFS repo on ARM Ubuntu 18.04

### ISSUE THREAD

**Issue by Zorlin** [lizardfs/lizardfs#751]
root@blinky:~# apt update
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:2 http://deb.odroid.in/5422-s bionic InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Ign:4 http://packages.lizardfs.com/ubuntu/bionic bionic InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Ign:6 http://packages.lizardfs.com/ubuntubionic bionic InRelease
Hit:7 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Err:8 http://packages.lizardfs.com/ubuntu/bionic bionic Release
  404  Not Found [IP: 185.16.37.20 80]
Err:9 http://packages.lizardfs.com/ubuntubionic bionic Release
  404  Not Found [IP: 185.16.37.20 80]
Reading package lists... Done
E: The repository 'http://packages.lizardfs.com/ubuntu/bionic bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://packages.lizardfs.com/ubuntubionic bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by anasasa** [comment]
Looks like http://packages.lizardfs.com/ubuntu/bionic url is wrong, there is no bionic folder there.

Also in manual there is error in command
echo "deb-src http://packages.lizardfs.com/ubuntu$(lsb_release -sc) $(lsb_release -sc) main" >> /etc/apt/sources.list.d/lizardfs.list

Missing / after ubuntu

**Comment by dsimic** [comment]
Putting this in the /etc/apt/sources.list.d/lizardfs.list file worked for me:

deb http://packages.lizardfs.com/ubuntu/xenial xenial main
deb-src http://packages.lizardfs.com/ubuntu/xenial xenial main

And it all seemed to install fine on bionic / ubuntu 18.04. Whether it will actually work remains to be seen....

**Comment by pbeza** [comment]
@dsimic Did it work?
