### ISSUE TITLE
poor man's cloud backup with lizard - terrible performance

### ISSUE THREAD

**Issue by eleaner** [lizardfs/lizardfs#760]
Hi,

I am using precompiled lizardfs 3.13.0.rc1 
I have 11 chunk servers each about 1TB disk space. Ten of them are VPS in different datacenters, 1GB ram mostly on Ubuntu 16.04 few on 14.04, one is a physical machine at my home (and apparently has the worst performance of all of them) although has 8GB ram it also does some backup tasks.
Each chunk server is running a metalogger too.
the master server is another VPS 2GB ram. I know it's too little but it should fit a few GB for testing.
my replication goal is EC 10_4

The lizardfs is mounted on the home chunkserver with fuse.
I tried to push some data to the locally mounted mfs with rclone, with multiple transfers as well as with single.
The speeds start with few around 4 MByte/s, It's not much but plenty for my needs.
Unfortunately in a few minutes always goes dow to around 300kBytes and this is very bad.

I am trying to read the information in the cgi frontend to find the bottleneck(s) but without luck

Any suggestions? or is it completely caused by the setup I've chosen?
By comparison, tahoe-lafs that is regarded as slow, in the same setup achieves around 1MByte sustainable transfers (with multiple threads)

**Comment by njhurst** [comment]
btw, 11 < 10+4, so you'll never achieve your replication goal.  perhaps 7,3 would be a better choice.  I easily saturate my 1Gb/s network with a similar setup, so I don't know what you're missing.  What's the machine to machine latency like?  perhaps you're waiting on network too much, can you do more file ops in parallel?

**Comment by eleaner** [comment]
Thank you Nathan
you are right, I have to adjust the goal. Regarding the machine, to machine latency, I think you might be right. Any suggestion how can I measure it?

**Comment by eleaner** [comment]
I found this type of error in my logs

`09/07/18 23:50:53.741 [warning] [23286:23293] : write file error, inode: 268, index: 0 - Chunkserver communication timed out (try counter: 29)`

is there a way I can learn which of the chink servers is failing?

**Comment by eleaner** [comment]
@njhurst thank you so much.
looks like latency between VPS in US and EU was too much to handle and ended up with 30 failed retries too often. Add to it the unpredicted drops of performance on some (cheap) VPS and you get the picture.
I moved all my VPS to EU and completely dropped the unreliable ones. In a longer term, I am moving to secondhand dedicated servers too.
And I am in love with lizardfs. I am closing the thread.
