### ISSUE TITLE
please help, how to fix "currently unavailable reserved file" 

### ISSUE THREAD

**Issue by eleaner** [lizardfs/lizardfs#765]
Hi,

Since a few days I see 
+ currently unavailable reserved file 150: xxxx

The file does not exist, so chunks should disappear in 24h but it's more like +48 now.
When I tried to remove it through META mount my root user was greeted with not enough privileges.

any ideas?

**Comment by eleaner** [comment]
@onlyjob 
Does not seem to work
SESSION_SUSTAIN_TIME is commented out in my config file 
it should mean 24h (Default: 86400) 

my master server was restarted 3 days ago
>    Loaded: loaded (/lib/systemd/system/lizardfs-master.service; enabled; vendor preset: enabled)
>    Active: active (running) since Tue 2018-09-11 23:20:16 CEST; 3 days ago

the problem still remains

**Comment by njhurst** [comment]
Why does it matter?  It's just one file.

**Comment by eleaner** [comment]
bothers me. I just started playing with lizzardfs and things happening without resolution or explanation are eating my confidence in the product.

**Comment by matthiaz** [comment]
You could also lower SESSION_SUSTAIN_TIME to something like 60seconds, and then reload lizardfs

Should disappear rather quickly. If it doesn't something is holding a lock on those files, so lizard can't remove it. I had it happen with a windows machine a couple months back (rebooting windows fixed it).
