### ISSUE TITLE
One missing chunk - which file does it belong to?

### ISSUE THREAD

**Issue by 19wolf** [lizardfs/lizardfs#766]
From `/var/log/syslog`:

```
mfsmaster[49093]: chunk 00000000000783bc has not enough valid parts (1) consider repairing it manually
```

How do I figure out which file it belongs to?

**Comment by onlyjob** [comment]
"Info" tab in CGI contains partial list of unavailable files, updated once in several hours.
You can get the same information from the following command:

    lizardfs-admin list-defective-files --porcelain --unavailable  mfsmaster 9421

**Comment by 19wolf** [comment]
Okay. It didn't show up in CGI until this morning (about 16 hours later). Can I change how often that is updated? Also, now that I found my missing chunk, can I just delete associated file?

**Comment by onlyjob** [comment]
I _think_ chunks check loop is not configurable...
What could possibly stop you from deleting a file?
Repair may be possible with `lizardfs filerepair`...

**Comment by 19wolf** [comment]
`lizardfs filerepair` just erased the chunk. Is this normal?

**Comment by onlyjob** [comment]
Yes it is. Sometimes it reverts the chunk to its previous version, if it is still available.
