### ISSUE TITLE
Number of missing chunks is climbing steadily after chunkserver restart

### ISSUE THREAD

**Issue by 19wolf** [lizardfs/lizardfs#770]
goal | allchunks | safechunks | endangeredchunks | missingchunks
-- | -- | -- | -- | --
single | 375653 | 2 | 374808 | 843
dup | 134328 | 133422 | 885 | 21
xor3 | 73230 | 70826 | 1614 | 790

As of just now, and all the missing chunk numbers are up from even 5 minutes ago.
All I did was run `mfschunkserver -c /etc/mfschunkserver-hdd-1.cfg` which restarted the process. Additionally, two of my drives are full while a new is at 40%. The full drives seem to continue to stay full while the new drive continues to increase in size. Until just now, `lizardfs-admin list-defective-files --unavailable` returned nothing, despite missing chunks in cgi. The `mfschunkserver` process tied to mfschunkserver-hdd-1.cfg is also at 200% cpu usage, and not otherwise moving.

I'm not sure exactly what my question is, but I'm losing data and I'd like to not.

**Comment by onlyjob** [comment]
Stay calm and work _slower_.  
Stop all your chunkservers on that machine (`killall mfschunkserver` or through systemd services. Of course you should be using systemd services to control chunkservers).  
Make sure to avoid #730; double check config files and services to make sure that there are no conflicts/overlaps between chunkservers (directories in `mfshdd.cfg`).  
Start chunkservers again - if chunks are still on your HDDs they will be found and registered with master. It is possible that nothing has been lost.

As diagnostics, check your _logs_ and "number of chunks deletions per minute" graph under "Server Charts" in CGI.

I hope that helps.

**Comment by 19wolf** [comment]
> Which repo did you install from? the lizardfs ones assumer user "mfs", the debian ones user "lizardfs"

I installed `3.12.0` from packages.lizardfs.com on Ubuntu, then I ran `apt upgrade` and it installed `3.12.0+dfsg-1`, and some of my services now run as user lizardfs instead of user mfs as before, and are looking for config files in `/var/lib/lizardfs` and `/etc/lizardfs` instead of `/etc/mfs/` and `/var/lib/mfs`

...Do I need to run `chown -R lizardfs:lizardfs` on all of my chunk drives?

**Comment by Blackpaw** [comment]
Yup, that should do it. Stop the services, change the ownership, then start the services.

**Comment by 19wolf** [comment]
Seems to be working. Now I have 1 missing chunk but `lizardfs-admin list-defective-files --unavailable  192.168.1.1 9421` lists 1001 files.

**Comment by Blackpaw** [comment]
I think it takes it a while to update that list, its not immediate. the master scans and rebuilds in the background.
