### ISSUE TITLE
Marked for Removal stopped at 50GB

### ISSUE THREAD

**Issue by 19wolf** [lizardfs/lizardfs#772]
I am trying to remove a 3TB drive that was 80%+ full, and after some hours/days, it's down to 54GB left, but for the last 24 hours, it hasn't gotten any lower. It still shows as marked for removal but obviously I can't remove it if it still has data on it. I'd really like to remove it as it's an external drive I used while replacing an internal drive.

**Comment by njhurst** [comment]
I've never tried this, but you might be able to just rsync the data onto another chunkserver and then remove it.

**Comment by onlyjob** [comment]
Most likely you do not have enough chunkservers to send data to.
Remember that chunkserver can not move data between its disks: marking HDD for removal sends its data to other chunkservers.

If you remove the disk then undergoal chunks will be re-created. It might be best to keep HDD around until there are no undergoal chunks left.

I do not recommend to use `rsync`. Let chunkservers to take care of data.

**Comment by 19wolf** [comment]
CGI does not show any undergoal chunks, and I'm moving from 5 chunkservers to 4 (each disk being one chunkserver in my case), and the only goals I use are `_`, `_ _`, and `$xor3`, so 4 chunkservers should be enough, in theory?

**Comment by 19wolf** [comment]
I've noticed there are 769 chunks left on the drive I'm removing, 769 chunks xor3 with one copy to replicate and 769 chunks xor3 with 2 copies to delete. I doubt that's a coincidence.

|Chunks which need replication|goal|0 copiesto replicate|1 copyto replicate|2 copiesto replicate|3 copiesto replicate|4 copiesto replicate|5 copiesto replicate|6 copiesto replicate|7 copiesto replicate|8 copiesto replicate|9 copiesto replicate|10+ copiesto replicate|single|dup|xor3|all|597793|771|-|-|-|-|-|-|-|-|-|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|390870|2|-|-|-|-|-|-|-|-|-|
|134462|-|-|-|-|-|-|-|-|-|-|
|72461|769|-|-|-|-|-|-|-|-|-|

|Chunks which need deletion|goal|0 copiesto delete|1 copyto delete|2 copiesto delete|3 copiesto delete|4 copiesto delete|5 copiesto delete|6 copiesto delete|7 copiesto delete|8 copiesto delete|9 copiesto delete|10+ copiesto delete|single|dup|xor3|all|597795|-|769|-|-|-|-|-|-|-|-|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|390872|-|-|-|-|-|-|-|-|-|-|
|134462|-|-|-|-|-|-|-|-|-|-|
|72461|-|769|-|-|-|-|-|-|-|-|


|Disks|#|info|I/O stats last min (switch to hour,day)|space|transfer|max time (switch to avg)|# of ops|IP path (switch to name)|chunks|last error|status|read|write|read|write|fsync|read|write|fsync|used|total|used (%)|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|1|192.168.1.1:9500:/mnt/hdd-1/|356984|2018-09-20 11:03|ok|162 MiB/s|1.2 MiB/s|76210 us|85895 us|749927 us|2238|1819|1077|5.4 TiB|7.3 TiB|73.67|
|2|192.168.1.1:9501:/mnt/hdd-2/|267541|no errors|ok|41 MiB/s|1.3 MiB/s|12452 us|75 us|126359 us|21|37|25|2.9 TiB|3.6 TiB|79.82|
|3|192.168.1.1:9502:/mnt/hdd-3/|167334|2018-09-20 15:22|ok|1.4 GiB/s|0 B/s|88 us|0 us|0 us|396|0|0|2.9 TiB|3.6 TiB|80.50|
|4|192.168.1.1:9503:/mnt/hdd-4/|160858|no errors|ok|1.3 GiB/s|954 KiB/s|96 us|36520 us|183542 us|116|83|77|2.9 TiB|3.6 TiB|79.82|
|5|192.168.1.1:9504:/mnt/usb-back-top-left/|769|no errors|marked for removal|-|-|-|-|-|-|-|-|54 GiB|2.7 TiB|1.93|

**Comment by 19wolf** [comment]
Update: It hasn't changed.

**Comment by 19wolf** [comment]
Update: After several more days, I removed the stuck drive, nothing happened, then I added a new temporary drive and the problem resolved. I then removed the new drive without issue.
