### ISSUE TITLE
nfs-ganesha - installed but cannot find

### ISSUE THREAD

**Issue by eleaner** [lizardfs/lizardfs#778]
Hi,

I installed precompiled packages 3.13.-rc1 for Ubuntu 16.04 
lizardfs works perfectly so does fuse client

Now I wanted to try nfs-anesha and my problem is that whichever tutorial I follow I cannot even find The service to enable. Forget the actual conf file to adjust.

Any help?

**Comment by hoobadank** [comment]
I think the packages for Ubuntu and Debian are missing;
libfsallizardfs.so
libfsallizardfs.so.4
libfsallizardfs.so.4.2.0

The precompiled CentOS packages have those files and allow for nfs-ganesha to run

**Comment by eleaner** [comment]
thank you
