### ISSUE TITLE
"lizardfs makesnapshot" times out on large file count

### ISSUE THREAD

**Issue by BloodBlight** [lizardfs/lizardfs#786]
When creating a snapshot of a very large directory (in our case, about 2 million files), the command will timeout, but complete.

So you will get this result:

```
lizardfs makesnapshot SomeFolder SomeFolder-Snap
Creating snapshot: SomeFolder -> /LizardFS/SomeFolder-Snap ...
Can't read data from socket: timeout
```

However, if you watch the file counts using lizardfs dirinfo, the command is continuing to work and does eventually complete.

Additionally, when this first happened I entered the directory before it was complete and "broke" something about it.

When I tried to move the "broken" folder into another folder that was marked for deletion later I got:

```
mv SomeFolder-Snap Delete/
mv: cannot move 'SomeFolder-Snap' to 'Delete/SomeFolder-Snap': Directory not empty
```

That one was odd...  It did let me delete the folder though.  I am not sure if the snap command was still running at that point, but I don't think so.

**Comment by onlyjob** [comment]
Unfortunately many LizardFS commands are [unreliable](https://github.com/lizardfs/lizardfs/issues/714#issuecomment-424710116) by default, unless `-l` option is used.

To avoid timeout one must use `-l` option as suggested by command mini-help:
~~~~
$ lizardfs makesnapshot
make snapshot (lazy copy)

usage:
 lizardfs makesnapshot [-ofl] src [src ...] dst
 -o,-f - allow to overwrite existing objects
 -l - wait until snapshot will finish (otherwise there is 60s timeout)
~~~~

**Comment by BloodBlight** [comment]
Ah, alright!  I can work with that.  :+1:   Just an FYI, that only comes up if you run "lizardfs makesnapshot", it isn't in the man.

> LIZARDFS-MAKESNAPSH(1)                                                                                                                            
> 
> NAME
>        lizardfs-makesnapshot - make lazy copies
> 
> SYNOPSIS
>        lizardfs makesnapshot [-o] [-f] SOURCE... DESTINATION
> 
> DESCRIPTION
>        makesnapshot makes a "real" snapshot (lazy copy, like in case of appendchunks) of some object(s) or subtree (similarly to cp -r command). It’s atomic with
>        respect to each SOURCE argument separately. If DESTINATION points to already existing file, error will be reported unless -f (force) or it’s alias -o (overwrite)
>        option is given.
