### ISSUE TITLE
how to compile 3.13 on ARM? at least chunkserver

### ISSUE THREAD

**Issue by eleaner** [lizardfs/lizardfs#790]
hi,

is there a tutorial for a new version of lizardfs to compile it on ARM?
Technically I would need only a chunkserver, but by default it tries to build all and requires fuse3 too and makes it even more complex

**Comment by dragon2611** [comment]
I managed to compile 3.12 for a ARM based synology, not sure if this will help any

https://github.com/lizardfs/lizardfs/issues/737

**Comment by pbeza** [comment]
FUSE3 is not required. It is only used only [if][1] CMake finds it. If it was not found, `mfsmount` executable is created. If it was found, `mfsmount` and `mfsmount3` executables are created.

You can build only `chunkserver` by running `make chunkserver`. You can list all makefile targets [by][2] running `make help` [or][3] by `make(space)(tab)(tab)`.

[1]: https://github.com/lizardfs/lizardfs/blob/master/src/mount/fuse/CMakeLists.txt#L13
[2]: https://stackoverflow.com/a/23667285/1321680
[3]: https://stackoverflow.com/a/41490195/1321680
