### ISSUE TITLE
How to configure the chunk size?

### ISSUE THREAD

**Issue by Onviziest** [lizardfs/lizardfs#791]
According to LizardFS WhitePaper,  each chunk up to 64 MB in size. I want to test the  performance  of Lizardfs with different chunk size. But I can't find any configuration about it.

How can I configure the chunk size?

**Comment by onlyjob** [comment]
There is no way to change block size without changing the source code.

IMHO current chunk size is optimal.

**Comment by Onviziest** [comment]
Thanks for your reply.
