### ISSUE TITLE
Rejoining failed chunkserver

### ISSUE THREAD

**Issue by geniesis** [lizardfs/lizardfs#796]
I have a question about what happens with chunkservers that are re-joined to the cluster after failure.

Situation is this:

- 8x chunkservers (2 disks, 1 OS, 1 data disk)
- Running v 3.12.0
- 1 Master
- 1 Shadow

Scenario

1. OS disk fail on chunkserver5 and goes offline. Note Data disk is working fine.
2. operations_delay_disconnect set to 1hr
3. Master initiates replication 1hr later
4. OS disk on failed chunkserver5 is replaced (several hours later)
5. chunkserver5 rejoins cluster with mounted data disk as it was prior to OS disk failure.

My questions are as follows:

1. Is it fine for the chunkserver to re-join the cluster after replication has already started?
2. What happens with chunks that were changed after the chunkserver failed? This would mean that the failed chunkserver holds an "older" copy of the chunk compared to other chunkservers.
3. Do these "older" copies get deleted automatically?

**Comment by njhurst** [comment]
Is it fine for the chunkserver to re-join the cluster after replication has already started?

yes

    What happens with chunks that were changed after the chunkserver failed? This would mean that the failed chunkserver holds an "older" copy of the chunk compared to other chunkservers.
    Do these "older" copies get deleted automatically?

yes
