### ISSUE TITLE
Relocated disks

### ISSUE THREAD

**Issue by 19wolf** [lizardfs/lizardfs#800]
I accidentally rebooted my server running 5 chunkservers (one for each disk), and now I need to start lizardfs again but I don't know where each specific disk was mounted. aka I don't know if /dev/sdb was /mnt/hdd-1 or if /dev/sdb is even the same disk as before the reboot. Does this matter? Will I lose data?

The same issue can be stated as such: Disks were removed from servers before moving, and after moving the manifest was lost for which disk goes in which server. Is LizardFS smart enough to figure out which disk/server has what data?

**Comment by corradofiore** [comment]
We tested this case, in a slightly different way:  we swapped some disks between different live machines.  LizardFS was able to recognise the chunks on each disk, so I'm seconding onlyjob's comment.
