### ISSUE TITLE
the way to run multiple chunkservers on the same machine doesn't work

### ISSUE THREAD

**Issue by ahnselina** [lizardfs/lizardfs#801]
the lizardfs version is 3.13.0-rc1
I want to run multiple chunkservers on the same machine.
I followed the steps:
"
1. Prepare another mfschunkserver.cfg file for the new chunkserver in a different path, let’s call it /etc/chunkserver2.cfg
2. Prepare another mfshdd.cfg file for the new chunkserver in a different path, let’s call it /etc/hdd2.cfg
3. Set HDD_CONF_FILENAME in chunkserver2.cfg file to the path of newly prepared mfshdd.cfg file, in this example /etc/hdd2.cfg
4. Set CSSERV_LISTEN_PORT to non-default, unused port (like 9522) in /etc/chunkserver2.cfg
5. Run the second chunkserver with mfschunkserver -c /etc/chunkserver2.cfg
6. Repeat if you need even more chunkservers on the same machine (not very recommended though)
"
 but I ran into a problem. There was the first mfschunkserver process(the original process mfschunkserver process) on the node, when I ran "mfschunkserver -c /etc/chunkserver2.cfg", the first mfschunkserver process(mfschunkserver start) disappeared.And I cannot figure out what's going on.
Is there any another steps to run multiple chunkservers on the same machine besides the steps mentioned above?

**Comment by njhurst** [comment]
Can you check the logs for error messages?

**Comment by ahnselina** [comment]
> Can you check the logs for error messages?

the error messages are:
"mfschunkserver[959]: connection failed, error: Connection refused.
 mfschunkserver[959]: connecting to Master
 mfschunkserver[959]: connection failed, error: Connection refused.
 mfschunkserver[959]: connecting to Master
"
do these messages mean there were some errors in the configuration of my mfsmaster?

**Comment by ahnselina** [comment]
oh....I knew "connection failed, error: Connection refused" because the port was not right. But there was another problem:
I can only start one mfschunkserver process on the same node, how can I solve this problem

**Comment by njhurst** [comment]
Are you setting the listen port of the chunkserver?  netstat -l might be helpful here.  You can definitely run lots of mfschunkservers on one machine, I've done it many times:
```
$ netstat -lp
tcp        0      0 0.0.0.0:9501            0.0.0.0:*               LISTEN      2948/mfschunkserver 
tcp        0      0 0.0.0.0:9502            0.0.0.0:*               LISTEN      2947/mfschunkserver 
tcp        0      0 0.0.0.0:9503            0.0.0.0:*               LISTEN      2953/mfschunkserver 
tcp        0      0 0.0.0.0:9504            0.0.0.0:*               LISTEN      2952/mfschunkserver 
tcp        0      0 0.0.0.0:9505            0.0.0.0:*               LISTEN      2950/mfschunkserver 
tcp        0      0 0.0.0.0:9506            0.0.0.0:*               LISTEN      2949/mfschunkserver 
tcp        0      0 0.0.0.0:9508            0.0.0.0:*               LISTEN      2951/mfschunkserver 
```

**Comment by ahnselina** [comment]
> Are you setting the listen port of the chunkserver? netstat -l might be helpful here. You can definitely run lots of mfschunkservers on one machine, I've done it many times:
> 
> ```
> $ netstat -lp
> tcp        0      0 0.0.0.0:9501            0.0.0.0:*               LISTEN      2948/mfschunkserver 
> tcp        0      0 0.0.0.0:9502            0.0.0.0:*               LISTEN      2947/mfschunkserver 
> tcp        0      0 0.0.0.0:9503            0.0.0.0:*               LISTEN      2953/mfschunkserver 
> tcp        0      0 0.0.0.0:9504            0.0.0.0:*               LISTEN      2952/mfschunkserver 
> tcp        0      0 0.0.0.0:9505            0.0.0.0:*               LISTEN      2950/mfschunkserver 
> tcp        0      0 0.0.0.0:9506            0.0.0.0:*               LISTEN      2949/mfschunkserver 
> tcp        0      0 0.0.0.0:9508            0.0.0.0:*               LISTEN      2951/mfschunkserver 
> ```
I had set the listen port of the chunkserver. The problem now seem to be that, once I start a new chunkserver process, the old chunkserver process exits.


the info of  netstat -l as follows:
> $ netstat -lp | grep mfs
> tcp        0      0 0.0.0.0:9419            0.0.0.0:*               LISTEN      15190/mfsmaster 
> tcp        0      0 0.0.0.0:9420            0.0.0.0:*               LISTEN      15190/mfsmaster
> tcp        0      0 0.0.0.0:9421            0.0.0.0:*               LISTEN      15190/mfsmaster 
> tcp        0      0 0.0.0.0:9422            0.0.0.0:*               LISTEN      16074/mfschunkserver 
> tcp        0      0 0.0.0.0:9424            0.0.0.0:*               LISTEN      15190/mfsmaster

I start a new chunkserver listen to the port 9522 use cmd "mfschunkserver -c /etc/chunkserver2.cfg":
> $ netstat -lp | grep mfs
> tcp        0      0 0.0.0.0:9419            0.0.0.0:*               LISTEN      15190/mfsmaster 
> tcp        0      0 0.0.0.0:9420            0.0.0.0:*               LISTEN      15190/mfsmaster
> tcp        0      0 0.0.0.0:9421            0.0.0.0:*               LISTEN      15190/mfsmaster 
> tcp        0      0 0.0.0.0:9424            0.0.0.0:*               LISTEN      15190/mfsmaster
> tcp        0      0 0.0.0.0:9522            0.0.0.0:*               LISTEN      6722/mfschunkserver 

" ps -ef | grep mfschunkserver " only see the new chunkserver process, the old chunkserver process disappeared.

**Comment by ahnselina** [comment]
> You're going to have to paste all your configuration here - my crystal ball has become cloudy now :)

ok, my all configuration:

/etc/hosts like this:
192.168.0.100 mfsmaster  #float IP
192.168.0.1 chunkserver1 metalogger
192.168.0.2 chunkserver2 cgiserver
192.168.0.3 chunkserver3 

I build a HA cluster use the uraft feature, and it's run ok. Now I want to run 2 chunkservers on the node 192.168.0.3, so the /etc/hosts like this:
192.168.0.100 mfsmaster  #float IP
192.168.0.1 chunkserver1 metalogger
192.168.0.2 chunkserver2 cgiserver
192.168.0.3 chunkserver3 chunkserver4



The mfsmaster.cfg was set to like this:
URAFT_NODE_ADDRESS = 192.168.0.1 # ip of first node
URAFT_NODE_ADDRESS = 192.168.0.2 # hostname of second node
URAFT_NODE_ADDRESS = 192.168.0.3 # hostname and custom port of third node
URAFT_ID = 0 # URAFT_ID for this node
URAFT_FLOATING_IP = 192.168.0.100 # Shared (floating) ip address for this cluster
URAFT_FLOATING_IFACE = eth1 # Network interface for the floating ip on this node


the last chunkserver listen port 9522, the first 3 chunkservers listen port 9422

**Comment by ahnselina** [comment]
> You're going to have to paste all your configuration here - my crystal ball has become cloudy now :)

What's your configuration when you run multiple chunkservers on the same machine. Maybe I can refer to your configuration

**Comment by ahnselina** [comment]
> You're going to have to paste all your configuration here - my crystal ball has become cloudy now :)

@njhurst 
thank you very much, now I have already solved this problem, the root cause of my problem is the item "DATA_PATH" in /etc/chunkserver2.cfg file are the same with /etc/mfs/mfschunkserver.cfg. Now I set new value to "DATA_PATH", and I can run multiple chunkservers on the same machine now : )

**Comment by njhurst** [comment]
Nice detective work!  Sorry I didn't get back to you earlier.

**Comment by ahnselina** [comment]
> Nice detective work! Sorry I didn't get back to you earlier.

It doesn't matter, thanks to your advice inspired me.
