### ISSUE TITLE
Unable to to disable default_permissions, allow_other from fstab mounts

### ISSUE THREAD

**Issue by fredricj** [lizardfs/lizardfs#802]
The default options when mounting a lizardfs includes allow_other and default_permissions. It is possible to disable these options when mounting with mfsmount -n . It is however unfortunately not possible to disable these options when mounting from fstab.
This leads to the user having to use rc.local, systemd service-files or mount it manually to workaround this limitation.
Disabling default_permissions is for instance required when the remote is shared between multiple systems and you dont have direct control over the permissions the other systems uses.

**Comment by pbeza** [comment]
Just add `-n` or `--nostdopts` to your [`mfsmount.cfg`][1].

[1]: https://docs.lizardfs.com/man/mfsmount.cfg.5.html
