### ISSUE TITLE
3.13.0~rc1: FTBFS on x86_32

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#806]
~~~~
src/mount/fuse/mfs_fuse.cc:54:16: error: static assertion failed: Types don't match
  static_assert(std::is_same<decltype(a), decltype(b)>::value,
                ^~~
make[3]: *** [src/mount/fuse/CMakeFiles/mfsmount3.dir/build.make:92: src/mount/fuse/CMakeFiles/mfsmount3.dir/mfs_fuse.cc.o] Error 1
~~~~

**Comment by oliverclaude** [comment]
I got exactly the same bug from source. Was/Is compiling it on an armv7 odroid board.

**Comment by pbeza** [comment]
Which Linux 32-bit distro version do you run?

**Comment by onlyjob** [comment]
Debian of course. Observed this problem on _Buster_.

**Comment by pbeza** [comment]
I probably successfully compiled latest ([`master`][1]) LizardFS on 32-bit Debian Buster before merging 37d4ae443c2da9c5201aa4f3f7dae5d9e403d536 but I will double check that when I will have access to 32-bit machine.

[1]: https://github.com/lizardfs/lizardfs

**Comment by pbeza** [comment]
I've just recompiled LizardFS on 32-bit machine pulled from `master` and _it compiles without any error_. If you find any compilation flags combination or any 32-bit environment that makes compilation fail, please reopen this issue.
