### ISSUE TITLE
FUSE3 client: allows to mount more than once

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#807]
~~~~
# mfsmount3 /mnt/r
mfsmaster accepted connection with parameters: read-write,restricted_ip,ignore_gid ; root mapped to root:root
02/07/19 17:15:26.953 [info] [23978:23979] : Received IO limits configuration update from master
[2019-02-07 17:15:26.953] [info] Received IO limits configuration update from master

# mfsmount3 /mnt/r    # attempt to mount over existing mount
mfsmaster accepted connection with parameters: read-write,restricted_ip,ignore_gid ; root mapped to root:root
02/07/19 17:15:32.342 [info] [24002:24003] : Received IO limits configuration update from master
[2019-02-07 17:15:32.342] [info] Received IO limits configuration update from master

# grep /mnt/r /proc/mounts
mfsmaster:9421 /mnt/r fuse.mfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
mfsmaster:9421 /mnt/r fuse.mfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0

# fusermount -u /mnt/r  # OK

# fusermount -u /mnt/r  # OK again(!)

# fusermount -u /mnt/r
fusermount: failed to unmount /mnt/r: Invalid argument
~~~~

Here is an example of correct/expected behaviour on MooseFS:

~~~~
# mfsmount /mnt/r
mfsmaster accepted connection with parameters: read-write,restricted_ip,admin ; root mapped to root:root

# mfsmount /mnt/r  # attempt to mount again, over existing mount
mfsmaster accepted connection with parameters: read-write,restricted_ip,admin ; root mapped to root:root
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
error in fuse_mount
~~~~

**Comment by onlyjob** [comment]
This is of course quite bad because benign command `mount -av` adds another LizardFS mount point on top of existing one (hence starting another `mfsclient` process) every time when command is invoked, for all LizardFS mounts in `/etc/fstab`...

**Comment by pbeza** [comment]
FYI interesting quote from `libfuse` [changelog](https://github.com/libfuse/libfuse/blob/a1bff7dbe3ad8950d8cf1b5640aa7a7b2e89211d/ChangeLog.rst):

> The -o nonempty mount point has been removed, **mounting over non-empty directories is now always allowed**. This brings the behavior of FUSE file systems in-line with the behavior of the regular mount command.
> 
> **File systems that do not want to allow mounting to non-empty directories should perform this check themselves before handing control to libfuse.**

**Comment by pbeza** [comment]
OK, let's break it down into 3 cases:

1. Single share `lizardfs-master:9421` mounted in 2 different directories `/mnt/a` and `/mnt/b` is *allowed in FUSE, FUSE3 (the same [is allowed][2] for e.g. ext4 partition)*.<br />
![mount1_small](https://user-images.githubusercontent.com/3036218/56345022-0f02cb80-61bf-11e9-987e-aadc3e6b22d4.png)<br />
Proof for FUSE:<br />
![Peek 2019-04-18 10-21](https://user-images.githubusercontent.com/3036218/56347199-1678a380-61c4-11e9-9aee-fe9aeee036ad.gif)<br />
Quote from [`mount(2)`][1] manual:<br /><br />
    > Since Linux 2.4 a single filesystem can be mounted at multiple mount points, and multiple mounts can be stacked on the same mount point.
1. Single share `lizardfs-master:9421` mounted in the same directory is *allowed in FUSE if `-o nonempty` flag is provided*. *FUSE3 and ext4 [allow][1]* you to mount the same share in the same directory without need to specify `-o nonempty` flag and that is the case that you don't like, _right?_<br />
![mount2_small](https://user-images.githubusercontent.com/3036218/56345398-eb8c5080-61bf-11e9-99b0-01dff773f50b.png)<br />
Proof for FUSE:<br />
![Peek 2019-04-18 10-57](https://user-images.githubusercontent.com/3036218/56349519-ff888000-61c8-11e9-9d78-d404f440a72e.gif)
1. Different shares `lizardfs-master-01:9421` and `lizardfs-master-02:9421` mounted in the same `/mnt/a` directory are *allowed in FUSE, FUSE3  (the same [is allowed][2] for e.g. ext4 partition)*.<br />
![mount3_small](https://user-images.githubusercontent.com/3036218/56345405-efb86e00-61bf-11e9-94a6-be97d90b363c.png)

[1]: http://man7.org/linux/man-pages/man2/mount.2.html#NOTES
[2]: https://unix.stackexchange.com/questions/276355/is-it-safe-to-mount-same-ext4-filesystem-at-different-mount-points

**Comment by onlyjob** [comment]
This ticket is about violating case 2 where `mfsmount3` silently mounts the same share over and over the same mount directory without `-o nonempty`. Wrongs of such behaviour is obvious without that much unrelated information.
Doesn't matter if FUSE3 allows it because it is dangerous and wrong.

**Comment by pbeza** [comment]
@onlyjob I just wanted to make sure that you consider only this particular case 2 *dangerous and wrong* – that's why I provided all the information that may be unrelated for you.

I've fixed the problem. Hopefully it would be merged soon.

Before fix:

After fix:
![after](https://user-images.githubusercontent.com/3036218/56426631-481f6680-62b9-11e9-89ef-f472e81d0771.gif)
