### ISSUE TITLE
Question: is it worth it to combine RAID0 with LizardFS?

### ISSUE THREAD

**Issue by tsujp** [lizardfs/lizardfs#810]
I'm only interested in RAID0 and my setup consists of 4 x 10 TB drives with 32 GB of ECC 32GB memory.

Is it worth it putting these drives in software-raid 0 before mounting LizardFS ontop of it? Or should I keep the 4 drives distinct? I'm concerned with performance only (as evidenced by RAID0). Redundancy does not interest me as the data stored on this setup can be regenerated from public networks quite easily, I just need to be able to read and write to it as fast as possible.

RAID0 writes and reads to multiple drives at the same time, hence the performance increase by using it. Does LizardFS do this also? Is using both better than either etc?

**Comment by onlyjob** [comment]
Your setup will be better without RAID.

RAID0 not always improves performance because all HDDs are symmetrically loaded while LizardFS on multiple HDDs can distribute I/O hence (at least theoretically) performing better under multi-threaded load. Access concentration is worse under RAID0.

**Comment by hito** [comment]
Rightio, time to deploy a second chunk server and then copy all of those chunks from the first across to the second and then fix the first one.

I have another question, my current setup is:

Machine 1:
- Metadata
- Chunk 1

I want to transition to having:

Machine 1:
- Metadata
- Chunk 1

Machine 2:
- Shadow metadata
- Chunk 2

In order for me to add the second chunk server to the network will the first have to go down for ANY period of time? I cannot afford to bring chunk 1 on Machine 1 offline for any time at all. So when I edit the mfsmaster.cfg and mfsexports.cfg and all of that on Machine 1 how do I reload those configurations without experiencing any downtime?

**Comment by hito** [comment]
I'm trying to mount the drives in the chunkserver and they show up as "damaged" on the lizardfs cgi server. I simply used mkfs.xfs to make each drive sda, sdb, sdc, sdd an XFS system and then mounted the entire drive (no partition) and then referenced that drive's mountpoint in mfshdd.cfg. Do you have any insight?

**Comment by njhurst** [comment]
When I've seen that it was because I had two chunkservers pointing to the same data directory.  Look very closely and make sure you didn't do this.

**Comment by hito** [comment]
Turns out I forgot to chown the directories for user `lizardfs`, that's an amateur mistake right there.
