### ISSUE TITLE
Question: changing configuration without downtime (mfsmaster.cfg and mfsexports.cfg)

### ISSUE THREAD

**Issue by hito** [lizardfs/lizardfs#812]
My current setup is:

Machine 1:
* Metadata
* Chunk 1

I want to transition to having:

Machine 1:
* Metadata
* Chunk 1

Machine 2:
* Shadow metadata
* Chunk 2

In order for me to add the second chunk server to the network will the first have to go down for ANY period of time? I cannot afford to bring chunk 1 on Machine 1 offline for any time at all. So when I edit the mfsmaster.cfg and mfsexports.cfg and all of that on Machine 1 how do I reload those configurations without experiencing any downtime?

**Comment by onlyjob** [comment]
You can add chunkserves without any down time -- they just register themselves with _master_. Same goes for metadata loggers (and shadow masters).

All daemons can reload their configuration by `systemctl reload` but some parameters are not reload-able (e.g. `HDD_LEAVE_SPACE_DEFAULT`).

If you have your data with _goal==2_ then you can safely restart any chunkserver without losing availability of your data.

**Comment by hito** [comment]
Ah lovely, I'll get on that.

Where is the goal == 2 option set?

**Comment by onlyjob** [comment]
https://manpages.debian.org/stretch/lizardfs-client/lizardfs-setgoal.1.en.html

Something like `lizardfs setgoal -r 2 {folder_name}`

**Comment by pbeza** [comment]
@hito Did it work for you?
