### ISSUE TITLE
Cannot reconnect chunkserver

### ISSUE THREAD

**Issue by hito** [lizardfs/lizardfs#813]
I created a chunkserver, then wiped the same machine to reinstall the operating system.

The chunkserver was listed as disconnected and I clicked remove on the cgi GUI, now when I start the chunkserver it never appears, even though the shadow master also running on the same machine is visible.

`systemctl reload lizardfs-chunkserver` outputs `lizardfs-chunkserver.service is not active, cannot reload.` and I am running the chunkserver with `service lizardfs-chunkserver start` to which `lizardfs-admin list-chunkservers` only outputs the other chunk server and not this one also.

**Comment by hito** [comment]
Chunkserver had incorrect /etc/host configuration due to ip loopback. Be sure to check that anyone who encounters this "bug" (really my own incompetence).

**Comment by onlyjob** [comment]
I just configure `mfsmaster` host in DNS and that's enough for one cluster on LAN...
