### ISSUE TITLE
Old Chunk Server(s) On-lined - Chunks unavailable, access extremely slow.

### ISSUE THREAD

**Issue by BloodBlight** [lizardfs/lizardfs#819]
Sorry, wasn't sure how to title this.

I am moving things around and had removed a chunk server from rotation some time ago.  Today I on-lined the server by accident and it started to re-join.  

I quickly took it back off-line, but now it is pissed.

I show 44k chunks as unavailable and the and read operations either fail or are extremely slow (averaging like 1kbps but in bursts).  To make it worse, when I on-lined it I was purging the disks and now I am not sure what to do.

Should I bring it back and let it try and purge?  The master server reports all files as healthy, but chunks missing..  :(

It isn't the end of the world if the data is lost, but I would prefer not too...

I tried restarting the master server, but that didn't make any difference.

Thoughts?

**Comment by BloodBlight** [comment]
I take that back, it is nor reporting almost all of the files as unavailable.

**Comment by BloodBlight** [comment]
Tried forcing a random deb file back online, killed it.

**Comment by BloodBlight** [comment]
I think the chunk servers connected to a different server before it connected to the old one, purging blocks as they suddenly had the newest stamp?

My data is probably toast, but if LizardFS is still being maintained, this should be looked at (at it appears the masters data can be overridden).

**Comment by blink69** [comment]
@BloodBlight wow, I don't know what you tied to do :)

First of, if you connect old chunkserver nothing bad should do, cluster will remove all unnecessary chunks from this server, nothing else.
Missing chunks you will get only when you will start play with disks manualy (via delete by hand random chunks from chunkserver drive).

Regarding connecting chunkserver from one cluster to another one, there is a probability that chunks name will have collision between clusters, but still checksums will be diffrent so for sure cluster will not start replicating this "no mine, crc wrong, but id the same" chunks.

If you want someone to take a closer look, please write to support@lizardfs.com

**Comment by jkiebzak** [comment]
The 44k chunks as unavailable probably show up because you the old chunk server was started. As soon as the daemon on the local server start, is finds all the local chunks, and tells the master what chunks exist locally. Then the master would report back to the chunk server what chunks to start purging. 

once you "quickly took it back off-line", the master now cannot see the chunks that it was just told about, thus is saying "missing chunks". as @blink69 said, bringing the old chunkserver online should not be a problem, and is probably the easiest way to clear the "missing chunks" status in the master.

**Comment by BloodBlight** [comment]
An update to this, I know it is closed.  But after recovery, many of the files where out of sync.  This corrupted every Borg archive we had on the cluster.

So the chunk version selection was not handled correctly.  

The older servers had been off-line for some time, and most of the files had been altered in some way.  So for what ever reason, the master choose to use the older version blocks..  I think..  Something isn't working correctly. 

This cluster is now gone, so I can do no more debugging on it.  It may be worth setting up a small virtual cluster and attempting to duplicate this as I feel this is still an issue.  I no longer feel confident to use LizardFS in a production environment.

**Comment by pbeza** [comment]
@BloodBlight What's the test scenario that you suggest to prepare? I can give it a try to test it but I need to be sure that my test scenario aligns with yours. What would be your [test acceptance criteria][1]? Would it be good test scenario in your opinion?:
 1. Create random files on a LizardFS share backed with 4 chunkservers.
 1. Shut down one of the chunkservers after completing step 1.
 1. Randomly alter data.
 1. Read random files and measure read speed. BTW: you mentioned that you measured `1 kbps` but in bursts – how did you measure that?
 1. Start shut down chunkserver again.
 1. Check whether data altered in step 3 are still altered.
 1. Read random files and measure read speed again.

Feel free to write any suggestions how should I test it to increase the chance to reproduce your problem (if it is actually a problem).

[1]: https://en.wikipedia.org/wiki/Acceptance_testing#User_acceptance_testing
