### ISSUE TITLE
Can I run Mariadb/Mysql on lizardfs?

### ISSUE THREAD

**Issue by lfjeff** [lizardfs/lizardfs#820]
Have been running Mariadb on ZFS for three years with absolutely no problems.  I have ZFS configured to take periodic snapshots of the database and sync them to a copy on remote server that is 3,000 miles away (just in case the main datacenter is destroyed by a meteorite or something).  If the main center goes down or is unreachable for some reason, I can (theoretically) restart Mariadb on the remote copy.

Could I run Mariadb under lizardfs and have it maintain a database copy on a geographically remote server?  Some clustered filesystems like StorageOS say you can use them for databases, while others like Ceph recommend against it.  I have not been able to find any recommendations pro or con regarding lizardfs.

**Comment by Zorlin** [comment]
You can but I'd strongly recommend against it.

**Comment by Zorlin** [comment]
Okay, now that I'm at a real keyboard, let me elaborate.

Performance doing many small reads/writes (as is common with relational databases) will not be great, and depending on the workload MySQL/MariaDB could trip over itself as LizardFS doesn't always handle fsync() properly.

On top of that, you'll have even less fun due to the added latency of a geographically remote server, unless you do some good tuning. Even then I think it's not a great way to go.

**Comment by lfjeff** [comment]
Thanks, that's what I wanted to know.  I won't waste my time pursuing this option.  Will probably set up a real database cluster (like Galera) and set up the remote Mariadb as a read-only copy.  If something fails, it can be promoted to master and take over.

**Comment by blink69** [comment]
@Zorlin Could you elaborate more on that ?

> LizardFS doesn't always handle fsync() properly
 
Because it's not true, of course, if you setup perform_fsync=0 in chunkserver then chunkserver will omit fsync by each write and push that role to Linux kernel. But if you setup 1 on option above all writes will be finished by fsync.

**Comment by Zorlin** [comment]
@blink69 it sounds like I'm mistaken, or that someone I listened to is mistaken :) thanks for clearing it up.

**Comment by lfjeff** [comment]
So are you saying that if `fsync=1` then you could run Mysql/Mariadb on Lizardfs?  Of course, I'm assuming that there is only one instance of `mysqld` that will be accessing the the database files.  If `mysqld` is running on a Docker container that is terminated, could it be be restarted and pick up where the last process stopped?

I'm curious because StorageOS claims they can do this:
[https://docs.storageos.com/docs/usecases/docker/mysql](https://docs.storageos.com/docs/usecases/docker/mysql)

I might trust this for a Redis server that is just storing session data (which is easily recreated).  However, but I'm not sure about how well it will work for Innodb files.  If they get corrupted, then I'd have much more serious problems.

**Comment by blink69** [comment]
We got a lot of instances of Mysql/MariaDB but there are running in virtual machines that are stored on LizardFS. I dont used Mysql running directly on LizardFS, this need to be checked how this setup will perform.

**Comment by eleaner** [comment]
@lfjeff 
any luck? which route did you finally go?

**Comment by lfjeff** [comment]
This project is on hold, so I have not done anything more

**Comment by zicklag** [comment]
I don't know how valuable this input is, but just in case: My team once ran a low utilization 3 node LizardFS cluster with Mysql using LizardFS for storage and I never ran into Data loss.

The whole LizardFS cluster was running on VMs with SSDs. The applications' responsiveness when using LizardFS for the database *was* noticeably slower compared to using the SSDs directly, but it wasn't unusable. We weren't serving a lot of traffic though so we didn't get a thorough test or anything.
