### ISSUE TITLE
lizardfs strightforward tutorial

### ISSUE THREAD

**Issue by codenoid** [lizardfs/lizardfs#823]
hi, i'm new in distributed file system world, i wanna make a replication set + multi data center with lizardfs, but i can't find strightforward tutorial for it, something like : 

1. what i must do in master-server
2. what i must do in node server
3. where (the config file) and how to config master/node server
4. how other server (as client) can connect to lizardfs service
5. how file path be arranged
6. more something like that

my server is ubuntu 16.04, thank you !

**Comment by blink69** [comment]
Hi, this page should help you https://docs.lizardfs.com/adminguide/index.html

**Comment by codenoid** [comment]
something wrong with Fedora Server 30
