### ISSUE TITLE
Compile 3.13.0-rc1

### ISSUE THREAD

**Issue by eleaner** [lizardfs/lizardfs#831]
Hi,

I tried to compile on Debian Stretch, technically docker stretch-slim
I followed [this](https://docs.lizardfs.com/devguide/obtaining.html) guideline but I cannot figure out all the dependencies.

Is there an easy to apply reference?

**Comment by tjohnston-cd** [comment]
The Debian/Ubuntu section [here](https://docs.lizardfs.com/devguide/creating_workspace.html#debian-8-ubuntu-16-10) seems to be empty..

**Comment by pbeza** [comment]
I've updated LizardFS prerequisites/dependencies [here][1]. This is the list of all required dependencies:

    git cmake g++ libspdlog-dev libfuse3-dev libfuse-dev fuse isal libisal-dev libboost-all-dev asciidoc-base zlib1g-dev pkg-config libthrift-dev libcrcutil-dev libjudy-dev libpam0g-dev libdb-dev libgtest-dev

If you have any issues regarding LizardFS documentation, please [open new issue][2] in [LizardFS documentation repository][3].

[1]: https://github.com/lizardfs/documentation/blob/master/source/devguide/obtaining.rst
[2]: https://github.com/lizardfs/documentation/issues/new
[3]: https://github.com/lizardfs/documentation

**Comment by eleaner** [comment]
@pbeza 
Thank you. 
Loks like it won't work on stretch but I can now easily compile on buster.
I only have a problem with "what next?"
I don't seem to have mfs user in the system, nor required folders or empty metadata file.

**Comment by tjohnston-cd** [comment]
Ah yes, that's the same problem I mentioned in #830

**Comment by pbeza** [comment]
@eleaner Did you run `make install`? If you ran `cmake` and `make install` with default options you should find your empty database in `/usr/local/var/lib/mfs/metadata.mfs.empty`. Please refer [this][1] documentation.

[1]: https://docs.lizardfs.com/adminguide/basic_configuration.html#the-metadata-database

**Comment by eleaner** [comment]
Yes I run make install
I will try what you suggested. Should it also create user and group to run lizard?

**Comment by onlyjob** [comment]
@eleaner, just in case please make sure that you are familiar with https://wiki.debian.org/DontBreakDebian especially in regards to `make install`.

_Stretch_ have official LizardFS packages:
https://packages.debian.org/source/stable/lizardfs

**Comment by eleaner** [comment]
@onlyjob thank you for the article.
The whole idea was to compile new 3.13.0. I don't believe it's available as official packages yet.

**Comment by eleaner** [comment]
unless there is a better base docker image to use for compiling lizard

**Comment by pbeza** [comment]
@eleaner If you don't need to use LizardFS cutting edge version or release candidate, [prefer][1] official packages. Otherwise, [you can][2] run:

    cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
    make -j6
    make install

This will install to e.g. `/usr/local` directory which prevents mixing files installed from official packages and your hand-compiled packages.

If you want to experiment with Docker you can check [my experimental development repository][3] that sets up containers for LizardFS.

[1]: https://wiki.debian.org/DontBreakDebian#A.27make_install.27_can_conflict_with_packages
[2]: https://unix.stackexchange.com/questions/11544/what-is-the-difference-between-opt-and-usr-local
[3]: https://github.com/pbeza/lizardfs-docker

**Comment by onlyjob** [comment]
> The whole idea was to compile new 3.13.0.

[3.13.0 milestone](https://github.com/lizardfs/lizardfs/milestone/2) still have pretty strong reasons  to avoid `3.13.0~rc1`.
