### ISSUE TITLE
3.10.0: under goal chunks don't replication unless restart chunkserver

### ISSUE THREAD

**Issue by fan41** [lizardfs/lizardfs#832]

**Comment by fan41** [comment]
We have use LFS with a 40 nodes cluster , it run good almost 2 years until last week one of chunk server has damaged disks and we stop chunk server service and replace the bad disk direct. we having a default goal with 3 copies , after the job , we found about 50 thousand chunks undergoal through cgi page. in several days the under goal chunks remain no copies to expect goals. mfsmaster.cfg and mfschunkserver.cfg config is set to default options . we attempt restart the CS service under goal chunks reduce by about 1 to 3 hundred . meanwhile CS log out an error "mfschunkserver[23949]: replication error: failed to create chunk (Chunk already exists)". is this match the expect, anything help with my situation?

**Comment by fan41** [comment]
attach lizardfs page 
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/29326610/61679969-96218b80-ad3a-11e9-890a-de913d36f984.png">

**Comment by njhurst** [comment]
When this happened to me, i wrote a script which looks for all the undergoal files using mfsgetfileinfo, and simply copied the undergoal files to a new temp file, then deleted the old and swapped in the new.  I don't know a real fix, but that solved the problem for me.

**Comment by jbarrigafk** [comment]
I think you just have to wait for lizardfs to start making a copy of the chunks that are below the goal.

Maybe in hours that there is not much workload, undergoal chunks begin to replicate little by little, I suppose you store large files in your cluster, right?

Because I store small files, each with a size of 8 or 12 Kb at most and when I have undergoal, the chunks replicate quickly by the size of my files i think

**Comment by fan41** [comment]
> When this happened to me, i wrote a script which looks for all the undergoal files using mfsgetfileinfo, and simply copied the undergoal files to a new temp file, then deleted the old and swapped in the new. I don't know a real fix, but that solved the problem for me.

Yes, it does. 

Did you do delete and swap file one by one in a loop ？

Due to the realtime business access cluster，request may failed。

I don't known how long this job will take. It may the final way I will try

**Comment by fan41** [comment]
> I think you just have to wait for lizardfs to start making a copy of the chunks that are below the goal.
> 
> Maybe in hours that there is not much workload, undergoal chunks begin to replicate little by little, I suppose you store large files in your cluster, right?
> 
> Because I store small files, each with a size of 8 or 12 Kb at most and when I have undergoal, the chunks replicate quickly by the size of my files i think

Yes, cluster store both small files and large files such as hundreds MB.

After I rolling restart the CS , since yesterday , I found the under goal chunks decreased.

I wonder whether the replication performed or the file deleted by user.

Is there anything I can do but wait?

**Comment by blink69** [comment]
First play with your setup changing master cfg file (only master reload required).

ENDANGERED_CHUNKS_PRIORITY = 1, this option will make all endangered chunks in priority to replication, without that rebalance, recalculation is on equal position.

CHUNKS_WRITE_REP_LIMIT = 200
CHUNKS_READ_REP_LIMIT = 200
This is how much chunks should be replicated, this value is depending on how big storage and how much chunk do you have.

And other very important options in your case (info from manual)

CHUNKS_LOOP_MAX_CPS
           Chunks loop shouldn’t check more chunks per seconds than given number (default is 100000)

       CHUNKS_LOOP_MIN_TIME
           Chunks loop will check all chunks in specified time (default is 300) unless CHUNKS_LOOP_MAX_CPS will force slower execution.

       CHUNKS_LOOP_PERIOD
           Time in milliseconds between chunks loop execution (default is 1000).

       CHUNKS_LOOP_MAX_CPU
           Hard limit on CPU usage by chunks loop (percentage value, default is 60).

       CHUNKS_SOFT_DEL_LIMIT
           Soft maximum number of chunks to delete on one chunkserver (default is 10)

       CHUNKS_HARD_DEL_LIMIT
           Hard maximum number of chunks to delete on one chunkserver (default is 25)

       CHUNKS_WRITE_REP_LIMIT
           Maximum number of chunks to replicate to one chunkserver (default is 2)

       CHUNKS_READ_REP_LIMIT
           Maximum number of chunks to replicate from one chunkserver (default is 10)

**Comment by fan41** [comment]
Okay, is there a guidance for smoothly upgrade to latest version without cluster downtime?

Besides, I found the master server which mfsmaster running on it , often a single cpu core  100% usage.Are there any improvements in the 3.12.0 version？

**Comment by pbeza** [comment]
- Of course there are lots of improvements in `3.12.0` – see [`NEWS`][1].
- It would be rather impossible to upgrade to new version without at least a few seconds of downtime when restarting LizardFS services/daemons.
- Can you provide output of the following command when CPU core is 100%? `ps -eo pcpu,pid,user,args | sort -k1 -r -n | head -10`. You can also [try][2] to run `strace -p <PID>`  for `<PID>` that causes 100% CPU usage. It will hopefully give some idea what may be wrong.

[1]: https://github.com/lizardfs/lizardfs/blob/master/NEWS
[2]: https://superuser.com/a/926465/139893

**Comment by fan41** [comment]
This issue should be closed, thanks for all your suggestions.
