### ISSUE TITLE
mfsmaster has permanent connection to li1467-192.members.linode.com

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#833]
As per the subject - mfsmaster on my system keeps an active connection to li1467-192.members.linode.com. Noticed when monitoring bandwidth with iftop.

* lizardfs 3.12.0
* Ubuntu 18.04 packages

**Comment by blink69** [comment]
Do you have master open to world ? If yes probably someone connect to your master. Check active mount list or even chunkservers :)

**Comment by Blackpaw** [comment]
Nope, absolutely not.

**Comment by pbeza** [comment]
Can you please run `netstat -tua` and see what is type of the connection (TCP/UDP) and which port is used?

**Comment by blink69** [comment]
@Blackpaw classically speaking "pics or it didn't happen" :)

**Comment by Blackpaw** [comment]
Not sure how that applies in this context. My servers are behind a firewall on a local lan with no incoming connections of any sort allowed. I would never dream of publically exposing mounts on the internet.

**Comment by Blackpaw** [comment]
> Can you please run `netstat -tua` and see what is type of the connection (TCP/UDP) and which local/foreign port is used? 

`tcp        0      0 mfsmaster:47132         li1467-192.member:https ESTABLISHED plex       125739`

>Can you try to mount your share from outside of your network?

Nope :)

I added -ee for extra detail and the user is "plex" - my Media server user, which is the only app which accesses the shares. Not sure why the app shows up as mfsmaster though, but I'm going to assume plex is the guilty party here - which makes more sense. I think we can close it for now - sorry for he false alarm.

**Comment by blink69** [comment]
@Blackpaw mfsmaster is you hostname use netstat -tlunp without resolving names ...

**Comment by Blackpaw** [comment]
D'oh! sorry...
