### ISSUE TITLE
mips64le compile error

### ISSUE THREAD

**Issue by qiyongxiao** [lizardfs/lizardfs#834]
Hi,
I am compiling with create-deb-package.sh on loongxin jessie on mips64le and am encountering the following error at the 90% stage. I had already installed libxslt and libxslt-devel. I'll be grateful for any help and if it's a problem with my system then any advice on how to fix it would be appreciated.
Thanks.
```
[root@apiserver lizardfs-3.13.0]# rpm -qa|grep libxslt
libxslt-1.1.28-5.ns7.mips64el
libxslt-devel-1.1.28-5.ns7.mips64el
[ 89%] Generating lizardfs.1
[ 90%] Generating globaliolimits.cfg.5
[ 90%] Generating iolimits.cfg.5
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/etc/asciidoc/docbook-xsl/manpage.xsl" "/root/Downloads/lizardfs-3.12.0/build-pack/doc/iolimits.cfg.5.xml" returned non-zero exit status 5
make[3]: *** [doc/iolimits.cfg.5] Error 1
make[3]: Leaving directory `/root/Downloads/lizardfs-3.12.0/build-pack'
make[2]: *** [doc/CMakeFiles/manpages.dir/all] Error 2
make[2]: Leaving directory `/root/Downloads/lizardfs-3.12.0/build-pack'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/Downloads/lizardfs-3.12.0/build-pack'
make: *** [all] Error 2
```

**Comment by onlyjob** [comment]
Why are you trying to build using `create-deb-package.sh` on non-Debian distro? 

You can check how official Debian package is built. There you can find a comprehensive list of build dependencies. Most certainly (especially for offline build) you'll need `docbook-xsl` and `docbook-xml` packages as well as `libxml2-utils` and `xsltproc` (as in Debian).

**Comment by qiyongxiao** [comment]
@onlyjob Sorry, it is not create-deb-package.sh, it is create-rpm-package.sh with loongxin on mips64le cpu

**Comment by pbeza** [comment]
@qiyongxiao Which Linux distro do you use? [Debian Jessie][1]?

[1]: https://www.debian.org/releases/jessie/

**Comment by qiyongxiao** [comment]
@pbeza is mips64le, Kylin System

**Comment by pbeza** [comment]
Which one should I download to try to reproduce?
- http://www.ubuntukylin.com/downloads/download.php?id=64 (`Ubuntu Kylin 优麒麟 19.04`)
- http://www.ubuntukylin.com/downloads/download.php?id=58 (`Kylin 4.0.2 Desktop`)
- http://www.ubuntukylin.com/downloads/download.php?id=55 (`Kylin 4.0.2 Server`)
- http://archive.kylinos.cn/kylin/KYLIN-ALL/dists/

**Comment by qiyongxiao** [comment]
> 我应该下载哪一个来尝试重现？
> 
> * http://www.ubuntukylin.com/downloads/download.php?id=64 ( `Ubuntu Kylin 优麒麟 19.04`）
> * http://www.ubuntukylin.com/downloads/download.php?id=58（`Kylin 4.0.2 Desktop`）
> * http://www.ubuntukylin.com/downloads/download.php?id=55 ( `Kylin 4.0.2 Server`）
> * http://archive.kylinos.cn/kylin/KYLIN-ALL/dists/

抱歉，我用的系统是国产中标麒麟（龙芯CPU，mips64le架构的CPU），你上面列举出来的是AMD64架构的CPU，咱们的是不通用。所有软件都需要重新编译

**Comment by pbeza** [comment]
Sorry @qiyongxiao but I'm not able to test it on [Godson][1] because I don't have one. However I guess that your problem is not CPU-specific.

[1]: https://en.wikichip.org/wiki/loongson/godson_2

**Comment by pbeza** [comment]
@qiyongxiao Can you post the output of the following command:

    "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/etc/asciidoc/docbook-xsl/manpage.xsl" "/root/Downloads/lizardfs-3.12.0/build-pack/doc/iolimits.cfg.5.xml"

This is command that failed for you.

**Comment by qiyongxiao** [comment]
> @qiyongxiao Can you post the output of the following command:
> 
> ```
> "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/etc/asciidoc/docbook-xsl/manpage.xsl" "/root/Downloads/lizardfs-3.12.0/build-pack/doc/iolimits.cfg.5.xml"
> ```
> 
> This is command that failed for you.

Enh, the CPU is only in China. I have build the v1.12.0
