### ISSUE TITLE
Unable to build on MacOSX

### ISSUE THREAD

**Issue by MShah890** [lizardfs/lizardfs#837]
I followed all the instructions for setting up the development environment on mac from [https://docs.lizardfs.com/devguide/creating_workspace.html#mac-os-x](url)

On doing `cmake ..` in build folder I get the following error

```
CMake Error at cmake/Libraries.cmake:10 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:146 (include)
```

**Comment by pbeza** [comment]
Have you installed [`spdlog`][1]? If not, follow [these][2] instructions.

[1]: https://github.com/gabime/spdlog
[2]: https://brewinstall.org/Install-spdlog-on-Mac-with-Brew/

**Comment by MShah890** [comment]
Hi I followed these instructions now I have new set of errors when I try to build

```
CMake Error at /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  cmake/FindFUSE.cmake:18 (find_package)
  cmake/Libraries.cmake:18 (find_package)
  CMakeLists.txt:146 (include)

-- Configuring incomplete, errors occurred!

```

**Comment by MShah890** [comment]
Now to remove these errors I did this

```
brew install pkg-config
brew install boost
```

Now I got the following errors

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RT_LIBRARY
    linked by target "lizardfs-uraft" in directory /Users/mshah7/OpenSource/lizardfs/src/uraft

-- Configuring incomplete, errors occurred!
```

**Comment by pbeza** [comment]
This library is in `/usr/lib/x86_64-linux-gnu/librt.so` on my Ubuntu system. `dpkg-query -S  /usr/lib/x86_64-linux-gnu/librt.so` output: `libc6-dev:amd64: /usr/lib/x86_64-linux-gnu/librt.so`, so you probably need `libc6-dev` package.

Try to run `brew install libc6-dev`.

**Comment by Peperzastey** [comment]
Hey. I'm not 100% sure about it, but this small change in `src/uraft/CMakeLists.txt` might fix your problem:
diff (delete the `-` lines, add the `+` lines):
```
--- a/src/uraft/CMakeLists.txt
+++ b/src/uraft/CMakeLists.txt
@@ -7,7 +7,11 @@ set(URAFT_SOURCES ${URAFT_SOURCES} ${CMAKE_SOURCE_DIR}/src/common/time_utils.cc)
 
 add_executable(lizardfs-uraft ${URAFT_MAIN} ${URAFT_SOURCES})
 
-target_link_libraries(lizardfs-uraft ${Boost_LIBRARIES} ${RT_LIBRARY} pthread)
+target_link_libraries(lizardfs-uraft ${Boost_LIBRARIES})
+if(RT_LIBRARY)
+target_link_libraries(lizardfs-uraft ${RT_LIBRARY})
+endif()
+target_link_libraries(lizardfs-uraft pthread)
```

I base this on the link @pbeza mentioned, and also these issues:
https://github.com/google/benchmark/issues/338
https://github.com/ocaml/oasis/issues/112
I don't have a Mac to check it right now, so I can't confirm it yet.

**Comment by MShah890** [comment]
The line

`a/src/uraft/CMakeLists.txt`

is not there in the file `src/uraft/CMakeLists.txt`

**Comment by Peperzastey** [comment]
Yes, yes, that's right.

What this diff means is:
Replace the line:
```
target_link_libraries(lizardfs-uraft ${Boost_LIBRARIES} ${RT_LIBRARY} pthread)
```
With:
```
target_link_libraries(lizardfs-uraft ${Boost_LIBRARIES})
if(UNIX AND NOT APPLE)
target_link_libraries(lizardfs-uraft ${RT_LIBRARY})
endif()
target_link_libraries(lizardfs-uraft pthread)
```

Sorry for the trouble ;)

**Comment by pbeza** [comment]
Try [my suggestion][1] in the first place because maybe you just need one more package to install. If it doesn't help you, follow @Peperzastey's [suggestion][2].

[1]: https://github.com/lizardfs/lizardfs/issues/837#issuecomment-525184563
[2]: https://github.com/lizardfs/lizardfs/issues/837#issuecomment-526945019

**Comment by MShah890** [comment]
@pbeza Tried to install libc6-dev using brew. It gave following errors

`Error: No available formula with the name "libc6-dev" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.`

**Comment by MShah890** [comment]
@Peperzastey Tried your suggestion 

`cmake ..` successfully builds. Now trying to make the build

**Comment by pbeza** [comment]
Great! Keep us updated. If it works we will push @Peperzastey suggestion to `master`.

**Comment by MShah890** [comment]
On trying to do make from build directory following errors occur

`In file included from /Users/mshah7/OpenSource/lizardfs/src/chunkserver/hddspacemgr.cc:69:0:
/Users/mshah7/OpenSource/lizardfs/src/chunkserver/iostat.h:33:27: fatal error: sys/sysmacros.h: No such file or directory
 #include <sys/sysmacros.h>
                           ^
compilation terminated.
make[2]: *** [src/chunkserver/CMakeFiles/chunkserver.dir/hddspacemgr.cc.o] Error 1
make[1]: *** [src/chunkserver/CMakeFiles/chunkserver.dir/all] Error 2
make: *** [all] Error 2`

**Comment by pbeza** [comment]
@MShah890 This message seems to be completely unrelated to the original problem, but let's try to quickly solve it in this issue. Your new problem is related to [this change][1].

Try to replace [this line][2]:

    #include <sys/sysmacros.h>

with the following:

    #if !defined(__APPLE__)
    #include <sys/sysmacros.h>
    #endif

Please write back if it helped.

[1]: https://github.com/lizardfs/lizardfs/commit/5d20c95179be09241b039050bceda3c46980c004
[2]: https://github.com/lizardfs/lizardfs/blob/master/src/chunkserver/iostat.h#L33

**Comment by Peperzastey** [comment]
Also, according to [this thread](https://www.redhat.com/archives/libvir-list/2016-April/msg00852.html) and [this Linux manual page](http://man7.org/linux/man-pages/man3/makedev.3.html) (see NOTES section) this include may also break build on BSD systems, not only on MacOSX.
So we may need to add additional check for BSDs before using this include

**Comment by MShah890** [comment]
While trying to make I am facing similar issue as [https://github.com/lizardfs/lizardfs/issues/650](url)

Following errors occur while linking

`Undefined symbols for architecture x86_64:
  "boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) in main.cc.o
  "boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) in main.cc.o
  "boost::program_options::basic_parsed_options<char> boost::program_options::parse_config_file<char>(std::basic_istream<char, std::char_traits<char> >&, boost::program_options::options_description const&, bool)", referenced from:
      parseOptions(int, char**, uRaftController::Options&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in main.cc.o
  "boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)", referenced from:
      parseOptions(int, char**, uRaftController::Options&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in main.cc.o
  "boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int) in main.cc.o
      void boost::program_options::validate<int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long) in main.cc.o
  "boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) in main.cc.o
  "boost::program_options::arg[abi:cxx11]", referenced from:
      boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char>::name[abi:cxx11]() const in main.cc.o
      boost::program_options::typed_value<int, char>::name[abi:cxx11]() const in main.cc.o
      boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name[abi:cxx11]() const in main.cc.o
  "boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*) in main.cc.o
  "boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)", referenced from:
      boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const in main.cc.o
      void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int) in main.cc.o
  "boost::program_options::operator<<(std::basic_ostream<char, std::char_traits<char> >&, boost::program_options::options_description const&)", referenced from:
      parseOptions(int, char**, uRaftController::Options&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in main.cc.o
  "boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      boost::program_options::variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const in main.cc.o
  "boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      vtable for boost::program_options::invalid_option_value in main.cc.o
      vtable for boost::program_options::validation_error in main.cc.o
      vtable for boost::wrapexcept<boost::program_options::validation_error> in main.cc.o
      construction vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >-in-boost::wrapexcept<boost::program_options::validation_error> in main.cc.o
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> > in main.cc.o
      vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error> in main.cc.o
      vtable for boost::wrapexcept<boost::program_options::invalid_option_value> in main.cc.o
      ...
  "boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const", referenced from:
      vtable for boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char> in main.cc.o
      vtable for boost::program_options::typed_value<int, char> in main.cc.o
      vtable for boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char> in main.cc.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/uraft/lizardfs-uraft] Error 1
make[1]: *** [src/uraft/CMakeFiles/lizardfs-uraft.dir/all] Error 2
make: *** [all] Error 2`

**Comment by pbeza** [comment]
You probably need to install Mac OS X equivalent of the Debian's [`libboost-all-dev`][1] package. Unfortunately I don't know how it's called on Mac OS X. Maybe [`boost-build`][2]?

[1]: https://packages.debian.org/sid/libboost-all-dev
[2]: https://formulae.brew.sh/formula/boost-build#default

**Comment by Peperzastey** [comment]
Post here your output of `cmake ..` run in an empty build directory, please. Then we may be able to help

**Comment by Peperzastey** [comment]
@MShah890 try building Lizard with Boost 1.60.0.
You should have Boost 1.70.0 installed (it's the newest version in `brew` and the default one).
You can uninstall 1.70.0 or simply install 1.60.0 alongside it (if you do so, you will need to add `-DBOOST_ROOT="your/path/to/boost-1.60.0"` when running `cmake`).

Boost 1.60.0 installation using brew:
`brew install boost@1.60`

I have successfully built Lizard (including `uraft` module) with Boost 1.67, 1.60 and 1.58, so these versions should work for sure.
There seem to be some [backward-compatibility-breaking changes](https://www.boost.org/doc/libs/1_71_0/libs/system/doc/html/system.html#changes_in_boost_1_69) in Boost.System introduced in 1.69 that `lizardfs-uraft` cannot deal with yet.

**Comment by pbeza** [comment]
@MShah890 Did it work for you?

**Comment by eleaner** [comment]
Are you guys planning to provide ready to use binaries for MacOSX?
and Arm?

**Comment by pbeza** [comment]
For now we don't have MacOSX and ARM machines. :-( But in the future we will do our best to support as many platforms as possible. ;-)

**Comment by pbeza** [comment]
I'm closing this issue due to lack of @MShah890 response. Please reopen it [this][1] doesn't help.

[1]: https://github.com/lizardfs/lizardfs/issues/837#issuecomment-527080787
