### ISSUE TITLE
General discussion of SDS solutions

### ISSUE THREAD

**Issue by eleaner** [lizardfs/lizardfs#839]
continuation from #805 

is HDFS a viable option as an SDS?

**Comment by pbeza** [comment]
IMHO we can try to move this discussion to [gitter.im/lizardfs][1]. What do you think? (See also: #238)

[1]: https://gitter.im/lizardfs/community?source=orgpage

**Comment by eleaner** [comment]
sure thing
I don't think I ever used gitter

**Comment by eleaner** [comment]
Though I don't see great many people there

**Comment by pbeza** [comment]
Maybe other will join after you start discussion there. General discussions are more like chat, so maybe its worth trying?

**Comment by pbeza** [comment]
As suggested by me, lets continue discussion on SDS options on [gitter.im/lizardfs][1]. Please join.

[1]: https://gitter.im/lizardfs/community
