### ISSUE TITLE
Question. ChunkServers RAID or not?

### ISSUE THREAD

**Issue by jbarrigafk** [lizardfs/lizardfs#840]
I understand that using raid offers you greater information security but sometimes what is needed is a high speed of writing and reading, do you recommend having chunkservers without RAID for faster writing speed?
I think that even if they do not have RAID, the security of the information is maintained a bit if at least 2 copies are kept in the goals.

Have you used this configuration?
echo noop> / sys / block / sdb / queue / scheduler

I have not noticed major changes with this.

regards
![Captura de pantalla de 2019-09-10 09-28-29](https://user-images.githubusercontent.com/35774470/64623188-2892f280-d3ae-11e9-8774-86fa3a735155.png)

**Comment by Blackpaw** [comment]
Definitely no RAID, that's what you should be using LizardFS for - Goal 2 or better. It's much more flexible and reliable than RAID.

**Comment by jkiebzak** [comment]
more reliable that RAID? Do we have anything to back that up?

**Comment by Blackpaw** [comment]
* Much more than two copies possible (we run goal 3 at work) plus ec variants.
* flexibility. Multiple chunkservers allows for data and I/O to be spread across multiple servers.
* Auto healing. If a disk or chunkserver goes out than the missing data will be autocopied to other disks/chunkservers
* Checksumming of chunks allows for automatic detection and healing of data corruption.

**Comment by onlyjob** [comment]
Using RAID does not offer "greater information security".

> more reliable that RAID?

Yes of course. RAID is not great, to say the least.

> Do we have anything to back that up?

Like what? Both theory (design) and practice support that claim.
LizardFS chunkservers are much better without RAID.

You only need redundant storage for master's metadata.

**Comment by jbarrigafk** [comment]
I appreciate each of your comments and suggestions, I have noticed a better performance in my chunkserver without RAID, now I am sure that I must remove the RAID feature from the rest of my chunkservers.
Thank you!

**Comment by phamthanhnhan14** [comment]
Could we use RAW disk for chunkserver?

**Comment by onlyjob** [comment]
> Could we use RAW disk for chunkserver?

Why not? Just format it with file system of your choice. :)
