### ISSUE TITLE
lizardfs-admin command does not work on debian

### ISSUE THREAD

**Issue by paladox** [lizardfs/lizardfs#844]
Hi, using version 3.12, lizardfs-admin cli tool is not working.

I get these errors:

lizardfs-admin info 185.52.1.71 9419
Error: Can't read data from socket: connection reset by peer

lizardfs-admin iolimits-status 185.52.1.71 9419
Error: Can't read data from socket: connection reset by peer

I see in the log:

Sep 27 11:47:22 misc3 mfsmaster[703]: mfsmaster[703]: master <-> metaloggers module: got unknown message (type:1543)
Sep 27 11:47:22 misc3 mfsmaster[703]: master <-> metaloggers module: got unknown message (type:1543)

**Comment by paladox** [comment]
Doing lizardfs-admin info 185.52.1.71 9421 works.

So documentation is wrong at https://docs.lizardfs.com/man/lizardfs-admin.8.html

It should be <client-mount-port>

**Comment by pbeza** [comment]
Your issue is nearly identical to this invalid issue: #681. You used wrong port number. Why you think documentation is wrong? Is it suggesting using wrong port? Where?

**Comment by paladox** [comment]
@pbeza the documentation said <master port> which i thought was the master port. But in fact it's the client/mount port.

**Comment by pbeza** [comment]
`mfsmaster` listens on multiple ports. By default (refer [`mfsmaster.cfg`][1]):
- on port `9419` it listens for *metaloggers*,
- on port `9420` it listens for *chunkservers*,
- on port `9421` it listens for *clients*,
- on port `9424` it listens for *tapeservers*.

You need to use port that `mfsmaster` listens for clients (`9421` by default).

![Screenshot from 2019-09-30 09-13-57](https://user-images.githubusercontent.com/3036218/65856792-d157c080-e362-11e9-9225-5261c7efe4d6.png)

[1]: https://linux.die.net/man/5/mfsmaster.cfg
