### ISSUE TITLE
Debian Buster/Kernel 5.3

### ISSUE THREAD

**Issue by Blackpaw** [lizardfs/lizardfs#851]
Does anyone know if the official lizardfs 3.12 repositories work with Debian Buster/Kernel 5.3?

I currently have a Proxmox 5.4 cluster (DebianStretch/Kernel 4.15) working with http://packages.lizardfs.com/debian/stretch/ and would like to upgrade it to Proxmox 6.1, which is Debian Buster/Kernel 5.3.

Unfortunately, there are no lizardfs official Buster packages :(

Buster does have its own 3.12 packages, but they are configured for user lizardfs and /etc/lizardfs - I'd rather not migrate the config to a new root and user if I can help it.

**Comment by onlyjob** [comment]
> Buster does have its own 3.12 packages, but they are configured for user lizardfs and /etc/lizardfs - I'd rather not migrate the config to a new root and user if I can help it.

Long outstanding issue with LizardFS is its hijack of MooseFS's name space (#188, #208, etc). If that conflict is to be resolved on LizardFS side (and it should be resolved) then you will not be able to upgrade without changes to configuration. And sure enough the future is already here (#456) so you should start planning to migratio your configuration. Fortunately adopting locations and configs is not hard.

Co-existence of LizardFS and MooseFS is partially solved in Debian at least in regards to location of config files.

Also _vendor_ packages provided by LizardFS are of poor quality and they are inferior to official Debian packages. [Don't break Debian](https://wiki.debian.org/DontBreakDebian) and always avoid vendor packages unless there is no other way to do things. For 3.12 there is no justification and no excuse to use _vendor_ LizardFS packages on Debian.

**Comment by Blackpaw** [comment]
> For 3.12 there is no justification and no excuse to use _vendor_ LizardFS packages on Debian.

Point taken and looking into it.

Unfortunately stretch only has 3.10 packages, which is going to complicate any switch to the debian packages while I'm still on stretch,

**Comment by Blackpaw** [comment]
ok, stretch-backports has 3.11.3

**Comment by onlyjob** [comment]
Why not upgrade to Buster first? You've got to do it sooner or later because _oldstable_ will not be supported much longer...

**Comment by Blackpaw** [comment]
Probably what I'll have to do, just concerned that the stretch binaries won't work on buster, meaning I'll have to schedule some cluster downtime to upgrade everything at once.

**Comment by Blackpaw** [comment]
Yup, took my cluster down and upgraded the whole system to buster, which auto-installed the distro 3.12 packages as well. Some hurried copying of config files, changing of ownership and editing of scripts and all was good.

Pretty easy in the end, but it did involve downtime.
