### ISSUE TITLE
Questions about hardlinks

### ISSUE THREAD

**Issue by 19wolf** [lizardfs/lizardfs#852]
So with LizardFS you can have a different goal for different directories-- 

What happens when you have `/dir/a/file` and `/dir/b/file` as hardlinks to the same thing, but `/dir/a/` is goal $xor3 and `/dir/b/` is goal {_ _} ?

**Comment by Blackpaw** [comment]
Files have their own goals independent of their containing directories, so /dir/a/file and /dir/b/file would have the same goal (being the same file), defaulting to the goal of the dir that the file was first created in.
