### ISSUE TITLE
HA and Network split (split brain)

### ISSUE THREAD

**Issue by MGAndreasen** [lizardfs/lizardfs#854]
How does Lizardfs handle an event like a Network split in a HA Setup with like a Master server, two shadow masters servers and x number of chunk servers.  Like in an event where we lose 1-2 switches and the master and shadow servers might be located on different no longer connected switched, but maybe have acccess to some chunk servers, and some clients.

**Comment by Zorlin** [comment]
It depends which solution you're using.

In your scenario, if we assume we're using the uRaft solution and we have 3 masters (one primary, two shadow), the Raft consensus algorithm is used. One side of the split would have 1 node (and therefore 1 "vote") and would shutdown/demote, whereas the other side of the split would have 2 nodes (and therefore 2 "votes") and would promote a new master.

**Comment by MGAndreasen** [comment]
Ah, I see.  So a 3 split Will leave All serveres with 1 vote, thus
promoting No master's.

tor. d. 12. dec. 2019 10.16 skrev Benjamin Arntzen <notifications@github.com

**Comment by Zorlin** [comment]
Basically, yes.

This is why it's typically a good idea to have an odd number of servers in almost all modern consensus algorithms.

**Comment by MGAndreasen** [comment]
Makes good sense.

Are there still good reasons for running any loggers if going for 3 or even 5 masters in a larger setup?

**Comment by Zorlin** [comment]
Yes - it gives you added safety. How much that safety is worth to you varies... with multiple shadow masters, metaloggers aren't /that/ useful, but they don't take much resources and there's no real reason not to run them if you can.
