### ISSUE TITLE
error spdlog while installing source on ubunto 

### ISSUE THREAD

**Issue by nabil215** [lizardfs/lizardfs#857]
could not find  a package configuration file provided by spdlog with any of the following name 
spdlogconfige.cmake
spdlog-config.cmake

**Comment by Peperzastey** [comment]
Spdlog library on your system is too old. The newer versions provide these files.
On Ubuntu 18.04 and older the spdlog version in the official repository is too low.
You can download the newest spdlog from its github repository.
