### ISSUE TITLE
Metadata Master RAM Usage

### ISSUE THREAD

**Issue by nickcoons** [lizardfs/lizardfs#860]
I have two clusters for comparison. The first is running 3.13rc1 with 11,116,931 and is using 4.1GB of RAM and a metadata.mfs size of 1.4GB. The second is running 3.13rc2 with 10,105,536 and is using 13GB of RAM and a metadata.mfs size of 5.5GB.

My understanding is that the Metadata Master's RAM usage was directly related to the number of chunks. So I'm curious why on one cluster I'm using 4.1GB of RAM with 11m chunks and on another I'm using 13GB of RAM with 10m chunks.

First, is my understanding of this correct, and that in one of these clusters I'm somehow using too much RAM, or is this right and I don't actually have an issue.

Second, if there is an issue, where would I start to troubleshoot this?

**Comment by kaitoan2000** [comment]
I have 80 GB RAM with about 230M chunks, metadata version is 76B. How is the biggest metadata version in Lizardfs? Is it claim ram of master to 1024GB ram?
