### ISSUE TITLE
Where exactly do we download the windows client exe?

### ISSUE THREAD

**Issue by jwest75674** [lizardfs/lizardfs#862]
The documentation reads:
Install our client from exe package provided
Add your credentials and the address and port of the master server.
Select the drive you want your lizardFS file system to appear as in your windows session.

However, the download is not available on the lizardfs website?

Help!

**Comment by Zorlin** [comment]
It's currently only available for paying users.

**Comment by jwest75674** [comment]
Great! Where are the details on becoming a paying user? Even that doens't appear to be on the site?

**Comment by antonboretskyi** [comment]
@jwest75674 hi there, just send an e-mail on contact@lizardfs.com and ask about a windows client.

**Comment by Peperzastey** [comment]
I close this issue, as it was already answered by @antonboretskyi
