### ISSUE TITLE
How to get name of file from chunk name?

### ISSUE THREAD

**Issue by sontt710** [lizardfs/lizardfs#871]
Hello,

I have chunk name like this "chunk_00000000030072BF_00000001.mfs", How can I trace back to find file name?

Thanks.

**Comment by szycha76** [comment]
Find all copies of the chunk, move them out of all chunk servers' directories (back up, not delete!), restart affected chunkservers, wait for the consistency scan to reveal affected filename in the Web UI.
;-)
Then put the chunks back & restart chunkservers - your file will (should) be accessible again.

YMMV. Do at your own risk. You may die in the process. You have been warned.

**Comment by pbeza** [comment]
LizardFS do not have functionality for preforming reverse chunk queries for now (i.e. find file based on chunk). You could run `lizardfs fileinfo` on every file in the file system and do correlation that way.
