### ISSUE TITLE
cgiserv python interpreter mismatch

### ISSUE THREAD

**Issue by zserik** [lizardfs/lizardfs#884]
In the [`cgiserv.py.in`](https://github.com/lizardfs/lizardfs/blob/master/src/cgi/cgiserv.py.in) file, the specified python interpreter is `python2`:
https://github.com/lizardfs/lizardfs/blob/968f735b94ec61465e1361e0f7b7ce5d4c6458a6/src/cgi/cgiserv.py.in#L1

But in the [debian init script](https://github.com/lizardfs/lizardfs/blob/master/debian/lizardfs-cgiserv.init), the specified python interpreter is `python3`:
https://github.com/lizardfs/lizardfs/blob/968f735b94ec61465e1361e0f7b7ce5d4c6458a6/debian/lizardfs-cgiserv.init#L17

This inconsistency should be fixed.

**Comment by Peperzastey** [comment]
Hi, zserik

The cgiserv.py is deprecated and thus wasn't updated to Python3.
Also, the lizardfs-cgiserv service doesn't use this file.

Thanks for your attention nevertheless

**Comment by zserik** [comment]
ok, in which file is the source code for the daemon of `lizardfs-cgiserv`? I wasn't able to find it.

**Comment by zserik** [comment]
Ah, ok. But [lizard-cgiserver](https://github.com/lizardfs/lizardfs/blob/3bde7fe2fd15e1c91e0364e995cd442114b9d1c1/src/cgi/lizardfs-cgiserver.py.in) apparently has the same problem.
https://github.com/lizardfs/lizardfs/blob/3bde7fe2fd15e1c91e0364e995cd442114b9d1c1/src/cgi/lizardfs-cgiserver.py.in#L1

**Comment by Peperzastey** [comment]
On this commit you linked, yes, there is python2. On master there's python3 ;)
