### ISSUE TITLE
CMake: ENABLE_URAFT isn't used (uraft is always built)

### ISSUE THREAD

**Issue by zseri** [lizardfs/lizardfs#885]
`-DENABLE_URAFT=NO` doesn't work as expected, URAFT is build regardless of it.

**Comment by Antuan-AE** [comment]
Hello,

Uraft is enabled by default. Should you want to disable it, consider using the following:

```cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_TESTS=ON -DENABLE_URAFT=OFF ..```
```nice make -j$(nproc)```

Best regard,
LizardFS dev team.
