### ISSUE TITLE
Website http://packages.lizardfs.com/ is down

### ISSUE THREAD

**Issue by helmerfud** [lizardfs/lizardfs#897]
hello
http://packages.lizardfs.com/ is down
https://packages.lizardfs.com/ is down 

is there any other package source ?

thank you.

**Comment by AmokHuginnsson** [comment]
The old packages repository has been moved to https://dev.lizardfs.com/old-packages/

**Comment by helmerfud** [comment]
Thank You !!

**Comment by creolis** [comment]
please update your docs -
your install guide at [https://lizardfs-docs.readthedocs.io/en/latest/adminguide/installation.html] still refers to packages.lizardfs.com

**Comment by ictus4u** [comment]
Created a new issue for fixing the docs
