### ISSUE TITLE
How to get the list of files which goal is 1

### ISSUE THREAD

**Issue by kerneltravel** [lizardfs/lizardfs#916]
by `lizardfs-admin chunks-health`  I'd get the count number of files which goal is 1, 
```
> lizardfs-admin chunks-health MASTER_IP  MASTER_PORT
Chunks availability state:
	Goal	Safe	Unsafe	Lost
	1	-	11	-
	2	22	-	-
	3	33	-	-

Chunks replication state:
	Goal	0	1	2	3	4	5	6	7	8	9	10+
	1	11	-	-	-	-	-	-	-	-	-	-
	2	10	12	-	-	-	-	-	-	-	-	-
	3	33	-	-	-	-	-	-	-	-	-	-
```
only by getting file list , can I then change these 1-goal files' goal to greater ,but how can I get the list of files which goal is 1 ?

**Comment by jkiebzak** [comment]
Only way I know if to walk the file system and feed each filepath into mfsfileinfo.

**Comment by kerneltravel** [comment]
@lgsilva3087 maybe by programming to parse file /var/lib/mfs/metadata.mfs to get all file's goal is faster then by using `lizardfs getgoal /mnt/lizardfs/data/* | grep ': 1' | awk '{split($0,a,":"); print a[1]}'`  one by one file, in case when where are  many many many files.

any tips on how to get goals more efficiently ?

**Comment by kerneltravel** [comment]
LizardFS keeps metadata and the data separately. Metadata is kept on metadata servers, while data is kept on chunkservers.  

so metadata should contains the goal info, and it's possible to parse metadata and got list of 1-goal files ?
