### ISSUE TITLE
Website http://lizardfs.com/ is down

### ISSUE THREAD

**Issue by bobapplemac** [lizardfs/lizardfs#923]
hello

It seems that the main project website http://packages.lizardfs.com/ is currently down

**Comment by ictus4u** [comment]
Hello,

Thank you for reporting. There are some issues with the main website [lizardfs.com](https://www.lizardfs.com) we are working to fix.

However, http://packages.lizardfs.com/ was moved to https://dev.lizardfs.com/old-packages/ (See [this answer](https://github.com/lizardfs/lizardfs/issues/897#issuecomment-726910879)).

Currently, https://dev.lizardfs.com/packages/ is the URL you probably wanted.

**Comment by ictus4u** [comment]
The http://lizardfs.com website is up again
