### ISSUE TITLE
[PATCH] CMake 3.25 compatibility

### ISSUE THREAD

**Issue by adriaandegroot** [lizardfs/lizardfs#928]
With CMake 3.25, the last tagged release of lizardfs (3.12.0) fails at cmake-time.  A typical error looks like this:

```
- Looking for include file arpa/inet.h
CMake Error at /usr/local/share/cmake/Modules/CheckIncludeFiles.cmake:136 (try_compile):
  SOURCE_FROM_VAR given invalid filename "arpa/inet.h_FOUND.c"
Call Stack (most recent call first):
  cmake/CheckIncludes.cmake:6 (check_include_files)
  cmake/EnvTests.cmake:39 (check_includes)
  CMakeLists.txt:137 (include)
```

Since lizardfs built with CMake 3.24 (I'm the package maintainer for CMake on FreeBSD, which is why I notice these things), it is related to something internal in CMake. Here is a patch for `cmake/CheckIncludes.cmake` that works around the problem (and also works for CMake 3.24 and earlier -- but I'll raise an issue with CMake as well).

```
--- cmake/CheckIncludes.cmake.orig      2022-12-24 21:43:32 UTC
+++ cmake/CheckIncludes.cmake
@@ -3,7 +3,9 @@ include(CheckIncludeFiles)
 function(check_includes INCLUDES)
   set(INCLUDE_MISSING FALSE)
   foreach(INCLUDE_FILE ${INCLUDES})
-    check_include_files(${INCLUDE_FILE} ${INCLUDE_FILE}_FOUND)
+    string(MAKE_C_IDENTIFIER "${INCLUDE_FILE}" c_include)
+    check_include_files(${INCLUDE_FILE} ${c_include}_FOUND)
+    set(${INCLUDE_FILE}_FOUND ${${c_include}_FOUND})
     if(NOT ${INCLUDE_FILE}_FOUND)
       set(INCLUDE_MISSING TRUE)
       set(MISSING_INCLUDES ${MISSING_INCLUDES} ${INCLUDE_FILE})
```

What this does is turn the pathname of the include-file (e.g. `arpa/inet.h` into a C identifier, first, before using that as a variable name. It looks like CMake now uses the variable name unchanged as a source-file-path for the test, which is fragile.

**Comment by adriaandegroot** [comment]
(not making a PR because this is a tiny change, and the state of PRs in this repo is not great)

**Comment by wojciesh** [comment]
Fixed: https://github.com/lizardfs/lizardfs/commit/b1e97f974fc3a4046edaf9fdc3962264d4cd24fa
