### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by peng42** [lizardfs/lizardfs#930]
Hi there!

I'd like to know the current status of the LizardFS project, as the latest pre-release is already 2.5 years old and packages have been removed from Debian stable.

Any hope to see further work and development around LizardFS ? Is it a good idea to build new storages with it now or should we prefer others like MooseFS or Ceph ?

Thank for the heads up!
Cheers

**Comment by MariuszLizardfs** [comment]
Hello.
Thank you for your question. LizardFS is still in development.

Our current goal is the completion of a new enterprise (closed) version of LizardFS. Most likely there will also be a free version available for home users. Right after that we will fix most of the bugs with issues on our GitHub and publish them to the community.
We're trying to get back to Debian but we can't promise if we'll meet the upcoming release date. If not, the packages will be available on our website later.

In the meantime, please write to us if you need any help with LizardFS.
https://lizardfs.com/contact
